Meteoriteの演出実装
LITO-apps/Treevel-client pull request #1012
Opened 2021-07-03 09:33 UTC by takasusuke

### 対象イシュー
Close #850

### 概要
タイトルまま

### 詳細
- [ ] Meteorite登場アニメーション
- [ ] 攻撃位置可視化
- [ ] Meteorite攻撃(移動アニメーション)
- [ ] Meteorite-partielc
- [ ] 攻撃判定
- [ ] Meteorite退出アニメーション
- [ ] ヒビ登場アニメーション
- [ ] ヒビ退出アニメーション

#### 現実装になった経緯
草案に基づく

#### 技術的な内容
特になし

### キャプチャ
2021/07/03
https://user-images.githubusercontent.com/26213141/124350027-2528c500-dc2d-11eb-887e-485f3c07adc7.mov

### 動作確認方法
Spring_2_5をプレイ

### 参考 URL

2021-07-09 17:03 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/MeteoriteController.cs
> +            _meteoriteRenderer.sortingLayerName = Constants.SortingLayerName.METEORITE;
落下前はBottleよりも手前のLayer、落下後はBottleとTileの間のLayer

2021-07-09 17:06 UTC, takasusuke commented
@LITO-apps/engineer 
レビューお願いします
30min~1hくらいです。

Particle以外のアニメーション要望などコメントしてください。
SEも後で、またやる気が出たタイミングで実装します。
(SEの長さとかは考慮せず、機能として入れるだけ)

2021-07-11 01:04 UTC, takasusuke commented
全部、右上から登場させてみる
（右下とかBottleの邪魔になりそう）

2021-07-12 12:15 UTC, xiii111 requested changes
対応ありがとうございます！動作は問題なさそうです

いくつかコメントしました

2021-07-12 12:15 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/MeteoriteController.cs
> +            SoundManager.Instance.PlaySE(ESEKey.Gimmick_Meteorite_Drop);
ここも同様

2021-07-12 12:15 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/MeteoriteController.cs
> +            yield return new WaitUntil(() => _meteoriteAnimator.GetCurrentAnimatorStateInfo(0).shortNameHash != _REMAINING_STATE_NAME_HASH);
### ask

これは ... `_REMAINING_STATE_NAME_HASH` になって、終わるまで ... みたいな？

2021-07-12 23:00 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/MeteoriteController.cs
> +            SoundManager.Instance.PlaySE(ESEKey.Gimmick_Meteorite_Collide);
MeteoriteのSEを止めるときに、全てのMeteoriteのSEを止めることしか出来なかったので、以下のように修正しました
- SEを再生するときに、どのAudioSourceを使っているかインデックスを返す
- SEを停止するときにインデックスを与え、特定のAudioSourceのSEを停止させる

超高頻度でMeteoriteを発生させる場合、SEの最大個数(16)を超えて再生しようとするので、上記の警告はまだ出ることがあり得ます。
しかし、そもそもSEの最大個数を超えてSEを再生しようとするゲームデザインが間違っているのでこれは対処しません。

8577a75
594c4b3
b8920f6

2021-07-12 23:00 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/MeteoriteController.cs
> +            SoundManager.Instance.PlaySE(ESEKey.Gimmick_Meteorite_Drop);
https://github.com/LITO-apps/Treevel-client/pull/1012#discussion_r668310740

2021-07-12 23:24 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/MeteoriteController.cs
> +            yield return new WaitUntil(() => _meteoriteAnimator.GetCurrentAnimatorStateInfo(0).shortNameHash != _REMAINING_STATE_NAME_HASH);
そう。
```
yield return new WaitUntil(() => _meteoriteAnimator.GetCurrentAnimatorStateInfo(0).shortNameHash != _REMAINING_STATE_NAME_HASH);
```
だけだと、Stateが切り替わってないことがあると一瞬で終わってしまうかな、、、と思ってたけど、実際そんなことなかったから上の行は消しました。

c990a1f

2021-07-12 23:26 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/MeteoriteController.cs
> +using Cysharp.Threading.Tasks;
f3ecf18

2021-07-12 23:29 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/MeteoriteController.cs
> +            position = new Vector2(Mathf.Min(position.x, (GameWindowController.Instance.GetGameCoreSpaceWidth() - _meteoriteRenderer.bounds.size.x) / 2f), Mathf.Min(position.y, (GameWindowController.
68735c7

2021-07-12 23:31 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/MeteoriteController.cs
> +            // TODO: 特殊なTileを狙わないように指定する
- WarpTileとか、Meteoriteの跡を残すと違和感のある見た目になるTileはそもそも狙わない。
- HolyTileは狙わない

みたいなやつ。
今考えることじゃないから消した。
2739643

2021-07-13 10:13 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/MeteoriteController.cs
> +            // TODO: 特殊なTileを狙わないように指定する
ok!

2021-07-13 10:17 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/MeteoriteController.cs
> +            yield return new WaitUntil(() => _meteoriteAnimator.GetCurrentAnimatorStateInfo(0).shortNameHash != _REMAINING_STATE_NAME_HASH);
```
// Attackまで待つ
yield return new WaitUntil(() => _meteoriteAnimator.GetCurrentAnimatorStateInfo(0).shortNameHash == _ATTACK_STATE_NAME_HASH);
```
と合わせるなら `==` の方を残すと思うんだけど、解釈合ってる？

2021-07-13 10:30 UTC, xiii111 requested changes
修正点について、追加コメントをしました。

2021-07-13 10:30 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public int PlaySE(ESEKey key)
### ask

インデックスは正常形で 0 以上であるという前提があるから、非正常系は `return -1;` で良いんですよね？

2021-07-13 10:30 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopSE(ESEKey key, int index = -1)
### imo

んーー流石に `int index = -1` は良くないと思う。`index` を与えるかどうかで `index` を見るかどうか決めるなら、オーバーロードして実装して欲しい

2021-07-13 10:31 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/MeteoriteController.cs
> +            SoundManager.Instance.PlaySE(ESEKey.Gimmick_Meteorite_Collide);
https://github.com/LITO-apps/Treevel-client/pull/1012#pullrequestreview-705010728 で追加コメントしました。こちらは Resolve します

2021-07-13 10:32 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopSE(ESEKey key, int index = -1)
golang書きすぎてオーバーロードとかいうめちゃ便利機能完全に忘れてた笑

2021-07-13 10:33 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopSE(ESEKey key, int index = -1)
えーーー今度 api 作る時も golang でやりたいから、教えて欲しい！（全く関係ない話）

2021-07-13 10:38 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopSE(ESEKey key, int index = -1)
何を教えるんだ。。。

gRPCザクザクやってる。
interceptor楽しい。
https://qiita.com/nisitanisubaru/items/abe11ff4248997d1fee2
https://soichisumi.net/2019/12/grpc-interceptor-method-setting/

2021-07-13 10:39 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopSE(ESEKey key, int index = -1)
gRPC 良いね

2021-07-13 10:39 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopSE(ESEKey key, int index = -1)
DDD そこそこ役に立ちそう

2021-07-13 10:41 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopSE(ESEKey key, int index = -1)
ScrapboxのDDDページカンニングしながら設計してる笑

2021-07-13 10:42 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopSE(ESEKey key, int index = -1)
まじかよ、一から作れてるの羨ましい。Scrapbox 進める欲が上がったわ

2021-07-13 12:37 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public int PlaySE(ESEKey key)
そうです

2021-07-13 12:39 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopSE(ESEKey key, int index = -1)
599a7f4

2021-07-13 12:40 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/MeteoriteController.cs
> +            yield return new WaitUntil(() => _meteoriteAnimator.GetCurrentAnimatorStateInfo(0).shortNameHash != _REMAINING_STATE_NAME_HASH);
Attackまで待つ(Attackが始まるまで待つ)
のと
Remainingが終わるまで待つ
なので、逆の状態です。

2021-07-13 12:46 UTC, takasusuke commented
右上１箇所から発生させた場合。思ったより違和感がある。

https://user-images.githubusercontent.com/26213141/125453887-e397ba5a-6698-4395-86b1-cf0d85c12faa.mov

2021-07-13 12:46 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopSE(ESEKey key, int index)
### imo

`インデックスを指定して SE を停止する` のであれば、`key` を利用した停止をサポートする必要はないと思います。引数を `index` だけにしませんか？

2021-07-13 12:46 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/MeteoriteController.cs
> +            yield return new WaitUntil(() => _meteoriteAnimator.GetCurrentAnimatorStateInfo(0).shortNameHash != _REMAINING_STATE_NAME_HASH);
ok

2021-07-13 12:48 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopSE(ESEKey key, int index = -1)
https://github.com/LITO-apps/Treevel-client/pull/1012#discussion_r668727596 に引き継ぎ

2021-07-13 12:51 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopSE(ESEKey key, int index)
SEが終わると、AudioSource.IsPlaying がfalseになるので、AudioSourceを明示的に解放しなくても、他のギミックとかがそのindexのAudioSourceを使っている可能性がある。
なので、既にSE終わっているのに、indexを指定して止めると、別のギミックとかのAudioSourceを止めてしまう可能性がある。
keyを指定した方が安全。

2021-07-13 12:53 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopSE(ESEKey key, int index)
別のギミックが同じindexでAudioSourceを使ってる、かつ、keyも同じ場合は、別のギミックのSEを止めるリスクはある。
なので、もしちゃんとやるなら、indexじゃなくて、SEを再生するごとにtokenを発行して、そのtokenで指定してSEを止める。
その場合はkeyは不要。

2021-07-13 12:56 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopSE(ESEKey key, int index)
毎度AudioSourceにtokenを紐づけておく労力に対して、tokenがないせいで不具合が起きる場面は少なそう
&&
indexだけにしても良いけど、少ない労力で若干リスクを減らせるならこのまま。

indexだけversionもサポートするのはまああり。

2021-07-13 12:58 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopSE(ESEKey key, int index)
なるほど、いろいろ考えてくれてるみたいなので、お任せします

2021-07-13 13:05 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/MeteoriteController.cs
> +            _startPosMargin = new Vector2(2.5f * GameWindowController.Instance.GetTileWidth(), 1.5f * GameWindowController.Instance.GetTileWidth());
`2.5f * GameWindowController.Instance.GetTileWidth()`
まで含めてマジックナンバー（別にTIleの横幅を基準にmarginを決めなくても良いから）なのでコメント難しいけどなんとなくコメント足しておきました。

3628ff8

2021-07-13 13:08 UTC, takasusuke commented
https://github.com/LITO-apps/Treevel-client/pull/1012#issuecomment-879056498
で右上からMeteoriteを発生させてみたけれど、違和感があるので、元の方法のままにします。

プレイしてみて、Bottleが被って結構プレイしづらいとかであれば、初期位置でのMeteoriteの大きさや透明度の調整等も考慮します

2021-07-13 13:09 UTC, merged