任意のタップに対して、タップした場所にオブジェクトを生成する
LITO-apps/Treevel-client pull request #1014
Opened 2021-07-04 03:46 UTC by takasusuke

### 対象イシュー
なし

### 概要
タイトルまま

### 詳細
- [ ] Tapした場所にオブジェクトを生成する`TapObejectGenerator.cs`を作成
- [ ] Tapして生成したオブジェクト(`TapObjectController.cs`)は一定時間後に消える。
アニメーションなどもこのクラスで実装予定。表示するオブジェクトの画像やアニメーションはSceneごとに変えられるのでGamePlaySceneだけ変えたりもできる。
- [ ] `TapObjectGenerator`をコンポーネントとして持つCanvasである`TapObjectCanvas`をprefabとして生成。全てのSceneに１つずつ配置。
- [ ] Tapした時の画像
- [ ] Tapした時のアニメーション
- [ ] 多様デバイス対応

#### 現実装になった経緯
- Tapした位置にオブジェクトを生成させたい
- 必ず最も手前に描画したい
以上の理由からCanvas配下にTapを生成したいので、Canvasのコンポーネントとした。
また、Canvasの設定で、`ScreenSpace-Camera`を使ってるCanvasではCanvas配下のオブジェクトが必ず手前に描画されるのではなく、他のGameObjectと同じようにLayerやSortingLayerで描画順序が決まる。また、タップした位置とCanvasの座標が必ずしも一致しない。

Sceneごとに使ってるCanvasの設定や、大きさが異なる。
そこで、TapObjectだけを描画する専用のCanvasを作成した。
このCanvasのSortingOrderは10000という大きな値を設定し、どのCanvasよりも手前に描画されることを期待している。

#### 技術的な内容
生成されるTapObject(Image)がButtonの反応などを奪わないように、Imageの設定でRaycastTarget設定をOFFにしている。

### キャプチャ
仮画像で実装中なのでまだ。

### 動作確認方法

- [ ] Tapした位置にオブジェクトが生成される
- [ ] ユーザの動線通りに動いてみて、特にButtonの反応が阻害されたりしないことを確認する

### 参考 URL

2021-07-04 15:52 UTC, takesi0627 commented
全部のシーンに配置するより `StartupScene` とかでインスタンス作成してから `DontDestroyOnLoad` にしたほうがいいのではないでしょうか

2021-07-05 12:57 UTC, takasusuke commented
> 全部のシーンに配置するより `StartupScene` とかでインスタンス作成してから `DontDestroyOnLoad` にしたほうがいいのではないでしょうか

た、確かに。。。

2021-07-17 08:07 UTC, xiii111 requested changes
対応ありがとうございます。動作確認やコードに関して、いくつかコメントしました

以下、問題ありませんでした

- [x] Tapした位置にオブジェクトが生成される
- [x] ユーザの動線通りに動いてみて、特にButtonの反応が阻害されたりしないことを確認する

以下、気になる点がありました。念のため確認できますか？

1. `Simulator` ではタップした場所にオブジェクトが生成されない（`Simulator` と実機の挙動はよく似ているので、実機でも生成されない可能性がある）

https://user-images.githubusercontent.com/26104258/126030396-d3f98ba1-556a-4a2c-bfe3-8b901b04cfab.mov


2. スクロール時にも表示されると、タップオブジェクトがズレて、違和感がある


https://user-images.githubusercontent.com/26104258/126030423-814d8a09-358d-40c9-a3d6-25b17c56bef1.mov

2021-07-17 08:07 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/UIs/TapObjectController.cs
> +        }
### ask

自身を削除する、くらいの機能なら animation 側の api で用意されてませんか？（位置を変えたりできるのであれば、ありそう）

2021-07-17 08:07 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/UIs/TapObjectGenerator.cs
> +            if (Input.GetMouseButtonDown(0))
### ask

`TouchScript` を使わないのは、特定のオブジェクトに対するタップイベントではなく、画面全体に対するイベントだからですか？

2021-07-17 14:39 UTC, takesi0627 commented
僕のsimulator問題なかったですね

https://user-images.githubusercontent.com/17778395/126040447-737d7e18-633e-41fa-9e84-f90497329508.mov

2021-07-17 14:40 UTC, takasusuke commented
> 僕のsimulator問題なかったですね
> 
>  2021-07-17.23.38.02.mov

e8db3a6
ごめんここでちょっと修正入れてる。
多分、Game modeだと表示されないと思う。

2021-07-17 14:42 UTC, takesi0627 commented
> > 僕のsimulator問題なかったですね
> > 2021-07-17.23.38.02.mov
> 
> [e8db3a6](https://github.com/LITO-apps/Treevel-client/commit/e8db3a66d4fa7ab430bd85cf98315461afd6e1b5)
> ごめんここでちょっと修正入れてる。
> 多分、Game modeだと表示されないと思う。

ごめんコミット気づかなかったw

2021-07-17 14:46 UTC, takesi0627 commented
![image](https://user-images.githubusercontent.com/17778395/126040584-91c7eb55-9139-4e17-8d1a-02f9ebf1ddc0.png)

スプライトの切り替えより、円の画像の大きさを変えたほうがいいのではないかと思いました。
最初わからなかった時にアニメーションが断続的に見えるから処理が重いかなって思いましたのでここは連続的にアニメーションさせたいところです。

2021-07-17 14:50 UTC, takesi0627 commented
最後にフェイドアウトかけて欲しいです。（5フレームとか一瞬だけでもいい）

2021-07-18 02:45 UTC, takesi0627 commented
https://user-images.githubusercontent.com/17778395/126054024-6dfa540a-b2f7-406c-8b97-e44be5ea7c99.mp4

2021-07-19 15:08 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/UIs/TapObjectGenerator.cs
> +            if (Input.GetMouseButtonDown(0))
ミーティングより

- 画面全体用のTouchScriptのComponentがあったけど、すぐには働かなかったこと
- 重なっているTouchScriptの反応を奪ってしまうこと

以上の理由からTouchScriptとEventSystemを共存させています

2021-07-19 15:08 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/UIs/TapObjectController.cs
> +        }
パッとはありませんでした。

2021-07-19 15:09 UTC, takasusuke commented
@takesi0627 
> 最後にフェイドアウトかけて欲しいです。（5フレームとか一瞬だけでもいい）

フレーム数を増加しました
フェードアウトをかけました

2021-07-19 15:12 UTC, takasusuke commented
> 1. `Simulator` ではタップした場所にオブジェクトが生成されない（`Simulator` と実機の挙動はよく似ているので、実機でも生成されない可能性がある）

fb1a651
解決しました

> 2. スクロール時にも表示されると、タップオブジェクトがズレて、違和感がある

タップ終了時に表示させると、ボトルのフリック等で違和感がありました。
今は、明らかにタップした場所を中心に発生していますが、
https://github.com/LITO-apps/Treevel-client/pull/1014#issuecomment-881988610
の動画のように、中心が若干わかりにくくなるような演出なら違和感は軽減されるかもしれません。

2021-07-20 16:12 UTC, takesi0627 commented
> @takesi0627
> 
> > 最後にフェイドアウトかけて欲しいです。（5フレームとか一瞬だけでもいい）
> 
> フレーム数を増加しました
> フェードアウトをかけました

5988c79
イメージ追加しただけで、アニメーション修正していなさそうですが・・

2021-07-21 14:28 UTC, takasusuke commented
> > @takesi0627
> > > 最後にフェイドアウトかけて欲しいです。（5フレームとか一瞬だけでもいい）
> > 
> > 
> > フレーム数を増加しました
> > フェードアウトをかけました
> 
> [5988c79](https://github.com/LITO-apps/Treevel-client/commit/5988c7936abf688e3459dbd87bc8bf6d4dc06e2c)
> イメージ追加しただけで、アニメーション修正していなさそうですが・・

886509c
また、保存し忘れて変更消し飛ばしてしまった。。。
失礼しました。

2021-07-22 04:10 UTC, takesi0627 approved these changes
OK!

2021-07-23 10:36 UTC, xiii111 approved these changes
対応ありがとうございます！一点だけ追加で確認して欲しいです

本ブランチのみで、以下のように `StartupScene` の背景色が変わっていますが、想定挙動でしょうか？（想定挙動であれば、マージして ok です）

|`本ブランチ`|`develop`|
|---|---|
|<img width="382" alt="スクリーンショット 2021-07-23 19 32 43" src="https://user-images.githubusercontent.com/26104258/126770567-5b7fd61f-4c6c-420d-841d-889c3f4f5dde.png">|<img width="380" alt="スクリーンショット 2021-07-23 19 32 16" src="https://user-images.githubusercontent.com/26104258/126770704-6d490631-926b-4e74-8785-7b0f85e000af.png">|

2021-07-24 04:10 UTC, takasusuke commented
> 
> 本ブランチのみで、以下のように `StartupScene` の背景色が変わっていますが、想定挙動でしょうか？（想定挙動であれば、マージして ok です）

現状でTapObjectが白いのでわかりやすくするために以下のcommitで色を変えました
ac21a42

2021-07-24 04:10 UTC, merged