GhostAttributeの演出実装
LITO-apps/Treevel-client pull request #1027
Opened 2021-07-16 14:45 UTC by takasusuke

### 対象イシュー
Close #996
Close #989

### 概要
タイトルまま

### 詳細
- 蜘蛛の巣にかかっているときにGhostAttributeの効果で移動しない
- 動き出す前にParticleを出す

#### 現実装になった経緯
#653 のデザイン草案に基づく

#### 技術的な内容
特になし

### キャプチャ
https://user-images.githubusercontent.com/26213141/125965539-20b698b1-e083-4f33-a945-6ef57e6127a9.mov

### 動作確認方法
Spring_1_1をプレイ

- [ ] ゲーム終了時にParticleなどGhostのアニメーションが止まっている

### 参考 URL

2021-07-16 14:47 UTC, takasusuke commented
@LITO-apps/engineer 
よろしくお願いします。
30minくらい、、、？

2021-07-17 07:42 UTC, xiii111 requested changes
対応ありがとうございます！いくつかコメントしたのと、動作についての確認も行いました。よろしくお願いします

以下、正常に確認が取れました

- [x] `Unity` と `Rider` の検索機能を用いて `selfish` の文言が完全に消えていること
- [x] 蜘蛛の巣にかかっているときに `GhostAttribute` の効果で移動しなくなっていること
- [x] ゲーム終了時に `Particle` など `GhostAttribute` のアニメーションが止まっていること（成功ポップアップを無効にして確認しました）

以下、気になった点です。念の為、確認できますか？

1. `GhostAttribute` がついた `Bottle` をフリックして移動しても、カウントダウンがリセットされなくなっている（蜘蛛の巣の確認のために、一時的に変更した？）

https://user-images.githubusercontent.com/26104258/126029603-f27cbeef-b257-4bdc-b2aa-2a2260f25b8e.mov

2. `GhostAttribute` がついた `Bottle` をホールドすると、`Particle` が消えてしまう（完全にアニメーションを停止するなら `Particle` も止まったほうが良いと思いました

https://user-images.githubusercontent.com/26104258/126029576-ad257e82-78c7-40dd-8229-2baae963e2aa.mov

2021-07-17 07:42 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/BottleAttributeType.cs
> +            }
### ask

`enum` の `case` の順番に依存しないようにしてくれた感じ？

2021-07-17 07:42 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/BoardManager.cs
> +            if (!bottle.IsMovable) return false;
### ask

良いと思います👍 `FYI` ですが、この処理を入れても `DynamicBottleController` の `IsMovable` 判定を消してはいけない理由は、フリックをしたときの計測などに影響が出てしまうからです

2021-07-17 07:42 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/GhostAttributeController.cs
> -        }
### ask

一応確認だけど、中身の処理が 1 行とかに減ったから、`Subscribe()` の中に直接書くようにしたってことだよね？

2021-07-17 07:42 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/GhostAttributeController.cs
> -                RestartAnimation();
### ask

これ消して大丈夫？

2021-07-17 07:42 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/GhostAttributeController.cs
> +            _bottleController.EndMove.Subscribe(_ => animator.SetFloat(_ANIMATOR_PARAM_FLOAT_SPEED, 1f))
### nits

下二つの記述と合わせて

```suggestion
            _bottleController.EndMove
                .Subscribe(_ => animator.SetFloat(_ANIMATOR_PARAM_FLOAT_SPEED, 1f))
```

2021-07-17 14:26 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/BottleAttributeType.cs
> +            }
### imo
おしゃれバージョンいかがでしょうか
```
            return type switch {
                EBottleAttributeType.Dark => 10,
                EBottleAttributeType.Reverse => 20,
                EBottleAttributeType.Ghost => 30,
                EBottleAttributeType.Life => 40,
                _ => 0,
            }
```

2021-07-17 14:26 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/GhostAttributeController.cs
> +        private static readonly int _ANIMATOR_PARAM_FLOAT_SPEED = Animator.StringToHash("GhostSpeed");
### ask

Animatorを覗いてみたんですが、どのトランジションにもこのパラメータ使ってなさそうですが、このパラメータはどこに使ってますか？

2021-07-17 14:31 UTC, takesi0627 commented
https://github.com/LITO-apps/Treevel-client/blob/db538e3a7a457f394bda0408251a36232a6f39b9/Assets/Project/Scripts/Modules/GamePlayScene/Bottle/SelfishAttributeController.cs#L82

```diff
- BoardManager.Instance.MoveAsync(_bottleController, tileNum - 1, Vector2Int.left);
+ BoardManager.Instance.MoveAsync(_bottleController, tileNum - 1, Vector2Int.left).Forget();
```
今回の変更範囲外ですが、ここ直していただけると助かります

2021-07-19 16:51 UTC, takesi0627 commented
一旦作業中に戻します

2021-07-21 15:21 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/GhostAttributeController.cs
> +        private static readonly int _ANIMATOR_PARAM_FLOAT_SPEED = Animator.StringToHash("GhostSpeed");
トランジションではなく、アニメーションの再生速度で使っています。
（途中で止めたり再開したりするため）
<img width="647" alt="スクリーンショット 2021-07-22 0 20 39" src="https://user-images.githubusercontent.com/26213141/126514753-3fb0fc44-7320-448b-a52f-77a75b50dfc5.png">

2021-07-21 15:22 UTC, takasusuke commented
> https://github.com/LITO-apps/Treevel-client/blob/db538e3a7a457f394bda0408251a36232a6f39b9/Assets/Project/Scripts/Modules/GamePlayScene/Bottle/SelfishAttributeController.cs#L82
> 
> ```diff
> - BoardManager.Instance.MoveAsync(_bottleController, tileNum - 1, Vector2Int.left);
> + BoardManager.Instance.MoveAsync(_bottleController, tileNum - 1, Vector2Int.left).Forget();
> ```
> 
> 今回の変更範囲外ですが、ここ直していただけると助かります

58b919b

2021-07-22 03:04 UTC, takasusuke commented on Assets/Project/Scripts/Common/Entities/BottleAttributeType.cs
> +            }
ef3ecf4

> `enum` の `case` の順番に依存しないようにしてくれた感じ？

まあそう。

2021-07-22 03:05 UTC, takasusuke commented
> 1. `GhostAttribute` がついた `Bottle` をフリックして移動しても、カウントダウンがリセットされなくなっている（蜘蛛の巣の確認のために、一時的に変更した？）
> 

この仕様忘れてた。修正した。
b061745

> 2. `GhostAttribute` がついた `Bottle` をホールドすると、`Particle` が消えてしまう（完全にアニメーションを停止するなら `Particle` も止まったほうが良いと思いました
> 

修正した。
b061745

2021-07-22 03:06 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/GhostAttributeController.cs
> +            _bottleController.EndMove.Subscribe(_ => animator.SetFloat(_ANIMATOR_PARAM_FLOAT_SPEED, 1f))
b061745

2021-07-22 03:07 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/GhostAttributeController.cs
> -                RestartAnimation();
GhostAttribute がついた Bottle をフリックして移動しても、カウントダウンがリセットされなくなっている

の仕様を満たすために必要。
この仕様を忘れて消してたので戻した。

2021-07-22 03:10 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/GhostAttributeController.cs
> -        }
微妙に違う。
以前は`RestartAnimation()`メソッドを複数箇所で使っていたので、他のメソッドも適宜名前をつけてメソッド化していた。

アニメーションの実装が変わったので、重複して行うメソッドがなくなったのでメソッド化せず、べた書きした。

2021-07-22 03:11 UTC, takasusuke commented
@LITO-apps/engineer 
再おねがい

2021-07-22 04:24 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/GhostAttributeController.cs
> +        private static readonly int _ANIMATOR_PARAM_FLOAT_SPEED = Animator.StringToHash("GhostSpeed");
なるほど、こんな機能あったんだ！

2021-07-22 05:17 UTC, takesi0627 approved these changes
OK!

2021-07-23 10:47 UTC, xiii111 approved these changes
Nice Work!

2021-07-24 04:11 UTC, takasusuke commented
Thank you~~~

2021-07-24 04:12 UTC, merged