成功画面実装
LITO-apps/Treevel-client pull request #1040
Opened 2021-07-27 16:40 UTC by takesi0627

### 対象イシュー
Close #1019  

### 概要
#1019 の要件を満たす実装

### 詳細

### 現実装になった経緯

### 技術的な内容

#### `TextMeshPro` 関連
* `TextMeshPro`を使ったコンポーネントを制御するために、 `Assembly Definition References` に`Unity.TextMeshPro` を追加しました。使用するには、`using TMPro;` を宣言した上で、 `TextMeshProUGUI` クラスを使います。
![image](https://user-images.githubusercontent.com/17778395/127189635-515bde65-d20e-4ee5-8e6e-c877ac3ea7c6.png)

* TextMeshProは色々パラメータをいじることができますが、マテリアルに反映してしまうため、テキスト毎に**マテリアルプリセット**を作成しました（詳しくは関連URLを参照）。また、マテリアルプリセットの名前はフォントと同じ名前から始まる必要があります（今回の作成したマテリアルは `LiberationSans SDF ~`という名前にしているのはこの理由です）。

### キャプチャ

https://user-images.githubusercontent.com/17778395/127191087-84d1da25-f4ab-4bd6-9b1a-993dfd629021.mov

レイアウト作る時描いたやつ。参考までに。
![随筆-9](https://user-images.githubusercontent.com/17778395/127193409-e6853077-a7fc-460b-b4db-4e05c0e6177e.jpg)

### 動作確認方法
任意のステージを成功し、
- [ ] `TAP TO RETURN`と表示される黒い領域をクリックするとステージ選択画面に戻ること
- [ ] それ以外の領域をクリックするとパネルが消えること
- [ ] さらにクリックするとパネルが表示されること。
- [ ] CLEARのテキストの色が季節に合わせて変化すること
- [ ] ステージのアイコンリストが現在の進行度を正しく反映していること
- [ ] 下から出てくるパーティクルが表示されないこと
- [ ] ツイッターアイコンを押すとTwitterが開くこと

※Spring-1以外の木のステージは現状ステージアイコンが設定していないため、ステージアイコンは表示されません。

### 参考 URL
* [Text Mesh Proのテキストをスクリプトから表示・変更する](https://unity-mantario.hatenablog.com/entry/2018/07/15/205727)
* [TextMesh ProでOutlineなどの設定を複数保持する方法](https://ekulabo.com/text-mesh-pro-material)
* [ツイッターアイコン](https://about.twitter.com/en/who-we-are/brand-toolkit)

2021-07-27 16:49 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/StageRecordService.cs
> +        public EStageState GetStageState(StageData stageData)
`EStageState` を計算する処理 `StageController.cs` もやっているので共通化するために `StageRecordService` に移動しました。
`StageRecordService` にする理由としては、この計算はユーザのレコードに依存するからです。

2021-07-27 16:54 UTC, takesi0627 commented
@LITO-apps/engineer 
@xiii111 @takasusuke 
思ったよりボリュームがあるようです。
時間かかるかもしれませんが、よろしくお願いします。

ちょっと時間使いすぎたので、今回はCLEAR テキストにアニメーションつけるのは割愛します。 ブラッシュアップイシュー(#1041 )として余裕あれば対応することにさせてください。

2021-07-28 10:44 UTC, xiii111 requested changes
対応ありがとうございました！いくつかコメントしました。よろしくお願いします

### imo
現状は、ボタンや画像、テキストがない位置をタップした場合には、ゲーム終了時の盤面をみれると思います。しかし、ボタンなどのタップイベントがない場所全てをタップ領域にしたいです（テキストや画像がある場所もタップしたら、盤面を見たいです）

### imo
`TAP TO RETURN` の演出、素晴らしいと思いました。一点気になったのが、以下のように最も `TAP TO RETURN` が目立つタイミングの視認性が低く感じました。もう少し背景を黒くするか、`TAP TO RETURN` のフォントカラーを白寄りにしても良いと思いました

<img width="378" alt="スクリーンショット 2021-07-28 18 58 34" src="https://user-images.githubusercontent.com/26104258/127303774-319c7ec1-978c-45c2-b714-2d254aae207f.png">

### ask
`Assets/Project/Actors/UIs/Common/Seasons/Spring/FullScreenBackground.png` ってどこかで使っていますか？

### ask
ステージアイコンがある `Spring_1_1` 以外は成功状態を成功画面に反映できてないように見えますが、想定挙動でしょうか？

2021-07-28 10:44 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/AddressableAssetManager.cs
> +            if (treeData.stageIcon.Asset == null && treeData.stageIcon.RuntimeKeyIsValid()) {
### ask

`treeData.stageIcon.RuntimeKeyIsValid()` ってなんだっけ？

2021-07-28 10:44 UTC, xiii111 commented on Assets/Project/Scripts/Common/Utils/StageRecordService.cs
> +        /// <param name="stageData"></param>
### nits

中身書かないなら消しましょう

2021-07-28 10:44 UTC, xiii111 commented on Assets/Project/Scripts/Common/Utils/StageRecordService.cs
> +            var stageRecord = Get(stageData);
### imo
オーバーライドは確かに便利ですが、`stageData` を渡す `Get()` は流石に廃止して `stageData.StageId` を渡すようにしたいです

2021-07-28 10:44 UTC, xiii111 commented on Assets/Project/Scripts/Common/Utils/StageRecordService.cs
> +            var isReleased = stageData.ConstraintStages.Select(constraintStage => StageRecordService.Instance.Get(constraintStage)).All(record => record.IsCleared);
### nits

以下のように書ける

```suggestion
            var isReleased = stageData.ConstraintStages.Select(Get).All(record => record.IsCleared);
```

### imo
`constraintStages` という名前、`constraintStageIds` にした方が誤読しなさそうです

2021-07-28 10:44 UTC, xiii111 commented on Assets/Project/Scripts/Modules/StageSelectScene/StageController.cs
> +            state = StageRecordService.Instance.GetStageState(stageData);
良いですね 👍

2021-07-28 13:51 UTC, takasusuke requested changes
- SuccessPopup/Contents/Stage/Image にAspectRatioFilterをつけて欲しいです。
HeightControlWidthが良さそう

2021-07-28 13:51 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                _successPopupController.Initialize(treeId, stageNumber);
初期化なら、SucessStateのコンストラクタとかで行いたい。

2021-07-28 13:51 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/SuccessPopupController.cs
> +        private const float _STAGE_LIST_CELL_WIDTH_RATIO = 0.19f;
### imo
SpriteRenderer(Unifier)にしたら制御楽そう。
どっちでも可。

2021-07-28 13:51 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/SuccessPopupController.cs
> +            // コンテンツを隠す・表示する
### imo
このコメント、メソッドのドキュメンテーションコメントにあるのが良いと思います。

2021-07-28 13:54 UTC, takasusuke commented
> ### imo
> 現状は、ボタンや画像、テキストがない位置をタップした場合には、ゲーム終了時の盤面をみれると思います。しかし、ボタンなどのタップイベントがない場所全てをタップ領域にしたいです（テキストや画像がある場所もタップしたら、盤面を見たいです）

ImageならRaycastTargetをoffにすれば良いです。
TextMeshProはよくわかってないです。

LayerをUI以外、Decoration Layerみたいなのを作って、反応しないCanvas下のオブジェクトは全部そのレイヤーにするっていうのもありかなと思いました。

2021-07-28 14:03 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                _successPopupController.Initialize(treeId, stageNumber);
そのタイミングだと成功記録がされてないので都合が悪いです。

2021-07-28 14:05 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/SuccessPopupController.cs
> +        private const float _STAGE_LIST_CELL_WIDTH_RATIO = 0.19f;
これは `GridLayoutGroup` のセルの幅を制御するものですので少し違うと思う。
GridLayoutGroupで各アイコン間の距離なども制御できるので採用しています

2021-07-28 14:06 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                _successPopupController.Initialize(treeId, stageNumber);
確かに。
コンストラクタでできることはコンストラクタ(initialize)でやって、このメソッドの名前を変えたい。

2021-07-28 14:07 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/AddressableAssetManager.cs
> +            if (treeData.stageIcon.Asset == null && treeData.stageIcon.RuntimeKeyIsValid()) {
`AssetReference` の `null` 判定みたいなもの

2021-07-28 14:08 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/SuccessPopupController.cs
> +        private const float _STAGE_LIST_CELL_WIDTH_RATIO = 0.19f;
あ、そうだわ。👍

2021-07-28 14:44 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                _successPopupController.Initialize(treeId, stageNumber);
コンストラクタって `Awake` か `Start` のことですか？
それだと `treeId` と `stageNumber` を渡せないのでどの道このメソッドは必要ですが、やるならL 81~L88の処理を別のメソッドにするしかないと思います。

2021-07-28 14:51 UTC, takesi0627 commented
> 対応ありがとうございました！いくつかコメントしました。よろしくお願いします
> 
> ### imo
> 現状は、ボタンや画像、テキストがない位置をタップした場合には、ゲーム終了時の盤面をみれると思います。しかし、ボタンなどのタップイベントがない場所全てをタップ領域にしたいです（テキストや画像がある場所もタップしたら、盤面を見たいです）

これは気づいてなかった。直す。

> ### imo
> `TAP TO RETURN` の演出、素晴らしいと思いました。一点気になったのが、以下のように最も `TAP TO RETURN` が目立つタイミングの視認性が低く感じました。もう少し背景を黒くするか、`TAP TO RETURN` のフォントカラーを白寄りにしても良いと思いました

そこらへん僕としては特にこだわりがないが、かと言ってどれくらいがいいか人それぞれだと思いますので、
よかったら `ReturnButton@idle` のここら辺をいじってみて、どれくらいがいいか教えていただけますか
もしくはそのままコミットしていただいても大丈夫です。

![image](https://user-images.githubusercontent.com/17778395/127343454-59ef5689-5f0d-416b-93a4-4ba705afcc5a.png)

> ### ask
> `Assets/Project/Actors/UIs/Common/Seasons/Spring/FullScreenBackground.png` ってどこかで使っていますか？

あ、説明忘れた。
ローカルで背景と合わせてみたいのでインポートしたらコミットしちゃったんですけど、まあ今後も使うしそのままにした。

> ### ask
> ステージアイコンがある `Spring_1_1` 以外は成功状態を成功画面に反映できてないように見えますが、想定挙動でしょうか？

これよくわかっていないですが、僕が上がった動画だと反映できていますが、
画像とか添付してくれませんか

2021-07-28 14:52 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                _successPopupController.Initialize(treeId, stageNumber);
SuccessStateのコンストラクタで、SuccessPopupControllerの`Initialize(treeId, stageNumber)`を呼んで、
今`Initialize`で呼んでるメソッドのstageDataの部分だけ、`UpdateStageState`とかそれっぽい名前にしたい。

2021-07-28 14:52 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/StageRecordService.cs
> +        /// <param name="stageData"></param>
22c222a

2021-07-28 14:53 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/StageRecordService.cs
> +            var stageRecord = Get(stageData);
a2d39b8

2021-07-28 14:56 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/StageRecordService.cs
> +            var isReleased = stageData.ConstraintStages.Select(constraintStage => StageRecordService.Instance.Get(constraintStage)).All(record => record.IsCleared);
> constraintStages という名前、constraintStageIds にした方が誤読しなさそうです

SerializedFieldに絡むので、一旦そのままで

2021-07-28 14:56 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                _successPopupController.Initialize(treeId, stageNumber);
あ、そっちのコンストラクタね

2021-07-28 14:57 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/SuccessPopupController.cs
> +            // コンテンツを隠す・表示する
6fa45a5

2021-07-28 14:58 UTC, takesi0627 commented
> > ### imo
> > 現状は、ボタンや画像、テキストがない位置をタップした場合には、ゲーム終了時の盤面をみれると思います。しかし、ボタンなどのタップイベントがない場所全てをタップ領域にしたいです（テキストや画像がある場所もタップしたら、盤面を見たいです）
> 
> ImageならRaycastTargetをoffにすれば良いです。
> TextMeshProはよくわかってないです。
> 
> UIとBottleとかのLayer以外は反応しない設定になっているので、
> Decoration LayerみたいなLayerを作って、反応しないCanvas下のオブジェクトは全部そのレイヤーにするっていうのもありかなと思いました。

ありがとう！助かる

2021-07-28 15:31 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/AddressableAssetManager.cs
> +            if (treeData.stageIcon.Asset == null && treeData.stageIcon.RuntimeKeyIsValid()) {
なるほど、判定に二つ必要なのダルいな

2021-07-28 15:40 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/StageRecordService.cs
> +            var isReleased = stageData.ConstraintStages.Select(constraintStage => StageRecordService.Instance.Get(constraintStage)).All(record => record.IsCleared);
7524bf3

2021-07-28 15:43 UTC, xiii111 commented
> これは気づいてなかった。直す。

あざます

> そこらへん僕としては特にこだわりがないが、かと言ってどれくらいがいいか人それぞれだと思いますので、
よかったら `ReturnButton@idle` のここら辺をいじってみて、どれくらいがいいか教えていただけますか
もしくはそのままコミットしていただいても大丈夫です。

39ba5f9 でちょろっと暗くしました

> あ、説明忘れた。
ローカルで背景と合わせてみたいのでインポートしたらコミットしちゃったんですけど、まあ今後も使うしそのままにした。

ok!

> これよくわかっていないですが、僕が上がった動画だと反映できていますが、
画像とか添付してくれませんか

すみません、`Spring_1` の木以外の木の話でした

|`Spring_1`|`Spring_1` 以外|
|---|---|
|<img width="377" alt="スクリーンショット 2021-07-29 0 41 44" src="https://user-images.githubusercontent.com/26104258/127353067-bc61ced6-e31d-4caa-b96f-e1aa23eda971.png">|<img width="377" alt="スクリーンショット 2021-07-29 0 42 09" src="https://user-images.githubusercontent.com/26104258/127353128-c3264f6a-c528-4a89-83e7-432e63ccc583.png">
|

2021-07-28 15:43 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/AddressableAssetManager.cs
> +            if (treeData.stageIcon.Asset == null && treeData.stageIcon.RuntimeKeyIsValid()) {
少し違うです。
一つ目の `treeData.stageIcon.Asset == null` はこの木のステージアイコン既に読み込んだかの判定です。
同じ木の違うステージをプレイすると同じアセットが2回ロードすることになってしまうのでこの判定を入れている。
正直ここでするのは良くないと思っているが、今後ステージセレクト画面でもステージボタンを読み込む必要があるのでその時にまた読み込むフローを検討できればと思っています。

2021-07-28 15:43 UTC, xiii111 commented
@takesi0627 返信を行いました

2021-07-28 15:45 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/AddressableAssetManager.cs
> +            if (treeData.stageIcon.Asset == null && treeData.stageIcon.RuntimeKeyIsValid()) {
あーーなるほど。前あったやつか。まとめてどこかで整理したいね

2021-07-28 15:48 UTC, takesi0627 commented
> すみません、`Spring_1` の木以外の木の話でした

それでしたら、予想内の挙動になります。
スプライトがないのでマテリアルが反映しないため、全部同じように見える。
もし `constraintStages` とか設定すれば鍵がつくと思います。

2021-07-28 15:49 UTC, xiii111 approved these changes
ok!

2021-07-28 15:56 UTC, takesi0627 commented
Raycast Targetの設定を行いました

2021-07-28 15:57 UTC, takesi0627 commented
@takasusuke 
改めてお願いします

2021-07-28 15:57 UTC, takesi0627 commented
あ、[これ](https://github.com/LITO-apps/Treevel-client/pull/1040#discussion_r678316542)まだだった。

2021-07-28 16:03 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                _successPopupController.Initialize(treeId, stageNumber);
3afb2e8

2021-07-28 16:04 UTC, takesi0627 commented
@takasusuke 
オネシャス

2021-07-29 12:58 UTC, takasusuke approved these changes
@takesi0627 
> * SuccessPopup/Contents/Stage/Image にAspectRatioFilterをつけて欲しいです。
>   HeightControlWidthが良さそう

これだけお願いします。
異なる縦横比のデバイスだとStageButtonの画像が崩れているので。

2021-07-29 14:37 UTC, merged