失敗画面実装
LITO-apps/Treevel-client pull request #1085
Opened 2021-08-12 03:05 UTC by takesi0627

### 対象イシュー
Close #1036 

### 概要
#985 の議論結果に基づいた失敗画面の実装

### 詳細

#### 現実装になった経緯

#### 技術的な内容

* カメラのレイヤー分けについて
「背景のボトルやギミックをグレースケールをかける」という仕様を満たすため、UIと非UIを違うカメラで写すように実装しました（`UI Camera` と `Main Camera` を `GamePlayScene`に配置しています）。
UIカメラは以下のように設定しています。その他の設定は大体メインカメラと同じです。
![image](https://user-images.githubusercontent.com/17778395/129131995-f7f3efa3-3651-45c2-bef2-731c25024525.png)

### キャプチャ

### 動作確認方法

### 参考 URL
[layered camera](https://www.youtube.com/watch?v=bbnVpPiQ_rU)
[カメラのグレースケール](https://baba-s.hatenablog.com/entry/2019/04/22/001600)

2021-08-12 03:19 UTC, takesi0627 commented
@LITO-apps/engineer 
お待たせしました。レビューよろしくお願いします。
30分以上はかかると思われます

2021-08-12 04:54 UTC, xiii111 requested changes
素晴らしいです！！動作に関しては一点だけコメントがあります

打ち合わせ中に口頭で話した気がしますが、失敗時の盤面を見る場合にはグレースケールを解除したいです。ユーザは失敗した時の状況を顧みたときに、色がないとギミックやタイルがどの種類か判断できないからです

<img src="https://user-images.githubusercontent.com/26104258/129138513-7bc0ad86-7a6b-40e5-b14f-28c9aa12dfb9.png" width="300">

### ask
- `ShareButton` は `Success` でも `Failure` でも利用されていますが、Prefab にはしないですか？

2021-08-12 04:54 UTC, xiii111 commented on Assets/Project/Shaders/GrayScalePostEffect.shader
> +}
### nits

No newline at end of file

2021-08-12 04:54 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/SeasonId.cs
> +        public static Color GetButtonColor(this ESeasonId seasonId)
### imo
Entity が UI の事情に左右されたくないので、名前に `Button` を使いたくないです。あくまでも `MainColor` や `SubColor` をボタンやテキストが利用しているだけ、という構図にしたいです

`ButtonTextColor` においても同様です

### ask
`GetColor` との棲み分けはどうなっていますか？

2021-08-12 04:54 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/GrayScaleCamera.cs
> +        private void OnRenderImage( RenderTexture src, RenderTexture dest )
### nits

```suggestion

        private void OnRenderImage( RenderTexture src, RenderTexture dest )
```

2021-08-12 04:54 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/SuccessPopupController.cs
> +    public class SuccessPopupController : MaskedPopup
素晴らし 🎉

2021-08-12 04:54 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/UIs/ButtonWithPressedImage.cs
> +        private void Awake()
### nits

```suggestion

        private void Awake()
```

2021-08-12 04:54 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/FailurePopupController.cs
> +        }
### imo

`ShareButton` を `Prefab` にすれば、この処理を `ShareButton` のスクリプトとしてアタッチできるから、重複したコードを減らせる気がする

2021-08-12 06:37 UTC, takesi0627 commented on Assets/Project/Shaders/GrayScalePostEffect.shader
> +}
453cf3f

2021-08-12 06:40 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/SeasonId.cs
> +        public static Color GetButtonColor(this ESeasonId seasonId)
画面によって使いたい色は違うと思うので流石に `MainColor`・ `SubColor` などでは扱いきれないと思います。
`GetColor` は現状 成功ポップアップと記録画面で使われていますが、今後も調整する方向になるかと思います。

@takasusuke そこらへんの管理って何か考えありますか

2021-08-12 06:45 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/FailurePopupController.cs
> +        }
ツイートする内容は違うから Prefabにしても違う画面ではメソッド違うからアタッチだけでは完全に制御できないんですよね。
やるとしたら`TwitterUtility.Post(string content)` みたいなやつ作ったほうがいいかなと思いました。

2021-08-12 06:55 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/FailurePopupController.cs
> +        }
あーーツイート内容違うのか。確かに。というか、失敗時に何を Share するんだっけ ... 

とりあえず、このレビューは対応しなくて良いです

2021-08-12 06:56 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/FailurePopupController.cs
> +        }
> やるとしたらTwitterUtility.Post(string content) みたいなやつ作ったほうがいいかなと思いました。

これはやりたいですね。repository 層に当たると思います

2021-08-12 06:57 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/SeasonId.cs
> +        public static Color GetButtonColor(this ESeasonId seasonId)
であれば、色を使うクラスで private な拡張関数を定義したいです！あくまでも何かに依存しない形で entity を構成していくことが大事だと（薄っぺらい）知識があるので、実践してみたい感じです

2021-08-12 06:59 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/SeasonId.cs
> +        public static Color GetButtonColor(this ESeasonId seasonId)
ここでいうとFailurePopUpに閉じておけばいいですか？

2021-08-12 07:00 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/SeasonId.cs
> +        public static Color GetButtonColor(this ESeasonId seasonId)
Button は FailurePopup という UI に属しているものなので、その中で閉じている拡張関数として定義するのであれば、問題ないと思います！

2021-08-12 07:29 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/SeasonId.cs
> +        public static Color GetButtonColor(this ESeasonId seasonId)
f503653
`private`のインナークラスとして定義することができなかったので外で `internal` にしました

2021-08-12 08:00 UTC, takesi0627 commented
> 打ち合わせ中に口頭で話した気がしますが、失敗時の盤面を見る場合にはグレースケールを解除したいです。ユーザは失敗した時の状況を顧みたときに、色がないとギミックやタイルがどの種類か判断できないからです

2bb70c0
マスク閉じた時にグレースケールを解除するようにしました。
ついでにですが、`FailurePopupController`、`SuccessPopupController` 別にマスククラスを継承する必要がないなと思ってバラしました。

2021-08-12 08:02 UTC, takesi0627 commented
@xiii111 改めてレビューお願いします

2021-08-12 08:03 UTC, xiii111 commented
土曜になる可能性あります

2021-08-12 13:32 UTC, takasusuke requested changes
以下のように比率の異なるデバイスでは傷がはみ出たりしているので
- FailurePopup/Contents/ScrathesのTopとBottomの値は0でお願いします。
- FailurePopup/Cntents/Scrathes/Scratchの5つにAspectRatioFilterをつけて欲しいです。
- FailurePopup/Cntents/Scrathes/Scratchの位置は比率指定で中心座標を決めて欲しいです。

<img width="330" alt="スクリーンショット 2021-08-12 22 08 16" src="https://user-images.githubusercontent.com/26213141/129202215-3caa0af5-acc1-4f29-acea-982629904c33.png">

2021-08-13 05:46 UTC, takesi0627 commented
> 以下のように比率の異なるデバイスでは傷がはみ出たりしているので
> 
> * FailurePopup/Contents/ScrathesのTopとBottomの値は0でお願いします。
> * FailurePopup/Cntents/Scrathes/Scratchの5つにAspectRatioFilterをつけて欲しいです。
> * FailurePopup/Cntents/Scrathes/Scratchの位置は比率指定で中心座標を決めて欲しいです。
> 

702fe62
レイアウトの調整しました

2021-08-13 12:17 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/SeasonId.cs
> +        public static Color GetButtonColor(this ESeasonId seasonId)
> privateのインナークラスとして定義することができなかった

あーなら今までとアクセス制御が変わらないですね ... んーー

> 画面によって使いたい色は違うと思うので流石に MainColor・ SubColor などでは扱いきれないと思います。

ということは、画面内で定義するべき、というのは分かるのですが、private の拡張関数として定義できないとなると、どうやってこの課題を解決するのが良いんだろうか。

申し訳ないですが、一旦、今回の `internal` にしてくれた変更はリバートして、`SeasonId.cs` 内の `GetButtonColor` と `GetButtonTextColor` に注釈として、この議論へのリンクを貼ってもらえると助かります🙏

2021-08-13 12:18 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/FailurePopupController.cs
> +        }
とりあえず、解決にしておきます

2021-08-13 12:22 UTC, xiii111 commented
@takesi0627 

> ついでにですが、FailurePopupController、SuccessPopupController 別にマスククラスを継承する必要がないなと思ってバラしました。

継承していたの、よかったと思いましたが、だめですか？あと、 2bb70c0 で `MaskedPopup` を `PopupMask` にリネームした意図はなんですか？`FailurePopupController`、`SuccessPopupController` が継承しなくなった今、そもそも `PopupMask` ってどこかから使われているんでしたっけ？

2021-08-13 12:26 UTC, xiii111 commented
> マスク閉じた時にグレースケールを解除するようにしました。

これは良さそうでした！

2021-08-13 12:27 UTC, xiii111 requested changes
以下の対応（返信）だけお願いします！
- [x] https://github.com/LITO-apps/Treevel-client/pull/1085#discussion_r688468654
- [x] https://github.com/LITO-apps/Treevel-client/pull/1085#issuecomment-898421543

2021-08-13 14:29 UTC, takesi0627 commented
> 継承していたの、よかったと思いましたが、だめですか？

マスク単体としても機能するので、例えば今後別の画面でも同じようなマスクが必要とした時は
マスクのコンポーネントさえ作れば機能するのでそれがいいと思います。

> あと、[2bb70c0](https://github.com/LITO-apps/Treevel-client/commit/2bb70c018fb16430ee44db34ce2afdec656c2944) で `MaskedPopup` を `PopupMask` にリネームした意図はなんですか

* 変更前：`マスクがあるポップアップ`という意味でポップアップが主体なので `MaskedPopup` とした。
* 変更後：`ポップアップで使うマスク`になってただのマスクになったから `PopupMask`に変更しました。 

> `FailurePopupController`、`SuccessPopupController` が継承しなくなった今、そもそも `PopupMask` ってどこかから使われているんでしたっけ？

各ポップアップのプレハブの `Mask` にアタッチしています。
![image](https://user-images.githubusercontent.com/17778395/129371917-9888c3fc-7f9d-4d23-9760-91a8e2869a6a.png)

失敗ポップアップに関しては、マスクが閉じる時に何かしたい都合があるので、マスクをメンバー変数で参照し、マスクのOn・Off時に発生するイベントを購読しています。

2021-08-13 14:37 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/SeasonId.cs
> +        public static Color GetButtonColor(this ESeasonId seasonId)
7cbd4c8
f69aceb

2021-08-14 06:55 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/SeasonId.cs
> +        public static Color GetButtonColor(this ESeasonId seasonId)
最高

2021-08-14 07:00 UTC, xiii111 approved these changes
対応ありがとうございます！良いと思います！！

2021-08-14 14:34 UTC, takasusuke approved these changes
お疲れサマンサタバサ

2021-08-14 14:36 UTC, merged

2021-08-14 14:37 UTC, takesi0627 commented
ありがとうございマッスル