AimingMeteoriteの演出実装
LITO-apps/Treevel-client pull request #1088
Opened 2021-08-14 15:11 UTC by takasusuke

### 対象イシュー
Close #849

### 概要
タイトルまま

### 詳細
- AimingMeteoriteの実装は話し合いの段階で確定していなく、実装してみて物足りなければ演出追加、という感じだった
(https://lito-apps.slack.com/archives/CJ30Q29HQ/p1616068033006400)
AimingMeteoriteの軌跡をMeteoriteと変更する、出現位置を変えるいう部分に関しては特になくても問題ないと感じて実装していません

#### 現実装になった経緯
- MeteoriteControllerの中でAimingMeteoriteかどうか判断していた実装を、AimingMeteoriteControllerに分離しました。
MeteoriteControllerとAimingMeteoriteControllerの違いが分かりやすくなると思いました
- Bottleの移動が完了したタイミングでAimingMeteoriteの落ちる位置を更新するようにした
TileとTileの間とかにAimingMeteoriteが落ちるようになったりしても嫌だなと思ったのでこうしました。(あと、GustWindとかと組み合わさってバグが起きないように)
- 追従することが伝わる && 目標位置が確定してからBottleが逃げられるよに、AimingMeteoriteが落ち始めるまでの時間(animation)はMeteoriteより長くしてあります。

#### 技術的な内容

### キャプチャ
https://user-images.githubusercontent.com/26213141/129450725-89bbfc20-8e1f-4398-8741-653c97ee0d5f.mov

### 動作確認方法
Spring_1_7をプレイ

- [ ] Bottleの移動が完了したタイミングで影が追従することを確認する
- [ ] ゲーム成功時、失敗時にMeteoriteが消えない

### 参考 URL

2021-08-14 15:12 UTC, takasusuke commented
@LITO-apps/engineer 
1hかからないくらい？だと思います
よろしくお願いいたします

2021-08-14 15:13 UTC, takasusuke commented
be34956 でアニメーション作ったつもりだったけど、unity保存してなくて変更消えたので
70b6ffd で改めてcommitしてます

2021-08-16 11:31 UTC, xiii111 requested changes
対応ありがとうございます！動画の前半、追従しているのがわかって面白いですね

以下、動作周りを中心にしたコメントです

### must
`Spring_1_1` をプレイしようとすると、エラーが発生し、プレイできないようです。確認できますか？（`Spring_1_2` など複数のステージで発生するようです）

<img width="558" alt="スクリーンショット 2021-08-16 20 07 55" src="https://user-images.githubusercontent.com/26104258/129554749-080542d0-2853-418c-ae86-3a3a61cbe16e.png">

https://user-images.githubusercontent.com/26104258/129554680-abad90ac-b8cb-45b2-bd15-179b48bb3cf2.mov

### must
`Spring_1_7` すると、`AimingMeteorite` は出現せず、`ErasableGimmick` などが出現してしまいます（おそらく index がずれています）。エラーも発生しているので、合わせてあげておきます

<img width="1134" alt="スクリーンショット 2021-08-16 20 12 58" src="https://user-images.githubusercontent.com/26104258/129555253-47666019-84c5-4d8a-ac86-f91b18b24b69.png">

https://user-images.githubusercontent.com/26104258/129555341-2dee3b5d-6ddf-41cc-8648-97e13eaa3ce3.mov

2021-08-16 11:31 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Meteorite/MeteoriteControllerBase.cs
> +        protected float attackAnimationTime;
### nits

`private` にできるようです

2021-08-16 11:31 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Meteorite/MeteoriteControllerBase.cs
> +        protected void Awake()
### ask

`C#` 詳しくないですが、これって `override` ではないんでしたっけ？

2021-08-16 11:43 UTC, takasusuke commented
> ### must
> `Spring_1_1` をプレイしようとすると、エラーが発生し、プレイできないようです。確認できますか？（`Spring_1_2` など複数のステージで発生するようです）
> `Spring_1_7` すると、`AimingMeteorite` は出現せず、`ErasableGimmick` などが出現してしまいます（おそらく index がずれています）。エラーも発生しているので、合わせてあげておきます

多分branch切り替えると出ると思っていて、branch切り替えてからUnity再起動すると出なくなると思うんだけど、対応必要？
（といっても何が原因かわかってない。）

2021-08-16 15:04 UTC, xiii111 commented
> 多分branch切り替えると出ると思っていて、branch切り替えてからUnity再起動すると出なくなると思うんだけど、対応必要？
（といっても何が原因かわかってない。）

知らなかったーー無事実行できました

2021-08-16 15:20 UTC, xiii111 requested changes
追加でいくつかコメントしました！

2021-08-16 15:20 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Meteorite/MeteoriteControllerBase.cs
> +        protected static readonly int ATTACK_STATE_NAME_HASH = Animator.StringToHash("Meteorite@attack");
### nits

これは `MeteoriteController` でしか使われていないようなので、そちらに定義したいです

2021-08-16 15:20 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Meteorite/MeteoriteControllerBase.cs
> +        private const string _ATTACK_ANIMATION_CLIP_NAME = "Meteorite@attack";
### nits

`Rider` が言うには、`Animator.StringToHash` を利用した方が良いらしいです

2021-08-16 15:20 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Meteorite/MeteoriteControllerBase.cs
> +
### nits

```suggestion
```

2021-08-16 15:20 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Meteorite/AimingMeteoriteController.cs
> +            disposable.Disposable = _bottleController.EndMove.Subscribe(_bottleController => {
```suggestion
            disposable.Disposable = _bottleController.EndMove.Subscribe(_ => {
```

2021-08-16 15:20 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Meteorite/AimingMeteoriteController.cs
> +        private float _TIME_TO_FINISH_AIMING = 0.2f;
```suggestion
        private const float _TIME_TO_FINISH_AIMING = 0.2f;
```

2021-08-16 15:20 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Meteorite/AimingMeteoriteController.cs
> +            disposable.Disposable = _bottleController.EndMove.Subscribe(_bottleController => {
### ask

以下の書き方ではダメなのは、なぜでしたっけ？

```suggestion
            var disposable = _bottleController.EndMove.Subscribe(_bottleController => {
```

2021-08-17 06:28 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Meteorite/MeteoriteControllerBase.cs
> +        protected float attackAnimationTime;
8b68c9d

2021-08-17 06:38 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Meteorite/MeteoriteControllerBase.cs
> +        protected static readonly int ATTACK_STATE_NAME_HASH = Animator.StringToHash("Meteorite@attack");
f72e936

2021-08-17 06:39 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Meteorite/MeteoriteControllerBase.cs
> +        private const string _ATTACK_ANIMATION_CLIP_NAME = "Meteorite@attack";
f77516a

2021-08-17 06:59 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Meteorite/AimingMeteoriteController.cs
> +        private float _TIME_TO_FINISH_AIMING = 0.2f;
078d703

2021-08-17 07:00 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Meteorite/MeteoriteControllerBase.cs
> +
9b90a4a

すぐ近くで同じイベントを購読していたのでついでにまとめた

2021-08-17 07:03 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Meteorite/AimingMeteoriteController.cs
> +            disposable.Disposable = _bottleController.EndMove.Subscribe(_bottleController => {
SingleAssignmentDisposable
という１つしかDispose対象を設定できないIDisposableを明示的に使っていて、それの書き方がobjectを作って、
Disposableにsetする書き方だから。(2回目にDisposableにsetすると例外が投げられる)
`WarningProcess`で閉じている購読処理だから使ってみた。

15de34f

Riderのおすすめ通りに多少記述は変えた

2021-08-17 07:04 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Meteorite/AimingMeteoriteController.cs
> +            disposable.Disposable = _bottleController.EndMove.Subscribe(_bottleController => {
https://github.com/LITO-apps/Treevel-client/pull/1088#discussion_r690091266
にまとめ

2021-08-17 07:10 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Meteorite/MeteoriteControllerBase.cs
> +        protected void Awake()
TileやBottleはちゃんとoverrideしてたけどGimmickは適当だったから全部明示的にoverrideするようにしました

4913cbe

2021-08-17 07:12 UTC, takasusuke commented
@xiii111 
再度お願いします

Meteorite落下中に一時停止ポップアップからゲーム終了するとSEが途切れないバグがあったので以下で修正しました(Meteorite以外でも起きてた問題)
多分、ここで購読して特に問題はないはず...
53c06e9

2021-08-17 09:15 UTC, takasusuke commented
@LITO-apps/engineer 
https://docs.google.com/presentation/d/10Vh5hkDJVqCuAyPtfU6cAITBtfL6OtS5GUd03uNW-2U/edit#slide=id.ge623e28ce7_0_21

ステージ選択画面、アイデア切れてきたんで、何でも良いんでコメント・アイデアよろです。
網羅的に案を作ってるわけではないので、良さそうな部分のキメラで案を作る予定。

2021-08-17 10:12 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Meteorite/AimingMeteoriteController.cs
> +            disposable.Disposable = _bottleController.EndMove.Subscribe(_bottleController => {
へーーー初めて知った！素晴らしい！

2021-08-17 10:21 UTC, xiii111 approved these changes
https://lito-apps.slack.com/archives/C01E5GTPRV3/p1629195428006900 にあるように、 53c06e9 をリバートしてアイデアにイシューを作りましょう。あとは問題ないです

2021-08-17 10:23 UTC, takesi0627 commented
死んでるので任せました。
議論は後で追って確認します

2021-08-18 12:42 UTC, takasusuke commented
一時停止中にSEが止まらない問題はこのissueで起きた問題ではないこと、また、すぐ直せそうな問題でもないので
#1095 issueとして別に対処します

それに関わる
53c06e9 
の変更は
042f581
でRevertしました

2021-08-18 12:46 UTC, merged