一時停止画面実装
LITO-apps/Treevel-client pull request #1115
Opened 2021-09-01 14:48 UTC by takesi0627

### 対象イシュー
Close #1110 

### 概要
デザイン草案に基づいて一時停止ポップアップを実装

### キャプチャ
![image](https://user-images.githubusercontent.com/17778395/131691070-b1241752-2b10-4c37-a275-3289001a2ad9.png)

### 動作確認方法
- [ ] 任意のステージをプレイ、一時停止して画面の各機能を確認

2021-09-01 14:55 UTC, takesi0627 commented
@LITO-apps/engineer 
レビューをよろしくお願いします。
10〜30分程度かと思います

2021-09-02 00:32 UTC, xiii111 requested changes
対応ありがとうございます〜！コードはとても簡潔でわかりやすかったです！
以下、動作に関する

### must
`備考` の `今発見する問題` に挙げられている二点はかなり気になるので、対応した方が良さそうです（別イシュー可）

### must
上記と関連するのですが、一時停止ボタンを押したと思われる箇所のパーティクルも残ったままで気になります

### must
またまた上記と関連するのですが、`再開` を押したタイミングで蓄積されていたパーティクル（一時停止ボタンを押した時 + 一時停止画面で点になってたやつ）が一気に解放されて楽しいことになっています

### must
`BGM` と `SE` が調整できないようです、確認お願いします

### imo
cc @takasusuke デザインが確定した後で申し訳ないのですが、`やりなおす` と `あきらめる` にテキストカラーをつけたり、アイコンをつけたりなどして、どちらがどちらなのかをすぐわかるようにした方が良い気がしました。5 文字ですし、毎回どっちがどっちだろうっていうのに時間を使ってしまいました（別イシュー可）

2021-09-02 13:05 UTC, takasusuke requested changes

2021-09-02 13:05 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/PauseWindow.cs
> +            GamePlayDirector.Instance.Dispatch(GamePlayDirector.EGameState.Preparing);
### must
Gimmick周りのエラーが出ているので、リトライ前に失敗時に行うイベントを呼んだほうが良いと思います。
(↓はめっちゃ雑だけど、これをしたい)
```suggestion
            GamePlayDirector.Instance._gameFailedSubject.OnNext(Unit.Default);
            GamePlayDirector.Instance.Dispatch(GamePlayDirector.EGameState.Preparing);
```

<img width="800" alt="スクリーンショット 2021-09-02 22 00 09" src="https://user-images.githubusercontent.com/26213141/131848001-56560726-40ce-47c5-be26-206b6633b4aa.png">

2021-09-02 13:05 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/PauseWindow.cs
> +            _resumeButtonImage.color = treeId.GetSeasonId().GetColor();
### imo
失敗ポップアップとかと合わせるなら
```
_resumeButtonText.color = treeId.GetSeasonId().GetButtonTextColor();
```
も？

2021-09-02 13:13 UTC, takasusuke commented
一時停止中のタップエフェクトの問題は別issueでお願いします。
(Time止めてるからなあ。。。一時停止中はタップエフェクト無くなるかも)
 
> ### imo
> * cc @takasusuke デザインが確定した後で申し訳ないのですが、`やりなおす` と `あきらめる` にテキストカラーをつけたり、アイコンをつけたりなどして、どちらがどちらなのかをすぐわかるようにした方が良い気がしました。5 文字ですし、毎回どっちがどっちだろうっていうのに時間を使ってしまいました（別イシュー可）

別issueで検討します。
そもそも言葉を見直すのが良い気はする。
「やりなおす」の背景に若干SeasonColorっぽい色をつけても良いけど、「やりなおす」と「あきらめる」に視覚的な違いをつけるほどの差異があるのか考えて行うほうが良いと思っている

2021-09-03 00:45 UTC, takesi0627 commented
> ### must
> * `BGM` と `SE` が調整できないようです、確認お願いします

8fb4bb1

https://answers.unity.com/questions/945148/ui-sliders-1.html
これを参考して、 `Canvas` の `Render Mode` を `Screen Space - Overlay` にしたら治りましたが、
ちょっとどういう経緯で `Screen Space - Camera`にしたか覚えてなかった。
一応色々動作確認してみて問題なさそうでした。
しかも `Screen Space - Overlay` にすることで、 `SpriteGlow` が見えなくなったので一石二鳥。

2021-09-03 14:24 UTC, xiii111 commented
@takasusuke 返信ありがとうございます

@takesi0627 議論をまとめると、以下をイシューにすると良さそうです
- 一時停止中のタップエフェクトに関する不具合。内容としては、一時停止中にタップするとエフェクトが点で現れて消えず、一時停止ボタンを押したと思われる箇所でもパーティクルが残ったままになっている。さらに `再開` を押したタイミングで蓄積されていたパーティクルが一気に解放されてしまう
- `やりなおす` と `あきらめる` にテキストカラーをつけたり、アイコンをつけたりなどして、どちらがどちらなのかをすぐわかるようにする

2021-09-03 14:28 UTC, xiii111 approved these changes
LGTM!

https://github.com/LITO-apps/Treevel-client/pull/1115#issuecomment-912578990 に示したイシューを作成してくれれば、私からは何もないです！

2021-09-03 14:29 UTC, xiii111 commented
BGM / SE の問題と、SpriteGlow がおかしい問題は解消されていることを確認しました！

2021-09-03 15:57 UTC, takasusuke commented
94e81a4
TapObject がtime scaleの影響を受けないようにAnimatorを設定しました

参考
https://baba-s.hatenablog.com/entry/2016/11/18/100000

<img width="385" alt="スクリーンショット 2021-09-04 0 52 24" src="https://user-images.githubusercontent.com/26213141/132034137-0527dc78-cedf-4b2d-a190-7c2e96c27840.png">

2021-09-05 06:28 UTC, takesi0627 commented
> [94e81a4](https://github.com/LITO-apps/Treevel-client/commit/94e81a48586dec0d835fd1b958add10a8571b541)
> TapObject がtime scaleの影響を受けないようにAnimatorを設定しました
> 
> 参考
> https://baba-s.hatenablog.com/entry/2016/11/18/100000
> 

こんなことができるんだ！
ありがとう！！

2021-09-05 06:38 UTC, takesi0627 commented
> * `やりなおす` と `あきらめる` にテキストカラーをつけたり、アイコンをつけたりなどして、どちらがどちらなのかをすぐわかるようにする

→ #1120

2021-09-05 06:40 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/PauseWindow.cs
> +            GamePlayDirector.Instance.Dispatch(GamePlayDirector.EGameState.Preparing);
リトライするたびに失敗扱いになるけど、
リトライするだけで失敗回数が増えるのはユーザに不利益と考えますがでどうでしょうか。

逆にいうとリトライすれば失敗にならないから失敗しそうな時にリトライすればいいんだっていう人もいるから、
仕様をちゃんと決めないとダメな気がする

2021-09-05 06:43 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/PauseWindow.cs
> +            _resumeButtonImage.color = treeId.GetSeasonId().GetColor();
その場合帯の色も `GetButtonTextColor` にする？
帯の色とボタンの色同じようにしたいと思っていので、一時停止画面専用の色にしたいかも

2021-09-05 06:47 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/PauseWindow.cs
> +            GamePlayDirector.Instance.Dispatch(GamePlayDirector.EGameState.Preparing);
このイベントは失敗回数を増やす処理は入っていなくて、ギミックやボトルを止めるためのイベントです。
(`FailureState.OnEnter()`参照)

リトライ時の仕様は別途、考えないといけないとは思っています。(アイデアに追加済)

2021-09-05 06:54 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/PauseWindow.cs
> +            _resumeButtonImage.color = treeId.GetSeasonId().GetColor();
そうだねーー
帯の色もボタンの色も一時停止専用の色にしたほうがわかりやすいと思います。

なんとなく赤系かなあと思っているけれど、一旦、何色でも良いかと思います。

2021-09-05 07:02 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/PauseWindow.cs
> +            _resumeButtonImage.color = treeId.GetSeasonId().GetColor();
bc7c64a

こんな感じで、プレハブから設定するようにしてみたがどうでしょうか。 @xiii111 この方法が良ければ `GetButtonTextColor` の問題をこれと同じ方法で解決したいですがどうですか
![image](https://user-images.githubusercontent.com/17778395/132118429-122130c9-2f63-4a9a-a0b9-9c36db42c46a.png)

2021-09-05 07:16 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/PauseWindow.cs
> +            GamePlayDirector.Instance.Dispatch(GamePlayDirector.EGameState.Preparing);
同じあことアイデアに書いてくれてるぅー

2021-09-05 14:34 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/PauseWindow.cs
> +            GamePlayDirector.Instance.Dispatch(GamePlayDirector.EGameState.Preparing);
0211bb5

とりあえずこれでエラー回避できるがまだ議論する余地あるかもしれない。

2021-09-05 14:34 UTC, takesi0627 commented
@takasusuke 
改めてレビューお願いします

2021-09-06 13:18 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/PauseWindow.cs
> +            _resumeButtonImage.color = treeId.GetSeasonId().GetColor();
`PauseColor`はどの季節も同じ色にすると思ってた。
（けど、これも良いなあ。。。）

2021-09-06 13:21 UTC, takasusuke approved these changes

2021-09-06 13:48 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/PauseWindow.cs
> +            _resumeButtonImage.color = treeId.GetSeasonId().GetColor();
`SeasonId.GetDarkColor`
`SeasonId.GetLightColor`
`SeasonId.GetDarkTextColor`
`SeasonId.GetLightTextColor`
にまとめる

2021-09-06 13:50 UTC, takasusuke requested changes
SeasonColorなど、特定のUIに依存しないColorはDomain扱いでお願いします。
SeasonDarkColot
SeasonTextColor

2021-09-09 04:24 UTC, takesi0627 commented
@takasusuke 
お願いします

もっと広義的がいいと思うので、名前は背景色/テキスト色は→`Background/Foreground`にしました。基本的に テキストは `Foreground`を使うと思っていただいて大丈夫です。

2021-09-09 04:26 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/SeasonId.cs
> +                ESeasonId.Winter => new Color(0x18 / 255.0f, 0x32 / 255.0f, 0x33 / 255.0f),
ここの色はまだ使うところないので、
[Colorbase](https://colorbase.app/colors/183233)というサービスを使って決めてみました。
都合上HEX表記の方しか検索できないので、HEX表記にしました

2021-09-09 11:51 UTC, takesi0627 commented
@LITO-apps/engineer 
1a9a1f6
議論通りに `ColorSet`を実装しました。
確認よろしくお願いします

2021-09-09 12:03 UTC, takasusuke approved these changes
お疲れ様です

2021-09-09 12:32 UTC, merged