フェードイン中BGM音量を設定する時にフェードし続ける問題を修正
LITO-apps/Treevel-client pull request #1121
Opened 2021-09-05 16:04 UTC by takesi0627

### 対象イシュー
Close #884 

### 概要
タイトル通り

### 詳細

#### 現実装になった経緯
* d48c99f
作業始めたら、フェイドイン機能がいつの間にか機能してなかったことを発覚。
原因は `PlayBGM` でBGMを再生する前に一個前のタスクをキャンセルするようにしていますが、
`_fadeCancellationToken` がキャンセルされたらすぐその後の `FadeBGMVolumeAsync`は当然機能しない。
そのため、キャンセル直後に `dispose`し、新たなキャンセルトークンソースを再生するようにしました。

* c33c13a
本題の問題を解決するために、 BGMの音量を調整するときに呼ばれる `ResetBGMVolume`にて `_fadeCancellationToken.Cancel()` を呼び出す。

### 動作確認方法
- [ ] BGMがフェイドインできることを確認
- [ ] BGMフェイドイン中設定画面よりBGMの音量調整して、指定の音量になり、フェイドインしなくなることを確認。

確認する際、`SoundManager.PlayBGM`の引数の`fadeInTime`を5.0とか高くすることをお勧めします。

2021-09-05 16:04 UTC, takesi0627 commented
@LITO-apps/engineer 
よろしくお願いします。
10~15min程度です

2021-09-07 00:25 UTC, xiii111 requested changes
ごめんなさい、`動作確認方法` ですが、フェードイン周りのコードや挙動をあんまり理解できていないせいで、何が正解かわからなかったです ...（多分レビューしてないんだな）

以下では、コード部分に関するコメントをしました！

2021-09-07 00:25 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +            _fadeCancellationToken.Dispose();
### ask
> 作業始めたら、フェイドイン機能がいつの間にか機能してなかったことを発覚。

を解決するためには、トークンを作り直すだけで良いのかと思っていた。実際に、`DynamicBottleController: MoveAsync()` ではそのようになっている

なので、`Dispose` をしないとどういう時に困るのか、少し解説が欲しい。内容次第では `DynamicBottleController` でも修正を入れないといけない

https://docs.microsoft.com/ja-jp/dotnet/api/system.threading.cancellationtokensource.dispose?view=net-5.0 などは眺めてみた

2021-09-07 00:25 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +
### ask
この後にトークン生成をしていないのは、結局 `PlayBGM` でトークンを生成するから？（その場合には、`Cancel` が一回余分に走っている？）

2021-09-07 00:25 UTC, xiii111 commented
@takasusuke お手隙のタイミングで、動作確認お願いしても良いですか？

2021-09-07 15:48 UTC, takasusuke requested changes
- 今まで気づかなかったんだけど、
`fadeCancellationToken`は`CancelletionTokenSource`だから、`FadeBGMVolumeAsync`に`fadeCancellationToken.Token`を渡さないと、`while loop`のたびに、`Token`が作られてるね。
https://github.com/LITO-apps/Treevel-client/blob/c33c13ad84408307bf8b52de22ee666648a1e462/Assets/Project/Scripts/Common/Managers/SoundManager.cs#L334


- いつからかわからないけど、最初にBGMを再生するときからすでにFadeInがかかってないようです。(`FadeBGMVolumeAsync`の`while loop`に入った瞬間にキャンセルがかかってる。

2021-09-11 15:12 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +            _fadeCancellationToken.Dispose();
![image](https://user-images.githubusercontent.com/17778395/132952331-38ace200-108e-4130-85f5-2a6ec28586c3.png)
![image](https://user-images.githubusercontent.com/17778395/132952367-aae68d14-0425-48a2-839f-e6ac92f33a3d.png)

キャンセル直後にトークンを発行し直しても、キャンセルされる扱いになっている

2021-09-11 15:14 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +            _fadeCancellationToken.Dispose();
`Dispose` するのはどちらかというと保険のためかな。
`_fadeCancellationToken = new CancellationTokenSource();` の前と後はTokenSourceのインスタンスが変わったので、
前のTokenSourceが何か残していたとしたら、newの後にそれを消すことができなくなってしまうので、Disposeしておいた方がいいかと思っています。

2021-09-11 15:33 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +            var token = _fadeCancellationToken.Token;
トークンを whileループの直前に作り直すことにしました。

2021-09-11 15:33 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> -
この後 `ResetBGMVolume` を呼んでいるので、 `ResetBGMVolume` の中にキャンセルしているので、
ここのキャンセルは不要になりました

2021-09-11 15:34 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +
https://github.com/LITO-apps/Treevel-client/pull/1121#discussion_r706626604
書き方変えました
複数回キャンセルことはなくなるはず

2021-09-11 22:02 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +            _fadeCancellationToken.Dispose();
> キャンセル直後にトークンを発行し直しても、キャンセルされる扱いになっている

うん、そうだね。そのために `new CancellationTokenSource` をするよね

> 前のTokenSourceが何か残していたとしたら、newの後にそれを消すことができなくなってしまうので、Disposeしておいた方がいいかと思っています。

ということは、`DynamicBottleController` の `MoveAsync` でも `Dispose()` 入れておいた方が良い？

2021-09-11 22:05 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +
みた、良さそう！

2021-09-11 22:06 UTC, xiii111 approved these changes
LGTM with nits!

### nits
https://github.com/LITO-apps/Treevel-client/pull/1121#discussion_r706696513 にあるように `DynamicBottleController` の `MoveAsync` でも `Dispose` を使った方が良いのであれば、イシューを作るか、サクッと直してもらえると助かります！

2021-09-11 23:35 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +            _fadeCancellationToken.Dispose();
> ということは、DynamicBottleController の MoveAsync でも Dispose() 入れておいた方が良い？

そう思いますね

2021-09-12 00:35 UTC, takesi0627 commented
> LGTM with nits!
> 
> ### nits
> [#1121 (comment)](https://github.com/LITO-apps/Treevel-client/pull/1121#discussion_r706696513) にあるように `DynamicBottleController` の `MoveAsync` でも `Dispose` を使った方が良いのであれば、イシューを作るか、サクッと直してもらえると助かります！

https://github.com/LITO-apps/Treevel-client/pull/1126/files#r706712214
#1126 で今ちょうどそこら辺修正しているので、Disposeするように @takasusuke にお願いしました

2021-09-13 15:41 UTC, takasusuke approved these changes
動作確認できましたーー

2021-09-14 00:25 UTC, merged