一時停止中に止まらないオブジェクトを止める
LITO-apps/Treevel-client pull request #1126
Opened 2021-09-08 16:30 UTC by takasusuke

### 対象イシュー
Close #1103

### 概要
タイトルまま

### 詳細
Warpなど、移動関係の処理が止まっているか確認する。

#### 現実装になった経緯

#### 技術的な内容

### キャプチャ

https://user-images.githubusercontent.com/26213141/132548402-89cc9c93-cc17-458d-8369-1818543b8e0e.mov

### 動作確認方法

### 参考 URL

2021-09-10 14:13 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +                    await UniTask.WaitUntil(() => Time.timeScale > 0.0f, cancellationToken: outerToken);
一時停止中なので、`cancellationToken`が働くことが想定されないので`cancellationToken`を別に設定しなくても問題なさそうだけど、設定しろと関数が言ってきたのでouterTokenを設定。

キャンセルを行うとしたら外部からのキャンセルかと思うので`outerToken`かなと思いました。

2021-09-10 14:14 UTC, takasusuke commented
@LITO-apps/engineer 
20min くらいだと思います。
おねぎゃあいたしやす。

2021-09-11 22:33 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +                    await UniTask.WaitUntil(() => Time.timeScale > 0.0f, cancellationToken: outerToken);
> 設定しろと関数が言ってきたので

なるほど、そうなんだね。

> キャンセルを行うとしたら外部からのキャンセルかと思うので`outerToken`かなと思いました。

そうですね。外からキャンセルされた場合にこのタスクが走っていたら、即時 `OperationCanceledException` が出るのが直感的だと思うので、これでいいと思います

2021-09-11 22:47 UTC, xiii111 requested changes
対応ありがとうございます！動作確認は問題ありませんでした（どんどん GustWind に sunk cost がかかっていて、引き返せない ... 今回は GustWind が根本原因ではないけど ...）

以下、数点コメントしました

### ask
> だとfloat同士の比較で安定しないので、0.0fより大きいかどうかで判定している。

公式ドキュメントを見る感じ、`1.0` との等価判定で良さそうですが、どうですか？

fyi: https://docs.unity3d.com/ja/2018.4/ScriptReference/Time-timeScale.html

### imo

> (timescaleを0.50fとかにしても止まらないので汎用的。)

は、汎用的だとは思いません。今回 TimeScale が 0.0 になった場合には、DynamicBottle の移動を止めているように、TimeScale が 0.5 になった場合には、DynamicBottle の移動は半減するはずです。しかし、この処理だと、半減せずに外部からは暗黙的に移動が正常に行われてしまいます。これは見つけづらいバグが生まれる可能性を高めている気がします

2021-09-12 00:33 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
>              _tokenSourceForMoveAsync = new CancellationTokenSource();
```suggestion
            _tokenSourceForMoveAsync.Dispose();
            _tokenSourceForMoveAsync = new CancellationTokenSource();
```
https://github.com/LITO-apps/Treevel-client/pull/1121#discussion_r703101440
ここの議論にあるように、`new`する前に一回`Dispose`して欲しいですが入れてもらえますでしょうか

2021-09-13 14:07 UTC, takesi0627 commented
作業中に戻します

2021-09-13 15:46 UTC, takasusuke commented
> ### ask
> > だとfloat同士の比較で安定しないので、0.0fより大きいかどうかで判定している。
> 
> 公式ドキュメントを見る感じ、`1.0` との等価判定で良さそうですが、どうですか？
> 
> fyi: https://docs.unity3d.com/ja/2018.4/ScriptReference/Time-timeScale.html

その書き方すると
```
Equality comparison of floating point numbers. Possible loss of precision while rounding values
```
という警告が出て
```
Mathf.Abs(Time.timescale - 1.0f) < epsilon
```
のように書き換えるように言われます

2021-09-13 15:53 UTC, takasusuke commented
> ### imo
> > (timescaleを0.50fとかにしても止まらないので汎用的。)
> 
> は、汎用的だとは思いません。今回 TimeScale が 0.0 になった場合には、DynamicBottle の移動を止めているように、TimeScale が 0.5 になった場合には、DynamicBottle の移動は半減するはずです。しかし、この処理だと、半減せずに外部からは暗黙的に移動が正常に行われてしまいます。これは見つけづらいバグが生まれる可能性を高めている気がします

Timescaleが0になった時は一時停止なのでBottleの移動を止めるとして、
Timescaleが0.5fとかになった時でも、Bottleの移動は通常通りだと考えていたので齟齬があります。
(ユーザの操作に伴う処理以外(ギミックとか)は遅くなるけど、Bottle移動は遅くならない。パズドラの時間止めてる感じ)
なので、この挙動がバグ、という認識がありませんでした。

現状の実装では、Time.timescaleは0fもしくは、0fより大きい何らかの値になることが示唆されています。
```
Mathf.Abs(Time.timescale - 1.0f) < epsilon
```
のように実装した場合、Time.timescaleが連続的に変化する値であることが示唆されるように感じます。

Timescaleが0fもしくは1f以外になる可能性があるなら、実装方法を議論すべきと思いますが、その可能性がなさそうなので、温度感としてはどっちでも良いと思ってます。

2021-09-13 16:04 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
>              _tokenSourceForMoveAsync = new CancellationTokenSource();
c3f7f23

2021-09-14 00:35 UTC, xiii111 commented
@takasusuke 

> Timescaleが0.5fとかになった時でも、Bottleの移動は通常通りだと考えていたので齟齬があります。

なるほど、確かに齟齬があった

> Timescaleが0fもしくは1f以外になる可能性があるなら、実装方法を議論すべきと思いますが、その可能性がなさそうなので、自分の温度感としてはどっちでも良いです。

んーその通りなんだよな。ちゃんとやるなら、`Time.timeScale` が `0` や `1` でなかった場合には、以下のコードに  exception を吐かせるようにしたいけど、まぁ良いか ...（`Time.timeScale` は 0 か 1 という知識をどこかに与えたい）

```csharp
// 一時停止中はBottleを移動させない
await UniTask.WaitUntil(() => Time.timeScale > 0.0f, cancellationToken: outerToken);
```

2021-09-14 00:37 UTC, xiii111 approved these changes
良いと思います！

2021-09-14 15:37 UTC, takasusuke commented
> んーその通りなんだよな。ちゃんとやるなら、`Time.timeScale` が `0` や `1` でなかった場合には、以下のコードに exception を吐かせるようにしたいけど、まぁ良いか ...（このアプリでは `Time.timeScale` は 0 か 1 という知識をどこかに与えたい）

わかる。(が、loop内で判定させるコストは超えてこない。。)

2021-09-14 15:38 UTC, merged