LevelSelect/Record, Othersが表示されない問題の修正
LITO-apps/Treevel-client pull request #1131
Opened 2021-09-11 00:05 UTC by takasusuke

### 対象イシュー
Close #1130

### 概要
#505 でタイトルのバグを発生させてしまったので修正

### 詳細
この他のSafeAreaPanelについては一通り確認し、正しく表示されることを確認した。

#### 現実装になった経緯
特になし

#### 技術的な内容
特になし

### キャプチャ

### 動作確認方法
- [ ] LevelSelect/RecordのFooterを押す。Recordが表示される。
- [ ] LevelSelect/OthersのFooterを押す。Othersが表示される。

### 参考 URL

2021-09-11 00:06 UTC, takasusuke commented on Assets/Project/Scenes/MenuSelectScene.unity
> +    - target: {fileID: 1664642187462754051, guid: 08bc31bccfd004d24846b057a089c860,
勝手に入った差分。

2021-09-11 00:07 UTC, takasusuke commented
@LITO-apps/engineer 
5minで終わります。
空いてる方お願いします。

2021-09-11 22:25 UTC, xiii111 requested changes
対応ありがとうございます！！

### must
以下のように、記録画面では問題が起こる前と後で見た目が若干異なるようです（サークルインジケータの位置が少し高い）今回の修正によるものなのか、 #1119 で混入したのかまでは調べられていないです。確認をお願いできますか？

|#1119 マージ前|本ブランチ|
|---|---|
|<img width="327" alt="before_record" src="https://user-images.githubusercontent.com/26104258/132963007-c23829b1-a1c6-445e-8d07-964cb9e6e554.png">|<img width="322" alt="after_record" src="https://user-images.githubusercontent.com/26104258/132963004-213d67f0-1526-4e04-8984-cb5d99c34e8b.png">|
|<img width="329" alt="before_settings" src="https://user-images.githubusercontent.com/26104258/132963008-5b183b55-639b-4196-ad92-812ab1f1477b.png">|<img width="329" alt="after_settings" src="https://user-images.githubusercontent.com/26104258/132963006-b6231ce7-f8d2-4291-a46d-289b0f2f0166.png">|

2021-09-13 17:14 UTC, takasusuke commented
@xiii111 
> ### must
> 以下のように、記録画面では問題が起こる前と後で見た目が若干異なるようです（サークルインジケータの位置が少し高い）今回の修正によるものなのか、 #1119 で混入したのかまでは調べられていないです。確認をお願いできますか？

確認しました。

SafeArea Panelを、[DefaultExecutionOrder(-100)]とかにするとWidthとHeightが異なる値のRectが取得された(以前の状態が再現された)ことから原因を以下のように推測しました。

サークルインジケータの位置を決めるために、インジケータが乗っている円のRectの大きさを取得しています。
その円にはAspectRatioFilterがついているのに、以前までは取得できるWidth, Heightが同じ値ではありませんでした。
取得するタイミングと、AspectRatioFilterとCanvasScaler等の縦横比の調整が入るタイミングが前後しているのが原因？(これは憶測)

今回、新しくSafeAreaPanelを作り直したことで、SafeAreaPanel配下の円やインジケータのオブジェクトも内部的な値が新しくなった？ことでAspectRatioFilter等の調整が入るタイミングとRectを取得するタイミングが入れ替わった？と思われます。
その結果、取得できる円のRectのWidthとHeightが同じ値で取得されるようになりました。(取得するHeightの値が変わったので、インジケータの高さもズレた)

対応するにしても、円グラフだと闇深そうだから、もうちょい安全で効果的な表示方法も考えたいかもしれん。。。
(インジケータの実装を変えたり、失敗グラフみたいに、色を塗るとか)
というアイデアを追加しておきました。

2021-09-14 00:27 UTC, xiii111 approved these changes
原因調査ありがとうございます。円グラフが確定デザインではないことなどから、対応方法も同意します

2021-09-14 00:28 UTC, xiii111 commented
@takasusuke この変更は各所に必要だと思うのでマージしてしまいますね🙏

2021-09-14 00:28 UTC, merged