実機でLevelSelectSceneにおける`NullReferenceException`の解消
LITO-apps/Treevel-client pull request #1146
Opened 2021-09-16 11:33 UTC by takesi0627

### 対象イシュー
Close #971 

### 概要
タイトル通り

### 詳細
実機でレベル選択画面にて`NullReferenceException` が発生する原因はスクリプトの実行順の問題でした。
そのため、 `LevelSelectDirector`、`LevelTreeController`、`RoadController`のスクリプトが互いの実行順が依存しないように修正を行いました。
#### 現実装になった経緯
主な変更点として以下の３つがある。

* UpdateStateの実行をLevelSelectDirectorから`LevelTreeController`、`RoadController`それぞれ自身の`OnEnable`に移す。
* `LocalSaveManager`を作成し、LevelSelectDirectorが持っている`releaseAnimationPlayedTrees`をそこで管理する。LevelSelectDirectorが持っていると、`LevelTreeController`や`RoadController`が参照したいときにまだ初期化されない可能性があるので、`GameDataManager`みたいな役割で管理する必要があると判断したためです。
* `RoadController`は `LevelTreeController` の `state`の計算を依存していたので、その計算を`StageRecordService`に移動する

### 動作確認方法
- [ ] 実機もしくはSimulatorにビルドし、LevelSelectSceneにて該当エラーが発生しないことを確認
- [ ] エディタでプレイし、今までと動作変わらないこと、（特に木の解放演出周りの確認）

2021-09-16 11:46 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/StageRecordService.cs
> +                return clearHandler.GetTreeState();
### `ask`

`clearHandler`内部でまた `StageRecordService` を呼び出しているという怪奇現象が起こっているので、
ここは `clearHandler.GetTreeState(clearNumber)` として `clearNumber`を渡すような形にしたかったんですが、
それだと `ITreeClearHandler`のシグネチャーを変えないといけないし、最初このインタフェースを設計したときの意図に反することになるんじゃないかと思いましたので断念しました。（最初は確かにクリアステージ数で判断するとは限らない形にしたいと今の実装に至ったと記憶している）

しかし、何回か議論になったと思いますが、`NumClearTreeHandler`の中に`StageRecordService`を依存するのは良くないとのことでこれを機に改善したいのです。
個人的にいっそ上記の案でシグネチャーを変えてしまいたいですが、他に何か案がありますでしょうか

2021-09-16 11:48 UTC, takesi0627 commented
@LITO-apps/engineer 
かなり大幅のリファクタリングになってしまいましたが、
依存関係を綺麗にしたつもりです。

レビューは念入りでみてもらえると助かります。
よろしくお願いします。

2021-09-18 12:39 UTC, xiii111 commented
📝 こちらの確認は `2020.3.18f1 `でするようにします

2021-09-18 13:06 UTC, xiii111 commented
📝 `2020.3.18f1 ` でも同様の問題が再現したので、普通にレビューを再開します

2021-09-18 13:27 UTC, xiii111 commented
📝 以下のエラーが発生しないところまでは確認した
```
NullReferenceException: Object reference not set to an instance of an object.
  at Treevel.Modules.MenuSelectScene.LevelSelect.LevelTreeController.UpdateState () [0x00027] in /Users/aoi/Treevel-client/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs:51 
  at Treevel.Modules.MenuSelectScene.LevelSelect.LevelSelectDirector+<>c.<OnEnable>b__6_0 (Treevel.Modules.MenuSelectScene.LevelSelect.LevelTreeController tree) [0x00001] in /Users/aoi/Treevel-client/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelSelectDirector.cs:67 
  at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x00000] in <00000000000000000000000000000000>:0 
  at Treevel.Modules.MenuSelectScene.LevelSelect.LevelSelectDirector.OnEnable () [0x0004f] in /Users/aoi/Treevel-client/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelSelectDirector.cs:67 
```

2021-09-18 14:11 UTC, takasusuke requested changes
### nits
このissue関係ないけど、直してもらいたい問題がありました。
`PlayerPrefsUtility.cs`の`SetList<T>()`(と`SetDictionary<Key, Value>()`)で
`PlayerPrefs.Save();`呼んでない。。。(LevelSelectを離れるときに、`UserSettings.cs`経由で`PlayerPrefsUtility.cs`の`SetObject`呼んでて、そっちは`Save()`してるので挙動は何とかなってた。)
`Save()`を追加しておいてもらえますか？

### must
Editorにて、以下のように、Stageの解放演出が行われない時がありました。(行われる時もある）
`StageRecordDirector`も`LevelSelectDirector`と同じように実装すれば直る？？
`StageRecordDirector.OnEnable()`を`StageRecordDirector.Start()`にしたり、
`StageRecordDirector.OnEnable()`で
```
// 枝野状態を更新
_branches.ForEach(branch => branch.UpdateState());
// ステージボタンの状態を更新
_stages.ForEach(stage => stage.UpdateState());
```
を呼び出さずに、`BranchController.cs`, `StageController.cs`の`OnEnable()`で各自が`UpdateState()`を呼ぶようにするなど、基本的に全部同じにしたい。

https://user-images.githubusercontent.com/26213141/133891635-aacdaac0-e33c-40e3-9090-f265443334d8.mov

2021-09-18 14:11 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Settings/ResetController.cs
>              PlayerPrefs.DeleteKey(Constants.PlayerPrefsKeys.STAGE_ANIMATION_STATE);
### imo
この行も
`LocalSaveManager.Reset()`でいかがでしょうか

2021-09-18 16:06 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Settings/ResetController.cs
>              PlayerPrefs.DeleteKey(Constants.PlayerPrefsKeys.STAGE_ANIMATION_STATE);
あ、移すの忘れた

2021-09-18 16:16 UTC, takesi0627 commented
> ### must
> Editorにて、以下のように、Stageの解放演出が行われない時がありました。(行われる時もある）
> `StageRecordDirector`も`LevelSelectDirector`と同じように実装すれば直る？？
> `StageRecordDirector.OnEnable()`を`StageRecordDirector.Start()`にしたり、
> `StageRecordDirector.OnEnable()`で
> 
> ```
> // 枝野状態を更新
> _branches.ForEach(branch => branch.UpdateState());
> // ステージボタンの状態を更新
> _stages.ForEach(stage => stage.UpdateState());
> ```
> 
> を呼び出さずに、`BranchController.cs`, `StageController.cs`の`OnEnable()`で各自が`UpdateState()`を呼ぶようにするなど、基本的に全部同じにしたい。

正直 `StageSelectScene` 周りの修正はあんまりここでやりたくないですが、ただ `LocalSaveManager` 作っちゃったからアニメーション保存周り一緒にやっとこという軽い気持ちでやっちゃったんです。
 #1134 も同じ原因でエラー起きてるので `UpdateState`などの修正はこのイシューでやって欲しいです。

2021-09-18 16:19 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Settings/ResetController.cs
>              PlayerPrefs.DeleteKey(Constants.PlayerPrefsKeys.STAGE_ANIMATION_STATE);
1b65157

2021-09-18 16:20 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/LocalSaveManager.cs
> +        }
`SingletonBase`publicのコンストラクターしか定義できないから自分で作っておきながらずっと微妙と思ってるからなー
まあ、別にいいか

2021-09-18 16:22 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/LocalSaveManager.cs
> +        }
8ed2115

2021-09-18 16:26 UTC, takesi0627 commented
> このissue関係ないけど、直してもらいたい問題がありました。
> `PlayerPrefsUtility.cs`の`SetList<T>()`(と`SetDictionary<Key, Value>()`で
> `PlayerPrefs.Save();`呼んでない。。。(LevelSelectを離れるときに、`UserSettings.cs`経由で`PlayerPrefsUtility.cs`の`SetObject`呼んでて、そっちは`Save()`してるので挙動は何とかなってた。)
> `Save()`を追加しておいてもらえますか？


4cdf241

2021-09-18 16:39 UTC, takasusuke commented
> 正直 `StageSelectScene` 周りの修正はあんまりここでやりたくないですが、ただ `LocalSaveManager` 作っちゃったからアニメーション保存周り一緒にやっとこという軽い気持ちでやっちゃったんです。
> #1134 も同じ原因でエラー起きてるので `UpdateState`などの修正はこのイシューでやって欲しいです。

なるほど。
機能がダウングレードする修正はあまり好みじゃないけど、直近で#1134 をやるだろうし、連携取れてるならOKです

2021-09-18 16:40 UTC, takesi0627 commented
> > 正直 `StageSelectScene` 周りの修正はあんまりここでやりたくないですが、ただ `LocalSaveManager` 作っちゃったからアニメーション保存周り一緒にやっとこという軽い気持ちでやっちゃったんです。
> > #1134 も同じ原因でエラー起きてるので `UpdateState`などの修正はこのイシューでやって欲しいです。
> 
> なるほど。
> 機能がダウングレードする修正はあまり好みじゃないけど、直近で#1134 をやるだろうし、連携取れてるならOKです

もしくは、 `StageSelectScene`周りの修正をリバートして、 #1134 でここの差分を取り組んでもらって改めてやってもらってもいいかなと思いますが、どうでしょうか

2021-09-18 16:42 UTC, takasusuke commented
desu

> > > 正直 `StageSelectScene` 周りの修正はあんまりここでやりたくないですが、ただ `LocalSaveManager` 作っちゃったからアニメーション保存周り一緒にやっとこという軽い気持ちでやっちゃったんです。
> > > #1134 も同じ原因でエラー起きてるので `UpdateState`などの修正はこのイシューでやって欲しいです。
> > 
> > 
> > なるほど。
> > 機能がダウングレードする修正はあまり好みじゃないけど、直近で#1134 をやるだろうし、連携取れてるならOKです
> 
> もしくは、 `StageSelectScene`周りの修正をリバートして、 #1134 でここの差分を取り組んでもらって改めてやってもらってもいいかなと思いますが、どうでしょうか

そっちの方が形としては綺麗だけど、戻すのめんどくない？このままで良いと思ってるよ。
「動作確認方法」にStageSelectの解放が働かないことを書いてもらえれば。

2021-09-18 16:45 UTC, takesi0627 commented
概要更新しました

2021-09-18 17:58 UTC, takasusuke commented
https://github.com/LITO-apps/Treevel-client/pull/1146#pullrequestreview-758062779
このコメントのバグ、1b65157 で直ったわ！
DataはResetしてるのに、アニメーション表示したかどうか記録をリセットしてないから起きてるだけだった！！

2021-09-18 17:59 UTC, takasusuke commented
> 4cdf241



> > このissue関係ないけど、直してもらいたい問題がありました。
> > `PlayerPrefsUtility.cs`の`SetList<T>()`(と`SetDictionary<Key, Value>()`で
> > `PlayerPrefs.Save();`呼んでない。。。(LevelSelectを離れるときに、`UserSettings.cs`経由で`PlayerPrefsUtility.cs`の`SetObject`呼んでて、そっちは`Save()`してるので挙動は何とかなってた。)
> > `Save()`を追加しておいてもらえますか？
> 
> [4cdf241](https://github.com/LITO-apps/Treevel-client/commit/4cdf2419cd363d054a82af406f00d3228f7795c0)

これcommitの内容あってる？？

2021-09-18 18:16 UTC, takesi0627 commented
> > > このissue関係ないけど、直してもらいたい問題がありました。
> > > `PlayerPrefsUtility.cs`の`SetList<T>()`(と`SetDictionary<Key, Value>()`で
> > > `PlayerPrefs.Save();`呼んでない。。。(LevelSelectを離れるときに、`UserSettings.cs`経由で`PlayerPrefsUtility.cs`の`SetObject`呼んでて、そっちは`Save()`してるので挙動は何とかなってた。)
> > > `Save()`を追加しておいてもらえますか？
> > 
> > 
> > [4cdf241](https://github.com/LITO-apps/Treevel-client/commit/4cdf2419cd363d054a82af406f00d3228f7795c0)
> 
> これcommitの内容あってる？？

あれ変なやつコミットしちゃった

2021-09-18 18:19 UTC, takesi0627 commented
> > > このissue関係ないけど、直してもらいたい問題がありました。
> > > `PlayerPrefsUtility.cs`の`SetList<T>()`(と`SetDictionary<Key, Value>()`で
> > > `PlayerPrefs.Save();`呼んでない。。。(LevelSelectを離れるときに、`UserSettings.cs`経由で`PlayerPrefsUtility.cs`の`SetObject`呼んでて、そっちは`Save()`してるので挙動は何とかなってた。)
> > > `Save()`を追加しておいてもらえますか？
> > 
> > 
> > [4cdf241](https://github.com/LITO-apps/Treevel-client/commit/4cdf2419cd363d054a82af406f00d3228f7795c0)
> 
> これcommitの内容あってる？？

7046808　これです

2021-09-18 22:25 UTC, xiii111 commented
> 機能がダウングレードする修正はあまり好みじゃないけど、直近で#1134 をやるだろうし、連携取れてるならOKです

ごめんなさい、連携は取れてる認識ないです

2021-09-18 22:44 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/LocalSaveManager.cs
> +        }
`StageRecordService` では `SingletonBase` をあえて使わずに実装していますね（ @takesi0627 とも確認した記憶がある）

https://github.com/LITO-apps/Treevel-client/blob/develop/Assets/Project/Scripts/Common/Utils/StageRecordService.cs

2021-09-18 22:46 UTC, xiii111 commented
連携 = https://github.com/LITO-apps/Treevel-client/issues/971#issuecomment-920818268 のことだな多分

2021-09-18 22:57 UTC, xiii111 reviewed
ごめん、一点しか間に合わなかった。他のところはまた追って見る

2021-09-18 22:57 UTC, xiii111 commented on Assets/Project/Scripts/Common/Utils/PlayerPrefsUtility.cs
> +            PlayerPrefs.Save();
### fyi

これね。[公式ドキュメント](https://docs.unity3d.com/ja/current/ScriptReference/PlayerPrefs.Save.html) に

> By default Unity writes preferences to disk during OnApplicationQuit(). In cases when the game crashes or otherwise prematuraly exits, you might want to write the PlayerPrefs at sensible 'checkpoints' in your game. This function will write to disk potentially causing a small hiccup, therefore it is not recommended to call during actual gameplay.

と書いてあって、`SetString()` などをするたびに `Save()` するのは微妙だなーと思って放置してたんだよね。どう思う cc @takasusuke

2021-09-20 13:33 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/StageRecordService.cs
> +                return clearHandler.GetTreeState();
f5c5f61

2021-09-20 13:48 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/PlayerPrefsUtility.cs
> +            PlayerPrefs.Save();
クラッシュが起きなければ正常にアプリを落とす場合 `Save` してくれるし、
PlayerPrefsに保存するものは大体セーブしなくてもそこまでユーザに不利益を与えるような影響が出ないので全部消してもいいと思いました。
BGMとかの `PlayerPrefs.SetFloat` 所でも `Save` してないしね

2021-09-20 13:55 UTC, takasusuke commented on Assets/Project/Scripts/Common/Utils/PlayerPrefsUtility.cs
> +            PlayerPrefs.Save();
全部消そう！

2021-09-20 13:57 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/PlayerPrefsUtility.cs
> +            PlayerPrefs.Save();
4f708e5

2021-09-21 00:06 UTC, xiii111 commented on Assets/Project/Scripts/Common/Utils/PlayerPrefsUtility.cs
> +            PlayerPrefs.Save();
データのキャッシュやスクロール位置はともかく、BGM や言語設定、アニメーションが実施されたかなどはユーザの体験に直結する情報だから Save しておいた方が良いと思う。ましてや、クラッシュの原因のほとんどは僕らのせいだから、僕らのせいでクラッシュさせて、言語設定とかが元に戻っていたら普通に体験がひどいと思う

要は、全て Save があっても良いと思う

2021-09-21 00:56 UTC, xiii111 reviewed
責務が切り出されて、見通しが良くなりました！！細かいロジックまではすぐに理解できなかったので、その点の確認は甘いですが、一通り確認しました！以前言ったように動作は問題ないです。細かい点をいくつか指摘しました

2021-09-21 00:56 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Settings/ResetController.cs
> +            // ローカルセーフデータリセット
```suggestion
            // ローカルセーブデータリセット
```

2021-09-21 00:56 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/LocalSaveManager.cs
> +    public class LocalSaveManager : SingletonBase<LocalSaveManager>
### imo

この名前だと、ローカルにセーブする関連全てをまとめているように見えます。しかし、実際に扱っているのは、木やステージの開放演出系だけ。名前が不適切だと思うので、もう少しスコープを絞った名前にしたいです

2021-09-21 00:56 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/LocalSaveManager.cs
> +            // ステージ選択画面の枝とステージボタンをリセット
### nits

このコメントと同等のコメントを直前の

```csharp
_releaseAnimationPlayedTrees.Clear();
PlayerPrefs.DeleteKey(Constants.PlayerPrefsKeys.TREE_ANIMATION_STATE);
```

の上にもつけましょう

2021-09-21 00:56 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelSelectDirector.cs
> +            SoundManager.Instance.PlaySE(ESEKey.LevelSelect_River);
### ask

`if (SceneManager.GetActiveScene().name == Constants.SceneName.MENU_SELECT_SCENE)` の分岐が消えてますが、大丈夫ですか？

2021-09-21 00:56 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/NumClearTreeHandler.cs
> +        public ETreeState GetTreeState(int clearStageNum)
### ask
そもそもの質問なんだけど、この関数が `ETreeState.UnReleased` を返す可能性がないのってなんでだっけ？

2021-09-21 01:22 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/LocalSaveManager.cs
> +    public class LocalSaveManager : SingletonBase<LocalSaveManager>
今後チュートリアルのセーブもここで扱ってもいいかなって思ってつけたんだけどどうでしょうか

2021-09-21 01:23 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelSelectDirector.cs
> +            SoundManager.Instance.PlaySE(ESEKey.LevelSelect_River);
これは前に`StartUpScene`と同時にロードするときに必要な分岐だったので、
`StartUpScene`と`MenuSelectScene`が別々ロードする今はいらない

2021-09-21 01:29 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/NumClearTreeHandler.cs
> +        public ETreeState GetTreeState(int clearStageNum)
`ETreeState.UnReleased`は他の木の`ClearTreeHandler`に依存したからかな？
詳しい事情自分も追えてないからなんとも。
で確かにここで `UnReleased` を計算するとややこしくなる

2021-09-21 01:29 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/NumClearTreeHandler.cs
> +        public ETreeState GetTreeState(int clearStageNum)
@takasusuke

2021-09-21 03:59 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelSelectDirector.cs
> +            SoundManager.Instance.PlaySE(ESEKey.LevelSelect_River);
おーこの pr とか関係なく不要になったってことね

2021-09-21 04:01 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/LocalSaveManager.cs
> +    public class LocalSaveManager : SingletonBase<LocalSaveManager>
んーー分けた方が良いんじゃない？これだけ見ると、`StageRecord` や `UserRecord` もここに含めた方が良いように見えてしまう。かといって、全部含めたら、このクラスでいろんなことしすぎだと思う

2021-09-21 10:36 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/LocalSaveManager.cs
> +    public class LocalSaveManager : SingletonBase<LocalSaveManager>
8d8c126　名前変えた

2021-09-21 10:39 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/LocalSaveManager.cs
> +            // ステージ選択画面の枝とステージボタンをリセット
bd4c31b　コメント追加、と少し文言を変えました

2021-09-21 10:43 UTC, takesi0627 commented
@takasusuke 
* https://github.com/LITO-apps/Treevel-client/pull/1146#discussion_r712615277 Unreleasedについて何か見解があればコメントください
* https://github.com/LITO-apps/Treevel-client/pull/1146#discussion_r712601119 PlayerPrefs.Saveを戻すことになりました。把握よろしく

@xiii111 
* https://github.com/LITO-apps/Treevel-client/pull/1146#discussion_r712914643
* https://github.com/LITO-apps/Treevel-client/pull/1146#discussion_r712913128
* https://github.com/LITO-apps/Treevel-client/pull/1146#discussion_r712912915

修正の確認をお願いします

2021-09-21 10:47 UTC, xiii111 commented on Assets/Project/Scripts/Common/Utils/PlayerPrefsUtility.cs
> +            PlayerPrefs.Save();
> BGMとかの PlayerPrefs.SetFloat の所でも Save してないしね

これは大丈夫？

2021-09-21 10:53 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/PlayerPrefsUtility.cs
> +            PlayerPrefs.Save();
この五箇所のあと全部つけて欲しいってことですか
![image](https://user-images.githubusercontent.com/17778395/134158445-0f4a4a30-d43a-454c-ac3a-b325ed75e43a.png)

2021-09-21 10:55 UTC, xiii111 commented on Assets/Project/Scripts/Common/Utils/PlayerPrefsUtility.cs
> +            PlayerPrefs.Save();
同じコンテキストなら付けるよね？`Save` を忘れることが懸念だから、このプロダクトの `SetFloat` では `Save` もセットなんだということを伝えるために、`PlayerPrefsUtility` に `SetFloat` と `Save` を行う `SetFloat` を用意しても良いと思います（このプロダクトでは `PlayerPrefsUtility` しか使わない前提で）

2021-09-21 10:56 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/PlayerPrefsUtility.cs
> +            PlayerPrefs.Save();
その方がいいかも

2021-09-21 10:59 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/PlayerPrefsUtility.cs
> +            PlayerPrefs.Save();
その場合、`GetFloat`、`GetInt`、`GetString` も同じく`PlayerPrefsUtility`で作る？

2021-09-21 11:01 UTC, xiii111 commented on Assets/Project/Scripts/Common/Utils/PlayerPrefsUtility.cs
> +            PlayerPrefs.Save();
必要ないから、俺なら作らないかな ... `Set` 系だけ `PlayerPrefsUtility` を使うというハイコンテキストな感じになるけど、まぁ許容できる

2021-09-21 11:17 UTC, xiii111 commented on Assets/Project/Scripts/Common/Utils/PlayerPrefsUtility.cs
> +            PlayerPrefs.Save();
完璧！

2021-09-21 11:17 UTC, xiii111 approved these changes
お疲れ様です！！
私からはもうないので、あとは @takasusuke にお任せします

2021-09-21 11:59 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/NumClearTreeHandler.cs
> +        public ETreeState GetTreeState(int clearStageNum)
なんでだろね。解放されてる前提、というハイコンテクストではある。
解放されてるかどうかは１Treeでは決められないから、実装上分けたんだろうね。

2021-09-21 12:01 UTC, takasusuke approved these changes

2021-09-21 12:01 UTC, merged