LevelSelectSceneの海のShaderを改良
LITO-apps/Treevel-client pull request #1147
Opened 2021-09-18 17:14 UTC by takasusuke

### 対象イシュー
Close 

### 概要

### 詳細

#### 現実装になった経緯

#### 技術的な内容

### キャプチャ

### 動作確認方法

### 参考 URL

2021-09-22 17:51 UTC, takasusuke commented
@LITO-apps/engineer 
よろしくお願いします。
30min くらい...?

2021-09-23 01:32 UTC, xiii111 requested changes
対応ありがとうございます！

### must
私の環境だけの可能性があるので、そちらでも確認して欲しいのですが、一部環境で Shader が反映されていないように見えます（海も黒くなります）。何か事前に設定すべきことなどあれば、教えて欲しいです。また今、実機環境でも試しています。取り急ぎ途中までで報告しました

### `iPhone 6s Plus iOS 14 Simulator`
<img src="https://user-images.githubusercontent.com/26104258/134442638-f30e4553-94ec-4c62-b187-aad7a35ec74a.png" width="300">

### `iPhone 12 iOS 15 Simulator`
<img src="https://user-images.githubusercontent.com/26104258/134442656-c0077ba7-3429-48dc-9f74-2cafb73fa2bd.png" width="300">

### Unity エディタ
こちらでは正しく反映されます
<img width="300" alt="スクリーンショット 2021-09-23 10 26 17" src="https://user-images.githubusercontent.com/26104258/134442679-c3936a77-ce70-46ea-8140-c0b2710d6db2.png">

2021-09-23 01:35 UTC, takesi0627 commented
> 対応ありがとうございます！
> 
> ### must
> 私の環境だけの可能性があるので、そちらでも確認して欲しいのですが、一部環境で Shader が反映されていないように見えます（海も黒くなります）。何か事前に設定すべきことなどあれば、教えて欲しいです。また今、実機環境でも試しています。取り急ぎ報告しました

@xiii111 
MenuSelectSceneはAASの管理下にあるので、変更がある時にアセットを再ビルドする必要がある。
再ビルドしてもう一回試してもらえませんか

2021-09-23 01:35 UTC, xiii111 commented
↑ キャッシュが残っていたりなど、さまざまな理由があると思うので、皆さんの環境で問題なければ問題ないと思います

2021-09-23 01:39 UTC, xiii111 commented
とりあえず ↑ でやってみます

2021-09-23 01:40 UTC, takesi0627 commented
準備の２番目ですね

2021-09-23 01:40 UTC, xiii111 commented
これ、iOS アセットの生成時に自動で通るようにしたいな ...

2021-09-23 01:47 UTC, takasusuke commented on Assets/Project/Actors/UIs/MenuSelectScene/LevelSelect/BackgroundPerlinNoiseShader.shader
> +}
70a0e5e

2021-09-23 01:47 UTC, takasusuke commented on Assets/Project/Actors/UIs/MenuSelectScene/LevelSelect/BackgroundPerlinNoiseShader.shader
> +			static const int surface_noise_fineness_y = 2 * surface_noise_fineness_x;
70a0e5e

2021-09-23 01:48 UTC, xiii111 commented
📝 動作確認中

2021-09-23 01:48 UTC, takasusuke commented on Assets/Project/Actors/UIs/MenuSelectScene/LevelSelect/BackgroundPerlinNoiseShader.shader
> +			}
Tabとspaceが混じってた。
参考にしたサイトとかからコピペしたときに混じった(?)

全部spaceにしました。

70a0e5e

2021-09-23 01:48 UTC, xiii111 commented on Assets/Project/Actors/UIs/MenuSelectScene/LevelSelect/BackgroundPerlinNoiseShader.shader
> +			}
ok です！！

2021-09-23 01:48 UTC, takesi0627 commented
なんかみんな一斉にやってるみたいなので自分は午後くらいに見る

2021-09-23 01:53 UTC, xiii111 approved these changes
AAS をビルドしなおしたら、問題なく動作しました！海の色も黒くなりませんでした

先程のレビューの 3 `nits` を直してくれたら、私からは以上です！

2021-09-23 01:53 UTC, xiii111 commented
@takesi0627 動作は問題なさそうなので、shader 周りを見てもらえると非常に助かります

2021-09-23 03:21 UTC, takesi0627 reviewed
シェーダー周りコメントしました。
@xiii111 が実機動作確認してくれたとのことで実機確認は機会あったらやる

2021-09-23 03:21 UTC, takesi0627 commented on Assets/Project/Actors/UIs/MenuSelectScene/LevelSelect/BackgroundPerlinNoiseShader.shader
> +        _Color ("Tint", Color) = (1,1,1,1)
### `imo`

この `_Color`使ってないし、最後のノイズの指定のところの色に使うのはどうでしょうか
```
col.r = 0.7;
col.g = 0.9;
col.b = 1;
```

2021-09-23 03:21 UTC, takesi0627 commented on Assets/Project/Actors/UIs/MenuSelectScene/LevelSelect/BackgroundPerlinNoiseShader.shader
> +            }
### `nits`

参考にした記事とかあればリンク貼って欲しい

2021-09-23 03:23 UTC, takesi0627 commented on Assets/Project/Actors/UIs/MenuSelectScene/LevelSelect/BackgroundPerlinNoiseShader.shader
> +            }
概要で貼ってくれたやつそのままね、このリンクはこのファイルのどこかに書いて欲しい
https://karanokan.info/2019/02/16/post-2202/

2021-09-23 04:01 UTC, takasusuke commented on Assets/Project/Actors/UIs/MenuSelectScene/LevelSelect/BackgroundPerlinNoiseShader.shader
> +            }
Scriptの中にってこと？

2021-09-23 04:02 UTC, takesi0627 commented on Assets/Project/Actors/UIs/MenuSelectScene/LevelSelect/BackgroundPerlinNoiseShader.shader
> +            }
そうですね
１行目からでもいい

2021-09-24 04:12 UTC, takasusuke commented on Assets/Project/Actors/UIs/MenuSelectScene/LevelSelect/BackgroundPerlinNoiseShader.shader
> +        _Color ("Tint", Color) = (1,1,1,1)
603daf0

2021-09-24 04:13 UTC, takasusuke commented
@takesi0627 
よろしくお願いします

2021-09-24 04:18 UTC, takesi0627 commented on Assets/Project/Actors/UIs/MenuSelectScene/LevelSelect/BackgroundPerlinNoiseShader.shader
> +        fixed4 _NoiseColor;
これ宣言だけして、計算に使ってなくない？

2021-09-24 04:19 UTC, takesi0627 commented on Assets/Project/Actors/UIs/MenuSelectScene/LevelSelect/BackgroundPerlinNoiseShader.shader
> +        fixed4 _NoiseColor;
今外出でエディタで確認できないから間違ってたらすみません

2021-09-24 04:20 UTC, takasusuke commented on Assets/Project/Actors/UIs/MenuSelectScene/LevelSelect/BackgroundPerlinNoiseShader.shader
> +        fixed4 _NoiseColor;
ごめんcommitの分割で間違えた。

インデント直す処理に入れちゃってる。
4f17b36

2021-09-24 04:34 UTC, takesi0627 commented
差分問題ないです！

2021-09-24 05:16 UTC, takasusuke commented
@takesi0627 

> 差分問題ないです！


..mmmMerge ok?

2021-09-24 12:18 UTC, takesi0627 approved these changes
マージおけです

2021-09-24 12:46 UTC, merged