エラーポップアップデザイン適用
LITO-apps/Treevel-client pull request #1150
Opened 2021-09-21 10:30 UTC by takesi0627

### 対象イシュー
Close #1094  

### 概要
エラーポップアップの実装

### 詳細

#### 現実装になった経緯

#### 技術的な内容

### キャプチャ

### 動作確認方法

### 参考 URL

2021-09-23 02:54 UTC, takesi0627 commented on Assets/Project/Actors/UIs/Common/MessageDialog.prefab
> +--- !u!1001 &3122476063678446103
`SafeAreaPanel`を配置したための変更

2021-09-23 02:54 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/ErrorCode.cs
> +        }
ここは `IEquatbale` を実装した時にRiderから提示された自動生成コード

2021-09-23 02:54 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/GameDataManager.cs
> +            await LoadTreeData();
ここは最初エラー定義ファイルみたいなアセットをロードするためにコード整理したが、
結局ロードしなくなったけど、関数分けた方がいいのでそのままにした

2021-09-23 02:56 UTC, takesi0627 commented
@LITO-apps/engineer 
よろしくお願いします。
30分程度かな？

2021-09-23 06:06 UTC, xiii111 requested changes
対応ありがとうございます！エラーコード周りのクラスの整理はとても分かりやすくて良いと思いました！細かい指摘を含めて、数点コメントしました！よろしくお願いします！

### imo
細かい UI の調整で、以下を検討できますか（元のデザインを見て話しています）
- `!` マークがもう少し上にあった方が良さそう
- `タイトルに戻る` のテキストの色をもう少し黒寄りにした方が良さそう
- ボタンの下部（凹む部分）のスペースをもう少し広くして、色はもう少し暗い方が良さそう
- `データの読み込みに失敗しました` と `ゲームを再起動してください` は別の内容を伝えていることがわかるように、間に空行などがあった方が良さそう（こちらは、デザイン案自体への意見です。 @takasusuke どう思いますか？）

|デザイン案|本実装|
|---|---|
|<img width="300" alt="スクリーンショット 2021-08-28 1 31 52" src="https://user-images.githubusercontent.com/26213141/131159658-c5641ce7-5bc8-46fb-86d4-fab8abb29c0e.png">|<img width="300" alt="スクリーンショット 2021-09-23 14 36 29" src="https://user-images.githubusercontent.com/26104258/134459067-a91523be-3634-4a08-a8ec-70725ac12768.png">|

2021-09-23 06:06 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/ErrorType.cs
> +            return errorType switch {
### imo

ここの並び順、`main` 昇順、続いて `sub` 昇順に並んでいて欲しいです。また `main` が変わるたびに空行が入る方が読みやすいです

2021-09-23 06:06 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/UIs/ErrorMessageBox.cs
> +        public EErrorType errorType {
### nits

プロパティは `UpperCamelCase` だった気がする

```suggestion
        public EErrorType ErrorType {
```

2021-09-24 04:27 UTC, takasusuke commented on Assets/Project/Scripts/Common/Entities/ErrorCode.cs
> +        public const int MAIN_CODE_DIGIT = 3;
かつ、アンダースコア始まり。
```suggestion
        private const int _MAIN_CODE_DIGIT = 3;
```

2021-09-24 04:27 UTC, takasusuke commented on Assets/Project/Scripts/Common/Entities/ErrorCode.cs
> +        public const int SUB_CODE_DIGIT = 4;
かつ、アンダースコア始まり。
```suggestion
        private const int _SUB_CODE_DIGIT = 3;
```

2021-09-24 05:09 UTC, takasusuke reviewed
お疲れ様ーーー👍👍

`BackButton`は`SafeAreaPanel`の下でお願いいたします

<img width="240" alt="スクリーンショット 2021-09-24 14 08 43" src="https://user-images.githubusercontent.com/26213141/134621450-ad76946f-3f8a-4b4d-b918-ceeba21159ca.png">

2021-09-24 05:13 UTC, takasusuke commented
@xiii111 
> * `データの読み込みに失敗しました` と `ゲームを再起動してください` は別の内容を伝えていることがわかるように、間に空行などがあった方が良さそう（こちらは、デザイン案自体への意見です。 @takasusuke どう思いますか？）

確かに、離れていた方がより効果的なUIだと思います。

@takesi0627 
もう少しだけ`ErrorReason`と`ActionMessage`を離してくれると嬉しい！

2021-09-24 12:23 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/ErrorCode.cs
> +        public const int MAIN_CODE_DIGIT = 3;
b8ca40f

2021-09-24 12:23 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/ErrorCode.cs
> +        public const int SUB_CODE_DIGIT = 4;
b8ca40f

2021-09-24 12:24 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/ErrorCode.cs
> +    public readonly struct ErrorCode : IEquatable<ErrorCode>
おそらく。メンバーを `readonly` つけたらつけとけって言われたので

2021-09-24 12:29 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/ErrorType.cs
> +            return errorType switch {
45fa6af

2021-09-24 12:29 UTC, takesi0627 commented on Assets/Project/Resources/GameDatas/translation.csv
> +LoadDataErrorAction,ゲームを再起動してください,Please restart the game.
b6bc3d5

2021-09-24 12:33 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/ErrorType.cs
> +                EErrorType.UnknownError => new ErrorInfo(new ErrorCode("001", "0001"), ETextIndex.UnknownErrorReason, ETextIndex.UnknownErrorAction),
37f61af

2021-09-24 12:42 UTC, takesi0627 commented on Assets/Project/Editor/DebugTools.cs
> +            var errorCode = errorCodes?.ElementAt(rand.Next(errorCodes.Length)) ?? EErrorType.UnknownError;
65c5a48

2021-09-24 12:42 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/ErrorInfo.cs
> +        public readonly ETextIndex ReasonText;
4fcbaaa

2021-09-24 12:43 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/ErrorMessageBox.cs
> +        public EErrorType errorType {
276533b

2021-09-24 12:43 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/ErrorMessageBox.cs
> +            get => _errorType;
9ce5851

2021-09-24 12:56 UTC, takesi0627 commented
> `BackButton`は`SafeAreaPanel`の下でお願いいたします

28d1789

2021-09-24 13:10 UTC, takesi0627 commented
> * `!` マークがもう少し上にあった方が良さそう

24e8d00
> * `タイトルに戻る` のテキストの色をもう少し黒寄りにした方が良さそう
> * ボタンの下部（凹む部分）のスペースをもう少し広くして、色はもう少し暗い方が良さそう

861c86c : ボタン全体が一枚のスプライトになっているので、片方だけ色を調整することができません。同様に、面積の比率はある程度決まっているので微調整は難しいです。アスペクト比を元画像に戻してみたのでどうでしょうか


> * `データの読み込みに失敗しました` と `ゲームを再起動してください` は別の内容を伝えていることがわかるように、間に空行などがあった方が良さそう（こちらは、デザイン案自体への意見です。 @takasusuke どう思いますか？）

c5e665d

| 修正前 | 修正後 |
|-|-|
|<img width="300" alt="スクリーンショット 2021-09-23 14 36 29" src="https://user-images.githubusercontent.com/26104258/134459067-a91523be-3634-4a08-a8ec-70725ac12768.png">|<img width="300" src="https://user-images.githubusercontent.com/17778395/134679372-e100820a-8836-4d06-a9dd-bc9eae2360d7.png">|

2021-09-24 13:11 UTC, takesi0627 commented
@takasusuke @xiii111 
諸々修正しました。
確認よろしくお願いします

2021-09-25 00:16 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/ErrorType.cs
> +            return errorType switch {
91e25ae の差分完璧すぎる

2021-09-25 00:22 UTC, xiii111 commented
> > * `!` マークがもう少し上にあった方が良さそう
> 
> [24e8d00](https://github.com/LITO-apps/Treevel-client/commit/24e8d005d15162fc9f2dfc25bbf24d2daedbd555)

👍

> > * `タイトルに戻る` のテキストの色をもう少し黒寄りにした方が良さそう
> > * ボタンの下部（凹む部分）のスペースをもう少し広くして、色はもう少し暗い方が良さそう
> 
> [861c86c](https://github.com/LITO-apps/Treevel-client/commit/861c86c24fe67bc2902db6050a262c39a7c43f46) : ボタン全体が一枚のスプライトになっているので、片方だけ色を調整することができません。同様に、面積の比率はある程度決まっているので微調整は難しいです。アスペクト比を元画像に戻してみたのでどうでしょうか

修正後の `タイトルに戻る` ボタンより、修正前の横長のボタンの方が窮屈でなくて良いですね ... `ボタンの下部（凹む部分）のスペースをもう少し広くして` の部分を破棄できますか？

> > * `データの読み込みに失敗しました` と `ゲームを再起動してください` は別の内容を伝えていることがわかるように、間に空行などがあった方が良さそう（こちらは、デザイン案自体への意見です。 @takasusuke どう思いますか？）
> 
> [c5e665d](https://github.com/LITO-apps/Treevel-client/commit/c5e665d4fc155374917a3169a2d967e6b44594ba)

👍

> 修正前	修正後
> <img alt="スクリーンショット 2021-09-23 14 36 29" width="300" src="https://user-images.githubusercontent.com/26104258/134459067-a91523be-3634-4a08-a8ec-70725ac12768.png">	<img alt="" width="300" src="https://user-images.githubusercontent.com/17778395/134679372-e100820a-8836-4d06-a9dd-bc9eae2360d7.png">

修正前と修正後では、そもそもデバイスが違うように見えますが、あってますか？また、ポップアップ外の暗さが、修正後で明らかに暗くなっている気がしますが、何か仕様変更がありましたっけ？

2021-09-25 02:18 UTC, takasusuke approved these changes
自分からは以上です

2021-09-25 03:30 UTC, takesi0627 commented
> 修正前と修正後では、そもそもデバイスが違うように見えますが、あってますか？また、ポップアップ外の暗さが、修正後で明らかに暗くなっている気がしますが、何か仕様変更がありましたっけ？

修正前の画像は https://github.com/LITO-apps/Treevel-client/pull/1150#pullrequestreview-761606770 の「本実装」の画像をお借りしてますので、デバイスの違いはあるかもしれません。
暗さについては特にいじっていません。単に呼び出すシーンの違いだと思います（StartupSceneの背景とStageSelectSceneの背景の色の違いが起因するものかと）

2021-09-25 15:13 UTC, takesi0627 commented
> > [861c86c](https://github.com/LITO-apps/Treevel-client/commit/861c86c24fe67bc2902db6050a262c39a7c43f46) : ボタン全体が一枚のスプライトになっているので、片方だけ色を調整することができません。同様に、面積の比率はある程度決まっているので微調整は難しいです。アスペクト比を元画像に戻してみたのでどうでしょうか
> 
> 修正後の `タイトルに戻る` ボタンより、修正前の横長のボタンの方が窮屈でなくて良いですね ... `ボタンの下部（凹む部分）のスペースをもう少し広くして` の部分を破棄できますか？


5c028b4 + 1e1792a
こういうことですかね

2021-09-28 10:12 UTC, xiii111 requested changes
見た目周り完璧だと思います！一点気になったことがあったので、コメントします

### must
`StartupScene` → `LevelSelectScene` と遷移した後に、デバッグコマンドから `タイトルに戻る` タップまでを行ったら、`StartupScene` へ遷移後、以下のようなエラーが出ました。一番上は既知ですが、その他もどこかで共有されてましたっけ？（見落としていたらすみません）

<img width="866" alt="スクリーンショット 2021-09-28 19 09 58" src="https://user-images.githubusercontent.com/26104258/135068044-0872a402-9e10-41b2-8f48-b4152c24bda4.png">

2021-09-28 10:20 UTC, xiii111 commented
↑ 以外は問題ないです

2021-09-28 13:32 UTC, takesi0627 commented
> `StartupScene` → `LevelSelectScene` と遷移した後に、デバッグコマンドから `タイトルに戻る` タップまでを行ったら、`StartupScene` へ遷移後、以下のようなエラーが出ました。一番上は既知ですが、その他もどこかで共有されてましたっけ？（見落としていたらすみません）
> 
> <img alt="スクリーンショット 2021-09-28 19 09 58" width="866" src="https://user-images.githubusercontent.com/26104258/135068044-0872a402-9e10-41b2-8f48-b4152c24bda4.png">

@takasusuke 
これ僕の環境は再現しないですが、
そちらは同じ状況ですか

2021-09-28 13:35 UTC, xiii111 commented
@takesi0627 僕の環境が悪い気がするので、 @takasusuke が問題なければマージして良いです

2021-09-28 13:36 UTC, xiii111 approved these changes
マージできるように Approve だけしておきます

2021-09-28 13:54 UTC, takasusuke commented
エラーは出ない時もあれば出る時もあった。
体感、LevelSelectSceneに入って、5秒くらい待ってから、エラーポップアップ出してタイトルに戻ると出る気がする。

2021-09-28 13:58 UTC, takesi0627 commented
> エラーは出ない時もあれば出る時もあった。
> 体感、LevelSelectSceneに入って、5秒くらい待ってから、エラーポップアップ出してタイトルに戻ると出る気がする。

情報ありがとう、再現できましたので調査します

2021-09-28 14:20 UTC, xiii111 commented
ok

2021-09-28 14:20 UTC, xiii111 commented
イシュー作ってもらったら、マージして ok です！

2021-09-28 14:22 UTC, takesi0627 commented
> > `StartupScene` → `LevelSelectScene` と遷移した後に、デバッグコマンドから `タイトルに戻る` タップまでを行ったら、`StartupScene` へ遷移後、以下のようなエラーが出ました。一番上は既知ですが、その他もどこかで共有されてましたっけ？（見落としていたらすみません）
> > <img alt="スクリーンショット 2021-09-28 19 09 58" width="866" src="https://user-images.githubusercontent.com/26104258/135068044-0872a402-9e10-41b2-8f48-b4152c24bda4.png">
> 
> この問題、 `develop` でも発生するのと、パッと見て分からなかったのでイシュー作成して別対応とします

→ #1166

2021-09-28 14:23 UTC, merged