未実装の木をシルエットで表示
LITO-apps/Treevel-client pull request #1158
Opened 2021-09-24 15:38 UTC by takesi0627

### 対象イシュー
Close #1135 

### 概要
タイトル通り

### 詳細

#### 現実装になった経緯
プレハブを新たに作成すると、既に`RoadController`等で設定済みのReferenceが全部設定し直さないといけないのと、今後レベル解放時も同じくやり直さないといけないのは手間なので、 `LevelTreeController`にプレハブから設定できる未実装かどうかのフラグを用意する形にしました。

### キャプチャ
![image](https://user-images.githubusercontent.com/17778395/134702242-a912c00d-9b39-4f22-8178-8c4c8fbf124e.png)

### 動作確認方法
- [ ] `MenuSelectScene`にて `Spring-1~3`,`Summer-1`,`Autumn-1`,`Winter-1`以外のステージが黒く塗りつぶしてはてなが表示されていること。また、未実装の木が操作できないこと。

2021-09-24 15:39 UTC, takesi0627 commented
@LITO-apps/engineer 
よろしくお願いします
10~15min程度で終わると思います

2021-09-25 00:38 UTC, xiii111 requested changes
### ask
対応イシューの完了条件には

> - [ ] 未実装の木用のプレハブ作成（桜木の画像＋黒色＋？のText Mesh Pro）

とありますが、本実装ではそうなっていないように見えます。経緯を教えてもらえますか？

<img width="300" alt="スクリーンショット 2021-09-25 9 36 43" src="https://user-images.githubusercontent.com/26104258/134751919-aa35149f-a39b-4e29-a6d1-16de7b3bfc80.png">

> - [ ] 未実装の木用のLevelTreeContorllerを用意（RoadControllerが参照するため）

に関しては

> 現実装になった経緯
プレハブを新たに作成すると、既にRoadController等で設定済みのReferenceが全部設定し直さないといけないのと、今後レベル解放時も同じくやり直さないといけないのは手間なので、 LevelTreeControllerにプレハブから設定できる未実装かどうかのフラグを用意する形にしました。

で変わった認識です

### ask

今回と関係ないかもですが、木の解放が正しく動いていないように見えます。パッと分かりそうなら調べてもらえますか？

|`Spring-1-1` 全部クリア|解放されない|
|---|---|
|<img width="373" alt="スクリーンショット 2021-09-25 9 30 12" src="https://user-images.githubusercontent.com/26104258/134751739-8d481e2b-2d5b-41c2-87ec-ce0013078ff0.png">|<img width="375" alt="スクリーンショット 2021-09-25 9 30 24" src="https://user-images.githubusercontent.com/26104258/134751750-88f44f7f-9fe9-4945-a0e8-7c8ac98d8dfd.png">|

2021-09-25 00:38 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs
> +        [SerializeField] private GameObject _questionMarkObj;
### ask

`_questionMarkObj` は未実装の木にのみセットされる `Nullable` なプロパティですか？もしそうであれば、`_isUnimplemented` プロパティは不要で、`_questionMarkObj` が `Null` かどうかで出し分ければ良いと思います。もしそうでなければ、本実装の通り `_isUnimplemented` が必要ですね

2021-09-25 00:42 UTC, xiii111 reviewed
追加コメントです！

2021-09-25 00:42 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs
> +                return;
### nits
```suggestion
            if (_isUnimplemented) return;
```

2021-09-25 00:42 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs
> +            }
### imo

私はこの書き方の方がネストが少なくて読みやすいです
```suggestion
            if (_isUnimplemented) {
                ReflectUnimplementedView();
                return;
            }
            
            base.Awake();
            _button.onClick.AsObservable()
                .Subscribe(_ => SoundManager.Instance.PlaySE(ESEKey.UI_Button_Click_General))
                .AddTo(this);
```

2021-09-25 00:42 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs
> +                base.Awake();
### ask

`base.Awake();` は `_isUnimplemented == True` の時には不要ですか？

2021-09-25 02:44 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs
> +                base.Awake();
`TreeControllerBase.cs`の`clearHandler`ってもう使われてないんだね。
これ消してもらって良いですか？？

あと、個人的には`LevelTreeController.cs`からは条件に関わらず`base.Awake()`を呼びたい。

2021-09-25 02:45 UTC, takasusuke reviewed
questionMarkObj の値が絶対値指定になっているので、こんな感じで設定をお願いいたします。

<img width="512" alt="スクリーンショット 2021-09-25 11 36 15" src="https://user-images.githubusercontent.com/26213141/134755328-16a54640-d33b-42de-867e-7e84d4ea1503.png">

2021-09-25 15:19 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs
> +                base.Awake();
59f0ada
`Awake` ごと消し飛ばしました

2021-09-25 15:28 UTC, takesi0627 commented
> ### ask
> 対応イシューの完了条件には
> 
> > * [ ]  未実装の木用のプレハブ作成（桜木の画像＋黒色＋？のText Mesh Pro）
> 
> とありますが、本実装ではそうなっていないように見えます。経緯を教えてもらえますか？

本来は`UnimplementedLevelTreeController.cs`を実装し、新たに作成した `UnimplementedLevelTree.prefab` にアタッチして、`MenuSelectScene` に配置するという想定でしたが、概要で述べたように、このような実装だと、新たにレベルを解放するたびにかかる手間が多いので現在使用している `LevelTree.prefab` 内に実装する形に変えました。

2021-09-25 15:30 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs
> +        [SerializeField] private GameObject _questionMarkObj;
> `_questionMarkObj` は未実装の木にのみセットされる `Nullable` なプロパティですか？

違います。どっちでもセットされます。`LevelTree.prefab`にて設置されているので、プレハブ使用しているのであればセットされます。

2021-09-25 15:31 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs
> +            }
e37a754

2021-09-25 15:54 UTC, takesi0627 commented
> ### ask
> 今回と関係ないかもですが、木の解放が正しく動いていないように見えます。パッと分かりそうなら調べてもらえますか？

`StageRecordService.GetTreeState`の処理で間違いがありました。
今回とは関係ないですが直しておきました
c7a6b4d

2021-09-28 00:34 UTC, takesi0627 commented
> questionMarkObj の値が絶対値指定になっているので、こんな感じで設定をお願いいたします。
> 
e8c70ca

2021-09-28 10:15 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs
> +        [SerializeField] private GameObject _questionMarkObj;
理解しました、それであればフラグは必須ですね。

2021-09-28 10:16 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs
> +                base.Awake();
最高

2021-09-28 10:17 UTC, xiii111 commented
> 本来は`UnimplementedLevelTreeController.cs`を実装し、新たに作成した `UnimplementedLevelTree.prefab` にアタッチして、`MenuSelectScene` に配置するという想定でしたが、概要で述べたように、このような実装だと、新たにレベルを解放するたびにかかる手間が多いので現在使用している `LevelTree.prefab` 内に実装する形に変えました。

であれば、シルエット化する全ての木の画像を桜の画像に差し替えた方が良いと思っています

@takasusuke 認識合ってますか？

2021-09-28 10:19 UTC, xiii111 commented
↑ 以外は問題ないです

2021-09-28 14:17 UTC, takasusuke commented
@xiii111 

> > 本来は`UnimplementedLevelTreeController.cs`を実装し、新たに作成した `UnimplementedLevelTree.prefab` にアタッチして、`MenuSelectScene` に配置するという想定でしたが、概要で述べたように、このような実装だと、新たにレベルを解放するたびにかかる手間が多いので現在使用している `LevelTree.prefab` 内に実装する形に変えました。
> 
> であれば、この pr 内でシルエット化する全ての木の画像（Winter_1_3 など色々）を桜の画像に差し替えた方が良いと思っています
> 

[?]は全部、桜の木のシルエットにするんだっけ。。。忘れた。。。
桜の木にするにしても、実際の桜の木を適用するときに、シルエットにも入れるので良いと思います。
(今、シルエットに画像入れても、実際の桜の木を適用するときに、また画像入れることになるので)

2021-09-28 14:19 UTC, xiii111 commented
> [?]は全部、桜の木のシルエットにするんだっけ。。。忘れた。。。

そう書いてあるし、その記憶だね

2021-09-28 14:19 UTC, xiii111 approved these changes
LGTM!

2021-09-29 02:23 UTC, takesi0627 commented
@takasusuke 
マージして大丈夫？

https://github.com/LITO-apps/Treevel-client/pull/1158#issuecomment-928512992
一応この修正の返事まだの気がする

2021-09-29 04:08 UTC, takasusuke approved these changes
遅れてごめん！OK！

2021-09-29 04:12 UTC, xiii111 commented
マージできそうなので、しちゃいますね！

2021-09-29 04:12 UTC, merged