チュートリアルポップアップデザイン適用
LITO-apps/Treevel-client pull request #1242
Opened 2021-11-05 10:53 UTC by takesi0627

### 対象イシュー
Close #1201 

### 概要
#1073 で決めたチュートリアルの仕様実装及びデザイン適用

### 詳細

#### 現実装になった経緯

* `GamePlayDirector` の変更について
  * スタートステートは`TutorialState`に統一
  * TutorialState -> TutorialState （2個以上チュートリアルがある場合）の遷移を許可

* 設定について
  * テキスト、画像の設定は`GameDatas/Tutorials/Data`に格納している `TutorialData`を設定（`TextIndex`と`TutorialType`の設定は基本済んでいるのであとは画像か動画を入れるだけ。
  * 画像や動画ファイルは `GameDatas/Tutorials/Resource`に格納する想定。
  * `StageData`で適切のチュートリアルタイプを設定
![image](https://user-images.githubusercontent.com/17778395/140499546-dbdfed8e-65f8-4cd7-9b45-cee23cc1f9da.png)
 
* `Tools > Debug Command > Reset Tutorial States`にてチュートリアル既読状態をリセットコマンドを実装したので、複数回確認したい場合ご利用ください。
![image](https://user-images.githubusercontent.com/17778395/140499801-ed3418ce-8165-4d34-9327-09d218e26568.png)

### キャプチャ

https://user-images.githubusercontent.com/17778395/140496645-1b565684-cedc-45b4-b434-0a4f19c30d02.mov

### 動作確認方法

- [ ] `Autumn-1-1`をプレイし、チュートリアルが開始すること
- [ ] チュートリアルポップアップが2回連続出していることを確認
- [ ] ゲームを抜けて再度入る時にチュートリアルが発生しないことを確認

### 参考 URL

2021-11-05 10:58 UTC, takesi0627 commented
@LITO-apps/engineer 
変更量が多いので時間かかりそうですがよろしくお願いします。

2021-11-06 13:36 UTC, takasusuke requested changes
以下の設定でいかがでしょうか。
IconのRectTransfrom
<img width="1396" alt="スクリーンショット 2021-11-06 22 34 31" src="https://user-images.githubusercontent.com/26213141/140611622-aab8c4a1-1059-4068-bc4f-e408f26f5efa.png">

LoadingのRectTransform
<img width="1383" alt="スクリーンショット 2021-11-06 22 34 37" src="https://user-images.githubusercontent.com/26213141/140611625-28f757ee-c5dc-48e0-b34b-0f0ad24933e4.png">

VideoPlayerにAspectRatioFilterを設定する
<img width="1395" alt="スクリーンショット 2021-11-06 22 34 53" src="https://user-images.githubusercontent.com/26213141/140611627-c553fcef-b29f-4494-8d6c-44465e719fd5.png">

2021-11-06 13:54 UTC, takasusuke requested changes
お疲れ様でございます。

`Debug Command`にチュートリアルリセットが出ません。
何かpushし忘れてたりしない？？

2021-11-06 13:54 UTC, takasusuke commented on Assets/Project/Resources/GameDatas/translation.csv
> +TutorialDescriptionLifeBottleAttribute,TutorialDescriptionLifeBottleAttribute_JPN_PLACEHOLDER,TutorialDescriptionLifeBottleAttribute_ENG_PLACEHOLDER,
### ask
「次へ」、「始める」に対応する翻訳文がない？

<img width="284" alt="スクリーンショット 2021-11-06 22 43 01" src="https://user-images.githubusercontent.com/26213141/140611851-bcb6dd11-688e-4a74-9086-4a69cd13387d.png">

2021-11-06 13:54 UTC, takasusuke commented on Assets/Project/Scripts/Common/Entities/TutorialType.cs
> +        public static void SetChecked(this ETutorialType type)
### must
このメソッド呼ばれてなくない？？
ステージに入ると毎回、チュートリアルが表示されます。

2021-11-06 13:54 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/TutorialPopupController.cs
> +    [SerializeField] private Button _button;
### imo
できる所はドキュメンテーションコメント描いてもらえると嬉しい

2021-11-06 13:54 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/TutorialPopupController.cs
> +public class TutorialPopupController : MonoBehaviour
### must
namespaceつけて〜〜
```
namespace Treevel.Modules.GamePlayScene
{
}
```

2021-11-06 13:54 UTC, takasusuke commented on Assets/Project/Scripts/Common/Entities/GameDatas/TutorialData.cs
> +
### imo
アイコンも動画も設定していたら、Editorか、TutorialPopupControllerの中でassert出せたら良いね。

2021-11-06 14:15 UTC, takesi0627 commented
> `Debug Command`にチュートリアルリセットが出ません。 何かpushし忘れてたりしない？？

すまん、コミットだけしてプッシュしてなかった

2021-11-06 14:16 UTC, takesi0627 commented on Assets/Project/Resources/GameDatas/translation.csv
> +TutorialDescriptionLifeBottleAttribute,TutorialDescriptionLifeBottleAttribute_JPN_PLACEHOLDER,TutorialDescriptionLifeBottleAttribute_ENG_PLACEHOLDER,
1df1120
プッシュし忘れた

2021-11-06 14:16 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/TutorialType.cs
> +        public static void SetChecked(this ETutorialType type)
af0090a
プッシュし忘れた

2021-11-06 14:59 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                    currentTutorial.SetChecked();
### imo
前の実装だと、TutorialStateを出るとき(ボタンを押す時)に既読扱いになっていました。
自分はそれが良いと思います。

2021-11-07 00:32 UTC, xiii111 reviewed
`StageRecord` から `tutorialChecked` を消してもらえますか？

2021-11-07 00:33 UTC, xiii111 commented
↑ ざっと差分を確認しました。あとは @takasusuke にお任せします

2021-11-07 02:52 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/TutorialPopupController.cs
> +public class TutorialPopupController : MonoBehaviour
df571f3

2021-11-07 02:59 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/GameDatas/TutorialData.cs
> +
015c5b9

2021-11-07 02:59 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/TutorialPopupController.cs
> +    [SerializeField] private Button _button;
df571f3

2021-11-07 03:00 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/TutorialPopupController.cs
> +public class TutorialPopupController : MonoBehaviour
3761605

2021-11-07 03:01 UTC, takesi0627 commented
> `StageRecord` から `tutorialChecked` を消してもらえますか？�また、ざっと差分を確認しました。あとは @takasusuke にお任せします

eb83050

2021-11-07 03:07 UTC, takesi0627 commented
> 以下の設定でいかがでしょうか。

なんか変な値になっちゃってたね。
これでいいですかね
cde6094、 5c0f0dd

2021-11-07 03:11 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                    currentTutorial.SetChecked();
5bdf2c3

2021-11-07 03:12 UTC, takesi0627 commented
@takasusuke 
一通りレビュー対応しました。確認よろしくお願いします。

@xiii111 
https://github.com/LITO-apps/Treevel-client/pull/1242#issuecomment-962543876 だけ確認お願いします

2021-11-07 11:40 UTC, xiii111 approved these changes
LGTM!

2021-11-07 11:40 UTC, xiii111 commented on ProjectSettings/DeviceSimulatorSettings.asset
> +    "ApplicationSimulation": true,
これ何？

2021-11-07 13:34 UTC, takesi0627 commented on ProjectSettings/DeviceSimulatorSettings.asset
> +    "ApplicationSimulation": true,
いつかのアップデートで出た差分かと思われる

2021-11-08 09:53 UTC, xiii111 commented on ProjectSettings/DeviceSimulatorSettings.asset
> +    "ApplicationSimulation": true,
おk

2021-11-08 12:14 UTC, takasusuke approved these changes
Nice~

2021-11-08 12:40 UTC, merged