プログレス系の UI を削除する
LITO-apps/Treevel-client pull request #1248
Opened 2021-11-08 12:41 UTC by xiii111

### 対象イシュー
Close #1184 

### 概要
- プログレスバーを削除する → cb9abb41b44e90456d81d141ab524e271e8806ae
- ゲーム画面遷移時のプログレスを削除する → cb9abb41b44e90456d81d141ab524e271e8806ae
- 上記削除時に、ポップアップを消してしまうと変だったので、消さないようにした → 39be81574a45d02090da6fe20a0572bdcd3c4a7a

### キャプチャ
#### 変更前
https://user-images.githubusercontent.com/26104258/140743169-737097a5-255c-46dc-820f-6aef0acab222.mov

#### 変更後
＊この動画は 39be81574a45d02090da6fe20a0572bdcd3c4a7a 適用前なので、ポップアップを消してしまう状態。これを消さないようにした

https://user-images.githubusercontent.com/26104258/140743293-00118035-ec4d-41e3-b462-16931b4878ad.mov

### 動作確認方法
- [ ] 各種プログレス UI が出ないこと
- [ ] 消し忘れがないこと

### 備考
- https://github.com/LITO-apps/Treevel-client/issues/1184#issuecomment-963112135

2021-11-08 12:43 UTC, xiii111 commented
@LITO-apps/engineer お願いします！

2021-11-08 13:42 UTC, takesi0627 requested changes
### `must`

`AddressableAssetManager`の`OnAssetStartLoad`はプログレスバーを表示するために作りました。プログレスバーが消えた現在使用されていない。
本当は残っておいても良いですが、よくよくみたらこの子ちゃんと`Dispose`してないし、 `static class`だから`Dispose`するタイミングよくわかりません。
なので申し訳ないが、ここら辺もとりあえず消してただけませんか。

2021-11-08 14:02 UTC, takasusuke approved these changes
自分は特にありません！

2021-11-08 14:28 UTC, xiii111 commented
@takesi0627 1ccf990 で修正しました！

2021-11-09 00:21 UTC, takesi0627 approved these changes
感謝🙏

2021-11-09 00:29 UTC, merged