設定画面（その他画面）デザイン適用
LITO-apps/Treevel-client pull request #1249
Opened 2021-11-09 14:56 UTC by takesi0627

### 対象イシュー
Close #625 

### 概要
タイトル通り

### 詳細

* テキストの翻訳については #1246 でローカライズシステムを導入することを想定するため、今回はあえてやらないことにした。 `Text` コンポーネントに日本語直接入力しています。

* `LevelSelect`を見えるようにしたため、設定画面に切り替えても海のSEが流し続けます。
（`LevelSelectDirector`の`OnDisable`呼ばれないから）
しかし、よく考えたら、設定画面でSEの音量設定があるのにSE一切聞こえないのも何が変だったのでそのままにしました。

### キャプチャ
![image](https://user-images.githubusercontent.com/17778395/140946208-f7df1e1e-afd7-4aab-94d3-7cab300586a7.png)

### 動作確認方法
- [ ] 設定画面を開き、レイアウトを確認する
- [ ] BGM、SEバー、ミュートボタンの機能確認
- [ ] 一時停止画面のBGM／SE制御周りの確認

### 参考 URL

2021-11-09 15:04 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Settings/ReviewController.cs
> +using UnityEngine.iOS;
変なところにいたので直しておきました

2021-11-09 15:04 UTC, takesi0627 commented on SOURCE.md
> +| File Path | Credit |
項目が増えてきて見にくくなったので表にしました

2021-11-09 15:04 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/PlayerPrefsUtility.cs
> +        public static void SetBool(string key, bool value)
Boolを扱うPlayerPrefs関数がないので拡張しました

2021-11-09 15:04 UTC, takesi0627 commented
@LITO-apps/engineer 
よろしくお願いします
10min~20min程度かと思います

2021-11-10 04:52 UTC, xiii111 reviewed
対応ありがとうございます！かなり良いと思います。見た目とコードに関して、いくつかレビューしました！お願いします

以下の画像に対して ...

<img width="331" alt="スクリーンショット 2021-11-10 13 18 55" src="https://user-images.githubusercontent.com/26104258/141049025-635b2339-aa27-4f28-950f-dee7ba501a89.png">

### imo
`Option` という文言の上の余白の広さに対して、`公式ツイッター` の下の余白が狭いので、全体的にやや上に位置をずらしたいです

### imo
これは別イシュー可なのですが、ミュートしているかどうかが思ったよりも分かりづらいので、色を変えて解決できないかを検討したいです。現状が淡い色だから分かりづらいのか、そもそもデザイン的に分かりづらいかを切り分けたいという意味もあります

### ask
`Option` という文言と、フッターの文言である `その他` は揃えるという認識でしたが、合っていますか？

2021-11-10 04:52 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Settings/TwitterButtonController.cs
> +            Application.OpenURL("https://twitter.com/NumberBullet?s=20");
### nits
```suggestion
            Application.OpenURL("https://twitter.com/NumberBullet");
```

2021-11-10 04:52 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/UserSettings.cs
> +            IsSeMute.SkipLatestValueOnSubscribe().Subscribe(value => SoundManager.Instance.SetSeMute(value)).AddTo(_disposable);
### ask

初期値が不要なのって何故でしたっけ？（ `bgmPlayer.mute` のデフォルト値になってしまわない？）

2021-11-10 04:52 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/UIs/MuteButton.cs
> +                image.sprite = isOn ? _offImage : _onImage; // toggleがOnの時サウンドはOff
### imo

これ分かりづらいので、トグルの on 状態をサウンドの on 状態にしませんか？

2021-11-10 04:52 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/UIs/VolumeController.cs
> +        };
### imo

`MuteButton` の `EControlType` と役割が同じだと思うので、一つの Entity として存在している方が自然に見えました

2021-11-10 04:52 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/UIs/VolumeController.cs
> +            // ユーザ設定が別のところで変えられた場合スライダーに反映
### nits

音量設定が、設定画面と一時停止画面に散らばっているということを明記しておきましょう

2021-11-10 04:59 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/VolumeController.cs
> +        };
グローバルのスコープを持つ必要のないデータと思ったのであえて両方にそれぞれ書いてますが、
どうでしょうか

2021-11-10 05:04 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/UserSettings.cs
> +            IsSeMute.SkipLatestValueOnSubscribe().Subscribe(value => SoundManager.Instance.SetSeMute(value)).AddTo(_disposable);
https://github.com/LITO-apps/Treevel-client/blob/b3cd7ff6496ad5532bf824bebbdf5a1dd7b7c4fe/Assets/Project/Scripts/Common/Entities/UserSettings.cs#L12


`static`  のインスタンスを作ってるので、エディタ立ち上げる段階でコンストラクタが呼ばれますが、その時点では `SoundManager` のインスタンスが存在しないので不都合が起きる。
しかし今考えてみたらこれだと、実機では確かに保存した値は反映されなさそうなので、
`if #UNITY_EDITOR`  で処理分けるべきかもしれない（ほかのプロパティも同様）

2021-11-10 14:28 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/UIs/VolumeController.cs
> +        };
実際に複数で利用している点で、グローバルになっている気がしないでもないですが、とりあえず今回は ok です！

2021-11-10 14:29 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/UserSettings.cs
> +            IsSeMute.SkipLatestValueOnSubscribe().Subscribe(value => SoundManager.Instance.SetSeMute(value)).AddTo(_disposable);
なるほど？とりあえず、問題が生じない形に直してもらえたらと！

2021-11-10 14:29 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/UserSettings.cs
> +            IsSeMute.SkipLatestValueOnSubscribe().Subscribe(value => SoundManager.Instance.SetSeMute(value)).AddTo(_disposable);
222613f

`SkipLatestValueOnSubscribe`全部消して、`SoundManager`に依存する設定は `StartUpDirector`から初期化するようにしました

2021-11-10 14:51 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/MuteButton.cs
> +                image.sprite = isOn ? _offImage : _onImage; // toggleがOnの時サウンドはOff
222613f

2021-11-10 14:55 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/VolumeController.cs
> +            // ユーザ設定が別のところで変えられた場合スライダーに反映
明記する必要ありますか？
このコンポーネント自体置く場所に制限する必要ないし、
明記するところで、もし万が一新しい場所に置くことになると、ここのコメントが不適切になるのではないでしょうか

2021-11-10 15:16 UTC, takasusuke requested changes
### must
SettingのBGMとSEのSliderのFillAreaの`Top`と`Bottom`を0にお願いします。
Sliderの色を濃くすると、ズレてるのがわかりやすい。
<img width="1409" alt="スクリーンショット 2021-11-11 0 11 21" src="https://user-images.githubusercontent.com/26213141/141139120-c24a7577-13cc-43c0-84df-f672993c4f49.png">

### imo
このissue外とは思うけど、
一時停止画面のSliderの大きさ・縦横比とSettingのSliderの大きさ・縦横比を揃えたい。

2021-11-10 15:16 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/UIs/VolumeController.cs
> +        };
### nits
```suggestion
        }
```

2021-11-10 15:20 UTC, takasusuke commented
このissue外とは思うけど、
一時停止画面のSliderの大きさ・縦横比とSettingのSliderの大きさ・縦横比を揃えたい。

2021-11-10 15:20 UTC, takesi0627 commented
> ### imo
> `Option` という文言の上の余白の広さに対して、`公式ツイッター` の下の余白が狭いので、全体的にやや上に位置をずらしたいです

e349beb

| 修正前 | 修正後 |
| --- | --- |
| <img width="300" src="https://user-images.githubusercontent.com/17778395/140946208-f7df1e1e-afd7-4aab-94d3-7cab300586a7.png"> | <img width="300" src="https://user-images.githubusercontent.com/17778395/141140097-79df5570-e792-4ec1-99c3-d413984b4d98.png"> |

スライダーも少し調整入れました

> ### imo
> これは別イシュー可なのですが、ミュートしているかどうかが思ったよりも分かりづらいので、色を変えて解決できないかを検討したいです。現状が淡い色だから分かりづらいのか、そもそもデザイン的に分かりづらいかを切り分けたいという意味もあります

淡い色だからだと思います、対比が足りない気がする

> ### ask
> `Option` という文言と、フッターの文言である `その他` は揃えるという認識でしたが、合っていますか？

この仕様は知らなかった。どこかに書いてあったりしますか？

2021-11-10 15:27 UTC, takesi0627 commented
> このissue外とは思うけど、
> 一時停止画面のSliderの大きさ・縦横比とSettingのSliderの大きさ・縦横比を揃えたい。


6d0996b

2021-11-10 15:34 UTC, takesi0627 commented
> SettingのBGMとSEのSliderのFillAreaの`Top`と`Bottom`を0にお願いします。 Sliderの色を濃くすると、ズレてるのがわかりやすい。 

420e053

2021-11-10 15:40 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/UIs/MuteButton.cs
> +            }).AddTo(this);
### ask
ここってこれだけでも良い？(あと、`VolumeController`の`volumePropertyのsubscriveも同じ)
デフォルトボタン押しても、Mute状態は変わらないからSubscribeしてる意味がなさそうに感じた。(デフォルト機能自体ないけど)

汎用的なUIcomponentだから、念のためってことならこのままでも良いとは思う。

```suggestion
            // ミュートプロパティに変化あった時にトグルに反映
            toggle.isOn = !muteProperty.Value;
```

2021-11-11 04:41 UTC, xiii111 commented
@takesi0627 

https://github.com/LITO-apps/Treevel-client/pull/1249#issuecomment-965380317

> e349beb

ごめんなさい、修正前から各余白を変えずに、全体を上にずらすだけのイメージでした。

> 淡い色だからだと思います、対比が足りない気がする

まぁ、追々

> この仕様は知らなかった。どこかに書いてあったりしますか？

漏れていたかもしれませんが、必要ですよね？

2021-11-11 04:42 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/UserSettings.cs
> +        public UserSettings()
何故外部からの初期化を許しましたか？（シングルトンなのに）

2021-11-11 04:42 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/UIs/MuteButton.cs
> +                if (isSoundOn != !muteProperty.Value)
`isSoundOn == muteProperty.Value`

2021-11-11 04:43 UTC, xiii111 commented
@takesi0627 以下三点お願いします！

- [ ] https://github.com/LITO-apps/Treevel-client/pull/1249#issuecomment-965984374
- [ ] https://github.com/LITO-apps/Treevel-client/pull/1249#discussion_r747194352
- [ ] https://github.com/LITO-apps/Treevel-client/pull/1249#discussion_r747195652

2021-11-11 04:44 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/UserSettings.cs
> +        public UserSettings()
`SingletonBase<T>` の制限です (`where T : new ()`)

2021-11-11 04:44 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/UserSettings.cs
> +        public UserSettings()
外部から初期化できたら、シングルトンではないのでは？

2021-11-11 04:49 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/UserSettings.cs
> +        public UserSettings()
そもそも `SingletonBase<T>` と `SingletonObjectBase<T>` は外部からインスタンスが作れてしまう点で、シングルトンじゃない気がしてきた

https://github.com/LITO-apps/Treevel-client/blob/develop/Assets/Project/Scripts/Common/Utils/StageRecordService.cs などがシングルトンの要件を満たしている気がします

2021-11-11 04:56 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/UserSettings.cs
> +        public UserSettings()
結構初期の時からこのクラスにはこの問題があると伝えたはずだけどな・・
`new()`の制約は `SingletonBase<T>` だけあって `SingletonObjectBase<T>` にはないので、`SingletonObjectBase<T>`は問題ないかと思いますが。（`Instantiate`を使えば誰でもインスタンス作れるから`Monobehaviour`に関してはどうしょうもないと思う）

そうしたら、`SingletonBase<T>` は廃止する方向で、
現状`SingletonBase`を継承している`AnimationStateManager`も、今後シングルトンで運用するものに関しては `StageRecordService` みたいに各自実装する方向がいいかな

2021-11-11 05:04 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/UserSettings.cs
> +        public UserSettings()
https://github.com/LITO-apps/Treevel-client/pull/1146#discussion_r711610181

同じやり取りしてたね、あの時は @takasusuke の要望で `SingletonBase` にしたんだけど、
やっぱり微妙なので、廃止する方向でいいと思います。

2021-11-11 05:15 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/UserSettings.cs
> +        public UserSettings()
8dcaf74

2021-11-11 05:24 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/MuteButton.cs
> +            }).AddTo(this);
739a0dd

2021-11-11 05:24 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/MuteButton.cs
> +                if (isSoundOn != !muteProperty.Value)
287ec55

2021-11-11 05:44 UTC, takesi0627 commented
| 修正前 | e349beb |  e0521c9 |
| --- | --- | --- |
| <img width="300" src="https://user-images.githubusercontent.com/17778395/140946208-f7df1e1e-afd7-4aab-94d3-7cab300586a7.png"> | <img width="300" src="https://user-images.githubusercontent.com/17778395/141140097-79df5570-e792-4ec1-99c3-d413984b4d98.png"> |<img width="300" src="https://user-images.githubusercontent.com/17778395/141244147-b7e2d97d-7c81-44db-b533-6207e4e4e717.png">

2021-11-11 05:52 UTC, takesi0627 commented
9084cfc : 記録画面から設定画面に切り替えるときに `LevelSelect`を`Active`にしないと真っ青の背景になるので `その他`ボタンを押す際に`LevelSelect`が`Active`になるよう設定した

![image](https://user-images.githubusercontent.com/17778395/141244968-d535ddaa-0740-41de-80f9-aa0539bfa3c4.png)

2021-11-11 09:51 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/UserSettings.cs
> +        public UserSettings()
> 結構初期の時からこのクラスにはこの問題があると伝えたはずだけどな・・

申し訳ない

対応ありがとうございます

2021-11-11 09:55 UTC, xiii111 approved these changes
一点質問しましたが、基本的に ok です。あとは @takasusuke にお任せします

2021-11-11 09:55 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/UserSettings.cs
> +
### ask

`StageRecordService` などでもシングルトンパターンを適用しているから質問なのだけど、この二行は

```csharp
public static readonly StageRecordService Instance = new StageRecordService();
```

これじゃだめ？

2021-11-11 09:57 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/UserSettings.cs
> +
今まで結構プログラム読み込む段階でインスタンス化したことが原因で不具合が起きてたから、
`static`変数をそのままインスタンスを作ることをあえて避けてます

2021-11-11 09:59 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/UserSettings.cs
> +
なるほど。いざ使うときにしかインスタンスを生成しないってことね。把握🙆‍♂️

2021-11-11 15:10 UTC, takasusuke approved these changes
👍❗️😀

2021-11-11 15:35 UTC, merged