世界観を伝えるOnBoarding（LevelSelectのOnBoarding）
LITO-apps/Treevel-client pull request #1267
Opened 2021-11-22 15:53 UTC by takesi0627

### 対象イシュー
Close #1191 

### 概要
LevelSelectで表示するOnBoardingの実装

### 詳細

* OnBoardingの基盤実装も含めましたので、 #1190  の工数が大幅に削減できると思います
* OnBaordingの仕組み基本チュートリアルと似ているので、 #1201 を参考してほぼ同じように実装しました。 （`TutorialData`自体そのまま使用することもできたが、スコープを分ける観点からデータの内容がほぼ一緒でも違うクラスにすることにした）
* シーンがロードされてからポップアップが表示されるまで少し間があるのでちらつくように見えるため、`FadeObject2D`を使ってフェイドインを実装しています。
* OnBoardingのためのStringTableを作成しました。今後はOnBoarding関連テキストはそちらに保存する予定。

### キャプチャ

https://user-images.githubusercontent.com/17778395/142891245-6bec7a7d-9cf7-4898-a9c5-1ac8b6143611.mov

### 動作確認方法
- [ ] 初めてゲームに入るときにポップアップが表示されること。
- [ ] ゲームを終了し、再開するときにポップアップが表示されないこと。

※`Tools > Debug Command > Reset On Boarding States`でデータを削除できる。
### 備考

* 英訳は仮（資料にある日本語の説明文とタイトルは確定だっけ？）
* 画像はスライドからキャプチャしたもの

2021-11-22 15:54 UTC, takesi0627 commented
@LITO-apps/engineer 
レビューよろしくお願いします。
チュートリアルポップアップの実装とほぼ変わらないので、
そんなに重くはないと思います。

2021-11-23 03:27 UTC, takasusuke requested changes
とても良い！フェードも良い！

MenuSelectSceneのコンフリクトごめん。。。

- `UIs/Common/OnBoarding/OnBoarding.SafeAreaPanel.Title`と`Description`に`Localize String Event`がアタッチされていないので、設定お願いします。
- `UIs/Common/ErrorMessageBox.Panel`の`image`componentみたいに`Tiling`でポップアップ画像の設定をお願いします
<img width="473" alt="スクリーンショット 2021-11-23 11 49 19" src="https://user-images.githubusercontent.com/26213141/142964456-e0af81e1-2e28-4467-a03a-ebc130634c5d.png">

### ask
ここの`additional shader channels`って何かこだわりある？
`Nothing`でも問題ないならそれにしても良い？

<img width="473" alt="スクリーンショット 2021-11-23 12 14 43" src="https://user-images.githubusercontent.com/26213141/142966276-2448d6e1-1dbb-4ae3-bfa9-47443ffc8396.png">

2021-11-23 03:27 UTC, takasusuke commented on ProjectSettings/ProjectSettings.asset
> +    4: UNITY_POST_PROCESSING_STACK_V2;ENV_PROD
### imo
あんまりこだわりないけど、`ENV_PROD`に変える理由もない気はする

2021-11-23 03:27 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/UIs/OnBoardingPopup.cs
> +                // 既読にする
### imo
`UI_Button_Close_Popup`のSE欲しい

2021-11-23 03:27 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelSelectDirector.cs
> +            }
### ask
popupの後のコーチマークを実装するときは、こんな感じになる理解で良い？
```
 // OnBoardingまだみてないなら表示する
if (!EOnBoardingType.MenuSelectScene.IsChecked()) {
    ShowOnBoardingAsync().Forget();
    OnBoardingのClose時にコーチマークを表示するようにイベントをセットする
} else {
    if (コーチマークを見てない) { 
        コーチマーク出す
    } else {
        // 解放できる道を計算し、演出を再生
        CheckReleaseNewLevelAsync().Forget();
    }
}
```

2021-11-23 03:28 UTC, takesi0627 commented on ProjectSettings/ProjectSettings.asset
> +    4: UNITY_POST_PROCESSING_STACK_V2;ENV_PROD
間違えてコミットしちゃった

2021-11-23 05:54 UTC, xiii111 reviewed
動作確認しました！詳細なレビューは @takasusuke にお任せしようと思います！

見た目に関しては、テキストが黒文字だと若干見づらかったり、行間が少し詰まりすぎていたりなどありますが、軽微な内容なので、β 版の範疇でやれば良い気がします。アイデアには載せておきます

2021-11-23 14:16 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelSelectDirector.cs
> +            }
いいえ、コーチマークのこと特に考慮していません。
ポップアップのあと必ずコーチマークが発生するんだっけ

2021-11-23 14:16 UTC, takesi0627 commented on ProjectSettings/ProjectSettings.asset
> +    4: UNITY_POST_PROCESSING_STACK_V2;ENV_PROD
5983027
戻した

2021-11-23 14:25 UTC, takesi0627 commented
> とても良い！フェードも良い！
> 
> MenuSelectSceneのコンフリクトごめん。。。

コンフリクト解決しました。

> * `UIs/Common/OnBoarding/OnBoarding.SafeAreaPanel.Title`と`Description`に`Localize String Event`がアタッチされていないようなので、設定お願いします。

テキストはスクリプトより制御するので `Localize String Event` をタッチする必要がありません。
もし、ゲーム実行中にローケルを変えても変化しないことを気にするなら、 スクリプト内で `localizedString.StringChanged`を購読する必要があります。
しかし現状ゲーム中に言語を変更する機能がないので特にその処理入れていないですが、入れたほうがいいですかね

> ### ask
> ここの`additional shader channels`って何かこだわりある？ `Nothing`でも問題ないならそれにしても良い？
> 

df008ba
マージの時についでにやっちゃった。

2021-11-23 14:32 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/OnBoardingPopup.cs
> +                // 既読にする
24168a7

2021-11-23 14:33 UTC, takesi0627 commented
@takasusuke 
再レビューお願いします

2021-11-23 14:53 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelSelectDirector.cs
> +            }
このポップアップの後に、コーチマークが出る想定です。

特に今の段階でコーチマークのことは考えなくてよくて、同じように実装するならこんな感じ？と聞きたかっただけ。

2021-11-23 15:05 UTC, takasusuke commented
> > * `UIs/Common/OnBoarding/OnBoarding.SafeAreaPanel.Title`と`Description`に`Localize String Event`がアタッチされていないようなので、設定お願いします。
> 
> テキストはスクリプトより制御するので `Localize String Event` をタッチする必要がありません。 もし、ゲーム実行中にローケルを変えても変化しないことを気にするなら、 スクリプト内で `localizedString.StringChanged`を購読する必要があります。 しかし現状ゲーム中に言語を変更する機能がないので特にその処理入れていないですが、入れたほうがいいですかね

Localization packageの言語選択って、アプリ初回起動時のユーザの言語設定で決まる、、、のかな？
それ以降にユーザがデバイスの言語設定を切り替えても、Treevelには反映されない？
途中でユーザが言語設定切り替えた時に、Treevelに反映されるなら、全てのTextには`Localize String Event`をアタッチした方が良いと思った。
OnBoardingのここだけじゃなくて、やるならチュートリアルとかもか。やるとしてもまとめてで良いと思うのでここでは大丈夫と思いました。

2021-11-23 15:05 UTC, takasusuke approved these changes

2021-11-24 14:37 UTC, takesi0627 commented
> > > * `UIs/Common/OnBoarding/OnBoarding.SafeAreaPanel.Title`と`Description`に`Localize String Event`がアタッチされていないようなので、設定お願いします。
> > 
> > 
> > テキストはスクリプトより制御するので `Localize String Event` をタッチする必要がありません。 もし、ゲーム実行中にローケルを変えても変化しないことを気にするなら、 スクリプト内で `localizedString.StringChanged`を購読する必要があります。 しかし現状ゲーム中に言語を変更する機能がないので特にその処理入れていないですが、入れたほうがいいですかね
> 
> Localization packageの言語選択って、アプリ初回起動時のユーザの言語設定で決まる、、、のかな？ それ以降にユーザがデバイスの言語設定を切り替えても、Treevelには反映されない？ 途中でユーザが言語設定切り替えた時に、Treevelに反映されるなら、全てのTextには`Localize String Event`をアタッチした方が良いと思った。 でもOnBoardingのここだけじゃなくて、やるならチュートリアルとかもか。やるとしてもまとめてで良いと思うのでここでは大丈夫と思いました。

ちょっと検証してみないとわからないですね、
もしシステム言語を変えてTreevelに戻ったら言語が変わったら、それは対応しないといけないんですが、
スクリプト制御のテキストに関しては多分 `Localize String Event` アタッチするだけじゃ対応できないと思うのでまた調査する必要があります。
アイデアに載せときます

2021-11-24 14:39 UTC, merged