ステージプレビュー機能実装
LITO-apps/Treevel-client pull request #1272
Opened 2021-11-26 16:03 UTC by takesi0627

### 対象イシュー
Close #1206 

### 概要
ステージ概要ポップアップのステージプレビュー機能の実装

### 詳細

#### 現実装になった経緯

* タイルについて
    * NormalTileは予め`OverviewPopup.prefab`のにて設定している。スクリプトより制御しない。
    * `HolyTile` については光のエフェクト（StagePreviewItem.HolyTileEffect）はボトルの手前に置く必要があるため、別オブジェクトにして制御している。

* ボトルについて
    * 各属性は割と違う作りになっているのでそれぞれオブジェクトを作成し状況によってOn／Offで制御する。

### キャプチャ

![image](https://user-images.githubusercontent.com/17778395/143606294-1ef3c046-a9d6-441c-877f-5c57aac28430.png)

### 動作確認方法
- [ ] 各ステージにてステージ概要で表示されたステージプレビューの内容と一致しているかの確認

### 参考 URL

2021-11-26 16:04 UTC, takesi0627 commented
@LITO-apps/engineer 
レビューよろしくお願いします。

* OverviewPopup.prefab
* StagePreviewItem.prefab
* StagePreviewItem.cs

を重点において見ていただければかと思います

2021-11-26 16:12 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/AddressableAssetManager.cs
> -                        tasks.Add(LoadAssetAsync<Sprite>(Constants.Address.STATIC_DUMMY_BOTTLE_SPRITE));
プレハブにアタッチしているので、ここでロード必要するがないため削除した。

2021-11-26 16:12 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/TileLibrary.cs
> +        }
本来 `SpiderwebTileController` で書いてるロジックをどうしても再利用したいんですが、適切の場所見つからなかったので`TileLibrary` を作りました。もっと適切の場所があるとお考えなら教えていただけると助かります

2021-11-28 03:04 UTC, takasusuke requested changes
8割くらい見た。動作は感動した。

### must
ボトル画像の横幅：縦幅=10:11なので、以下のように設定してもらえますか？

<img width="1561" alt="スクリーンショット 2021-11-28 11 57 26" src="https://user-images.githubusercontent.com/26213141/143727231-bf4b11c2-5e55-4717-8cf1-f1dfbef8207f.png">

2021-11-28 03:04 UTC, takasusuke commented on Assets/Project/Scripts/Modules/StageSelectScene/StageDetail/StagePreviewWindowView.cs
> +                _items[tileData.number - 1].SetTileAsync(tileData).Forget();
### must
`WarpTile`の場合、相方WarpTileの画像も設定しないといけないので、ちょっと工夫必要だわ。。

<img width="702" alt="スクリーンショット 2021-11-28 11 31 26" src="https://user-images.githubusercontent.com/26213141/143727202-8ee33f97-0f22-48cd-b299-608cdb8303ce.png">

2021-11-28 07:08 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/StageSelectScene/StageDetail/StagePreviewWindowView.cs
> +                _items[tileData.number - 1].SetTileAsync(tileData).Forget();
確かに・・完全に頭から抜けた

2021-11-28 07:15 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/TileLibrary.cs
> +        }
`SpiderwebTileController`に置かないのはその理由であってます。
今回の変更を加えてこのロジックは `StageSelectScene` と `GamePlayScene`ともに必要のあるものなので、`Common` の方が適切だと思います。

2021-11-28 07:26 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/StageSelectScene/StageDetail/StagePreviewWindowView.cs
> +                _items[tileData.number - 1].SetTileAsync(tileData).Forget();
b5c37aa

2021-11-28 07:28 UTC, takesi0627 commented
> ### must
> ボトル画像の横幅：縦幅=10:11なので、以下のように設定してもらえますか？
> 
> <img alt="スクリーンショット 2021-11-28 11 57 26" width="1561" src="https://user-images.githubusercontent.com/26213141/143727231-bf4b11c2-5e55-4717-8cf1-f1dfbef8207f.png">

d481715 でボトルの縦横比を調整した
また `DarkAttribute` と `LifeAttribute` の縦横比が `BottleImage` に依存していたので、
それぞれ依存しないように階層を調整した。

2021-11-29 11:46 UTC, xiii111 reviewed
すごい 👏👏 動作確認を中心に行いました〜！

|プレビュー|ゲーム|
|---|---|
|<img width="372" alt="スクリーンショット 2021-11-29 20 32 49" src="https://user-images.githubusercontent.com/26104258/143860875-7d38d20e-2348-41ea-8883-b2cd96bb38a0.png">|<img width="370" alt="スクリーンショット 2021-11-29 20 33 00" src="https://user-images.githubusercontent.com/26104258/143860894-d6a3d25c-2a57-4c25-a597-785fc7679ab6.png">|

- プレビューにおいて、ボトルより後ろに蜘蛛の巣が来ていますが、想定通りですか？
- Static の大きさ（縦横比？）が、プレビューとゲームで違いそうです

2021-11-29 11:55 UTC, takasusuke commented
DarkAttributeがちょっと大きい気がするがまあ良いか。。。
直すとすると、画像の大きさをそもそも変えたり、余白を切ったりしないといけないし、GamePlaySceneにも影響出そう。
ちょっとだけDarlAttibute小さくしてもらえる助かります。。。

2021-11-29 14:27 UTC, takesi0627 commented
@xiii111 @takasusuke 

暗闇エフェクトとStaticボトル両方解決しました。

static と goalの横縦比が違う問題は、`Image.preserveAspect`プロパティを使えば解決できるので、
`BottleImage`の`Anchor`は`0.05`,`0.95`に戻しました

| プレビュー | ゲーム |
| --- | --- |
| <img width="300" src="https://user-images.githubusercontent.com/17778395/143884888-2860d089-34cb-4c05-b37d-f86c2028508d.png"> | <img width="300" src="https://user-images.githubusercontent.com/17778395/143885120-5a980ffc-ba39-4614-b7e1-f20bbb44a160.png"> |

2021-11-29 16:17 UTC, takasusuke approved these changes
天才

2021-11-30 04:11 UTC, xiii111 approved these changes
LGTM!!

2021-11-30 15:14 UTC, merged