[OnBoarding-2] 木への誘導コーチマークのデザイン適用
LITO-apps/Treevel-client pull request #1282
Opened 2021-12-03 16:17 UTC by takesi0627

### 対象イシュー
Close #1140 

### 概要
コーチマークの基盤実装とLevelSelectへの適用

### 詳細

* [UnmaskForUGUI](https://github.com/mob-sakai/UnmaskForUGUI)の導入
マスクの実装では、今までの黒マスクの真ん中をくり抜く必要があり、それは uGUI のコンポーネントの組み合わせでは実現できませんでしたので、ライブラリを導入しました（[参考記事](https://kan-kikuchi.hatenablog.com/entry/UnmaskForUGUI)）
    * `Hierarchy`で右クリックで `Unmask > Iris Shot`で基本のマスクが作れる。
![image](https://user-images.githubusercontent.com/17778395/144635132-52c90dcf-abd7-4a82-bb52-bd71298e7248.png)
    * フォーカスされた領域にインプットを通すために `Screen` に `UnmaskRaycastFilter` をアタッチする必要がある。<img width="500" src="https://user-images.githubusercontent.com/17778395/144635700-57373452-2f09-422a-b669-a9a52fbfa186.png">
* `LevelSelect` でのコーチマークはマップのスクロール位置がデフォルト位置になっていることを想定としているので、キャンバススクロール情報をリセットするコマンドを `Tools > Debug Command > Reset Level Select Canvas` にて用意しました。動作確認する際ご利用ください。

* 理想としては、テキストを`CoachMark`に渡して吹き出しの大きさを動的に調整したいんですが、現状それが難しいので、`CoachMark.prefab` をシーンに置いて各シーンで吹き出しの大きさ及び `StringReference` を事前に設定することで運用して行きたいと思います。

### キャプチャ

OnBoardingからのコーチマーク
https://user-images.githubusercontent.com/17778395/144632234-c3ed33b7-aa72-423e-a08e-40f222f4d181.mov

| iPhone12 | iPhone8 |
| --- | --- |
| <img width="300" src="https://user-images.githubusercontent.com/17778395/144632357-c61a77fe-97db-4167-8322-372d9323249b.png"> | <img width="300" src="https://user-images.githubusercontent.com/17778395/144632544-1a949a7c-f4b6-4d01-a1a1-0fe878d2f5f9.png"> |

### 動作確認方法
確認する前に、あらかじめ`Tools > Debug Command > Reset On Boarding State`、 `Tools > Debug Command > Reset Level Select Canvas`を実行してください。
- [ ] OnBoardingポップアップのボタンを押した後、コーチマークが表示されることを確認。 
- [ ] フォーカスされてるオブジェクト以外、インプットが遮断されてることを確認。

### 参考 URL
[uGUIの画像(Image)の内側を切り抜いて(逆マスクで)表示【Unity】【uGUI】](https://kan-kikuchi.hatenablog.com/entry/UnmaskForUGUI)

2021-12-03 16:50 UTC, takesi0627 commented
@LITO-apps/engineer 
レビューよろしくお願いします。

2021-12-05 03:12 UTC, takesi0627 commented
📝`SOURCE.md` に追記すること

2021-12-05 16:08 UTC, takasusuke requested changes
見た目は完璧でした！

### imo
`SpeechBubble.png`の元素材を白色にして、`Image`componentで色をつける方が使いやすいと思います。いかがでしょうか。

2021-12-06 03:32 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/ScaleContent.cs
> +            _contentRect.localScale = new Vector3(scale, scale, 1.0f);
Unmaskの`Fit Target`機能を使ってみたらエラーが起きてしまって、調査してみたら、`Contents`の`scale.z`が`0.0`が原因でしたので修正を入れた。
結果的にいま`Fit Target`使ってないが、`z`値が`0.0`だと何かと不具合が起きそうなのでそのままにしました。

2021-12-06 10:09 UTC, xiii111 commented
@takasusuke 任せます

2021-12-07 13:56 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelSelectDirector.cs
> +        {
3c13fef

2021-12-07 13:57 UTC, takesi0627 commented
> ### imo
> `SpeechBubble.png`の元素材を白色にして、`Image`componentで色をつける方が使いやすいと思います。いかがでしょうか。

454e27e

2021-12-07 13:59 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelSelectDirector.cs
> +                _coachMark.InitializeByRectTransform(spring1.GetComponent<RectTransform>());
2e0bae6
`CoachMark.InitializeByRectTransform` で null check しました

2021-12-07 14:00 UTC, takesi0627 commented
@takasusuke 
再レビューお願いします

2021-12-07 14:46 UTC, takasusuke approved these changes
Great work!!

2021-12-07 15:14 UTC, merged