縁なしのステージアイコンの適用
LITO-apps/Treevel-client pull request #1297
Opened 2021-12-16 13:06 UTC by takasusuke

### 対象イシュー
Close #1172

### 概要
タイトルまま

### 詳細
- 記録画面に縁なしアイコンの適用
- OverviewPopupに縁なしアイコンの適用
- GamePlaySceneに縁なしアイコンの適用

#### 現実装になった経緯
特になし

#### 技術的な内容
特になし

### キャプチャ
変更前 | 変更後
記録画面

OverViewPopup

一時停止画面

失敗画面

成功画面

### 動作確認方法
- [ ] 記録画面の確認(ほぼ変化なし)
- [ ] Spring_1_1のOverviewPopupの確認
- [ ] Spring_1_1をプレイ。一時停止画面・成功画面・失敗画面の確認

### 参考 URL

2021-12-16 13:13 UTC, takasusuke commented
@LITO-apps/engineer 
お願いします。
20minくらいだと思います。

2021-12-16 15:36 UTC, takesi0627 requested changes

2021-12-16 15:36 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/GameDatas/TreeData.cs
> +        public AssetReferenceSprite stageEdgeIcon;
### `IMO`

`stageIconWithEdge`とかの方が文法的にいいような気がする

2021-12-16 15:36 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/GameDatas/TreeData.cs
> +        public AssetReferenceSprite stageEdgeIcon;
### `MUST`

`Tools > Reserialize Tree Data` を実行して全部の木データに新しいプロパティを反映させください

2021-12-17 00:48 UTC, xiii111 reviewed
基本的には良さそうです！

2021-12-17 00:48 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/GameDataManager.cs
>              await UniTask.WhenAll(backgroundTasks);
### Imo

他にも同様のところが沢山ありそうだけど、この辺は直列に await する必要なさそうだから、並列にした方が処理速度が上がる気がする

2021-12-17 00:48 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/GameDatas/TreeData.cs
> +        public AssetReferenceSprite stageEdgeIcon;
### Ask

見積もりの時に聞いた気がするけど、縁ありのアイコンはどういう時に使うんだったっけ？

2021-12-17 21:55 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/GameDataManager.cs
>              await UniTask.WhenAll(backgroundTasks);
9815eb5
https://aircocomputing.hatenablog.com/entry/2014/04/12/141645

2021-12-17 21:56 UTC, takasusuke commented on Assets/Project/Scripts/Common/Entities/GameDatas/TreeData.cs
> +        public AssetReferenceSprite stageEdgeIcon;
Rename
ad0bf8f

Re-serialize
46d75f1

2021-12-17 21:56 UTC, takasusuke commented on Assets/Project/Scripts/Common/Entities/GameDatas/TreeData.cs
> +        public AssetReferenceSprite stageEdgeIcon;
StageSelectSceneに置く、ユーザがタップできるアイコンは縁ありを使う。

2021-12-17 21:56 UTC, takasusuke commented
@LITO-apps/engineer 
再よろです。

2021-12-17 23:43 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/GameDataManager.cs
>              await UniTask.WhenAll(backgroundTasks);
へーー良いね！

2021-12-17 23:43 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/GameDatas/TreeData.cs
> +        public AssetReferenceSprite stageEdgeIcon;
あーーStageSelectScene のステージボタンね。おけおけ

2021-12-17 23:44 UTC, xiii111 approved these changes
オッケー！

2021-12-19 00:21 UTC, takesi0627 approved these changes

2021-12-19 00:21 UTC, merged