特定のステージ群のクリアを木のクリア条件とする
LITO-apps/Treevel-client pull request #1372
Opened 2022-01-04 02:50 UTC by takasusuke

### 対象イシュー
Close #1288

### 概要
タイトルまま

### 詳細
- 1個以上の特定のステージをTreeごとに設定し、それらのステージをクリアした時に木をクリアしたこととする
- (既存)Tree内の全てのステージをクリアした時、木を完全クリアしたこととする

#### 現実装になった経緯
issueコメントでの議論に基づく

#### 技術的な内容
特になし

### キャプチャ

https://user-images.githubusercontent.com/26213141/148003051-7e21e1aa-df33-46dc-b4ac-27a1f780310b.mov

### 動作確認方法
Tools > Debug command > Reset Stage Record を実行
Tools > Debug command > Reset Animation Stateを実行
- [ ] Spring_1の[7]と[8]をクリア。LevelSelectに戻る。Summer_1が解放されないことを確かめる。
- [ ] さらに、Spring_1の[10]をクリア。LevelSelectに戻る。Summer_1が解放される。

### 参考 URL

2022-01-04 02:53 UTC, takasusuke commented
@LITO-apps/engineer 
お願いします。
20minくらいだと思います。

TreeDataのconflictあっても嫌だったので、#1343 の実装からbranchを生やしています。

2022-01-04 03:01 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/ClearTreeHandler.cs
> +    public class ClearTreeHandler : IClearTreeHandler
当初は、クリア条件が木によって大きく異なる可能性を考えて`IClearTreeHandler`があったけど、当分、クリア条件は１種類しかなさそうだから今では不要。

前はクラス名が`NumClearTreeHandler`だった。
１種類しかないからクラス名も`ConstraintStageClearTreeHandler`とかにする必要ないかと思い、`ClearTreeHandler`にしました。

2022-01-04 14:57 UTC, takesi0627 requested changes
`MUST`

`Spring-1-10`をクリアした後に道の解放演出が再生されますが、
その後もう一回`LevelSelectScene`に戻ると、道の状態（色が変わらない）が未解のなままになっているので、
調査、対応をお願いします。

2022-01-04 14:57 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/ClearTreeHandler.cs
> +                throw new Exception($"constraintStageNumbers(={constraintStageNumbers}) must not be less than 1");
### `MUST`
新しい `EErrorType` を作りましょう

2022-01-04 14:57 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/ClearTreeHandler.cs
> +                throw new Exception($"constraintStageNumbers(={constraintStageNumbers}) must not be larger than the number of stages");
### `MUST`
新しい `EErrorType` を作りましょう

2022-01-04 14:57 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/StageRecordService.cs
> +                var constraintTreeClearStageNumers = Get(constraintTreeId).Where(stageRecord => stageRecord.IsCleared)
### `NITS`
```suggestion
                var constraintTreeClearStageNumbers = Get(constraintTreeId).Where(stageRecord => stageRecord.IsCleared)
```

2022-01-05 13:49 UTC, takasusuke commented on Assets/Project/Scripts/Common/Utils/StageRecordService.cs
> +                var constraintTreeClearStageNumers = Get(constraintTreeId).Where(stageRecord => stageRecord.IsCleared)
8ee4111

2022-01-05 13:59 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/ClearTreeHandler.cs
> +                throw new Exception($"constraintStageNumbers(={constraintStageNumbers}) must not be larger than the number of stages");
355340a

2022-01-05 13:59 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/ClearTreeHandler.cs
> +                throw new Exception($"constraintStageNumbers(={constraintStageNumbers}) must not be less than 1");
355340a

2022-01-05 14:31 UTC, takasusuke commented
> `MUST`
> 
> `Spring-1-10`をクリアした後に道の解放演出が再生されますが、 その後もう一回`LevelSelectScene`に戻ると、道の状態（色が変わらない）が未解のなままになっているので、 調査、対応をお願いします。

ec1ac3f
いつからかわからんけど、結構長い間このバグあったみたい。

2022-01-07 14:42 UTC, takesi0627 approved these changes
LGTM

2022-01-08 01:50 UTC, takasusuke commented
感謝〜

2022-01-08 01:50 UTC, merged