1度見たOnBoarding, Tutorialポップアップを眺める機能
LITO-apps/Treevel-client pull request #1373
Opened 2022-01-08 08:14 UTC by takasusuke

### 対象イシュー
Close 

### 概要
- ヒストリー画面（1度見たOnBoarding, Tutorialポップアップを眺める機能）の実装
- その他画面をフッターから、LevelSelect配下に移動
- EditorのScene viewでLevelSelectの道や木が表示されない不具合の改善

### 詳細
- 1度既読にしたOnBoardingやTutorialのポップアップを何度も眺めることのできる画面を用意。未読のTutorialについてはテキストを「？？？？」とし、ポップアップは表示されない。
- MenuSelectSceneのフッターがあるので、TutorialPopupを閉じるButtonは、本来のTutorialPopupのボタンの位置よりやや上に配置。

未実装
- OnBoardingのヒストリー機能
- ヒストリーアイコン
- ヒストリー背景
- ポップアップを閉じるボタンの文言を一律「閉じる」とかにする？

#### 現実装になった経緯
その他画面の背景はLevelSelectの背景を転用していたので、フッターの形式で並置するのは違和感があったから

#### 技術的な内容

### キャプチャ
その他画面の表示ボタンをフッターから独立

https://user-images.githubusercontent.com/26213141/148636958-5c9124f6-b056-48fb-a533-f0070021c331.mov

既に表示したポップアップのヒストリー機能（ポップアップ表示中に別ウィンドウを開いてヒストリーに戻ったときにポップアップは閉じてるべき？？）

https://user-images.githubusercontent.com/26213141/148636979-cba3fa27-0072-489a-8250-7a3fdec93229.mov

### 動作確認方法

### 参考 URL

2022-01-27 16:56 UTC, takasusuke commented
@LITO-apps/engineer 
よろしくお願いします。
ぱっと見の使用感から何でもコメントしてもらえると助かります。

議論点
- ポップアップを閉じるボタンの文言を一律「閉じる」とかにする？
- "History"という要素名かどうか
- OnBoardingとTutorialの列挙を分けるかどうか(分けた方がより良いのかもしれないが、OnBoardingとTutorialそれぞれユーザに表記する名称が必要になる。OnBoardingがもっと増えたときに別画面にするなどそれなりの方法を考えても良いのではないか)

迷い点
- 歯車アイコンはどうすれば良い感じになるか
- ポップアップのボタンと、フッターが微妙にかぶっている。本来のポップアップのボタンの位置より上にしたり、大きさを小さくして、フッターに被らない方が良い気もしてる（あくまでメインはポップアップの内容であり、それを閉じるボタンまでは再現しなくても良い？OnBoardingのボタンとかは、そこまで含めてOnBoardingとも思える）

対象外の点
- 「蜘蛛の巣」の「蜘」の字が表示されていませんが、フォントの問題なのでPRの対象外

2022-01-27 16:58 UTC, takasusuke commented
メモ
- もう１回自分でも実装内容見直して、動作確認内容を過不足なく記述する
- 説明を追加する

2022-01-29 16:21 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/UIs/OnBoardingPopup.cs
> +        protected AssetReferenceSprite image;
子クラスで使うために`protected`に変更

2022-01-29 16:21 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/TutorialPopupController.cs
> +        [SerializeField] protected Text displayName;
子クラスで使うために`protected`に変更

2022-01-30 02:15 UTC, takasusuke commented
- ヒストリーの文字を小さくする
- トルネード、などの文字を小さくする
- ポップアップのボタンはなしにして、どこをタップしても閉じれるようにする
- リストの下部分にはマスクをかけない
- 茶色をもう少し明るくする
- 文字は左揃え
- ポップアップ中はFooterを非表示にしする
- 各リストにアイコンを付けられるなら付ける

2022-02-02 12:24 UTC, xiii111 commented
@takasusuke レビューしようと思いましたが、通話での修正内容を入れてからの方が良さそうなので、一旦見るのやめます！レビューアサインを外し、InProgress に持っていきます

2022-02-04 15:47 UTC, takasusuke commented
@LITO-apps/engineer 
レビューに基づき見た目を修正しました

https://user-images.githubusercontent.com/26213141/152558674-7cbbfd6c-0323-4686-a410-68beb4ee2bac.mov

2022-02-05 01:24 UTC, xiii111 commented
見ますー

2022-02-05 02:23 UTC, xiii111 requested changes
素晴らしい機能ですーー！👏👏 割と念入りにレビューしました🙇‍♂️🙇‍♂️

コメントですが、文言に対する修正は一切しないようにします（他のところでやると思うので）

## Must

### Must1
以下のように、一番下までスクロールしても、一番下のコンテンツが全て表示されないのは良くないと思いました。直前の `Imo` である、スクロール領域は `Home` と同様に SafeArea 外にまで広げてほしい、をやっていただいた前提での解決策としては、以下があると思います
- `下の SafeArea の高さ` + `フッターアイコンの高さ` + `要素間のスペース` 分、スクロール領域の下に空白の領域を確保する

<img src="https://user-images.githubusercontent.com/26104258/152623832-fc04f377-56d8-4689-a57e-7b25f511ba07.png" width="300">

### Must2
ポップアップを表示するたびにインジケーターが表示される（画像がロードされる）のは体験的に良くないと思うので、修正したいです
https://user-images.githubusercontent.com/26104258/152625103-7c8c951d-445a-4a89-8d30-237ce1805f0b.mov

## Nits

### Nits1

> 各リストにアイコンを付けられるなら付ける

こちら、イシューを作っても良いかなと思いました！少なくとも、各チュートリアルポップアップにおいては、一つの画像（or Gif）があるはずなので、実装自体はできそうです！

### Nits2
`ヒストリー` というタイトル領域の下端に細めの境界線を設けたほうが良いと思います。現状では、タイトル領域と、スクロールコンテンツが同じレイヤーに見えてしまいますが、スクロールコンテンツはタイトル領域の下に消えていくので、違和感を持ちます

### Nits3
`ヒストリー` というタイトルが、画面上に近すぎると思います。余白を設けてください

## Imo

### Imo1
以前の通話での伝え方が悪かった気がしますが、スクロール領域は `Home` と同様に SafeArea 外にまで広げてほしいです（SafeArea 外はスクロール操作できないですが、コンテンツが見えるようになると思います）。現状は、ユーザーにとってよく分からない空間にコンテンツが消えていくように見えると思います。実際、iOS の標準アプリでも、スクロール領域は SafeArea 外まで広がっています

<img src="https://user-images.githubusercontent.com/26104258/152623976-22cbaa42-3d57-4dab-8ef0-91f79c895a4b.jpeg" width="300">

### Imo2
やはりオンボーディングとチュートリアルが混ざっていると、粒度が荒いかなと思いました。また、現状は色だけから違いを示していますが、セクションを分けたりなどの工夫をしないと、これらの色の違いは何か、をユーザが理解できない気がします

### Imo3
`????` をタップした際には、チュートリアルを閉じる時と同じ SE を設定しても良いと思いました。まだ選択ができないことが伝わると思います。もしくは、SE を設定せず、`????` の場合には、タップ時のボタンの揺れを無くしたほうが良いと思います

### Imo4
`ScrollRect` の `MovementType` は、[`Elastic`](https://docs.unity3d.com/ja/2018.4/ScriptReference/UI.ScrollRect.MovementType.Elastic.html) のほうがユーザーは使い慣れていると思いました

2022-02-05 02:23 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/Settings/ToDefaultController.cs
> +namespace TTreevel.Modules.MenuSelectScene.LevelSelect.Settings
### Nits

```suggestion
namespace Treevel.Modules.MenuSelectScene.LevelSelect.Settings
```

2022-02-05 02:23 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelSelectDirector.cs
> +            _otherToggle.OnValueChangedAsObservable().Subscribe(_ => _othersObject.SetActive(!_othersObject.activeSelf)).AddTo(this);
### Ask

引数を利用せずに、ただ `_othersObject` の Active を反転したいだけなら、`Toggle` ではなく `Button` でも良いですか？

2022-02-05 02:23 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/TutorialButton.cs
> +            if (type.IsChecked()) {
### Imo

こうやって読むと `IsChecked` は読みづらいですね。`IsShown` などにリネームしておきませんか？（`OnBoardingButton.cs` でも同様）

2022-02-05 02:23 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/TutorialButton.cs
> +        public void Initialize(ETutorialType type, GameObject tutorialPopup)
### Nits

`type` という名前だと読みづらいので、`tutorial` にしませんか？内部的には `type` なのは承知しています（`OnBoardingButton.cs` でも同様）

2022-02-05 02:23 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryOnBoardingPopupController.cs
> +            if (image.IsValid()) image.ReleaseAsset();
### Ask

これをやらないとどうなりますか？

2022-02-05 02:23 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryOnBoardingPopupController.cs
> +    public class HistoryOnBoardingPopupController : OnBoardingPopup
### Nits
以下のようにリネームしておいたほうが良いかもしれないです

```suggestion
    public class HistoryOnBoardingPopupController : OnBoardingPopupController
```

2022-02-05 02:23 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryDirector.cs
> +                var button = Instantiate (_onBoardingButtonPrefab, _content.transform);
### Nits
```suggestion
                var button = Instantiate(_onBoardingButtonPrefab, _content.transform);
```

2022-02-05 02:23 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryDirector.cs
> +                var button = Instantiate (_tutorialButtonPrefab, _content.transform);
### Nits

```suggestion
                var button = Instantiate(_tutorialButtonPrefab, _content.transform);
```

2022-02-05 04:32 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/Settings/ToDefaultController.cs
> +namespace TTreevel.Modules.MenuSelectScene.LevelSelect.Settings
[cd4eca4](https://github.com/LITO-apps/Treevel-client/pull/1373/commits/cd4eca433f2954c3cc79796f20ba091cb529608a)

2022-02-05 04:32 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryDirector.cs
> +                var button = Instantiate (_tutorialButtonPrefab, _content.transform);
[c1d1890](https://github.com/LITO-apps/Treevel-client/pull/1373/commits/c1d1890b5d8989250a6f1b23d7d0deea88b08d50)

2022-02-05 04:33 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryDirector.cs
> +                var button = Instantiate (_onBoardingButtonPrefab, _content.transform);
[c1d1890](https://github.com/LITO-apps/Treevel-client/pull/1373/commits/c1d1890b5d8989250a6f1b23d7d0deea88b08d50)

2022-02-05 04:34 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/TutorialButton.cs
> +            if (type.IsChecked()) {
表示したかどうかではなく、表示して「次へ」などのボタンを押したタイミングでフラグが変わるから、微妙に異なる気はする

2022-02-05 04:44 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryOnBoardingPopupController.cs
> +    public class HistoryOnBoardingPopupController : OnBoardingPopup
[ca2d4e1](https://github.com/LITO-apps/Treevel-client/pull/1373/commits/ca2d4e1e3019e604132e523378fc09fd196fab2a)

2022-02-05 04:54 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelSelectDirector.cs
> +            _otherToggle.OnValueChangedAsObservable().Subscribe(_ => _othersObject.SetActive(!_othersObject.activeSelf)).AddTo(this);
Buttonで良いので、Buttonに変更。
[babd357](https://github.com/LITO-apps/Treevel-client/pull/1373/commits/babd35751354cf195a4d3d82c7d9397989f5c577)

2022-02-05 04:57 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/TutorialButton.cs
> +        public void Initialize(ETutorialType type, GameObject tutorialPopup)
[030ddfb](https://github.com/LITO-apps/Treevel-client/pull/1373/commits/030ddfb0a6c93ba7233944c8f2e2f935efdb7e2f)

2022-02-05 05:43 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryOnBoardingPopupController.cs
> +    public class HistoryOnBoardingPopupController : OnBoardingPopup
リネームミスの修正
[9689f2c](https://github.com/LITO-apps/Treevel-client/pull/1373/commits/9689f2c38d9c7c818559ffa5c15c49b0248255a1)

2022-02-05 05:44 UTC, takasusuke commented
- [ ] ヒストリーtextの位置、スクロールの大きさ、位置の調整
[682f595](https://github.com/LITO-apps/Treevel-client/pull/1373/commits/682f595d1aadf92fc48b12b932da5b98f0ca859f)
- [ ] 画像ロード
- [ ] ????リストの挙動
- [ ]

2022-02-05 05:55 UTC, takasusuke commented
> ### Nits1
> > 各リストにアイコンを付けられるなら付ける
> 
> こちら、イシューを作っても良いかなと思いました！少なくとも、各チュートリアルポップアップにおいては、一つの画像（or Gif）があるはずなので、実装自体はできそうです！

チュートリアルでは薄黄色の背景に大きくアイコンが表示されるのに対し、ヒストリーでは小さく、かつ、背景色が異なるので、見せ方は一考しないといけないと思っている。
とりあえずアイデアには書いておいた。


> ### Imo2
> やはりオンボーディングとチュートリアルが混ざっていると、粒度が荒いかなと思いました。また、現状は色だけから違いを示していますが、セクションを分けたりなどの工夫をしないと、これらの色の違いは何か、をユーザが理解できない気がします

OnBoardingとTurtorialを分けるとすると、それぞれユーザに表示する文言(ラベル)が必要。
OnBoardingの方が難しい。
色を分けることもしなくて良いかなと思い始めてる。

2022-02-05 06:38 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryOnBoardingPopupController.cs
> +            if (image.IsValid()) image.ReleaseAsset();
解放しないと、次に押したときに、読み込んだAssetをまた読み込もうとしてエラーになる。

2022-02-05 06:41 UTC, takasusuke commented
@xiii111 
修正しました。よろしくお願いします。

2022-02-05 06:48 UTC, xiii111 commented
@takasusuke 次から ReRequest もらえると助かる！

2022-02-05 06:50 UTC, takasusuke commented
> @takasusuke 次から ReRequest もらえると助かる！

@xiii111 
メールを飛ばしたいってこと？

2022-02-05 06:51 UTC, xiii111 commented
@takasusuke レビュー状態になっていると、コメントを見落とした時にもわかるし、いろいろと便利かなー

2022-02-05 06:55 UTC, takasusuke commented
> レビュー状態になっていると、コメントを見落とした時にもわかるし、いろいろと便利かなー（Pending review にも入って、dev チャンネルにも書き込まれるし）

Pending reviewはそれで判断してるのね

2022-02-05 06:57 UTC, xiii111 commented
違かったらすまん、まぁレビュー依頼ということで、その機能で通知をもらえた方が自分的に分かりやすいってだけかも

2022-02-05 23:45 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/TutorialButton.cs
> +            if (type.IsChecked()) {
なるほど、`Check` という名前が少しソフトウェア的な検証とかに `Validate` みたいな雰囲気に読めてしまうのが、気になっているのかも。`HasCompleted` とかはどう？

2022-02-05 23:48 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryOnBoardingPopupController.cs
> +            if (image.IsValid()) image.ReleaseAsset();
次に読み込むときに、すでに読み込んだ Asset は読み込まないようにはできますか？淡い記憶ですが、`OverviewPopup` では、最初の1回目の読み込み以外は画像ロードされず、インジケーターなども見えなかったと思います

2022-02-05 23:57 UTC, xiii111 requested changes
いやー素晴らしい修正です！後少しだけ、お願いします

- [ ] https://github.com/LITO-apps/Treevel-client/pull/1373#discussion_r800108996
- [ ] https://github.com/LITO-apps/Treevel-client/pull/1373#discussion_r800109160
- [ ] https://github.com/LITO-apps/Treevel-client/pull/1373#discussion_r800109160 に関連して `Must2`。`OverviewPopup` のように、2回目以降はロードされないようにできたらしたい
- [ ] `Nits2` の境界線ですが、やや太すぎる気がします。もう少し細めで表現できませんか？

2022-02-06 00:51 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryOnBoardingPopupController.cs
> +            if (image.IsValid()) image.ReleaseAsset();
ロードして参照しているリソース、解放した方がいい気がするけどどうなんだろ。
参照をなくす、ということがイコールすぐにメモリからなくなる、ということなんかな。
Scene消えても参照は消えずに、同じリソースをロードするほど参照が残っちゃうみたいだし、どのタイミングでリソース解放するのが良いんだ。

参考：https://shikaku-sh.hatenablog.com/entry/unity-addressables-and-asset-bundle-and-resources

2022-02-06 01:00 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryOnBoardingPopupController.cs
> +            if (image.IsValid()) image.ReleaseAsset();
使わなくなったタイミングで解放した方がいいです。
できるだけ解放のタイミングは自分で制御するのが理想

2022-02-06 01:23 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryOnBoardingPopupController.cs
> +            if (image.IsValid()) image.ReleaseAsset();
画像のインジケーターを表示する方針に戻してください

2022-02-07 16:21 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryOnBoardingPopupController.cs
> +            if (image.IsValid()) image.ReleaseAsset();
現状 `OnBoarding`も`Tutorial`もポップアップを閉じるたびにアセットをリリースしているので、
History画面で開けて閉じるを繰り返すケースを考慮するとリソースがもったいないです。

アセットのリリースは`HistoryDirector`で管理するのがいいかもしれません。
そもそもロードもHistoryDirectorでやっちゃてもいい気がします。
`OnEnable -> LoadIcons`
`OnDisable -> ReleaseIcons`みたいな
その場合、チュートリアルのアイコンとオンボーディングの画像にラベルをつけて管理すると実装が楽だと思います

2022-02-07 16:22 UTC, takesi0627 commented
AASの件（https://github.com/LITO-apps/Treevel-client/pull/1373#discussion_r800109160）以外は @xiii111 に任せました

2022-02-08 12:41 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/TutorialButton.cs
> +            if (type.IsChecked()) {
[77e3042](https://github.com/LITO-apps/Treevel-client/pull/1373/commits/77e3042e8ab0dab31dd6a7a7da115c58d79b4aa9)

2022-02-08 12:44 UTC, takasusuke commented
[3caccb7](https://github.com/LITO-apps/Treevel-client/pull/1373/commits/3caccb74383de677d0d0625cfb7b47565ca8a53f)

| 前 | 後 |
| --- | --- |
| <img width="279" alt="スクリーンショット 2022-02-08 21 43 49" src="https://user-images.githubusercontent.com/26213141/152989553-f694c4a4-c3f2-49b4-ae33-236805d103ce.png"> | <img width="279" alt="スクリーンショット 2022-02-08 21 43 31" src="https://user-images.githubusercontent.com/26213141/152989592-be0e93f0-8e04-4e5c-896c-63ba6f541867.png"> |

2022-02-08 13:11 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryOnBoardingPopupController.cs
> +            if (image.IsValid()) image.ReleaseAsset();
[cbb9af6](https://github.com/LITO-apps/Treevel-client/pull/1373/commits/cbb9af6ca770fbee542627d6db7b7cf7974ce381)

一旦、インジケータの表示に戻した

2022-02-08 13:14 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryOnBoardingPopupController.cs
> +            if (image.IsValid()) image.ReleaseAsset();
HistoryDirectorのOnEnable/OnDIsableで管理すると、History画面のON/OFFを繰り返すとコストが無駄になるし、
HistoryDirectorのAwake/Destroyで管理すると、MenuSelectSceneのON/OFFを繰り返すとコストが無駄になるので、
どのユースケースを最も考慮するのかじゃないかな。

どれもON/OFFを繰り返すユースケースが通常利用では想定されないので、特に決め手はない気がする。

2022-02-08 13:15 UTC, takasusuke commented
@xiii111 @takesi0627 
再修正、コメントしました

2022-02-08 14:50 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryOnBoardingPopupController.cs
> +            if (image.IsValid()) image.ReleaseAsset();
そうしたら、
ロード：ヒストリー画面に入るタイミング （ `HistoryDirector.OnEnable` ?）
リリース：MenuSelectSceneを離れるタイミング（ `HistoryDirector.Destroy` ? ）

がいいのではないでしょうか

2022-02-09 14:48 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryOnBoardingPopupController.cs
> +            if (image.IsValid()) image.ReleaseAsset();
[24177ea](https://github.com/LITO-apps/Treevel-client/pull/1373/commits/24177ea9020730a614e94443f980597b5a3bc905)

こんなんでどうだろうか。
`HistoryDirector`の`Awake()`の後の`OnEnable()`でロードしたいので、ロードタイミングは`HistoryDirector`が管理。
解放するタイミングは各GameObject。

2022-02-09 15:34 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryOnBoardingPopupController.cs
> +            if (image.IsValid()) image.ReleaseAsset();
* ボタンがアセット管理するのはどうかと思いました
* `AssetReference.IsValid()`でアセットがロードされているかどうかをチェックできるからそれを利用してほしい

自分もそんなに深く考えてなくてコメントしてしまいましたが、
よく考えたら課題としては「ポップアップが表示される度にロードインジケーターが発生すること」なので
`HistoryTutorialPopup.OnDisable`で`Release`するのをやめてそれを`OnDestroy`にすれば良いのではないでしょうか
と今思いました。

ちょっと修正量が多いのと、自分が伝えたいことちゃんと伝えたかわからないので
ローカルで修正したものをコミットしてもいいですか？

2022-02-09 15:38 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryOnBoardingPopupController.cs
> +            if (image.IsValid()) image.ReleaseAsset();
yes

2022-02-09 15:40 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryOnBoardingPopupController.cs
> +            if (image.IsValid()) image.ReleaseAsset();
ありがとうございます。
[95f6fd5](https://github.com/LITO-apps/Treevel-client/pull/1373/commits/95f6fd5e3bb3c512b90b31d857e1d4236088226e)
こんな感じです。いかがでしょうか

2022-02-09 15:49 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryOnBoardingPopupController.cs
> +            if (image.IsValid()) image.ReleaseAsset();
そうか、チュートリアルポップアップは共通で使ってるんでしたね。その通りです

2022-02-09 15:57 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryOnBoardingPopupController.cs
> +            if (image.IsValid()) image.ReleaseAsset();
これはどうでしょうか
```csharp
class HistoryDirector
        private List<AssetReference> _assetReferences = new ();
        private void OnDestroy()
        {
            foreach (var assetReference in _assetReferences)
            {
                if (assetReference.IsValid()) {
                    assetReference.ReleaseAsset();
                }
            }
        }
```

_assetReferencesはtutorialをInitializeするところから集める。
ロードした分だけ最後リリースする

2022-02-10 10:44 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryOnBoardingPopupController.cs
> +            if (image.IsValid()) image.ReleaseAsset();
@takasusuke @takesi0627 こちら、お二人にお任せします

2022-02-10 11:09 UTC, xiii111 commented
@takasusuke 境界線ですが、私の想定と違いましたので、勝手ながらコミット abd54b0 させていただきました（本当は pr を作るのが良いんだけど、軽微だったので ...）。個人的な課題感は以下です
- 境界線がやけに目立つ（太かったり、色が明るかったりの理由で）
- 明確に境目がわかる必要はなく、無意識的に境界を感じられれば良い

| 前 | 後 |
| --- | --- |
| <img width="279" alt="スクリーンショット 2022-02-08 21 43 31" src="https://user-images.githubusercontent.com/26213141/152989592-be0e93f0-8e04-4e5c-896c-63ba6f541867.png"> | ![スクリーンショット 2022-02-10 20 03 43](https://user-images.githubusercontent.com/26104258/153394335-ae457f20-5eab-4c8c-881f-4a3d0d230b7b.png) |

後ですが、`Travel to save tree` のセルの上方向の offset がやや狭く感じたので、セルとセルの間の offset と同じ分、offset を設けて欲しいです

2022-02-10 11:10 UTC, xiii111 commented
上記以外は問題ないです！

2022-02-10 11:45 UTC, takasusuke commented
OptionボタンはSafeArea内

2022-02-11 03:05 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryOnBoardingPopupController.cs
> +            if (image.IsValid()) image.ReleaseAsset();
@takesi0627 
修正しました
[da1875a](https://github.com/LITO-apps/Treevel-client/pull/1373/commits/da1875abf67205e249aa8650f7747577115f4070)

2022-02-11 03:08 UTC, takasusuke commented
@xiii111 
- Optionの位置修正
[1a040f4](https://github.com/LITO-apps/Treevel-client/pull/1373/commits/1a040f4db8256284a0ac921088723504ff9f3f63)
- History画面の一番上のボタンのMargin
[bd04b93](https://github.com/LITO-apps/Treevel-client/pull/1373/commits/bd04b93824529b5ac7a94c9f7e62f8b0dd0c1442)

https://user-images.githubusercontent.com/26213141/153531822-22282f1e-d4ae-4a46-931b-c5479bb04111.mov

2022-02-11 03:12 UTC, xiii111 approved these changes
最高です！！！！！

2022-02-11 06:28 UTC, takesi0627 approved these changes
[da1875a](https://github.com/LITO-apps/Treevel-client/pull/1373/commits/da1875abf67205e249aa8650f7747577115f4070)

について問題はなさそうですが `IMO` として一点コメント。

### `IIMO`
この実装では 
`HistoryDirector <-> HistoryTutorialPopupController`
という相互依存し合う関係になっているが、DDDの観点？だと好ましくないと思いました。
できれば
 `HistorDirector -> HistoryTutorialPopupController` 
の一方通行になってほしい。
`TutorialType` から `TutorialData` 取る時のパフォーマンスを考慮している上今の実装にしてくれているとは思いますが、現状のチュートリアルの量的には多少依存関係の方を重みおいてもいいと思いました

2022-02-11 06:41 UTC, xiii111 commented
上記の依存関係の調整、気になるので、私もやるかもしれません！

2022-02-11 08:12 UTC, takasusuke commented
なるほど。問題意識は理解しました。
また考えてみます。

レビュー色々ありがとうございました。

2022-02-11 08:12 UTC, merged

2022-02-11 08:28 UTC, xiii111 commented
あ、、、、

2022-02-11 08:28 UTC, xiii111 commented
修正したのですが

2022-02-11 08:32 UTC, xiii111 commented
@takasusuke @takesi0627 とりあえず、#1422 出しておいた！