[Phase2] DarkAttribute のデザイン適用 - アニメーションを出し分ける
LITO-apps/Treevel-client pull request #1379
Opened 2022-01-13 13:07 UTC by xiii111

### 対象イシュー
ref: #1192

### 概要
- #1192 の手順 2 を実施
- ユーザがボトルをホールドした時と、ボトルがゴールに移動した時で、アニメーションを出し分ける

### キャプチャ

https://user-images.githubusercontent.com/26104258/149335680-a887c0d0-ccbb-488e-9177-63d76f50afe4.mov

### 動作確認方法
- [ ] ユーザがボトルをホールドした時は、内側から暗闇が晴れるアニメーションを行う
- [ ] ユーザがボトルをホールドし終えた時は、外側から暗闇が現れるアニメーションを行う
- [ ] ボトルがゴールに移動した時は、外側から暗闇が晴れるアニメーションを行う
- [ ] ボトルがゴール以外に移動した時は、内側から暗闇が現れるアニメーションを行う

2022-01-13 13:21 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> +                .WithLatestFrom(_bottleController.isSuccess, (_, isSuccess) => isSuccess)
rx を利用していたら、極力 `_isSuccess ` などの状態は持たないように工夫する

2022-01-13 13:21 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> +                .Where(isSuccess => isSuccess && _isDark)
極力 `Subscribe` 内では `if 文` を利用せず、オペレーターで対処する

2022-01-13 13:21 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> +                .WithLatestFrom(_bottleController.isSuccess, (_, isSuccess) => isSuccess)
ここまでを Hot な Observable で宣言して、直前のストリーム処理と共通化をすることもできたが、恩恵が少ないのでやめておいた

2022-01-13 13:21 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> +                .Where(_ => _isDark)
`_isDark` を見て、必要十分なタイミングでのみ `SetTrigger` をしないと、余分な Trigger のフラグが立ってしまい、おかしな遷移を起こしてしまう

2022-01-13 13:21 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> +                    _isDark = false;
割とこの変更は苦肉の策。そこまで読みづらいわけではなかったので、許容した

2022-01-13 13:21 UTC, xiii111 commented
📝 
- ed6dde7 : アニメーションが二種類になるので、わかりやすいように既存のものは 1 をつけて命名するようにした
- 346c38d : 内側から暗闇が現れるアニメーションのための画像を追加した
- fd13e3b : https://lito-apps.slack.com/archives/C01E5GTPRV3/p1642051227014100
- e5198a7 : rx 周りのリファクタリングを行い、修正をしやすくした
- a731b6e : `IsDark` という Animator の Parameter では、アニメーションの出し分けをしづらかったので、既存の挙動を変えずに Trigger で制御するようにした
- 2e5a052 : Animation ファイルに、新しい画像を適用した
- 649a5c0 : おまじない
- f8eb48e : 新しい画像を用いた Animation ファイルを利用するようにした

2022-01-14 00:52 UTC, takesi0627 requested changes
### `MUST`
何回か長押し連打すると、放置しても晴れる状態になる
（遷移図でちょっと確認したが、おそらく `DarkOut1` と `DarkIn1` 同時に２回触発されてるとそうなる模様）
![image](https://user-images.githubusercontent.com/17778395/149432073-88260819-2bc2-4367-9edb-d55eb5e52ef1.png)


### `ASK`
長押ししながらゴールにフリックする場合、
ゴールタイルに乗ったままで一回闇に飲まれてから晴れることになりますが、
これは想定挙動でいいですか？

https://user-images.githubusercontent.com/17778395/149432270-79237179-f092-4351-930d-bf8ba7b8768e.mov

2022-01-14 00:52 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> +                    _isDark = false;
### `IMO`

`_isDark` は自分で制御するより、今ステートが`Dark@dark`かどうかで判断した方がいいと思いました
```
_isDark = animator.GetCurrentAnimatorStateInfo(0).shortNameHash == Animator.StringToHash("Dark@dark")
```

2022-01-15 01:52 UTC, xiii111 commented
📝 一旦作業中に戻します

@takasusuke `WithLatestFrom` の書き方は覚えておくとよさそうなので、見てみてください！

2022-01-15 09:19 UTC, xiii111 commented
以下の変更を加えました（まだ修正は続きます）
- 0a7e5a3 : `DarkAttribute` の検証がしやすいように `isDark` なボトルを増やし、fps が落ちるのを防ぐために、Tornado の頻度を下げた
- 05c67c0 : `isDark` プロパティを保持しないようにした
- 10d27b0 : コードを読みやすいように整理した
- e1b2442 : `EndMove` を利用する必要はなく、すべて `isSuccess` で賄えたので、その修正をした

2022-01-15 09:21 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> +                    _isDark = false;
@takesi0627 05c67c0 をコミットしました！

```
animator.GetCurrentAnimatorStateInfo(0).shortNameHash == Animator.StringToHash("Dark@dark")
```

でダメだった理由は、アニメーション中の `== Animator.StringToHash("Dark@in1")` などの時にイベントが起きても正しくハンドリングできるようにです。`!=` を使うと `Dark@Opening` なども含まれてしまうので、正確ではないですが、分岐を多くするが嫌だったので、このようにしました

2022-01-15 09:29 UTC, xiii111 commented
@takesi0627

> ASK
長押ししながらゴールにフリックする場合、
ゴールタイルに乗ったままで一回闇に飲まれてから晴れることになりますが、
これは想定挙動でいいですか？

よくはなかったので、修正しようと思いましたが、意図せず e1b2442 で治りました！

2022-01-15 09:29 UTC, xiii111 commented
残課題
- [ ] https://github.com/LITO-apps/Treevel-client/pull/1379#pullrequestreview-852383984 の `MUST`
- [ ] CI が落ちている問題

2022-01-16 00:35 UTC, xiii111 commented
@takasusuke 

> 非成功状態でホールドしてDark@initになっている状態で

`Dark@idle` ですか？

2022-01-16 00:49 UTC, xiii111 commented
@takasusuke 

> IsSuccessを同じ値に更新する時にも通知するようにすると、BoardManager.UpdateNumOfSuccessBottles(bool isSuccess)で多分不具合が出る

これに加えて、ボトルがタイルを離れた時（移動中？）も `isSuccess = false` としているので、このイベントを受け取りトリガーされ、来たる状態になった時にトリガーが解放され、変な状態遷移をしてしまいますね

2022-01-18 06:40 UTC, xiii111 commented
@takasusuke 

> 非成功状態でホールドしてDark@initになっている状態でフリックして、非成功タイルに移動させると、Dark@darkに戻ってくる遷移がTriggerしないのでは。

これ調査したんですが、`isSuccess` のせいではなく、`releaseGesture` が発火していないですね。`releaseGesture` が潰されて、フリックにイベントが奪われている気がしますね

2022-01-18 12:16 UTC, xiii111 commented
これが原因そう

```
/// <summary>
/// アタッチされているTouchScriptイベントの状態を変更する
/// </summary>
/// <param name="isEnable"></param>
private void SetGesturesEnabled(bool isEnable)
{
    _flickGesture.enabled = isEnable;
    pressGesture.enabled = isEnable;
    releaseGesture.enabled = isEnable;
}
```

2022-01-18 12:29 UTC, xiii111 commented
830b4aa でフリック中に無効にするジェスチャーはフリックだけにした。実際、この修正が問題かどうか考えたけど、むしろ正しい仕様かもしれない

2022-01-18 12:37 UTC, xiii111 commented
@takesi0627 

> MUST
何回か長押し連打すると、放置しても晴れる状態になる
（遷移図でちょっと確認したが、おそらく DarkOut1 と DarkIn1 同時に２回触発されてるとそうなる模様）

これですが、`DarkOut1 と DarkIn1 同時に２回触発されてるとそうなる模様` この部分をもう少しちゃんと教えてもらえませんか？そもそも再現があまりしないので、なかなか原因がわからず ...

2022-01-18 13:48 UTC, takesi0627 commented
> @takesi0627
> 
> > MUST
> > 何回か長押し連打すると、放置しても晴れる状態になる
> > （遷移図でちょっと確認したが、おそらく DarkOut1 と DarkIn1 同時に２回触発されてるとそうなる模様）
> 
> これですが、`DarkOut1 と DarkIn1 同時に２回触発されてるとそうなる模様` この部分をもう少しちゃんと教えてもらえませんか？そもそも再現があまりしないので、なかなか原因がわからず ...

具体的の手順僕もうまく説明できないんですが、
再現したやつを動画にしたから参考にできればと思います

https://user-images.githubusercontent.com/17778395/149949295-de309e4a-0000-4114-a7c7-3c6818e1ba69.mp4

2022-01-20 04:33 UTC, xiii111 commented
@takasusuke @takesi0627 こちら修正に時間がかかっておりますので、以下に残課題などを共有します。お力を貸してもらえたら助かります

## 元々あった問題
1. 何回か長押し連打すると、放置しても晴れる状態になる https://github.com/LITO-apps/Treevel-client/pull/1379#pullrequestreview-852383984
2. 非成功状態でホールドして、非成功タイルに移動させると、晴れる状態になる https://github.com/LITO-apps/Treevel-client/pull/1379#commitcomment-63951395

## 修正
- 830b4aa : ボトルが移動中に OnRelease ジェスチャーが無効になっていたので、有効にした。これにより、2 が修正された
- c5315f1 : `idle` 状態から `IN1` と `IN2` が同時に発火した場合、片方のトリガーだけが処理されて、もう片方のトリガーは残存してしまう。これにより、`idle` → `dark` → `idle` と遷移した際に、何もトリガーされていないのに `idle` → `dark` の移動がされてしまうので、一度遷移が終わったら、トリガー状態をリセットするようにした
- 7d87246 : 以下の動画のように、`IN1` と `IN2` がほぼ同時にトリガーされる状況では、`IN1` が先に発火していた。なので、わずかに delay させることで、`IN2` が優先して発火するようにした。この問題は `OnRelease` がフリック後にも呼ばれることとが原因である

https://user-images.githubusercontent.com/26104258/150273184-c5d9364b-b80d-483f-add6-a95681521035.mov

## 残っている問題
1. 何回か長押し連打すると、放置しても晴れる状態になる https://github.com/LITO-apps/Treevel-client/pull/1379#pullrequestreview-852383984
2. 失敗状態から成功状態に移動した際に、稀に暗闇状態になる問題を新たに発見した

https://user-images.githubusercontent.com/26104258/150273600-1d220169-bd6a-45a9-9b7d-26d69cb9bf5d.mov

2022-01-21 11:37 UTC, xiii111 commented
@takasusuke @takesi0627 現状までで再レビューもらえますか？また、残っている問題に関する知見があればお願いします！（私としても、まだ調査できることはあるので、こちらは任意で大丈夫です！）

2022-01-21 12:14 UTC, xiii111 commented
📝 `Dark@out1` → `Dark@idle` / `Dark@out2` → `Dark@idle` / `Dark@in1` → `Dark@dark` / `Dark@in1` → `Dark@dark` は Has Exit Time が On で Exit Time が 1 だった。全て Condition がない遷移なので、Has Exit Time を Off にしてしまうと、遷移自体がしなくなってしまうし、Has Exit Time を On のまま、Exit Time を 0 にしてみたが、既存の 2 つの問題は両方とも再現できた

2022-01-22 06:29 UTC, takasusuke commented
> ## 残っている問題
> 1. 何回か長押し連打すると、放置しても晴れる状態になる [[Phase2] DarkAttribute のデザイン適用 - アニメーションを出し分ける #1379 (review)](https://github.com/LITO-apps/Treevel-client/pull/1379#pullrequestreview-852383984)
> 2. 失敗状態から成功状態に移動した際に、稀に暗闇状態になる問題を新たに発見した

1. は非成功タイルでホールド(A)した状態で、リリース(A)直後に再度ホールド(B)、リリース(B)すると高確率で起こせる。
ホールド(B)で、Dark@out1へのトリガーが入る。
リリース(B)のタイミングがDark@in1のタイミングの場合、Dark@out1へのトリガーは既に入っているから入らないので、Dark@out1だけが起動して非成功状態でも晴れる。
リリース(B)のタイミングがDark@darkのタイミングの場合、relaeseGestrueの
```
.Where(_ => animator.GetCurrentAnimatorStateInfo(0).shortNameHash != _ANIMATOR_DARK_STATE)
```
の条件に引っかかり、Dark@out1へのトリガーが入らないので、Dark@out1だけが起動して同じように非成功状態でも晴れる。                

Dark@in1の最中は、ホールドしてもDark@out1へのトリガーが入らない仕様でも良いと思います。

2022-01-22 06:52 UTC, takasusuke commented
> 2. 失敗状態から成功状態に移動した際に、稀に暗闇状態になる問題を新たに発見した
ホールドして、darkが晴れるアニメーションの終わりくらいに、成功状態に移動させると起きる気がする

成功状態になったときに、Dark@idleにいるので、out2が発火してない。（+もうBottle的には成功状態になっている？からreleaseGeatureでDarkになることもないっぽい）

2022-01-22 06:55 UTC, takasusuke commented
諸々の挙動を見るとTriggerよりBoolの方が楽そう。

あと、成功から成功への挙動も確認したいので、同色タイルを追加してもらいたいです。

2022-01-22 23:27 UTC, xiii111 commented
@takasusuke 調査ありがとうございます！コメントを読んで、継続して作業を続けます！

2022-01-22 23:30 UTC, xiii111 commented
@takasusuke 

> 諸々の挙動を見るとTriggerよりBoolの方が楽そう。

ね、これでも十分色々検討はしたけど、それでも漏れが出ている。複雑すぎるという点で、変えた方が良いかもしれない。とはいえ、直感的にわかりやすい遷移にできないかなと思い、やめていた。少し検討してみる

> あと、成功から成功への挙動も確認したいので、同色タイルを追加してもらいたいです。

追加します！

2022-01-22 23:35 UTC, takesi0627 commented
修正後また見ます

2022-01-22 23:37 UTC, xiii111 commented
@takesi0627 

> 修正後また見ます

Trigger → Bool の修正を待つということですか？

2022-01-22 23:38 UTC, xiii111 commented
成功状態 → 成功状態です

https://user-images.githubusercontent.com/26104258/150658945-88881a33-6341-41b2-8a5c-345aad1fad14.mov

2022-01-22 23:38 UTC, takesi0627 commented
> @takesi0627
> 
> > 修正後また見ます
> 
> Trigger → Bool の修正を待つということですか？

はい

2022-01-22 23:40 UTC, xiii111 commented
@takasusuke @takesi0627 

わかりました。ちなみに Bool にするという話ですが、どのような遷移で現状の遷移を再現するということになりますか？`isDark` という一つの状態では、Out1 と Out2 は振り分けられない気がするのですが、上手いテクニックがあったら教えてほしいです

2022-01-22 23:41 UTC, xiii111 commented
とりあえず、遷移図を書き直してみます

2022-01-23 00:08 UTC, xiii111 commented
> in, outアニメーション中は全てホールドしてもトリガーが入らなくても○？

ok だったわ。挙動としても自然

2022-01-23 00:20 UTC, xiii111 commented
> ホールドして、darkが晴れるアニメーションの終わりくらいに、成功状態に移動させると起きる気がする
> 
> 成功状態になったときに、Dark@idleにいるので、out2が発火してない。

やー、これトリガーで対応するのは確かに大変だなー

2022-01-24 08:04 UTC, xiii111 commented
@takasusuke @takesi0627 暫定案にはなりますが、以下のような処理にさせていただきました
- 闇が登場するアニメーションを一つに統一
- 闇が晴れるアニメーションは従来通り二つ

理由としては以下
- 元々、アニメーションを分けようとしていた理由が、手でホールドした位置から闇を晴れさせたい、というもの。なので、闇がどう登場するかについては、気にしていなかったから
- アニメーションの処理がとても複雑になる。特に、成功状態と長押し状態が切り替わる瞬間がほぼ同時になるパターンが多く、そのためのディレイなどを必要とするから
- 思ったよりも見た目がおかしくないから

https://user-images.githubusercontent.com/26104258/150744237-f7dc3260-a984-4d6f-8867-b11e51e875ec.mov

2022-01-24 08:06 UTC, xiii111 commented
@takasusuke @takesi0627 ↑ 上記がどれくらい問題かを意識確認したいです。また、差分が複雑ですが `DarkAttributeController` とアニメーション周りを見ていただければ、問題ないです

2022-01-25 00:15 UTC, takesi0627 approved these changes
素晴らしい！
いいと思います

2022-01-25 00:18 UTC, takesi0627 commented
90a11a0 : 多分アップグレードで `.png.meta` に新しいプロパティが追加されて毎回差分が出るのでコミットしておきました

2022-01-25 14:43 UTC, takasusuke approved these changes
Animation良い感じな気がする

2022-01-25 15:15 UTC, merged