[Phase3] DarkAttribute のデザイン適用 - Particle の実装
LITO-apps/Treevel-client pull request #1396
Opened 2022-01-27 10:45 UTC by xiii111

### 対象イシュー
Close #1192 

### 概要
- Particle を実装
- Dark 状態の時にのみ Particle の Scale を 1 とする
- Particle は背景部分（`DarkBackgroundParticle`）と、本体部分（`DarkParticle`）に分離した

### キャプチャ
#### 開始時
https://user-images.githubusercontent.com/26104258/151342882-06c27941-94b1-4b57-a3ef-1fddc3925d03.mov

#### 移動中
https://user-images.githubusercontent.com/26104258/151343155-c6e926a7-163c-41ac-9a74-74070325c7a7.mov

### 動作確認方法
- [ ] Dark 状態の時にのみ Particle の Scale が 1 になっていること

2022-01-27 10:45 UTC, xiii111 commented
@LITO-apps/engineer レビューお願いします！

2022-01-27 11:37 UTC, xiii111 commented
📝 ブラッシュアップ案
- 透明度をいじる
- 半径をデカくしてみる
- 背景にもう少し動きを出す

2022-01-27 11:40 UTC, xiii111 commented
📝 ライフなどと合わせて Particle を Play する

2022-01-27 15:26 UTC, takasusuke requested changes
## imo
`DarkParticle`と`DarkBackgroundParticle`のpositionのYを`-10`とかに設定して、中央より若干下側に配置する方が収まりがよく見える（元絵に描かれている同心円の中心に近い）

## must
ゲームが開始するまでParticleを止めるのの他に、ゲームが終了した時もparticleを止めて欲しい
(Ghostでも同じことをやっている)

2022-01-28 06:15 UTC, xiii111 commented
> ## must
> ゲーム開始までParticleを止めるのの他に、ゲームが終了した時もparticleを止めて欲しい
> (Ghostでもやっているので、それと同じ感じで)

dad88c4

## ゲーム開始時

https://user-images.githubusercontent.com/26104258/151496319-6bef9d94-ffee-451a-9e95-98b3378078a2.mov

## ゲームリトライ時

https://user-images.githubusercontent.com/26104258/151496481-7dc4b3fc-748a-48c1-b6f7-039cd065d1e7.mov

## ゲーム成功時

https://user-images.githubusercontent.com/26104258/151496573-b2549dc9-dc5e-4207-bcbb-d12fc1d26f8f.mov

## ゲーム失敗時

https://user-images.githubusercontent.com/26104258/151496792-552f2630-02aa-410d-9f18-8030e83186d0.mov

2022-01-28 11:28 UTC, xiii111 commented
> ## imo
> `DarkParticle`と`DarkBackgroundParticle`のpositionのYを`-10`とかに設定して、中央より若干下側に配置する方が収まりが> よく見える（元絵に描かれている同心円の中心に近い）

9f66575

2022-01-28 11:28 UTC, xiii111 commented
@takasusuke 修正しました！あと少しだけ、演出を洗練できないか試しますが、大きく方向性を変えるつもりはありません！

2022-01-28 11:36 UTC, xiii111 commented
なんか良い感じの演出に変えられなかったから、一旦これで🙏

2022-01-28 14:15 UTC, takesi0627 commented
ごめん、
@takasusuke に任します
🙏

2022-01-29 04:36 UTC, takasusuke approved these changes

2022-01-29 04:46 UTC, merged