[OnBoarding-5] ゲームチュートリアル
LITO-apps/Treevel-client pull request #1403
Opened 2022-02-02 15:07 UTC by takesi0627

### 対象イシュー
Close #1187 

### 概要

### 詳細

#### 現実装になった経緯

#### 技術的な内容

### キャプチャ

### 動作確認方法

### 参考 URL

2022-02-03 11:27 UTC, takesi0627 commented
`TODO`

* 赤いボトルを移動するときに左右に移動できないように
* 赤いボトルを移動するときにフリックしてねという説明が足りない

2022-02-03 12:44 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +        protected readonly Dictionary<EGameState, StateBase> _stateList = new Dictionary<EGameState, StateBase>();
```suggestion
        protected readonly Dictionary<EGameState, StateBase> stateList = new Dictionary<EGameState, StateBase>();
```

2022-02-03 13:37 UTC, takasusuke reviewed
Assets/Project/Scripts/Modules/GamePlayScene/GamePlayTutorialDirector.cs
と
Assets/Project/Actors/UIs/GamePlayScene/Tutorial/FlickDownDirectorTimeline.playable
以外は見た

2022-02-03 13:37 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/UIs/CoachMark.cs
> +        private GameObject GetAvailableMaskOrAdd()
## nits
ドキュメンテーションコメントお願いします

2022-02-03 13:37 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/UIs/CoachMark.cs
> +        private GameObject GetAvailableMaskOrAdd()
## imo
メソッド名`GetAvailableMask`でも好み。
`Add`を名前に入れるなら`GetOrAddAvailableMask`が好み。

何でも。

2022-02-03 13:37 UTC, takasusuke commented on Assets/Project/Actors/UIs/GamePlayScene/TutorialPopup.prefab
> +  m_ConstrainProportionsScale: 0
## ask
このファイル、何が変わった...??
なんか勝手に差分が生まれただけ??

2022-02-04 04:50 UTC, xiii111 commented
動作に関しては https://github.com/LITO-apps/Treevel-client/pull/1403#issuecomment-1028891634 で良さそうでした。 @takasusuke が念入りに見てくれているようなので、任せるかもしれません

2022-02-04 14:01 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayTutorialDirector.cs
> +        private void SetBottleInputEnabled(bool enabled)
## nits
`static`にできる。
```suggestion
        private static void SetBottleInputEnabled(bool enabled)
```

2022-02-04 14:14 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayTutorialDirector.cs
> +                if (_tapCount == 1) // Input.touchCount > 0 だけだとちょっとタップしただけで何段階もスキップすることになる
## ask
`is (_tapCount > 0)`で何段階もスキップする？？
`_tapCount = 0;`があるから大丈夫そうには見える、けど違う？？

連打してチュートリアルを読み損ねてほしくないから、
`tapCount`の他に、`elapsedTime > 0.50f`みたいな条件も欲しいかもと思った。
少し考えてもらえると嬉しい。

2022-02-04 14:27 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayTutorialDirector.cs
> +                    (mainCamera.WorldToScreenPoint(redTile.transform.position), tileSpriteSize * 1.4f),
## nits
`1.3f`は定数定義よろしくお願いします。

2022-02-04 14:45 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayTutorialDirector.cs
> +                if (_tapCount == 1) // Input.touchCount > 0 だけだとちょっとタップしただけで何段階もスキップすることになる
`_tapCount > 0 `は大丈夫だと思います。
`_tapCount`を作らず、`Input.touchCount`だけ条件にすると問題がある。

一定時間経過してからタップ有効にするのはいいと思います。

2022-02-04 14:47 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayTutorialDirector.cs
> +                if (_tapCount == 1) // Input.touchCount > 0 だけだとちょっとタップしただけで何段階もスキップすることになる
あ、ごめん勘違いしてた。
`Input.touchCount > 0`か。

2022-02-04 14:48 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayTutorialDirector.cs
> +                if (_tapCount == 1) // Input.touchCount > 0 だけだとちょっとタップしただけで何段階もスキップすることになる
しかも時間経過を設けたら、`Input.touchCount`で完結できると思う

2022-02-04 14:50 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayTutorialDirector.cs
> +                if (_tapCount == 1) // Input.touchCount > 0 だけだとちょっとタップしただけで何段階もスキップすることになる
確かに！

2022-02-04 14:53 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayTutorialDirector.cs
> +                if (_tapCount == 1) // Input.touchCount > 0 だけだとちょっとタップしただけで何段階もスキップすることになる
[9d6a299](https://github.com/LITO-apps/Treevel-client/pull/1403/commits/9d6a29970213e64343783dc8f1e30293e5c4253e) スッキリ！

2022-02-04 14:54 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayTutorialDirector.cs
> +            public override void OnEnter(StateBase @from = null)
意図はなかった。
オーバライドするときに自動生成なコードでそのまま放置しています。

2022-02-04 14:55 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayTutorialDirector.cs
> +            public override void OnEnter(StateBase @from = null)
自動生成か。
じゃあこのままで良いかな。

推奨されてるんだろうし。

2022-02-04 14:56 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayTutorialDirector.cs
> +            public override void OnEnter(StateBase @from = null)
おそらくですが `from` はLINQを書くときに使うキーワードの一つでもあるので、
混同しないようにRiderがつけてくれたかと思われます

2022-02-04 15:06 UTC, takesi0627 commented on Assets/Project/Actors/UIs/GamePlayScene/TutorialPopup.prefab
> +  m_ConstrainProportionsScale: 0
多分作業中に開いてたからUnityアップデートの変更がと思われます

2022-02-04 15:12 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/CoachMark.cs
> +        private GameObject GetAvailableMaskOrAdd()
[1271a23](https://github.com/LITO-apps/Treevel-client/pull/1403/commits/1271a2322aa8fae7bf985bab3051b0a1cf2edd1a)

2022-02-04 15:13 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/CoachMark.cs
> +        public (Vector3 position, float size)[] highlightInfoArr;
[cec269b](https://github.com/LITO-apps/Treevel-client/pull/1403/commits/cec269b95fde80b1167a92155f94323d1476e496)

2022-02-04 15:13 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +        protected readonly Dictionary<EGameState, StateBase> _stateList = new Dictionary<EGameState, StateBase>();
[065ebb1](https://github.com/LITO-apps/Treevel-client/pull/1403/commits/065ebb1ec254ce9a8f5770467370ca01735604d0)

2022-02-04 15:13 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +        protected class SuccessState : StateBase
[2d55f0b](https://github.com/LITO-apps/Treevel-client/pull/1403/commits/2d55f0b259d741ef767d2c32b7be6136c86dc38e)

2022-02-04 15:14 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/CoachMark.cs
> +        public float circleSize;
[cec269b](https://github.com/LITO-apps/Treevel-client/pull/1403/commits/cec269b95fde80b1167a92155f94323d1476e496)

2022-02-04 15:18 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayTutorialDirector.cs
> +                    (mainCamera.WorldToScreenPoint(redTile.transform.position), tileSpriteSize * 1.4f),
7478345a
これでいかがでしょうか

2022-02-04 15:32 UTC, takesi0627 commented
> ## imo
> 青いボトルも動かせると、下の動画みたいにクリアできて変な感じだから、 少なくとも、赤いボトルのチュートリアル中は青いボトルは動かせない、という制約は必要だと思います。

59aa31ea

2022-02-05 06:42 UTC, takasusuke commented
@takesi0627 
#1407 をこのbranchにmergeしました。

2022-02-05 14:28 UTC, takesi0627 commented
> @takesi0627
> #1407 をこのbranchにmergeしました。

あざます！

2022-02-05 16:10 UTC, takesi0627 commented
> * 赤いボトルを移動するときに左右に移動できないように

[cadf29d](https://github.com/LITO-apps/Treevel-client/pull/1403/commits/cadf29d59d70f10b500f43901df5dde6dbcb9759)

> * 赤いボトルを移動するときにフリックしてねという説明が足りない

[b4e4096](https://github.com/LITO-apps/Treevel-client/pull/1403/commits/b4e4096ba1166315d62803aed1eaad47f04cf2ad)
結局ダミーボトルを配置する方法を採用しました。
理由としては、FlickGestureをなんとか左右にいけないようにしても、上にいかせても困るし、
とはいえ、下にだけ許可すると、一回下にフリックして上にフリックできないのもどうかと思います。
あくまでも「マスク内にだけ移動してほしい」という仕様だと思うので、周囲にダミーボトルを配置することにしました。

2022-02-05 16:12 UTC, takesi0627 commented
@xiii111 @takasusuke 
再度レビューよろしくお願いします。

2022-02-05 18:06 UTC, takasusuke reviewed
不自然なパターンを見つけてしまった...😭
https://user-images.githubusercontent.com/26213141/152653531-3edd1513-6962-4e02-94d6-3acc473a99aa.mov

2022-02-06 00:01 UTC, xiii111 commented
↑ よく見つけた

2022-02-06 00:05 UTC, xiii111 requested changes
動作確認をしようとしたんですが、以下のようになってしまいました。お二人は起きていないですか？

https://user-images.githubusercontent.com/26104258/152663114-aed32aba-adf7-46af-becb-81332fe241f0.mov

2022-02-06 00:44 UTC, takasusuke commented
@xiii111 
そういえば、今はSimulatorだとタップできない。

2022-02-06 00:56 UTC, takesi0627 commented
あれー確認します

2022-02-06 01:15 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayTutorialDirector.cs
> +            };
## nits
スペース調整

2022-02-06 09:53 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayTutorialDirector.cs
> +            };
[3090c7d](https://github.com/LITO-apps/Treevel-client/pull/1403/commits/3090c7d6fd03bf4e77f7754f7333a728ddbf2466)

2022-02-06 10:10 UTC, takesi0627 commented
[c1657da](https://github.com/LITO-apps/Treevel-client/pull/1403/commits/c1657dae4c57bf52f5eddb33e90cc929e8efb772)
シミュレータのバグ修正した

2022-02-06 10:34 UTC, takesi0627 commented
> 不自然なパターンを見つけてしまった...😭
> 
>  2022-02-06.3.05.43.mov

[20a1088](https://github.com/LITO-apps/Treevel-client/pull/1403/commits/20a1088e9f4b314430f1e3e2fd9ed146a78cee34)
条件を修正しました

2022-02-06 10:34 UTC, takesi0627 commented
@xiii111 @takasusuke 
もう一回お願いします！

2022-02-06 14:32 UTC, takasusuke approved these changes
お疲れ様です！

2022-02-07 05:05 UTC, xiii111 approved these changes
再度動作を確認し直しましたが、素晴らしかったです！

2022-02-07 05:08 UTC, merged

2022-02-07 05:08 UTC, takesi0627 commented
あざーした！