チュートリアルポップアップのアイコン作成
LITO-apps/Treevel-client pull request #1423
Opened 2022-02-12 15:27 UTC by takasusuke

## 対象イシュー
Close #1221

## 概要
- チュートリアルポップアップに表示するリソースを作成し、それを適用する

## 詳細
リソースの作成方法はissueコメントに記載

未実装
- [ ] mp4の透過部分が黒塗りになっているので修正
- [ ] 複数回VideoClipを再生できない問題の修正
- [ ] Meteoriteを新しい画像に更新
- [ ] OverviewPopupでTutorialで同じギミックのアイコンを参照し、重複する画像は削除(?)(将来的に、基本Tutorialは動画を使うことを考えると、OverviewPopupのリソースとは異なるのが正しいかも)

## レビューの観点
Tutorial Popupの見た目を確認

## キャプチャ
| before | after |
|--------|-------|
| XXXXXX | XXXXX |

## 動作確認方法
Tools > Debug Command > Complete Tutorial Statesを実行し、全てのチュートリアルを既読状態にする
- [ ] History画面で全てのチュートリアルを確認

## 備考

2022-02-12 15:30 UTC, takasusuke commented
@takesi0627 
同じVideoClipを複数回再生しようとすると、
```
Cannot Prepare a disabled VideoPlayer
```
が出て、二回目以降は表示されない。手助け願う。。。
`videoClip`か`videpPlayer`を初期化しないといけない...?

2022-02-12 16:47 UTC, takesi0627 commented
@takasusuke 

2回目以降なぜか`SetActive`から`enabled`になるまで少し時間かかってるみたいです。
とりあえずこれで再生はできますが、明らかに時間差があるのでちょっとロードインジケーターを出す必要あるかもしれません
[670bed0](https://github.com/LITO-apps/Treevel-client/pull/1423/commits/670bed07213dc11db30a720643b866b176218ca7)

2022-02-14 13:52 UTC, takasusuke commented
@LITO-apps/engineer 
よろしくお願いします。

動作確認が主です。

2022-02-15 14:14 UTC, xiii111 requested changes
素晴らしいタスクです👏 いくつかコメントしました！

### Nits
`Autumn-1-2` で `Meteorite` のチュートリアルが表示されないようになっていそうです

### Imo
やや、ライフの大きさが大きく見えます（ゲーム時と同様の比率ですか？）

<img width="248" alt="スクリーンショット 2022-02-15 23 03 34" src="https://user-images.githubusercontent.com/26104258/154078059-125ea32f-dfe1-4ed6-8da9-ed16074f8cdc.png">

### Nits
今回とは関係ないと思いますが、蜘蛛の巣の文言が左に揃っていないようです

<img width="257" alt="スクリーンショット 2022-02-15 23 02 38" src="https://user-images.githubusercontent.com/26104258/154078179-eb2cc164-5573-4360-8a61-3c30cda0805d.png">

### Imo
個人的には、混乱も動画の方が良いように感じました。背景色が黄色に近いのも相まって、星の視認性がかなり悪いです

<img width="259" alt="スクリーンショット 2022-02-15 23 03 22" src="https://user-images.githubusercontent.com/26104258/154078316-a630365e-588f-41d2-b2bb-abd4b395e2a6.png">

### Must
黄色背景がない気がします

https://user-images.githubusercontent.com/26104258/154079125-9c0cd8f4-befe-40c7-8db2-166f7cbaaa22.mov

2022-02-15 14:14 UTC, xiii111 commented on Assets/Project/Editor/DebugTools.cs
> +        }
素晴らしい👏👏

2022-02-15 15:05 UTC, takesi0627 commented
> ### Imo
> やや、ライフの大きさが大きく見えます（ゲーム時と同様の比率ですか？）
> 
> <img alt="スクリーンショット 2022-02-15 23 03 34" width="248" src="https://user-images.githubusercontent.com/26104258/154078059-125ea32f-dfe1-4ed6-8da9-ed16074f8cdc.png">

![image](https://user-images.githubusercontent.com/17778395/154089150-feb9b3f4-d1eb-4258-934c-c3c59834227f.png)

[c623a25](https://github.com/LITO-apps/Treevel-client/pull/1423/commits/c623a253f03e1e6244bb4d9087958e9b014b40aa)

調整しました。
比率で作ってないので多少の誤差があるかもしれません。

2022-02-15 15:27 UTC, takesi0627 reviewed
素晴らしかったです。
僕からは特に他のコメントがありません

2022-02-16 13:27 UTC, takasusuke commented
@xiii111 

> ### Nits
> `Autumn-1-2` で `Meteorite` のチュートリアルが表示されないようになっていそうです

[08da990](https://github.com/LITO-apps/Treevel-client/pull/1423/commits/08da9904ac3ff4e80eab812da4f1dac934a20aa9)

> ### Nits
> 今回とは関係ないと思いますが、蜘蛛の巣の文言が左に揃っていないようです

「蜘」の字は、適用されているフォントが未対応なので表示されていません。
https://github.com/LITO-apps/Treevel-client/pull/1373#issuecomment-1023438546

> ### Imo
> 個人的には、混乱も動画の方が良いように感じました。背景色が黄色に近いのも相まって、星の視認性がかなり悪いです

ReverseAttributeなど、透明な部分があるとmp4を作成できません。
透明に対応した拡張子は容量が大きいです。
対処法としては、
- Bottleは全てNormalTileの上に載せる(と透明な部分は無くなるのでmp4で楽に作れる)
- AnimationControllerとかTimelineとかにする

が今思いつく対処法です。
AnimationControllerやTimelineにする場合は、別issueで対応を考えようかと思っています。(元々全て画像にする予定で、mp4はそんなにコストがかからないから導入してみたため)
 
> ### Must
> 黄色背景がない気がします

[09041d2](https://github.com/LITO-apps/Treevel-client/pull/1423/commits/09041d244e81c26d1741bff7486407f44edad783)

2022-02-16 22:58 UTC, xiii111 commented
@takasusuke 

> 「蜘」の字は、適用されているフォントが未対応なので表示されていません。フォント適用issueで拾います。

ボケてました、、ごめんなさい

> 確かに見づらい。解決はすぐには難しい。 ReverseAttributeなど、透明な部分があるとmp4を作成できません。 透明に対応した拡張子は容量が大きいので、あまり使いたくはない。 対処法としては、
> 
> * Bottleは全てNormalTileの上に載せる(と透明な部分は無くなるのでmp4で楽に作れる)
> * AnimationControllerとかTimelineとかにする
> 
> が今思いつく対処法です。 AnimationControllerやTimelineにする場合は、別issueで対応を考えようかと思っています。(元々全て画像にする予定で、mp4はそんなにコストがかからないから導入してみたため)

あーーーなるほど。詳細な説明をありがとうございます！それでしたら、チュートリアルのアイコンでは、星の色をハッキリした色にしたり、見やすく星を縁取ったりなどの、デフォルメをするのはどうでしょうか？

> > ### Must
> > 黄色背景がない気がします
> 
> [5e80904](https://github.com/LITO-apps/Treevel-client/pull/1423/commits/5e8090415a62e86df8fb95417dad8fbafd759a71)

参照が外れているのか、`聖域` のみ例外が発生してしまいます

<img src="https://user-images.githubusercontent.com/26104258/154371566-65aac4ea-cdc5-4cb0-9a5e-8a4459f8a5aa.png" width="300">

2022-02-16 22:59 UTC, xiii111 requested changes
混乱と聖域について、追加でコメントさせていただきました

2022-02-17 12:09 UTC, takasusuke commented
@xiii111 
ReverseAttibuteの星部分に縁をつけました
[60f182f](https://github.com/LITO-apps/Treevel-client/pull/1423/commits/60f182f487727e57c27e18f5f88828ec35198832)

<img width="251" alt="スクリーンショット 2022-02-17 21 07 22" src="https://user-images.githubusercontent.com/26213141/154478843-f4b45ee6-9967-472e-b8d5-de6a99eb9de3.png">

2022-02-18 09:51 UTC, xiii111 approved these changes
Great Work!!

2022-02-19 01:44 UTC, merged