ボトルの移動が完了したら、フリックの SE を流し `flickNum` をインクリメントする
LITO-apps/Treevel-client pull request #1428
Opened 2022-02-15 12:49 UTC by xiii111

## 対象イシュー
Close #1401 

## 概要
- ボトルが実際に移動していない場合でも、フリックの SE が流れるようになっていたので、ボトルの移動が完了した場合に、フリックの SE が流れるようにした
- `flickNum` も、ボトルが実際に移動していない場合にインクリメントされていたので、ボトルの移動が完了した場合に、インクリメントするようにした

## 詳細
`BoardManager` の `FlickBottle()` は単純に `MoveAsync()` を呼び出すわけではなく、フリックする方向にタイルが存在しない場合には `MoveAsync()` を呼び出さずに処理を終了している。また、`MoveAsync()` も単純にボトルを移動させるわけではなく、さまざまな判定（移動先にボトルがある、ボトルが移動可能か、タイルが受け入れ可能か）が通った場合に初めて、ボトルが移動開始される。また、移動が開始されても、移動中に移動が中断されたら、移動は完了しないとして、返り値としては移動失敗となる。こういう状況なので、単純に `FlickBottle()` の前後や `MoveAsync()` の前後に、フリックの SE を流したり `flickNum` をインクリメントしたりしても、想定通りの処理にならない場合がある。

今回は、一律、移動は完了した場合に、フリックの SE を流し `flickNum` をインクリメントするようにした

## レビューの観点
- ボトルの移動が完了した場合に SE が流れるので、従来よりは流れるタイミングが遅くなった。そこまで違和感はないが、許容できないかどうか（許容できない場合には `BoardManger` の `MoveAsync()` にそこそこの変更が必要になるので、変更範囲が大きくなる可能性が高い）

## 動作確認方法
- [ ] ボトルの移動が完了したら、フリックの SE が流れるようになっていること
- [ ] ボトルの移動が完了したら、`flickNum` がインクリメントされるようになったこと

## 備考
- 特になし

2022-02-15 14:39 UTC, takesi0627 requested changes

2022-02-15 15:04 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +                        SoundManager.Instance.PlaySE(ESEKey.Bottle_Move);
> ここで待ってると、SEの再生が移動が完了したタイミングになってしまうので意図した挙動ではないと思われます。

レビューの観点に書いた通り、意図した挙動として対応しましたが、許容できないということですね？

2022-02-15 15:04 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +                        SoundManager.Instance.PlaySE(ESEKey.Bottle_Move);
`StartMove` だと、フリック以外の移動も含まれてしまいませんか？

2022-02-15 15:22 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +                        SoundManager.Instance.PlaySE(ESEKey.Bottle_Move);
ごめんなさい、見落としました。
そうですね、ちょっと個人的には許容できないかも

2022-02-15 15:31 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +                        SoundManager.Instance.PlaySE(ESEKey.Bottle_Move);
ほんとだ `Bottle_Move` ですね

2022-02-16 05:42 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +                        SoundManager.Instance.PlaySE(ESEKey.Bottle_Move);
@takesi0627 cc @takasusuke 基本的に良さそうだったんですが、`Warp` タイルによる移動の時も `StartMove` が呼ばれているようでした。`StartMove` によりどのような処理が実行されているかというと、`GhostAttribute` と `PowderGimmick` の状態リセット処理でした。こちら、ワープでの移動の時にも、行うべきかというと、どちらでも良い気がしたので、`Warp` タイルによる移動の時は `StartMove` を呼ばないようにしました（空間的には移動しているが、ボトルが連続的に移動したわけではない）この意思決定に問題がありそうだったら、言ってください。他の方法を考えます！

[340fbb8](https://github.com/LITO-apps/Treevel-client/pull/1428/commits/340fbb8fbce1aa55ba8ed9eb6cc14f5f4f7f8dc6)

2022-02-16 22:47 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +                        SoundManager.Instance.PlaySE(ESEKey.Bottle_Move);
お、よかったです

@takesi0627 良さそうでしたら、Approve ください！

2022-02-18 00:19 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +                        SoundManager.Instance.PlaySE(ESEKey.Bottle_Move);
@takesi0627 これみて

2022-02-18 09:53 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +                        SoundManager.Instance.PlaySE(ESEKey.Bottle_Move);
ごめん、アプルーブしたつもりでいた・・

2022-02-18 09:55 UTC, merged