結晶ステージのチュートリアル
LITO-apps/Treevel-client pull request #1523
Opened 2022-03-26 16:09 UTC by takesi0627

## 対象イシュー
Close #1441 

## 概要
結晶ステージのチュートリアルの実装

## 詳細
* マスクの制御はソースコードベースでしないといけないのでコードベースで実装
* `CoachMark`に四角いマスクが使えるようにしました。（指定しない場合は丸いマスクを使う）

## レビューの観点
* `CoachMark`周りの変更
* `StageSelectDirector.CrystalStageCoachMark`の処理

## キャプチャ

https://user-images.githubusercontent.com/17778395/160247633-25033c6e-9968-40dd-8d23-0d1ed449bb04.mov

## 動作確認方法
- [ ] `Reset Stage Record`、`Reset Animation State`、`Reset OnBoarding State`を行って、`Spring-1-1`をクリアして演出を確認

## 備考

2022-03-26 16:10 UTC, takesi0627 commented
@xiii111 @takasusuke 
レビューよろしくお願いします。
30minくらいはかかりそうです。

2022-03-26 16:13 UTC, takesi0627 commented
[70f7075](https://github.com/LITO-apps/Treevel-client/pull/1523/commits/70f7075f1c4caa667b94d1ac1e709057123da702)
@takasusuke 
`Mplus1-Bold SDF.asset`を使っただけで差分が出ていたけど、なんかわかりますか？
一回戻してみたけど実行したらまた出てきたからコミットしました。
もし何か懸念点があれば、`TMP`じゃなくて普通の`Text`を使おうかなと思います。

2022-03-28 13:36 UTC, takasusuke commented
> [70f7075](https://github.com/LITO-apps/Treevel-client/pull/1523/commits/70f7075f1c4caa667b94d1ac1e709057123da702) 
`Mplus1-Bold SDF.asset`を使っただけで差分が出ていたけど、なんかわかりますか？ 一回戻してみたけど実行したらまた出てきたからコミットしました。 もし何か懸念点があれば、`TMP`じゃなくて普通の`Text`を使おうかなと思います。

問題ないです。
TextMeshProで使うためのMeshがFontデータから作られるのでその差分です。

2022-03-28 14:09 UTC, takasusuke requested changes
お疲れ様です！

## must
Historyを表示できないので、
`Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryDirector.cs`の`Awake`を以下のように変更してほしい。
(CoachMarkのみでBoardが出ないタイプと出るタイプで区別できるようにすべきとは思うがとりあえず)
```
// OnBoardingポップアップ表示ボタンの列挙
            foreach (var onBoarding in (EOnBoardingType[])Enum.GetValues(typeof(EOnBoardingType))) {
                if (onBoarding == EOnBoardingType.GamePlayScene || onBoarding == EOnBoardingType.StageSelectCrystalStage) continue;
                var button = Instantiate(_onBoardingButtonPrefab, _content.transform);
                button.GetComponent<OnBoardingButton>().Initialize(onBoarding, _onBoardingPopup);
            }
```

## imo
このオブジェクトの名前は`CircleMask`が適当そう。
<img width="1652" alt="スクリーンショット 2022-03-28 22 57 01" src="https://user-images.githubusercontent.com/26213141/160414023-bbb22823-29b8-417a-a892-6d44df034a4d.png">

## imo && ask
鍵オブジェクトのアニメーション途中でCoachMarkが出るけど、鍵オブジェクトのアニメーションを待ったりとかは容易ではない...よね？

2022-03-28 14:09 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/UIs/CoachMark.cs
>          public void ClearMask()
## imo
`Clear`のイメージと離れてきてると感じるので、リネームいかがでしょうか。
```suggestion
        public void InitializeMask()
```

2022-03-29 14:55 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/StageSelectScene/StageSelectDirector.cs
> +        private async UniTask CrystalStageCoachMark()
[738d935](https://github.com/LITO-apps/Treevel-client/pull/1523/commits/738d93588e183d7d8216878b415d265f12234cd1)

2022-03-29 15:19 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/CoachMark.cs
>          public void ClearMask()
[26c2a55](https://github.com/LITO-apps/Treevel-client/pull/1523/commits/26c2a558e0ff59ba099f11c88cff810a929ffc7e)

2022-03-29 15:44 UTC, takesi0627 commented
> お疲れ様です！
> 
> ## must
> Historyを表示できないので、 `Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryDirector.cs`の`Awake`を以下のように変更してほしい。 (CoachMarkのみでBoardが出ないタイプと出るタイプで区別できるようにすべきとは思うがとりあえず)
> 
> https://github.com/LITO-apps/Treevel-client/blob/6ec2ab82cc249ec275827f630d2d77ae664c6710/Assets/Project/Scripts/Modules/MenuSelectScene/History/HistoryDirector.cs#L60
> ↓
> ```
> if (onBoarding == EOnBoardingType.GamePlayScene || onBoarding == EOnBoardingType.StageSelectCrystalStage) continue;
> ```
> 

[f0ce6ce](https://github.com/LITO-apps/Treevel-client/pull/1523/commits/f0ce6ce3c0516b07567eb3b44061f31591a9b5dc)


> ## imo
> このオブジェクトの名前は`CircleMask`が適当そう。 <img alt="スクリーンショット 2022-03-28 22 57 01" width="1652" src="https://user-images.githubusercontent.com/26213141/160414023-bbb22823-29b8-417a-a892-6d44df034a4d.png">
> 

[b5223de](https://github.com/LITO-apps/Treevel-client/pull/1523/commits/b5223de756cb9500af4fb15e6de4fa0ce8fb0de7)

> ## imo && ask
> 鍵オブジェクトのアニメーション途中でCoachMarkが出るけど、鍵オブジェクトのアニメーションを待ったりとかは容易ではない...よね？

[470018d](https://github.com/LITO-apps/Treevel-client/pull/1523/commits/470018df22b5513ea994723cf847297377c561d5)

鍵解放アニメーションが`90`フレームの長さに対して、タイムラインの `StagePlayableAsset`クリップが`60`フレームだったので、途中で終わってしまった。
タイムラインの方を`95`フレームにしました。（鍵解放からオンボーディングまでちょっとだけ間を開く）

2022-03-30 04:49 UTC, xiii111 commented
@takasusuke お任せします🙏

2022-03-30 13:58 UTC, takasusuke approved these changes
お疲れ様でございます😀

2022-03-31 05:18 UTC, merged