`ErasableBottle` の演出を改善する
LITO-apps/Treevel-client pull request #1540
Opened 2022-04-03 00:26 UTC by xiii111

## 対象イシュー
Close #1329 

## 概要

## 詳細

## レビューの観点

## キャプチャ
| before | after |
|--------|-------|
| XXXXXX | XXXXX |

## 動作確認方法
- [ ] 

## 備考

2022-04-10 02:00 UTC, xiii111 commented
📝 
- アニメーションを短くする
- 破壊後の画像の淵の白色を消す
- SE を追加する
- 画像を半透明にする（90%）
- 隙間の領域に小さい画像を含める
- 競り上がる時の下の画像のコマを増やせたら

2022-04-13 11:20 UTC, xiii111 commented
@takasusuke @takesi0627 レビューお願いします！

2022-04-13 14:25 UTC, takesi0627 requested changes
音源の元ファイルを一緒に管理したいので、
マージ後でもいいんですが、こちらにファイルのアップロードをお願いします。
https://drive.google.com/open?id=1ztYUTa3JRU_ljV_T_oYUC5ZJvM2A7-LZ&authuser=woody90825.ep01%40g2.nctu.edu.tw&usp=drive_fs

音量とトリミングはもうちょっと調整できそうですが、
調整するイシューあるので別途対応させていただきます。

2022-04-13 14:25 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/ErasableBottleController.cs
>                      SoundManager.Instance.StopSE(ESEKey.ErasableBottle_Out);
### `MUST`
音切れがひどいので、ここはStopせずにそのまま最後まで流してほしい

2022-04-13 14:25 UTC, takesi0627 commented
ちなみにアニメーションは最高でした

2022-04-13 16:36 UTC, takasusuke commented
@xiii111 
> 細かい岩石片を追加しました。色々とパターンを試しましたが、以下の条件を満たす画像が良さそうでした

良いと思います。
割れた際の画像の縁の色が、割れる前の画像の縁の色と異なるのが気になったので変更しました。
あと多分、色々拡大縮小したりして配置を試した過程?か、プレビューでトリミングする過程?かわからないけど解像度が落ちていた(色の境界がぼやけていた)のが気になったので塗り直しました。
元の割れた際の画像中央の破片が気になったので(説明しづらいけど、衝撃が加わった状態の破片ぽくない)、改変しました。
意図がずれてないかご確認ください。

[bae4653](https://github.com/LITO-apps/Treevel-client/pull/1540/commits/bae465358c4d2154e403226a7aaa7b31efa198d9)

2022-04-14 05:40 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/ErasableBottleController.cs
>                      SoundManager.Instance.StopSE(ESEKey.ErasableBottle_Out);
プツッと聞こえる原因がわからず、PR を出してしまったのですが、音切れだったんですね ... `StopSE` を消したらめちゃくちゃ良くなったので助かりました。`ErasableBottle_In` は `StopSE` していることから、経緯がわかるように修正しました

→ a2ce61e

2022-04-14 05:45 UTC, xiii111 commented
@takasusuke 色々と不備があったようですみません🙏 確認しましたが、意図と外れた修正はされていないように思いました。修正ありがとうございます！

2022-04-14 05:45 UTC, xiii111 commented
@takesi0627 再レビューお願いします！

2022-04-14 05:47 UTC, takesi0627 approved these changes
OKです
ファイルのアップロードは忘れずにお願いします

2022-04-15 00:25 UTC, xiii111 commented
完全に忘れてたので、アップロードしておきました！

2022-04-15 00:25 UTC, merged