CRIWARE導入
LITO-apps/Treevel-client pull request #1550
Opened 2022-04-09 14:41 UTC by takesi0627

## 対象イシュー
なし

## 概要
CRIWAREの導入

## 詳細
CIテストのため一旦PR出す

## レビューの観点

## キャプチャ
| before | after |
|--------|-------|
| XXXXXX | XXXXX |

## 動作確認方法
- [ ] 

## 備考

2022-04-19 17:16 UTC, takesi0627 commented
@xiii111 @takasusuke 
レビューよろしくお願いします。
CriWareについてどこまで書けばいいかよくわからなかったので何かわからないところあればどんどん補足しますのでコメント、質問お願いします。
一応通話で説明するつもりなので、その後でのレビューでも構いません。

2022-04-21 13:14 UTC, takasusuke requested changes
元々ある不具合かもしれないけど報告します。

バグ報告１
Footerを１度押して、LevelSelectnに遷移後、StageSelectSceneに遷移したり他のFooterを押すと水のSEが流れ続ける（複数鳴ってる）

https://user-images.githubusercontent.com/26213141/164464406-d03ed693-abf6-4de5-8829-bc0861bfec11.mov

バグ報告２
BGMをミュートした状態でResumeボタンを押すとBGMが再生される

https://user-images.githubusercontent.com/26213141/164464724-49578156-a269-4f88-af1e-4239c44aad41.mov

バグ報告３
GamePlaySceneでPause⇄Resumeを繰り返し続けると、以下の警告が出てSEが再生されなくなる
```
Failed to Play SE: UI_Button_Close_Popup because audio sources are fully assigned
UnityEngine.Debug:LogWarning (object)
Treevel.Common.Managers.SoundManager:PlaySE (Treevel.Common.Entities.ESEKey,bool) (at Assets/Project/Scripts/Common/Managers/SoundManager.cs:81)
Treevel.Modules.GamePlayScene.PauseWindow:PauseBackButtonDown () (at Assets/Project/Scripts/Modules/GamePlayScene/PauseWindow.cs:52)
UnityEngine.Events.UnityEvent:Invoke ()
Treevel.Common.Components.UIs.CustomButton/<>c__DisplayClass12_0:<Awake>b__1 (UnityEngine.EventSystems.PointerEventData) (at Assets/Project/Scripts/Common/Components/UIs/CustomButton.cs:113)
UniRx.Observer/Subscribe`1<UnityEngine.EventSystems.PointerEventData>:OnNext (UnityEngine.EventSystems.PointerEventData) (at Library/PackageCache/com.neuecc.unirx@284d5c50d3/Observer.cs:165)
UniRx.Subject`1<UnityEngine.EventSystems.PointerEventData>:OnNext (UnityEngine.EventSystems.PointerEventData) (at Library/PackageCache/com.neuecc.unirx@284d5c50d3/Subjects/Subject.cs:62)
UniRx.Triggers.ObservablePointerUpTrigger:UnityEngine.EventSystems.IPointerUpHandler.OnPointerUp (UnityEngine.EventSystems.PointerEventData) (at Library/PackageCache/com.neuecc.unirx@284d5c50d3/UnityEngineBridge/Triggers/ObservablePointerUpTrigger.cs:17)
UnityEngine.EventSystems.EventSystem:Update () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:501)
```

2022-04-22 02:20 UTC, xiii111 commented
@takasusuke @takesi0627 

> バグ報告１
Footerを１度押して、LevelSelectnに遷移後、StageSelectSceneに遷移したり他のFooterを押すと水のSEが流れ続ける（複数鳴ってる）

こちらですが、develop では発生していないようでした

> バグ報告２
BGMをミュートした状態でResumeボタンを押すとBGMが再生される

こちらも develop では発生していないようでした

> バグ報告３
GamePlaySceneでPause⇄Resumeを繰り返し続けると、以下の警告が出てSEが再生されなくなる

こちらも develop では発生していないようでした

2022-04-22 02:20 UTC, xiii111 commented
@takesi0627 `0.1 (28)` をアップロードしました。容量を確認できると思います。また、まだ全てレビューし切れていないです🙏

2022-04-23 06:31 UTC, xiii111 reviewed
差分周りは良さそうでした！動作確認は追ってします

2022-04-24 00:42 UTC, xiii111 commented
一旦 InProgress に戻しておきます

2022-05-05 03:28 UTC, takesi0627 commented
@xiii111 @takasusuke 

不具合修正しました。
不具合修正のため、特にSE再生周りは大幅の改修しましたので、
再度確認お願いします。

2022-05-08 00:37 UTC, xiii111 commented
develop だけ取り込みますね

2022-05-08 00:46 UTC, takasusuke requested changes
BGMをmute中に、SEの音量を変更するとBGMのmuteが解除されます。
(SEのmute中にBGMの音量を変更する場合も同じ)
(AudioSourceのmute中かどうか、みたいなpropertyが必要？)

2022-05-08 00:52 UTC, takesi0627 commented
> BGMをmute中に、SEの音量を変更するとBGMのmuteが解除されます。
> (SEのmute中にBGMの音量を変更する場合も同じ)
> (AudioSourceのmute中かどうか、みたいなpropertyが必要？)

[85f89d6](https://github.com/LITO-apps/Treevel-client/pull/1550/commits/85f89d6dc56179bee6327781f0d87ea20b39cddd)

`UserSettings`かたミュート状態を参照することで修正した

2022-05-08 01:02 UTC, xiii111 approved these changes
一通りいじってみましたが、気になる点は見つかりませんでした！

2022-05-08 01:05 UTC, takasusuke approved these changes
## ask
前までは16個しかSEを同時再生できなかったけどその制約はなくなったと考えてOKってこと？？

2022-05-08 01:09 UTC, takesi0627 commented
> ## ask
> 前までは16個しかSEを同時再生できなかったけどその制約はなくなったと考えてOKってこと？？

その設定はCriAtomCraftで設定している。
SEカテゴリのカテゴリキューリミット数を32しています。
16にした方がいいならちょっと調整します。

![image](https://user-images.githubusercontent.com/17778395/167277522-811383ad-cefd-4656-8b2b-f91c043b119c.png)

ちなみにBGMは1にしてます
![image](https://user-images.githubusercontent.com/17778395/167277553-ae243819-0160-4a85-842f-19cf4f2da79e.png)

2022-05-08 01:10 UTC, takesi0627 commented
> > ## ask
> > 前までは16個しかSEを同時再生できなかったけどその制約はなくなったと考えてOKってこと？？
> 
> その設定はCriAtomCraftで設定している。 SEカテゴリのカテゴリキューリミット数を32しています。 16にした方がいいならちょっと調整します。
> 
> ![image](https://user-images.githubusercontent.com/17778395/167277522-811383ad-cefd-4656-8b2b-f91c043b119c.png)
> 
> ちなみにBGMは1にしてます ![image](https://user-images.githubusercontent.com/17778395/167277553-ae243819-0160-4a85-842f-19cf4f2da79e.png)

参考資料：
https://game.criware.jp/manual/native/adx2/latest/criatom_feat_priority.html

2022-05-08 01:11 UTC, takasusuke commented
> その設定はCriAtomCraftで設定している。 SEカテゴリのカテゴリキューリミット数を32しています。 16にした方がいいならちょっと調整します。

なるほど！
32で良いと思います。(増えて嬉しい)

2022-05-08 01:11 UTC, takesi0627 commented
OK! マージします！

2022-05-08 01:11 UTC, merged