Feature/1533 tree icon
LITO-apps/Treevel-client pull request #1559
Opened 2022-04-22 15:44 UTC by takesi0627

## 対象イシュー
Close #1533 
Close #1339 

## 概要
ナンバー付き木のアイコンの実装

## 詳細
* `TreeIconView`クラスを作成した。主に木のアイコンの見た目を管理する目的のクラス。（ボタンなどの処理はしない）
* `LevelTreeController`と`TreeIconView`の役割分担は`StageController`と`StageIconView`の役割分担を参考にしている。

## キャプチャ
![image](https://user-images.githubusercontent.com/17778395/164748692-a0b81d94-702a-4d12-b9ac-1a15f81a323d.png)

## 動作確認方法
- [ ] LevelSelectSceneの見た目確認
- [ ] 未実装木がタップできないことの確認
- [ ] 木の各ステートの見た目が反映されていることの確認

## 備考
*

2022-04-22 15:47 UTC, takesi0627 commented
@LITO-apps/engineer 

レビューよろしくお願いします。
10~15min程度想定です。

2022-04-23 07:03 UTC, xiii111 reviewed
対応ありがとうございます！数点コメントしました！

## Ask

数字アイコンの縁に白い線が入っているのが凄く気になるのですが、どこか別で対応とかでしたっけ？（この話をしたような気がする）

## Ask
`.../Summer/FieldIcon.png` や `.../Summer/LevelIcon` は #1188 の対応をこの pr に含めちゃってる感じですかね？

2022-04-23 12:06 UTC, takasusuke requested changes
未実装の木が一瞬でも表示されるのは良くないと思うので、`LEVEL_ICON_NUMBER`もあらかじめLoadした方が良いかと思います。

https://user-images.githubusercontent.com/26213141/164893624-db1e3031-7f3d-4fbe-aba2-06b7225ca922.mov

2022-04-23 16:35 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/TreeIconView.cs
> +        _fieldImage.gameObject.SetActive(showField);
`Record`画面が使うときを考慮してフィールドを非表示にした方がいいかと思うので

2022-04-23 16:44 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/TreeIconView.cs
> +
[a2a7cc9](https://github.com/LITO-apps/Treevel-client/pull/1559/commits/a2a7cc9fb7f5929f6ae0ba7668eeafea0737dbd7)

2022-04-23 16:48 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/TreeIconView.cs
> +                _treeImage.material = _unreleasedMaterial;
[fada907](https://github.com/LITO-apps/Treevel-client/pull/1559/commits/fada907854b2f0839404a56b539864ce7ca22701)

2022-04-23 16:52 UTC, takesi0627 commented
> 対応ありがとうございます！数点コメントしました！
> 
> ## Ask
> 数字アイコンの縁に白い線が入っているのが凄く気になるのですが、どこか別で対応とかでしたっけ？（この話をしたような気がする）

特に対応する必要がある認識がなかったですが、
僕が聞きそびれた可能性もありますが、この指摘初めて聞いたような気がします。
具体的にどう気になるか、どう直して欲しいか教えていただけますでしょうか。
内容によってはすぐ対応できるかもしれませんが、大変だった場合は別途対応とさせていただきます

> ## Ask
> `.../Summer/FieldIcon.png` や `.../Summer/LevelIcon` は #1188 の対応をこの pr に含めちゃってる感じですかね？

#1188 ではなく、 #1339 ですね。
対象イシューのところ記載しております。

2022-04-23 16:57 UTC, takesi0627 commented
> 未実装の木が一瞬でも表示されるのは良くないと思うので、`LEVEL_ICON_NUMBER`もあらかじめLoadした方が良いかと思います。

`SetUnimplementedView`を呼び出すタイミングを調整すれば予めロードせずに改善できますが、いかがでしょうか

2022-04-23 17:05 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/TreeIconView.cs
> +                _treeImage.material = null;
`Sprites-Default`はおそらく必要ないので、
インスペクタで`null`にしておくが、
ここでは `null`をアサインする処理が必要です。
`Unreleased`から他のステートへ変化するときに `GrayScale`のマテリアルを外す必要があるからです。

2022-04-23 17:09 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/TreeIconView.cs
> +            _ => throw new ArgumentOutOfRangeException()
[bf4d380](https://github.com/LITO-apps/Treevel-client/pull/1559/commits/bf4d3800d07d536d9d2cb81687f822213c6c03b5)

2022-04-23 17:10 UTC, takesi0627 commented
@xiii111 @takasusuke 
コメント一通り返しました。
ご確認よろしくお願いします

2022-04-23 22:43 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/UIs/TreeIconView.cs
> +        _fieldImage.gameObject.SetActive(showField);
Record画面か！最高。

2022-04-23 22:47 UTC, takasusuke commented
@takesi0627 
> > 未実装の木が一瞬でも表示されるのは良くないと思うので、`LEVEL_ICON_NUMBER`もあらかじめLoadした方が良いかと思います。
> 
> `SetUnimplementedView`を呼び出すタイミングを調整すれば予めロードせずに改善できますが、いかがでしょうか

解決できればあらかじめLoadじゃなくても良いです。
未実装の木は解決されるけど、実装済みの木についてはNUMBERが一瞬「１」と表示されてから「２」とかになる気はする。

2022-04-24 00:45 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/UIs/TreeIconView.cs
> +                _treeImage.material = null;
> `Unreleased`から他のステートへ変化するときに `GrayScale`のマテリアルを外す必要があるからです。

あーそうか。アニメーションで変わることがあるから、同じ Scene インスタンスで `Unreleased` から変化するとかが起こりうるのか！であれば、変更はしなくて大丈夫です

2022-04-24 00:49 UTC, xiii111 commented
@takesi0627 

> 特に対応する必要がある認識がなかったですね・・
> 僕が聞きそびれた可能性もありますが、この指摘初めて聞いたような気がします。
> 具体的にどう気になるか、どう直して欲しいか教えていただけますでしょうか。
> 内容によってはすぐ対応できるかもしれませんが、大変だった場合は別途対応とさせていただきます

あ、ほんと。そしたら勘違いかもしれないです。実機で確認したら綺麗に見えるのかもしれませんが、#1493 のようにややギザギザしているように見えました。@takasusuke はそこまで気になりませんでしたか？

> #1188 ではなく、 #1339 ですね。
> 対象イシューのところ記載しております。

お、失礼しました🙏 #1339 を In Review に移動しておきますね

2022-04-24 00:52 UTC, takesi0627 commented
> > #1188 ではなく、 #1339 ですね。
> > 対象イシューのところ記載しております。
> 
> お、失礼しました🙏 #1339 を In Review に移動しておきますね

なんか同じ内容のものをレビュー中にあるのは結構自分混乱しがちなので、あえて移動しなかったが、
そこらへんみなさんはどうでしょうかね

2022-04-24 01:04 UTC, xiii111 commented
> なんか同じ内容のものをレビュー中にあるのは結構自分混乱しがちなので、あえて移動しなかったが、
そこらへんみなさんはどうでしょうかね

僕はあった方が分かりやすいと感じますが（In Review レーンにいるのは Issue であり PR ではないから）、基本的に 1 つの PR で複数の Issue を閉じないようにするのが良いんじゃないですかね

2022-04-24 01:05 UTC, xiii111 approved these changes
ギザギザ問題は許容することになったので Approve です！お疲れ様でした！

2022-04-24 01:32 UTC, takesi0627 commented
> @takesi0627
> 
> > > 未実装の木が一瞬でも表示されるのは良くないと思うので、`LEVEL_ICON_NUMBER`もあらかじめLoadした方が良いかと思います。
> > 
> > 
> > `SetUnimplementedView`を呼び出すタイミングを調整すれば予めロードせずに改善できますが、いかがでしょうか
> 
> 解決できればあらかじめLoadじゃなくても良いです。 未実装の木は解決されるけど、実装済みの木についてはNUMBERが一瞬「１」と表示されてから「２」とかになる気はする。
> 
> （MenuSelectScene.unityであらかじめ実装済みの木についてはNUMBERを正しく設定すれば大丈夫か）

とこで読み込めばいいかすごい悩んでだが、`MenuSelectScene`に必要なアセットを読み込む関数を`AddressableAssetManager`に作って、`StartUpDirector`で読み込むようにした。
確認よろしくお願いします
[0b692f7](https://github.com/LITO-apps/Treevel-client/pull/1559/commits/0b692f77e303f4fb5be7313a408ba326b8ced5cd)

2022-04-25 11:33 UTC, takasusuke approved these changes
お疲れ様です！

2022-04-25 11:58 UTC, merged