タップエフェクトのブラッシュアップ
LITO-apps/Treevel-client pull request #1566
Opened 2022-05-02 15:30 UTC by takasusuke

## 対象イシュー
Close #1331

## 概要
- タップエフェクトを画像を用いたAnimationからParticleに変更
- タップ時のみでなく、フリック時にもエフェクトを出すように変更

## 詳細
Particleの編集箇所
- 発生からの時間経過でParticleを小さくする
- Particleの`Simulation Space`を`World`にすることで`Particle System`の位置にParticleの位置が依存しなくなる

## レビューの観点
見た目

## キャプチャ
before

after

https://user-images.githubusercontent.com/26213141/166257346-8a00d1a2-5405-4544-b147-d7707f202b87.mov

## 動作確認方法
- [ ] タップする. 見た目の確認
- [ ] フリックする. 見た目の確認
- [ ] UnityRemote等で、実機のinputを受け付けて、マルチタップを行う。それぞれのタップ位置にエフェクトが出ることを確認する。

## 備考

2022-05-02 15:34 UTC, takasusuke commented
@xiii111 @takesi0627 
よろしくお願いいたします。30minくらい...?
急ぎでないです。

2022-05-03 01:52 UTC, takesi0627 requested changes
### `Must`
実機で確認しましたが、
タップしたポイントが画面上や下に近つけるとエフェクトがズレてるようです。
調査、修正お願いいたします。

https://user-images.githubusercontent.com/17778395/166393781-52e0df0c-7f05-4454-8472-6e00d64d9233.mov

2022-05-05 00:29 UTC, xiii111 commented
@takesi0627 一旦お任せします。レビューできそうならします

2022-05-05 06:03 UTC, takasusuke commented
@takesi0627 

> 実機で確認しましたが、 タップしたポイントが画面上や下に近つけるとエフェクトがズレてるようです。 調査、修正お願いいたします。

CanvasScalerがアタッチされていましたが、不要だったので削除することで修正しました。
[d042271](https://github.com/LITO-apps/Treevel-client/pull/1566/commits/d04227177dcb273aedc2a56e5b29f587ce2b9152)

2022-05-05 06:20 UTC, takesi0627 approved these changes
Excellent!

2022-05-07 01:30 UTC, xiii111 reviewed
素晴らしいです👏👏

## Ask

`TapObjectCanvas.prefab` に `UIParticle` を置くのではなく、`TapObjectCanvas` の具象に対して `UIParticle` を置いているのはなぜですか？今までの経験だと Prefab 内に要素が収まっていた方が、差分管理の観点でも良いという理解でした

## Ask

緑色という色はどういう意図で設定しましたか？

2022-05-07 01:30 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/UIs/TapObjectGenerator.cs
> +        public ParticleSystem _particleSystem;
## Nits

```suggestion
        /// <summary>
        /// タップ時に発生させるParticle
        /// </summary>
        [SerializeField] private ParticleSystem _particleSystem;
```

2022-05-07 01:30 UTC, xiii111 commented on Assets/Project/Resources.meta
> +DefaultImporter:
## Ask

今回は `TapObject.prefab` が削除されただけだと思いますが、なぜ `Assets/Project/Resources.meta` への差分になっているのでしょうか？心当たりありますか？

2022-05-07 09:49 UTC, takasusuke commented on Assets/Project/Resources.meta
> +DefaultImporter:
いつも出てる。いつもcommitから外してるけど外し忘れた。戻した。

[a68cbe1](https://github.com/LITO-apps/Treevel-client/pull/1566/commits/a68cbe1b625be7675750c9b0746f3277dfacea0c)

2022-05-07 09:49 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/UIs/TapObjectGenerator.cs
> +        public ParticleSystem _particleSystem;
[95a020e](https://github.com/LITO-apps/Treevel-client/pull/1566/commits/95a020ef9c1a61c4cee9369a8243f6b5486318a7)

2022-05-07 09:51 UTC, takasusuke commented
> ## Ask
> `TapObjectCanvas.prefab` に `UIParticle` を置くのではなく、`TapObjectCanvas` の具象に対して `UIParticle` を置いているのはなぜですか？今までの経験だと Prefab 内に要素が収まっていた方が、差分管理の観点でも良いという理解でした

ミス。prefabにした。
[82b8128](https://github.com/LITO-apps/Treevel-client/pull/1566/commits/82b8128cfe4d48db869500656397e7dac1106273)

> ## Ask
> 緑色という色はどういう意図で設定しましたか？

何色にしても何かしらのGoalBottleと被るので、色の重なりはあまり考えず
https://github.com/LITO-apps/Treevel-client/issues/1497
で実装するような回復っぽいエフェクトの色を意識しました。

2022-05-08 00:17 UTC, xiii111 approved these changes
LGTM!!

2022-05-08 00:17 UTC, xiii111 commented
マージまでしちゃいますね

2022-05-08 00:17 UTC, merged