記録画面の各レベルの木の実装
LITO-apps/Treevel-client pull request #1577
Opened 2022-05-11 13:48 UTC by takasusuke

## 対象イシュー
Close #1532

## 概要

## 詳細

## レビューの観点

## キャプチャ
| before | after |
|--------|-------|
| XXXXXX | XXXXX |

## 動作確認方法
- [ ] 

## 備考

2022-05-12 10:09 UTC, takasusuke commented
@xiii111 @takesi0627 
よろしくお願いします。30minくらいです。

スクリプトの変更自体はそこまで多くないです。
見た目を草案から変えた部分も結構あるので一見お願いします。

2022-05-12 13:14 UTC, takesi0627 commented
## `MUST?`

`Simulator / iPhone11` 環境でゲージが被っているように見えるので、調整できるなら調整して欲しいです。
<img src="https://user-images.githubusercontent.com/17778395/168082865-844699dc-5a12-446f-9740-2591243384f1.png" width="400">

2022-05-12 13:15 UTC, xiii111 reviewed
素晴らしい対応でした！！コードに関しては、問題なさそうです！見た目に関して、コメントさせてください

## Must

Game ではキャプチャに上げてくれている画像のように正常に配置されていますが、Simulator では円グラフ同士が近すぎるように見えます。確認お願いできますか？

|Simulator|Game|
|---|---|
|<img width="300" alt="スクリーンショット 2022-05-12 21 40 24" src="https://user-images.githubusercontent.com/26104258/168078885-9cb74e2c-f2f4-4b9d-b727-75a61282e6e5.png">|<img width="300" alt="スクリーンショット 2022-05-12 21 39 54" src="https://user-images.githubusercontent.com/26104258/168078861-57403128-66f0-4cd5-a724-3532f7acff2f.png">|

## Nits & Ask

軽微な修正点です
1. 上記 Must を修正する際に変更しそうですが、「旅の記録」の上部にスペースが多く空いているのが気になります。少し詰めたいです。これに伴い、「旅の記録」と「プレイ回数」のマージンももう少し余裕を持たせたいです
2. 「旅の記録」と「15 日目」のアラインメントが揃っていないように思います。「旅の記録」をもう少し左に寄せるか、「15 日目」をもう少し左に寄せるかしたいです
3. 日記アイコンが「旅を始めた日」に近すぎるのが気になりました。「旅を始めた日」をもう少し右に寄せたいです
4. 「旅を始めた日」と「4月 16日」が離れ過ぎており、関連のある要素だと分かりづらい気がします。「：」などを使って、関連があることを伝えたいです
5. 「15 日目」は数字と漢字の間に半角スペースがありますが、「4月 16日」には半角スペースがありません。これは意図通りですか？

<img width="376" alt="スクリーンショット 2022-05-12 22 02 58" src="https://user-images.githubusercontent.com/26104258/168081533-6f8bedab-8c54-4966-95bf-06fb05243116.png">

2022-05-14 05:58 UTC, takasusuke commented
| iPhone 11| Samsung Galaxy S9 |
| ---- | ---- |
| <img width="272" alt="スクリーンショット 2022-05-14 14 56 04" src="https://user-images.githubusercontent.com/26213141/168412877-e11f7a0d-4ea3-43e2-8c44-1bd1cd168a16.png"> | <img width="246" alt="スクリーンショット 2022-05-14 14 56 56" src="https://user-images.githubusercontent.com/26213141/168412882-435187c1-9121-4b1a-a931-8996810618a7.png"> |

2022-05-14 05:58 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/ClearStageNumController.cs
> +
[dad5ed7](https://github.com/LITO-apps/Treevel-client/pull/1577/commits/dad5ed7f182c5ca31c302cb6912fe7709b58d671)

2022-05-14 06:02 UTC, takasusuke commented
- 上部のスペースを埋めました。
- 各オブジェクトの左右両端を揃えました
- 日記アイコンが、「旅を始めた日」の背景をはみ出るように配置する理由がないので背景の中に収めました。
- 日記アイコンの大きさをフリックアイコンやステージアイコンと同じ大きさに揃えました。

| before | after |
| ---- | ---- |
| <img width="260" alt="スクリーンショット 2022-05-14 15 00 10" src="https://user-images.githubusercontent.com/26213141/168412982-8de591d3-413f-43c0-a869-cb89bd4f2176.png"> | <img width="264" alt="スクリーンショット 2022-05-14 14 59 37" src="https://user-images.githubusercontent.com/26213141/168412991-f8ee4858-8189-446b-b3b8-bf875a1eae73.png"> |

2022-05-14 06:09 UTC, takasusuke commented
@xiii111 
> 1. 上記 Must を修正する際に変更しそうですが、「旅の記録」の上部にスペースが多く空いているのが気になります。少し詰めたいです。これに伴い、「旅の記録」と「プレイ回数」のマージンももう少し余裕を持たせたいです

上部スペースを埋めました。
ヒストリー画面と同じに揃えたつもりだったけど、ヒストリー画面はフッターに被るような配置なのに対して、記録画面はフッターに必ず被らないように大枠のオブジェクトがあることを忘れたので揃えられてなかった。

> 2. 「旅の記録」と「15 日目」のアラインメントが揃っていないように思います。「旅の記録」をもう少し左に寄せるか、「15 日目」をもう少し左に寄せるかしたいです

両端に揃えました。

> 3. 日記アイコンが「旅を始めた日」に近すぎるのが気になりました。「旅を始めた日」をもう少し右に寄せたいです

日記アイコンが背景をはみ出る理由がなかったので、背景の中に収めて位置を調整しました。

> 4. 「旅を始めた日」と「4月 16日」が離れ過ぎており、関連のある要素だと分かりづらい気がします。「：」などを使って、関連があることを伝えたいです

日記アイコンの位置調整に伴い位置が近くなりました（のはたまたまで、白背景で囲むことで関連のある要素だと示していたので特に対応する予定はなかった）。

> 5. 「15 日目」は数字と漢字の間に半角スペースがありますが、「4月 16日」には半角スペースがありません。これは意図通りですか？

多言語対応のため上部の日数表示と下部の日付表示でオブジェクトの配置方法が異なり、意味も異なるのでそんなに意識してなかった。
けど、言われると確かに気になったのでスペースがないように見えるように位置調整しました。

2022-05-14 06:12 UTC, takasusuke commented
@xiii111 @takesi0627 
レイアウト調整しました。確認お願いします。

ヒストリー画面にも多少変更が入っていますが見た目の違いはほぼありません。
BorderLineの太さを変えました。
ヒストリー画面全体はスクロールするのでSafeAreaを考慮していませんでしたが、見出しの部分はSafeAreaに収めるように調整しました。
（記録画面と見出しの位置を揃えたかったので両画面ともSafeAreaに収まったくれていた方が調整しやすかった）

2022-05-14 07:38 UTC, xiii111 requested changes
修正ありがとうございます！素晴らしいと思います！

一点だけ追加で確認をお願いします。iPhone 8 などのデバイスでは、まだ円グラフがかぶるようです

<img src="https://user-images.githubusercontent.com/26104258/168416026-04e9df88-519e-43db-8f28-701368a47a0e.png" width="300">

設定を見ると、横幅を割合配置した後、アスペクト比 1:1 で高さを決めているようです。これは横幅の制約が大きいということでの設定だと思いますが、端末によっては縦幅の制約が重要になるようでした

<img src="https://user-images.githubusercontent.com/26104258/168416061-802bca64-2c36-4646-8816-ab516b62a3a5.png" width="300">

2022-05-14 09:01 UTC, takasusuke commented
> 端末によっては縦幅の制約が重要になるようでした

これは3時間かかる。気長にやる。

2022-05-14 10:04 UTC, takasusuke commented
iPhone 8 での見た目
<img width="261" alt="スクリーンショット 2022-05-14 19 03 11" src="https://user-images.githubusercontent.com/26213141/168421144-eb3d253d-843e-4b37-9084-a9ac218ccf8a.png">

2022-05-14 10:12 UTC, xiii111 commented
良さそう！複数デバイス対応は、最も普及しているデバイスで最善に見えており、後のデバイスでは画面が崩れない程度に見えているだけで十分だと思っている

2022-05-14 10:19 UTC, takasusuke commented
１枚目
このデバイスは縦長かどうかの判定。
GUIで設定した横幅(0.28f)を縦に並べ、余白も加味した結果、TreeGraphの高さを超えないかどうか確認する

２枚目
縦方向を支配的に配置する時の定数値とその意味

<img src="https://user-images.githubusercontent.com/26213141/168421598-89509351-d591-4204-9ce3-e0987257bee1.png" width="300"> <img src="https://user-images.githubusercontent.com/26213141/168421604-bde7f33f-63d4-4e73-86cb-d88ab78020ae.png" width="300">

2022-05-14 10:23 UTC, takasusuke commented
@xiii111 

> 良さそう！複数デバイス対応は、最も普及しているデバイスで最善に見えており、後のデバイスでは画面が崩れない程度に見えているだけで十分だと思っている

今までの記録画面(4つだけ木が表示されている時)は、AspectRatioFilterのAspectRatioを0.50とかに設定すれば良い感じに（雑に）高さも幅も考慮して配置できていた。

12本にして、端の調整等も行った結果、良い感じに（雑に)のクオリティでは満足いかなくなった。
iPhoneX 等では今の見た目を維持して多様デバイス対応しようとした結果、ちゃんと判定ロジックを入れることになりました。

2022-05-14 11:36 UTC, xiii111 commented
@takasusuke In Review ??

2022-05-15 00:17 UTC, takesi0627 commented
指摘が @xiii111 と被ったので任した

2022-05-15 00:35 UTC, xiii111 approved these changes
8 デバイスくらいで試しましたが、問題なく表示されていました。以下は `iPod Touch 6th Generation` です

<img width="335" alt="スクリーンショット 2022-05-15 9 32 10" src="https://user-images.githubusercontent.com/26104258/168452495-46252efd-e7b5-46ca-87f6-0a684dbd8e03.png">

`SetAspectRationFilters` なる関数は他の画面でも今後必要になるかもしれませんね ... お疲れ様です！

2022-05-15 00:38 UTC, takasusuke commented
レビュー感謝！

2022-05-15 00:38 UTC, merged