Localization 設定周りの幾つかの修正を行った
LITO-apps/Treevel-client pull request #1602
Opened 2022-05-26 13:49 UTC by xiii111

ref: #1345 

## 対象イシュー
なし

## 概要
- #1345 をやる際に気になった箇所を修正した

## 詳細
### d7e0b37f96515f467f0463e2b72247e0f5ec462c
日本語と英語の設定が両方日本語になっているものは、多言語対応できているか分からないので、英語の方に `[EN]` をつけた

### 3736128dfa6c86d84a452da8e8be91e0b452b28b
オプションのタイトル、両言語とも "Option" にする確証がないので、多言語対応しておいた

### ec3cff78c6e090192dcfbe883327eef7d0a03442
ポーズ画面のリトライと失敗画面のリトライは同じでなく分けたほうが良いと思ったので、`FailurePopupRetry` を新たに作った。また失敗画面の戻るボタンは、両言語とも "BACK" にする確証がないので、多言語対応しておいた

### 976337f76ae7462a4b6e7260064271c2a564acbf
個別記録画面周りは不要なので消しておく。個別記録の Prefab には影響出そうだが、実装し直すだろうし良いかなと

### 6325ba80291fc394eb0226f72db92065e40a8d0c & f6185f4dec2ff31459966634561246698ded6ad8
記録削除機能や、通信失敗時のリトライ機能などもリリースされないので、消しておく。必要になったら、また設定する。これによりメッセージダイアログ周りの一部の参照が使えなくなるが、メッセージダイアログは初回リリースで今の所使わない想定だし、既に表示しようとしても例外が発生しているので、諸々改良を加える前提で放置している

### a158818b8a0c055829e089cec5e2232d7dbf6915

`StageSelectScene` のオンボーディングが以下のようになっていたので、"旅に出る" ではなく "木に近づく" に修正した

<img src="https://user-images.githubusercontent.com/26104258/170500622-17898f2b-a685-4209-8496-6efe1b61e5e8.jpeg" width="300">

### 508b6c4a706a29665c279eab1496e1746ef91b93
ヒストリーのヘッダータイトルが多言語対応していなかったので、フッターのテキストを使うようにした

## レビューの観点
- 消しすぎている設定がないか
- 他にも消すべき設定がないか

## 備考

2022-05-26 13:53 UTC, xiii111 commented
@takasusuke @takesi0627 レビューお願いします！ちゃんと確認すると大変だと思いますが、よろしくお願いします

2022-05-26 23:41 UTC, takesi0627 requested changes
### `MUST`
`SpringStageSelectScene`の`UICanvas/OnBoarding`がデフォルトでアクティブになってしまっている。修正お願いします。

2022-05-27 01:17 UTC, xiii111 commented
@takesi0627 大変失礼いたしました。aea9d52 で修正しました！

2022-05-27 01:18 UTC, xiii111 commented
再レビュー依頼を投げさせてもらいました

2022-05-27 13:17 UTC, takasusuke approved these changes
良さそう

2022-05-27 14:29 UTC, takesi0627 approved these changes
LGTM

2022-05-28 23:00 UTC, xiii111 commented
レビューありがとうございました！

2022-05-28 23:00 UTC, merged