ジェスチャー用のコライダーを分離する
LITO-apps/Treevel-client pull request #1606
Opened 2022-06-03 04:05 UTC by takesi0627

## 対象イシュー
Close #1486 

## 概要
フリック感知範囲を少し広げられるように従来のコライダーとは別にジェスチャー受付用のコライダーを作成。
ついでにジェスチャーを制御クラスを分離する。

## 詳細

### プレハブの変更について

* `GestureController`を子オブジェクトに追加
![image](https://user-images.githubusercontent.com/17778395/171781402-4b8e58ce-bb0c-4a36-8cf2-d62add3152ce.png)
* 本来アタッチしていた`XXXGesture`コンポーネントを削除
* 対象プレハブ
  * `GoalBottlePrefab`
  * `DynamicDummyBottlePrefab` 
  * `AttackableDummyBottlePrefab`

### TouchLayerの設定
* `BottleGesture`レイヤーを新規追加
* `GamePlayScene/Main Camera`の`Standard Layer`の`Layer Mask`を`ErasableBottle,BottleGesture`に変更
  * `ErasableBottle`は`DynamicBottle`ではないので、`GestureController`の処理通していないため。
  * **`ErasableBottle`に`GestureController`をアタッチするのもありですが、需要あるかな？**

## レビューの観点
* 実装の方向性は適切か
* エンバグはないか
* 実装漏れはないか

## キャプチャ
| before | after |
|--------|-------|
| ![image](https://user-images.githubusercontent.com/17778395/171782854-cc567e1f-ba98-423f-a10c-4c5306fadbfc.png)| ![image](https://user-images.githubusercontent.com/17778395/171782738-cec6e1a5-0ab2-4209-87a0-3f6c167e405f.png)|

正方形のコライダーが追加されたのを確認できる。

## 動作確認方法
- [ ] 任意のステージにて薬ボトルのフリックの動作確認。
- [ ] `Winter-1-1`にて爆薬ボトルと鋼ボトルのフリック動作確認。
- [ ] `GhostBottleAttribute`の長押し動作確認
- [ ] `DarkAttribute`の長押し動作確認

## 備考

2022-06-03 04:05 UTC, takesi0627 commented
@takasusuke 
@xiii111 

レビューよろしくお願いします。
できれば動作確認を重めにお願いします。

2022-06-04 06:14 UTC, takasusuke requested changes
1点対応お願いいたします。
基本的なゲームプレイで問題ないと思います！！👍

## MUST
`GamePlayTutorialDirector`で`blueBottle.GetComponent<TransformGesture>()`を参照している箇所があるので以下のエラーが出ます。
```
NullReferenceException: Object reference not set to an instance of an object
Treevel.Modules.GamePlayScene.GamePlayTutorialDirector.AsyncDoTutorial () (at Assets/Project/Scripts/Modules/GamePlayScene/GamePlayTutorialDirector.cs:100)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].GetResult (System.Int16 token) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/CompilerServices/StateMachineRunner.cs:218)
Cysharp.Threading.Tasks.UniTaskExtensions+<>c.<Forget>b__16_0 (System.Object state) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTaskExtensions.cs:572)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTaskScheduler.cs:90)
Cysharp.Threading.Tasks.<>c:<Forget>b__16_0(Object) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTaskExtensions.cs:576)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetException(Exception) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTaskCompletionSource.cs:167)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:SetException(Exception) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/CompilerServices/StateMachineRunner.cs:210)
Treevel.Modules.GamePlayScene.<AsyncDoTutorial>d__5:MoveNext() (at Assets/Project/Scripts/Modules/GamePlayScene/GamePlayTutorialDirector.cs:175)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:Run() (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/CompilerServices/StateMachineRunner.cs:189)
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTask.cs:21)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(AsyncUnit) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:SetResult() (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/CompilerServices/StateMachineRunner.cs:204)
Treevel.Modules.GamePlayScene.<CreateDummyBottle>d__7:MoveNext() (at Assets/Project/Scripts/Modules/GamePlayScene/GamePlayTutorialDirector.cs:208)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:Run() (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/CompilerServices/StateMachineRunner.cs:189)
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTask.cs:21)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(AsyncUnit) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.WhenAllPromise:TryInvokeContinuation(WhenAllPromise, Awaiter&) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTask.WhenAll.cs:210)
Cysharp.Threading.Tasks.<>c:<.ctor>b__3_0(Object) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTask.WhenAll.cs:189)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(AsyncUnit) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:SetResult() (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/CompilerServices/StateMachineRunner.cs:204)
Cysharp.Threading.Tasks.<ContinueWith>d__23`1:MoveNext() (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTaskExtensions.cs:698)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:Run() (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/CompilerServices/StateMachineRunner.cs:189)
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTask.cs:21)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(GameObject) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.AsyncOperationHandleConfiguredSource`1:Continuation(AsyncOperationHandle`1) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/External/Addressables/AddressablesAsyncExtensions.cs:333)
DelegateList`1:Invoke(AsyncOperationHandle`1) (at Library/PackageCache/com.unity.addressables@1.19.17/Runtime/ResourceManager/Util/DelegateList.cs:69)
UnityEngine.ResourceManagement.AsyncOperations.<>c__DisplayClass57_0:<add_CompletedTypeless>b__0(AsyncOperationHandle`1)
DelegateList`1:Invoke(AsyncOperationHandle`1) (at Library/PackageCache/com.unity.addressables@1.19.17/Runtime/ResourceManager/Util/DelegateList.cs:69)
UnityEngine.ResourceManagement.Util.DelayedActionManager:LateUpdate() (at Library/PackageCache/com.unity.addressables@1.19.17/Runtime/ResourceManager/Util/DelayedActionManager.cs:159)
```

2022-06-04 09:42 UTC, xiii111 reviewed
一通り動作を確認しましたが、既存の指摘点以外は問題ありませんでした！！

2022-06-04 09:42 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/BottleGestureController.cs
> +        public LongPressGesture LongPressGesture { get; private set; }
## Ask

これって `private set;` いる？

2022-06-04 09:42 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +            _gestureController.SetColliderSize(bottleHeight, bottleHeight);
なるほどー。タイルは正方形で、ボトルは高さの方が大きい長方形だから、高さと同じ値だけ幅を確保した `Collider` にしたってことね

<img width="592" alt="スクリーンショット 2022-06-04 18 24 46" src="https://user-images.githubusercontent.com/26104258/171993463-0071e65f-a769-47fd-b070-30258874f532.png">

2022-06-04 17:28 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/BottleGestureController.cs
> +        public LongPressGesture LongPressGesture { get; private set; }
消してみたらこれが出たので要りますね
![image](https://user-images.githubusercontent.com/17778395/172018592-bbe6e572-17b0-4f5c-9fec-bea36cf716e7.png)

2022-06-04 17:28 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +            _gestureController.SetColliderSize(bottleHeight, bottleHeight);
その通りっす

2022-06-04 17:29 UTC, takesi0627 commented
@takasusuke 
指摘していただいた不具合修正しました。
ご確認よろしくお願いします

2022-06-04 23:06 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/BottleGestureController.cs
> +        public LongPressGesture LongPressGesture { get; private set; }
あーー 読み取り専用になっちゃうのか、初期化の段階で代入しているかと思っていたが、Unity は `Start` とか `Awake` とかだった 💡

2022-06-04 23:07 UTC, xiii111 approved these changes
LGTM!!

2022-06-05 01:10 UTC, takasusuke approved these changes
最高

2022-06-05 01:11 UTC, merged