蜘蛛の巣には一つの画像のみを用いるようにする
LITO-apps/Treevel-client pull request #1644
Opened 2022-06-10 14:15 UTC by xiii111

## 対象イシュー
Close #1598

## 概要
- 現行では角などを考慮して画像を出し分けていたが、解像度が悪かったことと、これから新たなデザインをもらうことは困難なことから、蜘蛛の巣には一つの画像のみを用いるようにする。なお、ボトルの上に蜘蛛の巣が展開されたときに画像は、通常時の画像とは分かれている

## 詳細
- 不要な 4 つの画像を削除した
- タイル番号によって、画像を出し分けていた処理を削除した
- 定数宣言なども上記に合わせて、消したり整理したりした

## レビューの観点
- 消し損ねがないか
- 妥当な削除になっていない箇所はないか

## キャプチャ
| before | after |
|--------|-------|
| <img width="380" alt="スクリーンショット 2022-06-10 22 44 22" src="https://user-images.githubusercontent.com/26104258/173084503-ee9c0acb-2d03-4139-b3d5-bf633a94f8e5.png"> | <img width="379" alt="スクリーンショット 2022-06-10 23 01 37" src="https://user-images.githubusercontent.com/26104258/173084530-c128306a-882f-4b31-a2e7-89d121588826.png"> |

https://user-images.githubusercontent.com/26104258/173084804-e8abf4ca-8590-4d22-8159-efb3f0a74b88.mov

## 動作確認方法
- [ ] `Winter-1-3` をプレイする

## 備考

2022-06-10 14:18 UTC, xiii111 commented
@LITO-apps/engineer レビューお願いします

2022-06-10 14:46 UTC, takesi0627 requested changes
## `MUST`
`Default Local Group.asset`(AASのアセット)に変更があるはずなのでそれもコミットしてください。

2022-06-10 14:46 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/Constants.cs
> +            public const string SPIDERWEB_TILE_ON_BOTTLE_SPRITE = "SpiderwebTile_on_bottle";
### `IMO`
今更だけど、なんか `OVER_BOTTLE`の方が意味あってそう

2022-06-10 23:52 UTC, xiii111 commented
@takesi0627 

> ## `MUST`
> `Default Local Group.asset`(AASのアセット)に変更があるはずなのでそれもコミットしてください。

de4d31d で修正しました

2022-06-10 23:53 UTC, xiii111 commented on Assets/Project/Scripts/Common/Utils/Constants.cs
> +            public const string SPIDERWEB_TILE_ON_BOTTLE_SPRITE = "SpiderwebTile_on_bottle";
こだわりがなかったので e6ce33f で修正しておきました

2022-06-10 23:53 UTC, xiii111 commented
@takesi0627 再レビュー依頼を投げました

@takasusuke 一応見てほしいので、レビュー依頼を投げました

2022-06-10 23:57 UTC, takesi0627 approved these changes
LGTM w/ nits.

### `nits`
どうせ変更するなら、命名規則に直してもらえると助かります
`spiderwebTile_ovevr_bottle.png` → `SpiderwebTileOverBottle.png`

2022-06-11 00:45 UTC, xiii111 commented
> ### `nits`
> どうせ変更するなら、命名規則に直してもらえると助かります `spiderwebTile_ovevr_bottle.png` → `SpiderwebTileOverBottle.png`

e1c6850 で修正しました

2022-06-11 13:58 UTC, takesi0627 approved these changes
LGTM

2022-06-12 11:23 UTC, takasusuke commented
レビューお任せしています。

2022-06-12 11:33 UTC, xiii111 commented
> @takasusuke 一応見てほしいので、レビュー依頼を投げました

あ、一応レビューして欲しかった感じです

2022-06-12 11:36 UTC, takasusuke approved these changes
メンションの方は見てなかった。
軽くは見ていましたが、特にコメントはなく素晴らしいです。

2022-06-12 11:36 UTC, xiii111 commented
ありがとうございます！

2022-06-12 11:36 UTC, merged