UIParticleが実機でも描画されるようにする
LITO-apps/Treevel-client pull request #1650
Opened 2022-06-18 04:38 UTC by takasusuke

## 対象イシュー
Close #1594
Close #1648

## 概要
Canvasが`Screen Space - Overlay`ではshader(やmaterial)を使った表現が実機では行われないみたいなので、TapEffectを`Screen Space - Camera`のCanvasを使って描画。

`Screen Space - Overlay`のCanvasがあるとTapEffectが最前面に描画されないので、全てのCanvasを`Sreen Space - Overlay`から`Screen Space - Camera`に変更

## 詳細
49bbf718a2678c113e81e15d1bb8f0d4bd27bda4 : UIParticle componentをparticleに付与。(なくても良かった..?)
1b415bd947e17fe5c1993ac304d17d57b2983eef : デフォルトのMaterialではなくTapEffect用のMaterialを用意(特にデフォルトから設定を変えたかったわけではない)
5791dea15a260c92edcdae85244f4859913dc32c : TapEffectのパラメータ調整
6f98500e4ee4ffe7d82ffb58af362880c0d529cd : TapEffect専用のCameraを用意して、それに描画するように変更
406893446752a64114db08d6a8ab4c5d5be58331 : 全てのCanvasの設定を`Screen Space - Camera`に設定
69ee8d03b6a6c6457c6ba761515a2eccc13f3484 : Canvas設定が変わったのでCoachMarkの位置の指定方法を修正
dc7c7cccb9cfca4c1c50a694ef26b5358ba39735 : (#1648)のやつ。エラー画面でも同様にTapEffectが描画されない問題があったので気になって直した.
e59892bb02bb0f0b76ff99480a28117c443e2ac7 : Canvas設定を全てCamera描画に変更したことで、成功画面などで、Maskの後ろで光っているBottleのSpriteGlowが変に描画されてしまう。（前はこれを回避するために成功画面のCanvasを`Screen Space - Overlay`にしていた。）Maskの特定のオブジェクトが描画されるときにScene内のSpriteGlowを描画しないようにした。
99b1290b4d9ffc86fe7cfa4b4c54b11395ecbd5a : 成功画面のParticleのリソースの解像度を下げすぎて粗くなっていたので修正
62e3c1d9cb41b1904142378f36ba568e9c2557d7 : LevelSelectのOnBoarding、Footerの描画順序を修正
cbd288ce403ed3abc04316508a1fa171977e3375 : 成功画面のParticleの位置修正がてら、prefabになってなかった成功画面のコンポーネントをprefab化

## レビューの観点
- 実機での動作確認
- 描画順序の動作確認

## キャプチャ
| before | after |
|--------|-------|
| XXXXXX | XXXXX |

## 動作確認方法
- [ ] 

## 備考

2022-06-18 04:50 UTC, takasusuke commented
@xiii111 @takesi0627 
レビューよろしくお願いいたします。

わかりにくい箇所は質問してください。
（Canvas変えまくって、設定(`.unity`周りの修正など)の変更が多いので、もう何を説明すべきかわからんくなった...）

2022-06-18 14:35 UTC, xiii111 commented
@takasusuke cc @takesi0627 

## Ask

`develop` / 53d9dae33 から `bug/1594-ui-particle` にチェックアウトして、Unity でビルドするとクラッシュするのですが（4 回くらい試した）、そちらの環境では再現しますか？

また、クラッシュした後に再度 Unity のビルドをしてみると成功しますが、以下のように `TapGesture` が表示されません。何か分かったら、教えてほしいです

### develop / 53d9dae33
https://user-images.githubusercontent.com/26104258/174443151-d5393e4b-43cb-4ac9-be53-18e17f683ae1.mov

### bug/1594-ui-particle
https://user-images.githubusercontent.com/26104258/174443183-d8486a3f-055e-4932-94c4-dcb68f2e82a4.mov

2022-06-18 15:20 UTC, takesi0627 requested changes
実機で確認できました。
問題なく描画されましたが、いくつか気づいたことをご報告します。

### タップエフェクトの色が背景に影響されることがある
動画にあるように、背景の色が明るい時にタップエフェクトの色も明るくなり白飛びする。
`develop`で確認したが、背景の色に影響されていなさそうでした。
これは想定した挙動でしょうか

<video src="https://user-images.githubusercontent.com/17778395/174444584-7ce17efb-83c7-4218-9040-e542c2e4951f.mov">


### 2点以上のドラッグの場合パーティクルの更新できていない
これは前からだったと思いますが、
実装見る限り、指２本でドラッグする場合タップエフェクトの軌跡も２本になるはずが、
２本目の軌跡の更新ができていなさそうです。
でもこれは今回の修正で発生した問題ではないので対応しなくても良いです。


<video src="https://user-images.githubusercontent.com/17778395/174444953-019e0ae1-d2a7-4f54-af00-06ab347ce35a.mov">


### `MUST`
エディターでタップエフェクトが描画されなくなりました。
`#if !UNITY_EDITOR`で括ったのは良くなかったみたいですので対応をお願いします。

2022-06-18 15:24 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/TapObjectGenerator.cs
>                              _particleSystem.Play();
ここの計算並列にできそうだな

2022-06-18 22:18 UTC, takasusuke commented
> ## Ask
> `develop` / [53d9dae](https://github.com/LITO-apps/Treevel-client/commit/53d9dae3338b3692ea54c908a12c249a38037d1c) から `bug/1594-ui-particle` にチェックアウトして、Unity でビルドするとクラッシュするのですが（4 回くらい試した）、そちらの環境では再現しますか？

再現した。
1. develop にchekcout
2. Unity起動
3. 当該branch にcheckout
4. build → crash

一度crachした後は特に当該branchでUnity起動し直せばcrashは起きなかった。

ちょくちょくある問題??(Canvas設定結構変えたから..?)
参考：https://forum.unity.com/threads/cannot-open-project-on-2021-2-0f1-apple-silicon-editor-m1.1188772/

2022-06-18 22:19 UTC, takasusuke commented
> `TapGesture` が表示されません。何か分かったら、教えてほしいです

> エディターでタップエフェクトが描画されなくなりました。
#if !UNITY_EDITORで括ったのは良くなかったみたいですので対応をお願いします。

Simulatorで動作確認するの忘れてた。
[0811ea1](https://github.com/LITO-apps/Treevel-client/pull/1650/commits/0811ea107b817671454726a640e072484053a7c5)

2022-06-18 22:20 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/UIs/TapObjectGenerator.cs
>              #if UNITY_EDITOR
[0811ea1](https://github.com/LITO-apps/Treevel-client/pull/1650/commits/0811ea107b817671454726a640e072484053a7c5)

で追加した条件分岐を消しました。

2022-06-18 22:23 UTC, takasusuke commented on ProjectSettings/TagManager.asset
> +  - UIParticle
- `TapObjectCanvas/ParticleSystem.Layer`
- `TapEffectCamera.CullingMask`

で使用しています。

TapEffectCameraにはTapEffect以外を描画しないようにしている。

2022-06-18 22:28 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +        [SerializeField] private GameObject _successPanel;
[75d0382](https://github.com/LITO-apps/Treevel-client/pull/1650/commits/75d038273ff89cb88041dc549c10b5171f643add)
コメントを修正しました。

Scene上のレイヤーは
```
Canvas
  - SuccessPanel
    - SuccessPopup
```
になってる。`SuccessPanel`をPrefabにする過程で、このSeralizeFieldが外れた。`_successPopup`という変数に`SuccessPopup`を設定したら動かなかった。`SuccessPanel`を設定しないといけない。
`_failurePopup`という変数は`FailurePopup`を設定するのに...

どうやら`Panel`と`Popup`を使い分けてるようでした...

2022-06-18 22:48 UTC, takasusuke commented
> ### タップエフェクトの色が背景に影響されることがある
> 動画にあるように、背景の色が明るい時にタップエフェクトの色も明るくなり白飛びする。 `develop`で確認したが、背景の色に影響されていなさそうでした。 これは想定した挙動でしょうか

TapEffect専用のMaterialを作成したときに、前の設定を再現できてなかった。修正。
（大きさも若干修正）
[d43d4c0](https://github.com/LITO-apps/Treevel-client/pull/1650/commits/d43d4c08616802cf0f236de6d3fe0b81e129a7d4)

2022-06-18 23:06 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/UIs/TapObjectGenerator.cs
>                              _particleSystem.Play();
> ### 2点以上のドラッグの場合パーティクルの更新できていない
> これは前からだったと思いますが、 実装見る限り、指２本でドラッグする場合タップエフェクトの軌跡も２本になるはずが、 ２本目の軌跡の更新ができていなさそうです。 でもこれは今回の修正で発生した問題ではないので対応しなくても良いです。

これに関連するんだけれど、複数Tap状態でどちらか離すと、もう片方も描画されなくなるかと思われます。
↑の問題もそうだけど、
別のissueでも良い？

2022-06-19 00:32 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/TapObjectGenerator.cs
>                              _particleSystem.Play();
良い

2022-06-19 00:37 UTC, xiii111 commented
> 再現した。
> 
> 1. develop にchekcout
> 2. Unity起動
> 3. 当該branch にcheckout
> 4. build → crash
> 
> 一度crachした後は特に当該branchでUnity起動し直せばcrashは起きなかった。
> 
> ちょくちょくある問題??(Canvas設定結構変えたから..?) 参考：https://forum.unity.com/threads/cannot-open-project-on-2021-2-0f1-apple-silicon-editor-m1.1188772/

同様の挙動ですね。ちょくちょくある問題 & これをマージすれば問題なくなりそうなので、一旦許容しますね

2022-06-19 00:43 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/StartUpScene/StartUpDirector.cs
> +            var particleCamera = GameObject.Find("TapEffectCamera").GetComponent<Camera>();
これは対応しませんか？

2022-06-19 00:44 UTC, takasusuke commented on Assets/Project/Scripts/Modules/StartUpScene/StartUpDirector.cs
> +            var particleCamera = GameObject.Find("TapEffectCamera").GetComponent<Camera>();
漏れてた
する

2022-06-19 00:48 UTC, takesi0627 approved these changes
修正対応ありがとうございます。

### `IMO`
修正後のタップエフェクトの色が若干濃く(or暗く)なったが、
もし前の状態に戻せるなら戻して欲しいです。

https://github.com/LITO-apps/Treevel-client/pull/1650/files#r900946776
これのイシューの作成もお願いします

2022-06-19 00:51 UTC, xiii111 approved these changes
動作問題なさそうでした！紙吹雪も飛ぶようになっていました🎉

2022-06-19 00:51 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/UIs/AntiSpriteGlow.cs
> +    public class AntiSpriteGlow : MonoBehaviour
こいつは https://github.com/LITO-apps/Treevel-client/issues/1497#issuecomment-1142212227 の `SpriteGlow がずれたり、透けたり` に使えそうかなと思ったけど、これを使うと概要ポップアップの最上部のアイコンが光らないなーとかも思った ...

2022-06-19 01:00 UTC, takasusuke commented on Assets/Project/Scripts/Modules/StartUpScene/StartUpDirector.cs
> +            var particleCamera = GameObject.Find("TapEffectCamera").GetComponent<Camera>();
[c4fe8ec](https://github.com/LITO-apps/Treevel-client/pull/1650/commits/c4fe8ecb0964675cc13a54a92d938c34291715cd)

2022-06-20 13:49 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/UIs/TapObjectGenerator.cs
>                              _particleSystem.Play();
issue作った
https://github.com/LITO-apps/Treevel-client/issues/1652

2022-06-20 13:49 UTC, takasusuke commented
@takesi0627 
ヨロです

2022-06-20 14:28 UTC, takesi0627 approved these changes
おつです

2022-06-20 14:48 UTC, takasusuke commented
っした！

2022-06-20 14:49 UTC, merged