確定した日本語文言を適用する
LITO-apps/Treevel-client pull request #1651
Opened 2022-06-19 00:08 UTC by xiii111

## 対象イシュー
Close #1345 

## 概要
- 確定した [Spread Sheet](https://docs.google.com/spreadsheets/d/1x68F67vbgdzW_50WbiLwWfFD53pWxVqExKBkUuem9hg/edit#gid=0) を元に、日本語文言を適用した
- 英語に関しては、ノータッチ。後続のイシューで対応する

## レビューの観点
- Spread Sheet に記載の通りの文言になっているか（自分でも確認したが、量が多かったので少し心配）

## キャプチャ
×

## 動作確認方法
- [ ] `Assets/Project/GameDatas/StringTables/*` にあるファイルを見て、想定通りの日本語文言になっていること

## 備考
×

2022-06-19 00:09 UTC, xiii111 commented
@LITO-apps/engineer レビューお願いします！結構時間かかると思います

2022-06-20 14:04 UTC, takasusuke requested changes
お疲れーー。2点ーー。
- メテオの説明がしつこいメテオの説明になっている。
- しつこいメテオの説明が変わっていない。

2022-06-21 10:21 UTC, xiii111 commented
大変失礼いたしました。修正しました

2022-06-21 10:21 UTC, xiii111 commented
@takasusuke 再レビューお願いします

2022-06-22 00:03 UTC, xiii111 commented
レビューありがとうございました！

2022-06-22 00:03 UTC, merged