総合記録画面を実装する
LITO-apps/Treevel-client pull request #529
Opened 2020-08-26 11:55 UTC by xiii111

### 対象イシュー
Close #495 

### 概要

### 詳細

#### 現実装になった経緯

#### 技術的な内容

### キャプチャ

### 動作確認方法

2020-08-26 11:57 UTC, xiii111 commented
### ここまでの見た目

<img src="https://user-images.githubusercontent.com/26104258/91300672-a1b57080-e7de-11ea-8274-e895a96e99d1.png" width="200">

2020-08-29 13:25 UTC, xiii111 commented
### 92402ab の変更による見た目

![スクリーンショット 2020-08-29 22 18 29](https://user-images.githubusercontent.com/26104258/91637879-8056bd80-ea46-11ea-8969-6c0b9129fb56.png)

2020-08-29 13:35 UTC, xiii111 commented
残タスクメモ
- `ステージクリア数` のゲージ
- `失敗回数` のグラフ
- `Share ボタン` の角を丸くする
- 色・配置の微調整

2020-08-30 00:38 UTC, xiii111 commented
- [x] `Share ボタン` の角を丸くする

![スクリーンショット 2020-08-30 9 35 57](https://user-images.githubusercontent.com/26104258/91648613-71065d00-eaa4-11ea-9192-b20aeb691e6d.png)

2020-09-01 13:14 UTC, xiii111 commented
- [x] `ステージクリア数` のゲージ

![スクリーンショット 2020-09-01 22 12 24](https://user-images.githubusercontent.com/26104258/91855660-6d3f2a00-eca0-11ea-8aa4-5a4c3046bbc1.png)

2020-09-01 13:25 UTC, xiii111 commented
#### f7a6b3f の変更
- 赤線で囲んだ部分の線を消した

![スクリーンショット 2020-09-01 22 12 24](https://user-images.githubusercontent.com/26104258/91856727-ea1ed380-eca1-11ea-8987-1f5cb0301563.png)

2020-09-01 15:00 UTC, xiii111 commented
#### 2ace966 の変更
- [x] `ステージクリア数` のゲージの先端

![スクリーンショット 2020-09-01 23 58 43](https://user-images.githubusercontent.com/26104258/91868012-3d4b5300-ecaf-11ea-9d38-7a9e92b17ec7.png)

2020-09-05 15:16 UTC, xiii111 commented
#### efb2d49 の変更
- [x] `失敗回数` のグラフ

![スクリーンショット 2020-09-06 0 05 24](https://user-images.githubusercontent.com/26104258/92308082-26ba3a00-efd6-11ea-9432-74ff2519e6fb.png)

2020-09-06 01:56 UTC, xiii111 commented
本イシューでやること
- [ ] Others はその他として表示．x % を下回っている失敗原因もその他に含める
- [ ] 円グラフの要素にアイコンを付与する
- [ ] 見た目の調整（色，配置・・・）

今後の課題にすること
- [ ] アニメーション
- [ ] グラフの要素タップ時に情報を示す

2020-09-06 04:45 UTC, xiii111 commented
#### f01b251
- [x] Others はその他として表示．x % を下回っている失敗原因もその他に含める（x = 10% ?)

2020-09-11 00:09 UTC, xiii111 commented
[v] 円グラフの要素にアイコンを付与する（アイコンは同じ大きさ）
- e591209 : アイコン画像と Prefab の追加
- 2c3a40f : Prefab をスクリプトにアタッチ
- 3aa12fc : リファクタリング
- 0d06e4d : リファクタリング
- eebcf20 : icon を適切な位置に配置（メイン）

2020-09-11 00:47 UTC, xiii111 commented
- [x] Base Text, Base Multi Text を使う
- [x] マルチ言語対応

|||
|---|---|
|![スクリーンショット 2020-09-11 9 44 06](https://user-images.githubusercontent.com/26104258/92833318-af403c80-f413-11ea-85c6-67e8318a092d.png)|![スクリーンショット 2020-09-11 9 44 19](https://user-images.githubusercontent.com/26104258/92833326-b10a0000-f413-11ea-9a38-167851d7b1b4.png)|

2020-09-11 00:49 UTC, xiii111 commented
@takasusuke @takesi0627 レビューお願いします

- [ ] 見た目の調整（色，配置・・・）

ですが，アイコンも完成してないですし，どんな配色にするかは追々変えていくでも良いかなと思いました．今回の PR でこの見た目だけは確定だし変えておいてってことがあったら言ってください

2020-09-11 07:54 UTC, takasusuke requested changes
お疲れ様でございます。
こりゃあ大変ですわ。。。

- RectTransformの値でCanvasの大きさに対する比で調整しているobjectは全てAspectRatioFilter無しで良いと思う。
RectTransformの調整を無視して、サイズ調整が入るので、灰色の背景枠を飛び出る(極端な比のデバイスで顕著)
- `hogeScene`に対応して`hogeDirector`がいるから`GeneralRecordDirector`ではなく`RecordManager`とか記録そのものの数値を編集するのではなく描画を担当するから、`RecordDrawer`とかの方がしっくりくる。
- [memo] 失敗回数==0の時は、`FailureReasonGraphBackground`に、"記録がありません"的なの表示した方が良さそう。

2020-09-11 07:54 UTC, takasusuke commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            float sum = RecordData.Instance.FailureReasonCount
```suggestion
            float sum = RecordData.Instance.FailureReasonCount.Sum(e => e.Value);
```
LinQで手に入るの(Key, Value)のペアらしいからdic(tionary)と名付けるのは違和感。
elementとか

2020-09-11 07:54 UTC, takasusuke commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            foreach (var dic in RecordData.Instance.FailureReasonCount) {
```suggestion
            foreach (var e in RecordData.Instance.FailureReasonCount) {
```
element
failureReasonCount
count
とか

2020-09-11 07:54 UTC, takasusuke commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            CreateFailureReasonGraphElement(EFailureReasonType.Others, startPoint, 1 - startPoint);
`EFailureReasonType.Others`の割合が0の時は描画しない

2020-09-11 07:54 UTC, takasusuke commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            // 暫定的にランダムな色を適用
```suggestion
            // 色の指定
            // FIXME : 色は暫定的
```

2020-09-11 12:36 UTC, takasusuke commented
ThirdPartyの、四角の角を丸くするやつの数字(80)とか、画面の縦横比を考慮して動的に変更できた方が良さそう。

2020-09-11 14:38 UTC, takesi0627 reviewed
プレハブってそんなに用意する必要ありますか？
一つ用意して画像だけ切り替えれば良いかと思いますけど・・じゃないとギミック作る度にプレハブを作らないといけないのはだるい

2020-09-11 14:38 UTC, takesi0627 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            }
不整合性が生じうるから `GameDataBase` からデータをとって欲しい。

```csharp
// GameDataBase.cs:
public static StageData[] GetAllStages()
{
   return _stageDataMap.Values.ToArray();
}

// GeneralRecordDirector.cs
_satageStatuses = GameDataBase.GetAllStages().Select(stage => StageStatus.Get(stage.TreeId, stage.StageNumber)).ToList();
```

2020-09-11 14:38 UTC, takesi0627 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            _shareButton.onClick.AddListener(ShareGeneralRecord);
```suggestion
            _shareButton.onClick.AddListener(() => Application.OpenURL("https://twitter.com/intent/tweet?hashtags=Treevel"));
```
これでいい気がするんだよね

2020-09-12 04:28 UTC, xiii111 commented
> * RectTransformの値でCanvasの大きさに対する比で調整しているobjectは全てAspectRatioFilter無しで良いと思う。

俺が誤解しているかもしれないけど， `Aspect Ratio Filter` って `canvas` の大きさに対する比ではなくて，`Aspect Ratio Filter` をアタッチしているオブジェクト自体がどのような比率の大きさで配置されるかを指定しているのではない？

>   RectTransformの調整を無視して、サイズ調整が入るので、灰色の背景枠を飛び出る(極端な比のデバイスで顕著)

ごめん，横長のデバイスでひどいことになってるね．iPad 対応はやるなら別途やることにしたいかな（位置調整のキリがないので）とりあえず iPhone X のアスペクト比で正常に表示されるようにしたつもり

> * `hogeScene`に対応して`hogeDirector`がいるから`GeneralRecordDirector`ではなく`RecordManager`とか記録そのものの数値を編集するのではなく描画を担当するから、`RecordDrawer`とかの方がしっくりくる。

ごめんなさい誤解を与える表現でした． `General` というのは一般記録画面の "一般" を取っているものです

> * [memo] 失敗回数==0の時は、`FailureReasonGraphBackground`に、"記録がありません"的なの表示した方が良さそう。

その通りだな．修正します

2020-09-12 04:34 UTC, xiii111 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            _shareButton.onClick.AddListener(ShareGeneralRecord);
今後，Twitter に画像を共有するとかの追加変更が増える可能性があるから関数にしておきたかった．現状ならそれで十分だと思うけど，今後修正が見込まれるからこのままが良いかな

2020-09-12 04:40 UTC, xiii111 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            }
なるほど？とりあえず直す

2020-09-12 04:47 UTC, xiii111 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            }
fc0caab 記録画面の結果が変わったけど， `Addressable` でロードできたゲームだけを対象にしているからであってるかな？

2020-09-12 04:51 UTC, xiii111 commented
> プレハブってそんなに用意する必要ありますか？
> 一つ用意して画像だけ切り替えれば良いかと思いますけど・・じゃないとギミック作る度にプレハブを作らないといけないのはだるい

画像を prefab にコードからアタッチする時って Addressable 関連でやった方がいい？

2020-09-12 04:54 UTC, xiii111 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +        [SerializeField] private GameObject _recordDirectorGameObject;
👍👍👍
5063975

2020-09-12 04:56 UTC, takesi0627 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            }
その通りです。
@takasusuke TreeInfoは確かに一時的な案であって、将来的に実際のデータと整合性をとれる実装にすべきという設定じゃなかったっけ

2020-09-12 04:57 UTC, takesi0627 commented
> > プレハブってそんなに用意する必要ありますか？
> > 一つ用意して画像だけ切り替えれば良いかと思いますけど・・じゃないとギミック作る度にプレハブを作らないといけないのはだるい
> 
> 画像を prefab にコードからアタッチする時って Addressable 関連でやった方がいい？

そうですね、できればそうしてほしい

2020-09-12 05:00 UTC, xiii111 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            _failureNum.text = GetFailureNum();
> > > プレハブってそんなに用意する必要ありますか？
> > > 一つ用意して画像だけ切り替えれば良いかと思いますけど・・じゃないとギミック作る度にプレハブを作らないといけないのはだるい
> > 
> > 
> > 画像を prefab にコードからアタッチする時って Addressable 関連でやった方がいい？
> 
> そうですね、できればそうしてほしい

お手数だけど，どこのコード参考にするとかある？ Addressable においた画像をコードから読み込む例って今まである？（パッと見つけられなかった）

2020-09-12 05:01 UTC, xiii111 commented
@takesi0627 

> > > プレハブってそんなに用意する必要ありますか？
> > > 一つ用意して画像だけ切り替えれば良いかと思いますけど・・じゃないとギミック作る度にプレハブを作らないといけないのはだるい
> > 
> > 
> > 画像を prefab にコードからアタッチする時って Addressable 関連でやった方がいい？
> 
> そうですね、できればそうしてほしい

お手数だけど，どこのコード参考にするとかある？ Addressable においた画像をコードから読み込む例って今まである？（パッと見つけられなかった）

2020-09-12 11:46 UTC, xiii111 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            CreateFailureReasonGraphElement(EFailureReasonType.Others, startPoint, 1 - startPoint);
`EFailureReasonType.Others` が 0 でも，10% 未満のものを含める場合があるので，それも考慮して実装しました
- 8aa221f

2020-09-12 11:52 UTC, xiii111 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            // 暫定的にランダムな色を適用
6378bad

2020-09-12 11:52 UTC, xiii111 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            foreach (var dic in RecordData.Instance.FailureReasonCount) {
一応型としては `KeyValuePair` って型みたいなので， `pair` にしました．
- 6378bad

2020-09-12 11:53 UTC, xiii111 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            float sum = RecordData.Instance.FailureReasonCount
この書き方できたのか．学び！
- 6378bad

2020-09-12 11:53 UTC, xiii111 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            var clearStageNum = _stageStatuses.Select(stageStatuses => stageStatuses.successNum > 0 ? 1 : 0).Sum();
6378bad

2020-09-12 11:54 UTC, xiii111 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            _failureNum.text = GetFailureNum();
> 後、記録画面開くたびに、グラフの要素がInstantiateされて増えるので、 `OnDisable()` で適宜消す必要あり。

これ，増え続けなかったんだけど，遷移経路間違ってたかな？

2020-09-12 12:52 UTC, xiii111 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            _failureNum.text = GetFailureNum();
増え続けるのは `OnEnable()` に寄せた未来の話でした

2020-09-12 12:53 UTC, takasusuke commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            }
その予定です

2020-09-14 06:57 UTC, takasusuke commented
> > * RectTransformの値でCanvasの大きさに対する比で調整しているobjectは全てAspectRatioFilter無しで良いと思う。
> 
> 俺が誤解しているかもしれないけど， `Aspect Ratio Filter` って `canvas` の大きさに対する比ではなくて，`Aspect Ratio Filter` をアタッチしているオブジェクト自体がどのような比率の大きさで配置されるかを指定しているよね？
> 

`Aspect Ratio Filter`の認識はそうだと思います。

2020-09-14 07:06 UTC, takasusuke commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +                .First();
`Others`の失敗が存在しない時、`Where`に該当する要素がないので`Select`のとこでエラー出ます。
<img width="1132" alt="スクリーンショット 2020-09-14 16 05 42" src="https://user-images.githubusercontent.com/26213141/93054359-2ab81d00-f6a4-11ea-949e-130b0564f320.png">

2020-09-14 11:06 UTC, xiii111 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            }
👍

2020-09-14 11:08 UTC, xiii111 commented
残タスク
- [ ] `失敗回数==0` の時に，その旨を表示
- [ ] https://github.com/LITO-apps/Treevel-client/pull/529#discussion_r487693778
- [ ] プレハブを減らす
- [ ] https://github.com/LITO-apps/Treevel-client/pull/529#discussion_r486808967
- [ ] https://github.com/LITO-apps/Treevel-client/pull/529#discussion_r486801479

2020-09-14 12:21 UTC, xiii111 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +                .First();
色々 Linq のオペレータとか調べてたけど，そもそも Key がないことが問題だと気づき，デフォルト値を設けることにした
- a5234ba

2020-09-14 13:19 UTC, xiii111 commented
一つの原因しかなかった場合にアイコンを中央に配置するようにした
- 3ea073d

2020-09-16 23:33 UTC, xiii111 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            // FIXME: 0.95 はゲージの太さを考慮するための Magic Number です
ゲージの縦の表示領域（灰色帯）のうち 0.1 ~ 0.9 の範囲を直径と決めて配置すれば，縦長の端末に関しては，正円のまま問題なく表示できた．楕円になることはない．
- 2a84b5c

2020-09-16 23:46 UTC, xiii111 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            _failureNum.text = GetFailureNum();
5e4d31a

2020-09-17 11:56 UTC, xiii111 commented
@takasusuke @takesi0627 再レビューお願いします

2020-09-20 13:06 UTC, takasusuke requested changes

2020-09-20 13:06 UTC, takasusuke commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            var radius = _clearStageGauge.GetComponent<RectTransform>().rect.width / 2;
比の異なるデバイスでの見た目を確認しました。
`indicator`の位置がズレます。

なんか`radius`の値が欲しい値より小さい(?)感じがする。（原因わからなかった)
`localPosition`で設定するのではなく、
例えば、クリアステージ数0の時、`indicator`の`anchor`が`(xMin, yMin, xMax, yMax) = (0.50-0.10 ,0.50+0.10, 0.95-0.10, 0.95+0.10)`となるように計算して設定すればどんなデバイスでもズレない気がした。
(`anchor`いじると`indicator`の`RectTransform`の`left, right, up, bottom`が`0`じゃない値になるかもだから`0`にするとか)

2020-09-20 13:11 UTC, takasusuke commented
ギミック増やす時、
- 失敗回数の`Dictionary`のデフォルト値に追加
- アイコン`sprite`をアタッチ

もする必要ありか。
新しい機能実装の時に追加記述する場所追えなくなってきた。
良い方法ないかなあ。。。

2020-09-23 12:13 UTC, xiii111 commented
> ギミック増やす時、
> 
> * 失敗回数の`Dictionary`のデフォルト値に追加
> * アイコン`sprite`をアタッチ
> 
> もする必要ありか。
> 新しい機能実装の時に追加記述する場所追えなくなってきた。
> 良い方法ないかなあ。。。

確かになぁ．ギミックのドメインが他のところ（Record Data や GeneralRecordDirector）に漏れ出ているからそうなるんだろうな

2020-09-23 12:16 UTC, xiii111 commented on Assets/Project/Scripts/Utils/PlayerPrefsUtils/RecordData.cs
> +            _failureReasonCount = MyPlayerPrefs.GetDictionary(PlayerPrefsKeys.FAILURE_REASONS_COUNT, new Dictionary<EFailureReasonType, int>
820405d

2020-09-23 12:55 UTC, xiii111 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            var radius = _clearStageGauge.GetComponent<RectTransform>().rect.width / 2;
`radius` の値が小さいな・・・・

2020-09-23 13:00 UTC, xiii111 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            var radius = _clearStageGauge.GetComponent<RectTransform>().rect.width / 2;
anchor だと正円にならないからなぁ

2020-09-23 13:03 UTC, xiii111 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            var radius = _clearStageGauge.GetComponent<RectTransform>().rect.width / 2;
@takasusuke Indicator だけでなく，ギミックアイコンも同じような原因で位置がおかしかったので，別イシューにさせてください．疲れました

2020-09-23 13:04 UTC, xiii111 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            var radius = _clearStageGauge.GetComponent<RectTransform>().rect.width / 2;
https://github.com/LITO-apps/Treevel-client/issues/547

2020-09-23 13:43 UTC, takasusuke commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            var radius = _clearStageGauge.GetComponent<RectTransform>().rect.width / 2;
縦幅はanchor指定して、横幅は縦幅と同じ大きさにするとか。
今みたいに、横幅=`70`、縦幅=`70`とprefabで設定しているのはこわい。

別イシューは了解しました。
お疲れ様です。

2020-09-23 13:44 UTC, xiii111 commented on Assets/Project/Scripts/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            var radius = _clearStageGauge.GetComponent<RectTransform>().rect.width / 2;
> 今みたいに、横幅=70、縦幅=70という数値をprefabで設定しているのはこわい。

その通りだな・・・

2020-09-23 13:52 UTC, takasusuke approved these changes
お疲れ様々。

コンフリクト解決頑張ってください。

2020-09-23 13:52 UTC, xiii111 commented
コンフリクト解決忘れた

2020-09-24 13:40 UTC, xiii111 commented
@takasusuke 感謝感謝感謝感謝感謝感謝感謝

2020-09-24 13:41 UTC, merged