Improvement/#517 audio manager
LITO-apps/Treevel-client pull request #533
Opened 2020-08-30 01:50 UTC by takesi0627

### 対象イシュー
Close 

### 概要

### 詳細

#### 現実装になった経緯

#### 技術的な内容

### キャプチャ

### 動作確認方法

### 参考 URL

2020-08-30 03:06 UTC, takesi0627 commented
@xiii111 @takasusuke 
レビュー宜しくお願いします

2020-08-30 08:32 UTC, takesi0627 commented on Assets/Project/Scenes/GamePlayScene.unity
> -  - component: {fileID: 1638029898}
GamePlayDirectorにアタッチしていた `AudioSource` を削除した

2020-08-30 08:33 UTC, takesi0627 commented on Assets/Project/Scenes/StartUpScene.unity
> +--- !u!1001 &2036325621
SoundManagerオブジェクトをStartUpに置いておく

2020-08-30 08:36 UTC, takesi0627 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +                    .ToList();
EnumとClipがペアとなるDictionaryを一回作って、またリストに戻す。
要は、Editorの描画を行う前に、`List<SoundData>`を常に`Enum`の数、順序で並べるようにする。

2020-08-30 14:03 UTC, xiii111 reviewed
動作確認ができなかったので，確認してもらえませんか？？自分の環境だけか，それとも手順が悪いかわかりませんが，音が聞こえません（設定で音量ゲージを十分高くしています）

- [ ] BGMが流れるか

- [ ] 成功時のSEが再生されるか

- [ ] 失敗時のSEが再生されるか

- [ ] （雷ギミックがあるステージで）雷のSEが再生されるか

雷ギミックに関しては，どこかのステージに雷ギミックを登場させるようにしてくれると助かります

2020-08-30 14:26 UTC, takesi0627 commented
ミュートしていませんか
![image](https://user-images.githubusercontent.com/17778395/91661622-26262d00-eb18-11ea-902a-525db8898f6a.png)

2020-08-30 14:26 UTC, xiii111 commented
泣いた．打ち合わせで変えたんだ・・・

2020-08-31 14:15 UTC, xiii111 requested changes
### 動作確認
- [x] BGMが流れるか
- [x] 成功時のSEが再生されるか
- [x] 失敗時のSEが再生されるか
- [x] （雷ギミックがあるステージで）雷のSEが再生されるか
- [x] SoundManagerに適当に新しいキーを登録し、元のリストが保持されることを確認する

### 気になったところ
1. アプリ起動時の初期音量がおかしい

動作確認手順としては，アプリ起動 → 設定から BGM と SE をとても小さくする → ゲームをプレイ → 設定通りの小さい音量 → アプリを落として起動し直す → ゲームをプレイ → 音量がデカくなってる → 設定のスライダーをいじり直すと反映される

2020-08-31 14:15 UTC, xiii111 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +            for (var i = 0; i < _MAX_SE_NUM; i++) {
これ `foreach` にしてぇと思ってコード書いたら， `foreach` にすると immutable なんだね．ひどい

2020-08-31 14:15 UTC, xiii111 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +                var soundData = _seClipList.Single(data => data.key.Equals(key.ToString()));
これが string で探すってやつか

2020-08-31 14:15 UTC, xiii111 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +                Debug.LogWarning($"Failed to Play SE: {key} because there is no available audio source");
```suggestion
                Debug.LogWarning($"Failed to Play SE: {key} because audio sources are fully assigned");
```
こういうこと？

2020-08-31 14:15 UTC, xiii111 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +            var player = _SePlayers.Where(src => src.clip != null).SingleOrDefault(src => src.clip.name == clip.name);
```suggestion
            var player = _SePlayers
                .Where(src => src.clip != null)
                .SingleOrDefault(src => src.clip.name == clip.name);
```

今更だけど，こう書く，もしくは

```suggestion
            var player = _SePlayers.Where(src => src.clip != null)
                .SingleOrDefault(src => src.clip.name == clip.name);
```

こう書く方がみやすい

2020-08-31 14:15 UTC, xiii111 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +        public bool IsPlaying(ESEKey key)
```suggestion
        public bool IsPlayingSE(ESEKey key)
```
の方が良いかな

2020-08-31 14:15 UTC, xiii111 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +            var player = _SePlayers.Where(src => src.clip != null).SingleOrDefault(src => src.clip.name == clip.name);
他同様

2020-08-31 14:15 UTC, xiii111 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +                src._bgmClipList = Enum.GetNames(typeof(EBGMKey))
null チェック

2020-08-31 14:15 UTC, xiii111 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +                foreach (var eBgm in Enum.GetValues(typeof(EBGMKey)) as EBGMKey[]) {
```suggestion
                foreach (var eBgm in (EBGMKey[]) Enum.GetValues(typeof(EBGMKey))) {
```
どっちが良いんやろ

2020-08-31 14:15 UTC, xiii111 commented
コメントしました，お願いします

2020-09-01 09:43 UTC, takesi0627 commented
> ### 気になったところ
> 1. アプリ起動時の初期音量がおかしい
> 
> 動作確認手順としては，アプリ起動 → 設定から BGM と SE をとても小さくする → ゲームをプレイ → 設定通りの小さい音量 → アプリを落として起動し直す → ゲームをプレイ → 音量がデカくなってる → 設定のスライダーをいじり直すと反映される

ごめんなさい、バグを調査している途中で差分がなくなったようです。 7dcca98 で直しました。

2020-09-01 09:45 UTC, takesi0627 commented on Assets/Project/Scripts/GamePlayScene/Bottle/AbstractBottleController.cs
> +            float elapsed = 0f;
おそらく `elapsedTime` が正しいかと

2020-09-01 09:50 UTC, takesi0627 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +        }
これは `SoundManager` の内部クラスで、 `enum` と同じ階層ではないですし、
このクラスの詳細は読まなくてもいいと思うから下に置いていました。

2020-09-01 09:52 UTC, takesi0627 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +            _BgmPlayer.loop = true;
うん？ 今まで`Monobehaviour`から`gameObject`をアクセスした時`null`チェックしてたっけ

2020-09-01 09:59 UTC, takesi0627 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +                var soundData = _seClipList.Single(data => data.key.Equals(key.ToString()));
いかにも

2020-09-01 10:05 UTC, takesi0627 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +                foreach (var eBgm in Enum.GetValues(typeof(EBGMKey)) as EBGMKey[]) {
どっちだろうね

2020-09-01 10:10 UTC, takesi0627 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +    }
どうして欲しいとかありますか

2020-09-01 10:11 UTC, takesi0627 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +                Debug.LogWarning($"Failed to Play SE: {key} because there is no available audio source");
そういうことですが、これってこう直せってこと？

2020-09-01 11:48 UTC, xiii111 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +    }
SE の Key なのだから，SE_ 要らないかなと思った．後， `Scene名_説明` とかが良いかな？と思ったけど，後者は色々追加した時に思うことだから，今すぐに変更しなくても良いかなぁみたいな

2020-09-01 11:48 UTC, xiii111 commented on Assets/Project/Scripts/GamePlayScene/Bottle/AbstractBottleController.cs
> +                }
あれ，これは

2020-09-01 11:50 UTC, xiii111 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +        }
あー
```
[SerializeField] private List<SoundData> _bgmClipList;
```

とかを見て，？？あ，下にあったってなったからコメントしたけど，今の位置が悪いわけでもないな

2020-09-01 11:50 UTC, xiii111 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +            _BgmPlayer.loop = true;
今まではしてないところもあるけど，本当はした方が良いと思う

2020-09-01 11:51 UTC, xiii111 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +                Debug.LogWarning($"Failed to Play SE: {key} because there is no available audio source");
そっちの方がわかりやすいかも，なんで no available なのかわかりづらい

2020-09-01 11:51 UTC, xiii111 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +                foreach (var eBgm in Enum.GetValues(typeof(EBGMKey)) as EBGMKey[]) {
今後統一していけたら良いね．個人的には as hoge

2020-09-01 12:00 UTC, xiii111 reviewed
> > ### 気になったところ
> > 
> > 1. アプリ起動時の初期音量がおかしい
> > 
> > 動作確認手順としては，アプリ起動 → 設定から BGM と SE をとても小さくする → ゲームをプレイ → 設定通りの小さい音量 → アプリを落として起動し直す → ゲームをプレイ → 音量がデカくなってる → 設定のスライダーをいじり直すと反映される
> 
> ごめんなさい、バグを調査している途中で差分がなくなったようです。 [7dcca98](https://github.com/LITO-apps/Treevel-client/commit/7dcca98e0b75a8ed9eaadd073c60bbbd000d8ab9) で直しました。

治ってました👍

ですが，別の問題が発生していました．
アプリ起動時に初めてゲームを開始する時，BGM が流れ始めるのが遅いです．1~2秒くらい遅延してから BGM が流れ始めます．アプリを起動したままの2回目以降のゲームでは問題なく動作します．

あとは，初回レビューのコメントへの対応を継続してもらえれば OK です

2020-09-01 12:02 UTC, xiii111 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +        }
なので OK

2020-09-01 12:03 UTC, xiii111 commented on Assets/Project/Scripts/GamePlayScene/Bottle/AbstractBottleController.cs
> +            float elapsed = 0f;
あ，これ typo

2020-09-01 14:14 UTC, takesi0627 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +                foreach (var eBgm in Enum.GetValues(typeof(EBGMKey)) as EBGMKey[]) {
`as` +1

2020-09-01 14:17 UTC, takesi0627 commented on Assets/Project/Scripts/Utils/SoundManager.cs
> +    }
> SE の Key なのだから，SE_ 要らないかなと思った

これは思ったw。

2020-09-01 15:43 UTC, takesi0627 commented
> アプリ起動時に初めてゲームを開始する時，BGM が流れ始めるのが遅いです．1~2秒くらい遅延してから BGM が流れ始めます．アプリを起動したままの2回目以降のゲームでは問題なく動作します．

clip設定してからplayback設定しないとダメだった。
ac9f178 で解決。

2020-09-01 15:51 UTC, takesi0627 commented on Assets/Project/Scripts/GamePlayScene/Bottle/AbstractBottleController.cs
> +                }
エラーメッセージポップアップで対応します

2020-09-02 13:38 UTC, xiii111 approved these changes
LGTM with nits!

2020-09-02 13:38 UTC, xiii111 commented on Assets/Project/Resources/GameDatas/translation.csv
> +ErrorLoadSceneFailed,データの読み込みが失敗しました。,Failed to load data
Scene じゃない
```suggestion
ErrorLoadDataFailed,データの読み込みが失敗しました。,Failed to load data
```
かな？

2020-09-02 14:55 UTC, takesi0627 commented
@takasusuke マージしちゃっていい？

2020-09-03 08:49 UTC, takasusuke commented
完全に任せてる心だった
merge ok〜

2020-09-03 09:30 UTC, merged

2020-09-03 09:30 UTC, takesi0627 commented
シェーシェー