[WIP]【GamePlaytScene】突風ギミック
LITO-apps/Treevel-client pull request #535
Opened 2020-09-03 16:32 UTC by takesi0627

### 対象イシュー
Close #456 

### 概要
突風ギミックの実装

### 詳細

#### 現実装になった経緯

#### 技術的な内容

### キャプチャ
![gustwind](https://user-images.githubusercontent.com/17778395/92142110-52aab380-ee4e-11ea-9012-3415afbd6542.gif)

### 動作確認方法
Summer_1_2で確認できます

### 参考 URL

2020-09-03 16:33 UTC, takesi0627 commented
GIFなんか色おかしいけど、気にしないでおくれ

2020-09-12 11:37 UTC, takesi0627 commented
進捗：
- [ ] 警告アニメーション
- [ ] タイミング調整
- [ ] 位置調整

![gustwind0912](https://user-images.githubusercontent.com/17778395/92994724-b19bb700-f537-11ea-8e98-57421b4156de.gif)

2020-09-16 17:10 UTC, takesi0627 commented
@takasusuke @xiii111 
警告アニメーションはまだ組んでいないが、ギミックのロジックは全て完了してますので、レビューを進んでいただいても大丈夫かと思います。

Summer_1_2とSummer_1_3にギミック配置していますのでそちらで確認していただければと思います。

![gustwind0917](https://user-images.githubusercontent.com/17778395/93369575-87752c80-f88a-11ea-87b8-a26d04c587ee.gif)

2020-09-17 08:38 UTC, takasusuke requested changes

2020-09-17 08:38 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/BoardManager.cs
> +        }
```
var r = (int)row - 1;
for (var c = 0 ; c < StageSize.COLUMN ; c++) {
    if (_squares[c, r].bottle) {
         ret.Add(_squares[c, r].bottle.gameObject);
    }
}
```
で良いのでは？

2020-09-17 08:38 UTC, takasusuke commented on Assets/Project/Scripts/Utils/Library/GimmickLibrary.cs
> +        /// ギミックの方向は縦向きか
```suggestion
        /// ギミックの移動方向は縦向きか
```

2020-09-17 08:38 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/Gimmick/GustWindController.cs
> +            _attackMoveDistance = WindowSize.HEIGHT + GetComponent<SpriteRenderer>().size.y * transform.localScale.y;
左右と上下でこの値って変えるべきじゃない？？

2020-09-17 08:38 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/Gimmick/GustWindController.cs
> +                        var xCord = BoardManager.Instance.GetTilePos(ERow.Third, gimmickData.targetColumn).x;
`xPos, yPos`にするか、`xCord, yCord`に統一してほしい

2020-09-17 08:38 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/Gimmick/GustWindController.cs
> +        [SerializeField] private float MoveBottleSpeed = 6.0f;
```suggestion
        [SerializeField] private float _moveBottleSpeed = 6.0f;
```

2020-09-17 08:38 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/Gimmick/GustWindController.cs
> +            var direction = (_attackEndPos - _attackStartPos).normalized;
```
var direction = GetMoveDirection();
```
で可？？

2020-09-17 10:02 UTC, takesi0627 commented on Assets/Project/Scripts/GamePlayScene/Gimmick/GustWindController.cs
> +            _attackMoveDistance = WindowSize.HEIGHT + GetComponent<SpriteRenderer>().size.y * transform.localScale.y;
アニメーションの長さで移動速度を決めているので、移動距離を固定にしないと上下と左右の移動速度変わってしまう

2020-09-17 10:03 UTC, takesi0627 commented on Assets/Project/Scripts/GamePlayScene/Gimmick/GustWindController.cs
> +                        var xCord = BoardManager.Instance.GetTilePos(ERow.Third, gimmickData.targetColumn).x;
あ、ここ変えるの忘れた

2020-09-17 10:05 UTC, takesi0627 commented on Assets/Project/Scripts/GamePlayScene/Gimmick/GustWindController.cs
> +        [SerializeField] private float MoveBottleSpeed = 6.0f;
デフォルトのままでも結構スピードいい感じだったのでこれ結局使ってないんだよね。削除しとく。

2020-09-17 10:05 UTC, takesi0627 commented on Assets/Project/Scripts/GamePlayScene/Gimmick/GustWindController.cs
> +            var direction = (_attackEndPos - _attackStartPos).normalized;
天才？

2020-09-17 10:32 UTC, takesi0627 commented
テストステージプッシュしてないの今気づいたけど・・・

2020-09-17 10:46 UTC, takesi0627 commented on Assets/Project/Scripts/GamePlayScene/BoardManager.cs
> +        }
素晴らしい

2020-09-18 10:34 UTC, takasusuke requested changes
- 突風って
```
GetComponent<SpriteRenderer>().enabled = true;
GetComponent<Collider2D>().enabled = true;
```
ってどこでやってる？？
当たり判定の記述見つからなくてよくわからなかったんだけど、Bottleのlifeが減らないのはなぜかお教え願います。

- 突風のボトル移動のアルゴリズムすごいわ😱

2020-09-18 10:34 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/Gimmick/GustWindController.cs
> +            MoveBottles();
攻撃列にボトルがN個あったら、N回呼ばれてる？
最初の１回だけ呼んだら当たり判定無くさない？

2020-09-18 10:34 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/Gimmick/GustWindController.cs
> +            _attackMoveDistance = WindowSize.HEIGHT + GetComponent<SpriteRenderer>().size.y * transform.localScale.y;
なるほど。

ユーザが見える画面だと、
縦方向の時は、
ギミック開始時間から、N秒のアニメーションが見える。
横方向の時は、
ギミック開始時間 + t 秒から(N-t)秒のアニメーションが見える。

という現状ですが、横方向の時は、
ギミック開始時間から(N-2t)秒のアニメーションが見える方が良いと思いました。

横方向の時は
```
startX = -sign * (WindowSize.WIDTH + GetComponent<SpriteRenderer>().size.y * transform.localScale.y) * 0.5f;
```
とするのはいかがでしょうか。

2020-09-18 10:34 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/Gimmick/GustWindController.cs
> +            var speed = _attackMoveDistance / attackAnimationTime;
これ`Awake()`で出来ませんか？

2020-09-18 11:31 UTC, takesi0627 commented
> * 突風って
> 
> ```
> GetComponent<SpriteRenderer>().enabled = true;
> GetComponent<Collider2D>().enabled = true;
> ```
> 
> ってどこでやってる？？

全部アニメーションで制御してます。

> 当たり判定の記述見つからなくてよくわからなかったんだけど、Bottleのlifeが減らないのはなぜなのかもお教え願います。

実はオブジェクトのタグをギミックしていないので、ボトルとの衝突は、ボトル側の処理で無視されてる。

2020-09-18 11:32 UTC, takesi0627 commented on Assets/Project/Scripts/GamePlayScene/Gimmick/GustWindController.cs
> +            MoveBottles();
無くさないとダメですね。盲点でした

2020-09-18 12:42 UTC, takesi0627 commented on Assets/Project/Scripts/Utils/Library/GimmickLibrary.cs
> +        public static Vector2Int GetDirectionVector(EGimmickDirection direction)
なるほど

2020-09-21 07:20 UTC, takesi0627 commented
@takasusuke @xiii111 
お待たせしました。レビューの修正及び警告アニメーションの実装が完了しました。ご確認お願いします。

5268760 : 警告アニメーションを実装するにあたり、警告を子オブジェクトにすると、親オブジェクトの `ObjetUnifier` に影響され、大きさの制御ができないことに気づきました。それを解決するために、突風自身のスプライトと警告のスプライトをそれぞれ子オブジェクトに置くことに調整しました。最初は `Collider` どうするかって問題があったけど、調べた結果、 `RigidBody` が親オブジェクトにあると自動的に子オブジェクトの `Collider` の衝突を検出してくれるということで、 `SpriteRender` 、 `Collider2D` 、 `ObjectUnifier` を子オブジェクトに移動しました。

2020-09-21 07:22 UTC, takesi0627 commented on Assets/Project/Scripts/GamePlayScene/Gimmick/GustWindController.cs
> +            var speed = _attackMoveDistance / attackAnimationTime;
できますが、このパラメータをここでしか使わないから、メンバー変数にはあんまりしたくないという考えでした

2020-09-21 07:44 UTC, takesi0627 commented on Assets/Project/Scripts/GamePlayScene/Gimmick/GustWindController.cs
> +            _attackMoveDistance = WindowSize.HEIGHT + GetComponent<SpriteRenderer>().size.y * transform.localScale.y;
989d8b8 で修正しました

2020-09-21 07:45 UTC, takesi0627 commented on Assets/Project/Scripts/GamePlayScene/Gimmick/GustWindController.cs
> +            MoveBottles();
8f95058 で修正しました

2020-09-21 08:09 UTC, takesi0627 commented
ボトルの移動アルゴリズムの簡単の説明を更新しました

2020-09-26 07:51 UTC, takasusuke commented on Assets/Project/Actors/Gimmicks/GustWind/GustWindPrefab.prefab
> +--- !u!61 &7894972585210036848
ここともう１つ
`GustWindPrefab`の`Core`と`Warning`の`ObjectUnifier`の`image ratio`の値なんだけど、
画面縦幅に合わせるなら
`Screen.HEIGHT / (Screen.WIDTH * ObjectUnifier.RatioToWindowWidth)`
↓
`16 / (9 * 0.20) = 8.8888...`
だから、8.9とかを入れておくと良いと思う。

2020-09-26 07:53 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/Gimmick/GustWindController.cs
> +                        var sign = _targetDirection == EGimmickDirection.ToLeft ? 1 : -1;
ここ、LeftとRightの符号変わってるけど、
前も正しく動いてるように見えたし、今も正しく動いてるのどゆこと？？？？

2020-09-26 07:58 UTC, takasusuke commented
あ、`GustWindController.OnEndGame()`無いや

2020-09-26 14:00 UTC, takesi0627 commented on Assets/Project/Scripts/GamePlayScene/Gimmick/GustWindController.cs
> +                        var sign = _targetDirection == EGimmickDirection.ToLeft ? 1 : -1;
画像の向きを合わせてたら、なんか警告のアニメーション逆になっちゃって、どうやら元々向き逆だったけど、攻撃のアニメーションが速すぎて気づけなかったらしい。

2020-09-26 23:33 UTC, takasusuke approved these changes
お疲れ様でした

2020-09-28 14:24 UTC, takesi0627 commented
あざまする

2020-09-28 14:24 UTC, merged