道(と枝)の描画順序を整える
LITO-apps/Treevel-client pull request #543
Opened 2020-09-15 17:17 UTC by takasusuke

### 対象イシュー
Close #471

### 概要
- `LevelSelectScene`において、`Background`→`Road`→`Tree`の順に描画されるようにする
- `StageSelectScene`において、`Background`→`Branch`→`Stage`の順に描画されるようにする

### 詳細
- 各Sceneにおいて、`Background`のみを映す`BackgroundCamera`を用意。
- `MainCamera`は`Background`以外を映す
- `BackgroundCamera`は`MainCamera`は背面に描画されるようにする
- `Road`(や`Branch`)は`MainCamera`に映し、`Tree`(や`Stage`)よりも後ろに描画されるようにする。

#### 現実装になった経緯
- 詳しくはissueコメントに記述。
同じ`Canvas`内のオブジェクトの描画順序を操作する場合、`Image`同士では`Hierarchy`の上下で制御。`Sprite`同士では`SortingLayer`などで制御。`Image`全般と`Sprite`全般は多分`Shader`で制御できる。
今回のように、`Image(Background)`→`Sprite(Road)`→`Image(Tree)`のような描画順序を実現する方法は1つの`Canvas`内では見つからなかった。
全てを`Sprite`にすることも考えたが、不都合も色々生じたので、今回の実装のように、`Image(Background)`のみを描画する`Canvas`および`Camera`を用意した。

#### 技術的な内容
- `MainCamera`に映す`Canvas`がスクロールされた時、`BackgroundCanvas`もスクロールする必要がある。
スクロールされる`Content`の`LocalPosition`や`LocalScale`は`Canvas`に対する相対的な位置や大きさである。
`BackgroundCanvas`と`Canvas`は同じ大きさであるので、`Background`以下のオブジェクトの`LocalPosition`や`LocalScale`を同期させるスクリプト`SynchronizeObject.cs`を作成した。
- `MenuSelectScene`の`LevelSelect`の背景が見えなくなるように、`Setting`に背景を追加した。`Record`には背景を追加していない(conflictしても面倒だから)ので、効果を比較可能。
- `Camera`のinspectorの`Camera/Culling Mask`の項目から描画する`Layer`の選択が可能。

### キャプチャ
変更前
<img width="196" alt="スクリーンショット 2020-09-16 2 14 07" src="https://user-images.githubusercontent.com/26213141/93242825-57625680-f7c2-11ea-94b6-61127415af5f.png"><img width="196" alt="スクリーンショット 2020-09-16 2 14 12" src="https://user-images.githubusercontent.com/26213141/93242833-59c4b080-f7c2-11ea-91d7-cd76008c109c.png">

変更後
<img width="197" alt="スクリーンショット 2020-09-16 2 13 17" src="https://user-images.githubusercontent.com/26213141/93242844-5d583780-f7c2-11ea-8a2f-0a2603c31c77.png"><img width="203" alt="スクリーンショット 2020-09-16 2 13 25" src="https://user-images.githubusercontent.com/26213141/93242855-5fba9180-f7c2-11ea-9354-b2460129b989.png">

### 動作確認方法

- [ ] `LevelSelectScene`の描画順序を確認

- [ ] `LevelSelectScene`でスクロールや拡大縮小を行い、背景も移動・拡大縮小されることを確認

- [ ] `SettingScene`で`LevelSelectScene`の背景が見えないことを確認(`RecordScene`では見える)

- [ ] `StageSelectScene`の描画順序を確認

### 参考 URL

2020-09-15 17:20 UTC, takasusuke commented
@xiii111 よろしくお願いします。
`Scene`の変更が多くて、具体的に`Scene`のどのパラメータを変更したのか等の説明漏れが多そうなので、どこかのタイミングでインタラクティブに説明できればと思います。

2020-09-15 17:34 UTC, takasusuke commented
- ad5dc10 `LevelSelectScene`の`Road`と`Tree`のヒエラルキー上での順番を入れ替えた。描画順序の変更はない。(意味なし)
- 54665f9 `Road`に使っている`material`の`Shader`を変更。(どっかのサイトでお勧めされていたやつ)
- b4be7c4 `Background`のみを映す`Camera`を配置、`Background`関連を別`Canvas`に移動。`Camera`と`Canvas`の対応関係を設定。
- a13c534 `LevelSelect/Canvas/Scroll View`の元々使われていない`image`コンポーネントを削除
- 51f30b6 `SettingScene`に背景を配置。
- 8605ff9 `LevelSelect/Canvas/Scroll View /Viewport/Content`と`LevelSelect/BackgrouncCanvas/Background`の位置・大きさを連動するようにスクリプトを作成・設定
- a97f23d `SettingScene`の背景のヒエラルキー上の位置、色、透明度を調整
- 56deb98 `LevelSelect/BackgroundCanvas`が`SafeArea`に収まるようにスクリプトをアタッチ
- b74b67b `Branch`の`material`を変更(`Road`と同じ)
- d6527a5 `Spring. Summer, Autumn, Winter`の描画順序を設定。これまでのcommitに示す`LevelSelectScene`で行った、`Canvas`や`Camera`等々の設定を`StageSelectScene`で行った
- 6a716bb 各`Level`の最初の`Stage`が解放されないバグを修正
- 76f78e7 自動コードリファクタリング
- fb84486 `Spring_1`をクリアしないと`Summer_1`が解放されないように変更(`LevelSelectScene`ではそうなっていたが、`StageSelectScene`ではその制約がなかったので変更した)
- ba2b62a `LevelSelect/BackgroundCanvas/Background`の`Rect/Scale`が変な数値になっていたのを修正

2020-09-17 12:30 UTC, takasusuke commented
`LevelSelectScene`の背景がスクロールで止めた後も動く状況について、できれば細かい再現方法お願いします。

2020-09-17 12:36 UTC, takesi0627 commented on Assets/Project/Scripts/Utils/SynchronizeObject.cs
> +            synchronizedObject.transform.localPosition = gameObject.transform.localPosition;
更新する必要あるときにだけ更新するようにして欲しい

2020-09-17 12:36 UTC, xiii111 approved these changes
LGTM with nits

- `LevelSelectScene` の場外の挙動がおかしい
- `StageSelectScene` の場外の挙動がおかしい
- `SynchronizeObject.cs` は `SynchronizeCanvasObjects.cs ` が良いかな

2020-09-18 05:02 UTC, takasusuke commented
cded01b `SnapScrollView`の`MoveMentType`を`Clamped`に設定し、`Content`の場外へのスクロールを禁止しました
4e2bc52 
- `SynchronizeObject` → `SynchronizeCanvasObject`にリネームしました
- scrollしたときだけ、背景の位置等を更新するように修正しました。
- `ScrollRect`の`OnEnable`よりも確実に後に`SynchronizeCanvasObject`の`OnEnable`を実行して欲しいので、
```
[DefaultExecutionOrder(1)]
```
という記述を行いました。数字の小さいスクリプトから実行されます。何も書いてない場合は数字は0です。
[参考](http://tsubakit1.hateblo.jp/entry/2017/02/05/003714)

2020-09-18 05:02 UTC, takasusuke commented on Assets/Project/Scripts/Utils/SynchronizeObject.cs
> +            synchronizedObject.transform.localPosition = gameObject.transform.localPosition;
4e2bc52 で対応しました

2020-09-18 05:02 UTC, takasusuke commented
@xiii111 改めてお願いいたします

2020-09-18 11:57 UTC, xiii111 requested changes
一点だけ．StageSelectScene の SnapScroll において，一番左の要素で左に移動するようにスワイプすると右に移動します．右に移動するようにスワイプしても右に移動しますし，一番右の要素は正常に動作します．確認お願いします

2020-09-20 19:03 UTC, takasusuke commented
- bf380fe `StageSelectScene`の一番左で左にスワイプしないようにしました
- `SynchronizeCanvasObject.cs`の`AddListener`のとこで`delegate`を使わずラムダ式とか関数化しようと思ったけど、引数とする関数の型が`UnityAction<Vector2>`でした。
```
func T A(Vector2 value)
{
    // do something
}
```
的なのを書く必要があるんですけど、`value`を必要としない処理なので、なんか微妙な気がしたので`delegate`のままにしてあります。

2020-09-20 19:03 UTC, takasusuke commented
@xiii111 @takesi0627 ヨロです

2020-09-23 11:46 UTC, xiii111 commented
動作問題ないです．

bf380fe この差分はどう読めばいいですか？

@takasusuke これでどう？
```
_scrollRect.onValueChanged.AddListener(_ => {
    _synchronizedObject.transform.localPosition = gameObject.transform.localPosition;
    _synchronizedObject.transform.localScale = gameObject.transform.localScale;
});

2020-09-23 11:48 UTC, xiii111 commented on Assets/Project/Scripts/Utils/SynchronizeCanvasObject.cs
> +        void Awake()
```suggestion
        private void Awake()
```

2020-09-23 11:48 UTC, xiii111 commented on Assets/Project/Scripts/Utils/SynchronizeCanvasObject.cs
> +        void OnEnable()
```suggestion
        private void OnEnable()
```

2020-09-23 15:02 UTC, takesi0627 commented
> あと `delegate` の問題はこれでどう？
> 
> ```
> _scrollRect.onValueChanged.AddListener(_ => {
>     _synchronizedObject.transform.localPosition = gameObject.transform.localPosition;
>     _synchronizedObject.transform.localScale = gameObject.transform.localScale;
> });
> ```

この書き方でいいかと思います。
しかし何で `delegate` だと引数を無視できるのか不思議です🤔

2020-09-24 13:47 UTC, takasusuke commented on Assets/Project/Scripts/Utils/SynchronizeCanvasObject.cs
> +        void OnEnable()
676d480

2020-09-24 13:47 UTC, takasusuke commented on Assets/Project/Scripts/Utils/SynchronizeCanvasObject.cs
> +        void Awake()
676d480

2020-09-24 13:48 UTC, takasusuke commented
> 
> あと `delegate` の問題はこれでどう？
> 
> ```
> _scrollRect.onValueChanged.AddListener(_ => {
>     _synchronizedObject.transform.localPosition = gameObject.transform.localPosition;
>     _synchronizedObject.transform.localScale = gameObject.transform.localScale;
> });
> ```

天才

2020-09-24 15:11 UTC, takasusuke commented
e463887 : 各季節のdummy stageとstage1を繋ぐbranchのデータのkeyが"Dummy_0_1"となっており、全ての季節で共通してしまっていました。そのため、例えば、Spring1でstage1を解放するとそれ以外の季節のstage1が解放されない状態になっていました。
"Spring1_0_1", `Summer1_0_1"のように一意の名前をつけました。

e15e384 : 道の解放アニメーション中に画面遷移すると、道の解放アニメーション中に解放される木が非解放のままになってしまうバグを直しました。
アニメーションの開始時点で既に、木のデータを解放扱いにしました。

2020-09-24 15:38 UTC, takasusuke commented
bf380fe 
contentの初期位置がずれていた。
`Clamped`の内部実装知らないけど、`Content`の境界が`ScrollView`の境界に触れたらスクロールできない的な実装なら下図のように１つの木の半分の大きさだけ左にずらせてしまっていた。
それを修正した。`Content`の中央を1 ÷ 3(=木の本数) ÷ 2 = 0.1666... → 0.1666に設定した。
![export 16](https://user-images.githubusercontent.com/26213141/94166212-050ded80-fec6-11ea-8e30-399a7040afcf.png)

左にスクロールしたら右に遷移した理由
スクロールされた時、`-pageSize * page - content.localPosition.x >= 0`なら右、`<0`なら左に遷移する。
`-pageSize * page`は左端だと`0`.
`content.localPosition.x `は`Content`が`ScrollView`の左側に行くので負の値をとり、式は正の値になる。
てなわけで右に遷移されましたとさ。

2020-09-24 15:50 UTC, takasusuke commented
86ff366 : developをmergeしました
@xiii111 泣きの1回...(になりますように...)

2020-09-26 22:18 UTC, xiii111 approved these changes
長々と修正ありがとうございました！最高です！

2020-09-26 23:34 UTC, merged