Staticボトル、Dummyボトル見えない不具合修正
LITO-apps/Treevel-client pull request #573
Opened 2020-10-04 14:32 UTC by takesi0627

### 対象イシュー
Close #558 

### 概要
ボトルデータにスプライト設定されていないと表示されない不具合を修正

### 詳細

#### 現実装になった経緯

#### 技術的な内容

### キャプチャ

### 動作確認方法
- [ ] Spring_1_1で表示されていることを確認

### 参考 URL

2020-10-04 14:33 UTC, takesi0627 commented
@xiii111 @takasusuke 手が空いたらお願いします。一瞬で終わります

2020-10-04 14:54 UTC, takasusuke requested changes

2020-10-04 14:54 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/Bottle/AbstractBottleController.cs
> +                GetComponent<SpriteRenderer>().enabled = true;
```suggestion
                var bottleWidth = GetComponent<SpriteRenderer>().sprite.bounds.size.x;
                var bottleHeight = GetComponent<SpriteRenderer>().sprite.bounds.size.y;
                
                transform.localScale = new Vector2(BottleSize.WIDTH / bottleWidth, BottleSize.HEIGHT / bottleHeight);

                if (GetComponent<Collider2D>() is BoxCollider2D) {
                    GetComponent<BoxCollider2D>().size = GetComponent<SpriteRenderer>().sprite.bounds.size;
                }
                GetComponent<Renderer>().sortingLayerName = SortingLayerName.BOTTLE;
                GetComponent<SpriteRenderer>().enabled = true;
```

画像をloadしたときに行っているこの部分も必要じゃない？

2020-10-04 15:11 UTC, takesi0627 commented on Assets/Project/Scripts/GamePlayScene/Bottle/AbstractBottleController.cs
> +                GetComponent<SpriteRenderer>().enabled = true;
そうだった。
じゃあ、 `ObjectUnifierにするわ`

2020-10-05 13:38 UTC, xiii111 commented
@takasusuke 任せた

2020-10-05 15:01 UTC, takesi0627 commented
@takasusuke 
修正しました。確認お願いします

2020-10-06 14:08 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/ObjectUnifier.cs
> +            var originalHeight = GetComponent<SpriteRenderer>().sprite.bounds.size.y;
```suggestion
            var originalWidth = _renderer.sprite.bounds.size.x;
            var originalHeight = _renderer.sprite.bounds.size.y;
```
`Awake()`で`_renderer`取得しているならそれ使いたい。

それから、`public`メソッドとして外部から呼ぶこともあるなら
```
public void Unify(){
    if (_renderer.sprite != null) return;
}
```
こっちで例外処理した方がよさそう

2020-10-06 14:15 UTC, takesi0627 commented on Assets/Project/Scripts/GamePlayScene/ObjectUnifier.cs
> +            var originalHeight = GetComponent<SpriteRenderer>().sprite.bounds.size.y;
a8b05ed で修正した

2020-10-06 14:37 UTC, takasusuke approved these changes
谢谢， 费心了

2020-10-06 14:46 UTC, merged

2020-10-06 14:46 UTC, takesi0627 commented
不客氣