データタイプを編集する際データをリセットする
LITO-apps/Treevel-client pull request #576
Opened 2020-10-06 15:18 UTC by takesi0627

### 対象イシュー
Close #544 

### 概要
ステージデータ編集する際、タイプを変えた時前回編集したデータが残ることがあるので、それを回避するために対応する

### 詳細

#### 現実装になった経緯
最初は[こちらの方法](https://answers.unity.com/questions/1555254/reset-a-serializedproperty-to-its-default-value.html)を試してみたんだけど、 `GimmickData` などは `ScriptObject` ではないのでできなかった。

なので、 `SerializedProperty` から全てのデータ取り出して一つずつリセットする方法に至りました。
#### 技術的な内容

### キャプチャ

### 動作確認方法
- [ ] 任意ステージデータから `BottleType` `TileType` `GimmickType` を編集してみて、データがリセットされることを確認する

### 参考 URL
[Loop through SerializedProperty children](https://forum.unity.com/threads/loop-through-serializedproperty-children.435119/)

2020-10-06 15:25 UTC, takesi0627 commented
@takasusuke @xiii111 
初めて `IEnumerator` 使って `foreach` 回す手法を使いました。そこら辺理解するのに少し調べる必要あるかもしれません。

2020-10-07 12:49 UTC, takasusuke reviewed
動作確認しました○

`IEnumerator`の`foreach`
おしゃれな書き方やわ。

2020-10-07 12:49 UTC, takasusuke commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +                    child.arraySize = 0;
どっちでも良いけど
```
continue;
```
が好み

2020-10-07 12:49 UTC, takasusuke commented on Assets/Project/Scripts/Editor/EditorExtension.cs
> +            SerializedProperty nextSiblingProperty = serializedProperty.Copy();
```suggestion
            var currentProperty = serializedProperty.Copy();
            var nextSiblingProperty = serializedProperty.Copy();
```

2020-10-07 12:49 UTC, takasusuke commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +                    }
一応
`default: `書く？
無くていい気もするけど。。。

2020-10-08 04:32 UTC, takesi0627 commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +                    }
全部列挙する必要あるかわからないし、それぞれ `SerializedPropertyType` がどのフィールド対応しているのかも正直把握してないから今はとりあえず困りそうなところだけ挙げている、他のはスルーしていいんじゃないかと思います

2020-10-08 04:34 UTC, takesi0627 commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +                    child.arraySize = 0;
```
if (child.isArray) {
    continue;
}

switch () {
}
```
ってこと？

2020-10-08 10:39 UTC, xiii111 commented
今日見れるかはわからないけど，金土には見ます

2020-10-08 11:24 UTC, xiii111 requested changes
動作確認 OK !!
細かいコメントしました

2020-10-08 11:24 UTC, xiii111 commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +        private void ResetData(SerializedProperty prop)
```suggestion
        private static void ResetData(SerializedProperty prop)
```

2020-10-08 11:24 UTC, xiii111 commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +                // タイプがリセットしたら意味ない
ごめん．日本語が少しだけ理解できなかったんだけど，何を伝えたかった？

2020-10-08 11:24 UTC, xiii111 commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +                    child.arraySize = 0;
現状維持でも，

```C#
if (child.isArray) {
    child.ClearArray();
    child.arraySize = 0;
    continue;
} else {
    switch (child.propertyType) {
        ...
    }
}
```

でも，

```C#
if (child.isArray) {
    child.ClearArray();
    child.arraySize = 0;
    continue;
}

switch (child.propertyType) {
    ...
}
```

でも良い 🙆‍♂️

2020-10-08 11:24 UTC, xiii111 commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +                            child.boolValue = false;
規定値入れたいだけなら `default` を使えば良いんじゃない？

refs: https://docs.microsoft.com/ja-jp/dotnet/csharp/language-reference/builtin-types/default-values

2020-10-08 11:24 UTC, xiii111 commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +                    }
コメントつけといて

```
// 現状，リセットする必要がある型だけをリセットしている
```

2020-10-08 11:24 UTC, xiii111 commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +                var newTileType = (int)(ETileType)EditorGUILayout.EnumPopup(new GUIContent("Type"), (ETileType)tileTypeProp.enumValueIndex);
```suggestion
                var newEnumValueIndex = (int)(ETileType)EditorGUILayout.EnumPopup(new GUIContent("Type"), (ETileType)tileTypeProp.enumValueIndex);
```

の方がわかりやすいな．以下同様

2020-10-08 11:24 UTC, xiii111 commented on Assets/Project/Scripts/Editor/EditorExtension.cs
> +                        break;
これは好み

2020-10-08 13:50 UTC, takasusuke commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +                    child.arraySize = 0;
```
if (child.isArray) {
    continue;
}

switch () {
}
```
を想定していた。
ちょっとネスト深いなと思ってコメントしたけど、好みだからお好きに！

2020-10-08 13:50 UTC, takasusuke commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +                    }
コメントいいね

2020-10-10 14:48 UTC, takesi0627 commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +                var newTileType = (int)(ETileType)EditorGUILayout.EnumPopup(new GUIContent("Type"), (ETileType)tileTypeProp.enumValueIndex);
理由を聞いていいですか？
個人的に前者の方が分かりやすい

2020-10-10 14:49 UTC, takesi0627 commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +                // タイプがリセットしたら意味ない
タイプ変える時にデータリセットするようにしているので、
タイプ（例えば `GimmickData.type`）までリセットすると永遠にタイプが0になる

2020-10-10 15:54 UTC, takesi0627 commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +                            child.boolValue = false;
2e75582 で対応

2020-10-13 11:37 UTC, xiii111 commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +                var newTileType = (int)(ETileType)EditorGUILayout.EnumPopup(new GUIContent("Type"), (ETileType)tileTypeProp.enumValueIndex);
実態として入れてるのは， `index` だよね？ `Type` ではない．そもそも int 型だし．
一番違和感を感じたのは
```
if (newTileType != tileTypeProp.enumValueIndex) {
    ...
}
```
ここの比較の時に， `Type` と `Index` の比較？ってなる

2020-10-13 11:42 UTC, xiii111 commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +                // タイプがリセットしたら意味ない
あーりかい！ちょっと日本語を
```
// タイプはリセットしない
or
// タイプをリセットしたら意味ない
```
にしてくれると助かる

2020-10-13 11:45 UTC, xiii111 approved these changes
LGTM with nits !

以下のコメントだけやってくれたらマージして良いです
- https://github.com/LITO-apps/Treevel-client/pull/576#discussion_r503882331
- https://github.com/LITO-apps/Treevel-client/pull/576#discussion_r503879619

2020-10-13 14:27 UTC, merged

2020-10-13 14:35 UTC, xiii111 commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +                var newTileType = (int)(ETileType)EditorGUILayout.EnumPopup(new GUIContent("Type"), (ETileType)tileTypeProp.enumValueIndex);
納得してなかったら棄却して良いからね

2020-10-13 14:36 UTC, xiii111 commented
お疲れ様です 👍