Bottleのリファクタリング
LITO-apps/Treevel-client pull request #577
Opened 2020-10-07 14:56 UTC by takasusuke

### 対象イシュー
Close #561

### 概要
- Bottleの実装のリファクタリング

### 詳細(≒技術的な内容)
- Bottle(TIleの上に乗るGameObject)の他に、Effect(Bottleの子Object)がある
- Bottleは各イベントに対してevent Actionを持つ
- BottleやEffectが、Bottleのevent Actionを実装する
- Bottleがevent Actionを実装する場合 : そのBottle唯一の機能
(例) 
NormalBottleControllerの成功判定実装
- Effectがevent Actionを実装する場合 : 複数のBottleに付与できる機能
(例)
SelfishEffect, LifeEffect

#### 現実装になった経緯
BottleやEffectなど複数のクラスが同じイベントに対して処理を実装するために、`event Action`を用いて実装した

### キャプチャ

### 動作確認方法
(記述途中)

- [ ] Spring_1-1をプレイすると、`Selfish`, `Life`, `Selfish & Life`のボトルが問題なく動作する

### 参考 URL

2020-10-07 14:58 UTC, takasusuke commented
@xiii111 @takesi0627 
レビューよろしくお願いします。

後述の不具合についてのコメントをいただけたらと思います。

2020-10-07 15:05 UTC, takasusuke commented
実行して、すぐにSpring_1-1をプレイすると下記のエラーが出る。
(エラーが出て実行が一時停止するが、再生して成功・失敗などすると以降は出ない)
また、実行してから`StageSelectScene`で何秒か待ってからSpring_1-1をプレイした場合も出ない。

`BoardManager._bottlePositions`dictionaryにBottleを登録する前に、`OnEnterTile()`が呼ばれて、dictionaryを参照してしまって、nullが出てるみたいなエラーなんだけど、
どう考えても、dictionaryに登録してから読んでる気がするんだよなあ。。。
ゆっくりSpring_1-1をプレイした場合にエラーが起きないのもよくわからない。。。

<img width="1148" alt="スクリーンショット 2020-10-07 23 24 29" src="https://user-images.githubusercontent.com/26213141/95348591-283e9100-08f9-11eb-8d48-be2f2db3a8ac.png">

2020-10-08 04:51 UTC, takesi0627 commented
`Action` の宣言について、今のどころ `protected` でよさあそうと思いました。
`FlickGesture.cs`とかを参考にして書くと丁寧かも。
![image](https://user-images.githubusercontent.com/17778395/95415960-95d7d500-096c-11eb-9940-6388e475dc9b.png)

2020-10-08 04:58 UTC, takesi0627 commented
違うエラーが出た・・・
```
Exception encountered in operation UnityEngine.ResourceManagement.ResourceManager+CompletedOperation`1[UnityEngine.GameObject], result='', status='Failed': Exception of type 'UnityEngine.AddressableAssets.InvalidKeyException' was thrown., Key=LifeEffectPrefab, Type=UnityEngine.GameObject
UnityEngine.AddressableAssets.Addressables:InstantiateAsync(Object, Transform, Boolean, Boolean)
Project.Scripts.Utils.AddressableAssetManager:Instantiate(Object, Transform, Boolean) (at Assets/Project/Scripts/Utils/AddressableAssetManager.cs:148)
Project.Scripts.GamePlayScene.Bottle.<Initialize>d__0:MoveNext() (at Assets/Project/Scripts/GamePlayScene/Bottle/AttackableDummyBottleController.cs:20)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start(<Initialize>d__0&)
Project.Scripts.GamePlayScene.Bottle.AttackableDummyBottleController:Initialize(BottleData)
Project.Scripts.GamePlayScene.Bottle.<<CreateBottles>b__1_0>d:MoveNext() (at Assets/Project/Scripts/GamePlayScene/Bottle/BottleGenerator.cs:26)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start(<<CreateBottles>b__1_0>d&)
Project.Scripts.GamePlayScene.Bottle.<>c:<CreateBottles>b__1_0(BottleData)
System.Collections.Generic.List`1:ForEach(Action`1)
Project.Scripts.GamePlayScene.Bottle.BottleGenerator:CreateBottles(List`1) (at Assets/Project/Scripts/GamePlayScene/Bottle/BottleGenerator.cs:21)
Project.Scripts.GamePlayScene.StageGenerator:CreateStages(ETreeId, Int32) (at Assets/Project/Scripts/GamePlayScene/StageGenerator.cs:39)
Project.Scripts.GamePlayScene.PlayingState:StageInitialize() (at Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs:340)
Project.Scripts.GamePlayScene.PlayingState:OnEnter(State) (at Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs:318)
Project.Scripts.Utils.Patterns.StateMachine.StateMachine:Start() (at Assets/Project/Scripts/Utils/Patterns/StateMachine/StateMachine.cs:43)
Project.Scripts.GamePlayScene.GamePlayDirector:Start() (at Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs:120)
```

でもなんかみたことある気がする

2020-10-08 05:03 UTC, takesi0627 commented
> 違うエラーが出た・・・
> 
> ```
> Exception encountered in operation UnityEngine.ResourceManagement.ResourceManager+CompletedOperation`1[UnityEngine.GameObject], result='', status='Failed': Exception of type 'UnityEngine.AddressableAssets.InvalidKeyException' was thrown., Key=LifeEffectPrefab, Type=UnityEngine.GameObject
> UnityEngine.AddressableAssets.Addressables:InstantiateAsync(Object, Transform, Boolean, Boolean)
> Project.Scripts.Utils.AddressableAssetManager:Instantiate(Object, Transform, Boolean) (at Assets/Project/Scripts/Utils/AddressableAssetManager.cs:148)
> Project.Scripts.GamePlayScene.Bottle.<Initialize>d__0:MoveNext() (at Assets/Project/Scripts/GamePlayScene/Bottle/AttackableDummyBottleController.cs:20)
> System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start(<Initialize>d__0&)
> Project.Scripts.GamePlayScene.Bottle.AttackableDummyBottleController:Initialize(BottleData)
> Project.Scripts.GamePlayScene.Bottle.<<CreateBottles>b__1_0>d:MoveNext() (at Assets/Project/Scripts/GamePlayScene/Bottle/BottleGenerator.cs:26)
> System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start(<<CreateBottles>b__1_0>d&)
> Project.Scripts.GamePlayScene.Bottle.<>c:<CreateBottles>b__1_0(BottleData)
> System.Collections.Generic.List`1:ForEach(Action`1)
> Project.Scripts.GamePlayScene.Bottle.BottleGenerator:CreateBottles(List`1) (at Assets/Project/Scripts/GamePlayScene/Bottle/BottleGenerator.cs:21)
> Project.Scripts.GamePlayScene.StageGenerator:CreateStages(ETreeId, Int32) (at Assets/Project/Scripts/GamePlayScene/StageGenerator.cs:39)
> Project.Scripts.GamePlayScene.PlayingState:StageInitialize() (at Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs:340)
> Project.Scripts.GamePlayScene.PlayingState:OnEnter(State) (at Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs:318)
> Project.Scripts.Utils.Patterns.StateMachine.StateMachine:Start() (at Assets/Project/Scripts/Utils/Patterns/StateMachine/StateMachine.cs:43)
> Project.Scripts.GamePlayScene.GamePlayDirector:Start() (at Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs:120)
> ```
> 
> でもなんかみたことある気がする

再起動したら出なくなった

2020-10-08 10:39 UTC, xiii111 commented
今日見れるかはわからないけど，金土には見ます

2020-10-08 12:29 UTC, xiii111 reviewed
コツコツ進めます．今日の分だけ

2020-10-08 12:29 UTC, xiii111 commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +                            EditorGUILayout.PropertyField(lifeProp);
`bottleSprite` 消えちゃってる

2020-10-08 12:29 UTC, xiii111 commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +            return _src.BottleDatas?.Where(x => x.type == EBottleType.Normal);
今回のタスクじゃなくて申し訳ないが， `AttackableDummy` も含めた方が良さそう

2020-10-08 13:37 UTC, takasusuke commented
033704e : developをmergeしました
e602abd : レニュー修正

2020-10-08 13:37 UTC, takasusuke commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +            return _src.BottleDatas?.Where(x => x.type == EBottleType.Normal);
e602abd で修正しました

2020-10-08 13:38 UTC, takasusuke commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +                            EditorGUILayout.PropertyField(lifeProp);
e602abd で修正しました

2020-10-08 13:45 UTC, takasusuke commented
> 
> <img alt="スクリーンショット 2020-10-07 23 24 29" width="1148" src="https://user-images.githubusercontent.com/26213141/95348591-283e9100-08f9-11eb-8d48-be2f2db3a8ac.png">

このエラーですが、お二人が再現できないようなので、自分も再現が確実ではないので一旦、放置で進めようかと思います。

2020-10-08 13:48 UTC, takasusuke commented
> `Action` の宣言について、今のどころ `protected` でよさあそうと思いました。

精査してみます。

> `FlickGesture.cs`とかを参考にして書くと丁寧かも。
> ![image](https://user-images.githubusercontent.com/17778395/95415960-95d7d500-096c-11eb-9940-6388e475dc9b.png)

これが主流？というか一般的な感じ？
なんで分けてるんだろう。。。？

2020-10-08 15:31 UTC, takasusuke commented
fe3732d
エラーについて、
ボトルAを辞書に登録 
→ ボトルAの`OnEnterTile()` 
→ ボトルAの成功判定 
→ ボトルAが目標タイルにいるとき、ゲーム終了かどうかの判定が入る 
→ 全てのタイルの成功判定
→ まだ辞書に登録していないボトルBの成功判定 ← null !! error !!
ということです。

今まではボトルBの辞書登録の後に、ボトルBの成功判定ハンドラを付与していたので、
そもそもボトルBの成功判定ハンドラがまだ付与されていない → 成功判定メソッドが処理されない → 辞書を参照する部分まで処理が走っていない、ということでエラーが起きていませんでした。


とりあえず辞書に登録されていないボトルの場合には、例外値を返すようにしたら解決しました。
なんか微妙な気もするので、`NormalBottleController.OnEnterTile()`はoverrideして成功判定を実装するんじゃなくて、
`AbstractBottleController.HandleOnEnterTile`eventに実装を付与するように変更します。


逆になぜ、エラーが起きない場合があるのか。。。

2020-10-10 09:18 UTC, xiii111 requested changes
ざっとレビューしました！ちょっと Action の使い方に疑問があったので解説欲しいです！

2020-10-10 09:18 UTC, xiii111 commented on Assets/Project/Scripts/GamePlayScene/Bottle/AbstractBottleController.cs
> +        public event Action<GameObject> HandleOnGetDamaged;
というか， `OnGetDamaged` って名前でいいじゃん

2020-10-10 09:18 UTC, xiii111 commented on Assets/Project/Scripts/GamePlayScene/Bottle/AbstractBottleController.cs
> +        public virtual void OnEnterTile(GameObject targetTile)
実装に違和感を感じる．
`Action` が折角あるんだから，この関数は要らなくない？

購読する側は `HandleOnEnterTile += HogeFunc` をすればいい．例えば `NormalBottleController` でやる．発火する側はわざわざこの関数を呼ばなくても， `HandleOnEnterTile?.Invoke` をよべばいい．この関数があったら `Action` にした旨味が減ってるように見えるけど間違ってる？

2020-10-10 09:18 UTC, xiii111 commented on Assets/Project/Scripts/GamePlayScene/Bottle/AbstractBottleController.cs
> +        public virtual void OnEnterTile(GameObject targetTile)
以下同様

2020-10-10 09:18 UTC, xiii111 commented on Assets/Project/Scripts/GamePlayScene/Bottle/DynamicBottleController.cs
> +        public event Action HandleOnStartMove;
`Handle` 消そう．以下同様

2020-10-10 09:18 UTC, xiii111 commented on Assets/Project/Scripts/GamePlayScene/Bottle/DynamicBottleController.cs
> +        private void Flicked(object sender, EventArgs e)
ここで `Handle` を消したのはなぜ？

2020-10-10 09:18 UTC, xiii111 commented on Assets/Project/Scripts/GamePlayScene/Bottle/SelfishEffectController.cs
> +            _bottleController.HandleOnEndProcess += HandleOnEndProcess;
購読っていつ解除される？解除されなかったらメモリリークする

2020-10-10 09:18 UTC, xiii111 commented on Assets/Project/Scripts/GamePlayScene/Bottle/SelfishEffectController.cs
> +        public void HandleOnStartMove()
```suggestion
        private void HandleOnStartMove()
```
じゃない？
以下同様

2020-10-10 09:36 UTC, xiii111 commented on Assets/Project/Scripts/GamePlayScene/Bottle/LifeEffectController.cs
> +            _bottleController.HandleOnEndProcess += HandleOnEndProcess;
購読の解除されている？

2020-10-10 09:36 UTC, xiii111 commented on Assets/Project/Scripts/GamePlayScene/Bottle/AbstractBottleController.cs
> +        public virtual void OnEnterTile(GameObject targetTile)
`OnGetDamaged` を正しい使われ方をしているように見える． `AbstractBottleController` が `Action` を公開． `LifeEffectController` が `HandleOnGetDamaged` で購読． `AbstractBottleController` ( ここは `Action` の公開元と同じある必要はない）が `OnHandleOnGetDamaged?.Invoke` にて発火

2020-10-10 12:24 UTC, xiii111 commented on Assets/Project/Scripts/GamePlayScene/Bottle/AbstractBottleController.cs
> +        public bool IsAttackable => HandleOnGetDamaged != null;
ごめんなさい．これミスです． `OnGetDamaged` です

2020-10-10 12:32 UTC, takesi0627 commented
> > `Action` の宣言について、今のどころ `protected` でよさあそうと思いました。
> 
> 精査してみます。
> 
> > `FlickGesture.cs`とかを参考にして書くと丁寧かも。
> > ![image](https://user-images.githubusercontent.com/17778395/95415960-95d7d500-096c-11eb-9940-6388e475dc9b.png)
> 
> これが主流？というか一般的な感じ？
> なんで分けてるんだろう。。。？

アサイン(set)を制限するためかと思います。

2020-10-10 12:52 UTC, takasusuke commented
> > > `FlickGesture.cs`とかを参考にして書くと丁寧かも。
> > > ![image](https://user-images.githubusercontent.com/17778395/95415960-95d7d500-096c-11eb-9940-6388e475dc9b.png)
> > 
> > 
> > これが主流？というか一般的な感じ？
> > なんで分けてるんだろう。。。？
> 
> アサイン(set)を制限するためかと思います。

んーーーーごめん、わからん。。。
ミーティングの時にもうちょい詳しく聞く。。。

2020-10-10 13:50 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/Bottle/SelfishEffectController.cs
> +        public void HandleOnStartMove()
b2d94f3 で修正しました

2020-10-10 13:50 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/Bottle/DynamicBottleController.cs
> +        private void Flicked(object sender, EventArgs e)
気の迷いです
ac6ba5d で修正しました

2020-10-10 13:51 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/Bottle/DynamicBottleController.cs
> +        public event Action HandleOnStartMove;
ac6ba5d で修正しました

2020-10-10 13:52 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/Bottle/AbstractBottleController.cs
> +        public bool IsAttackable => HandleOnGetDamaged != null;
a0b6cb4 で修正しました

2020-10-10 13:52 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/Bottle/AbstractBottleController.cs
> +        protected event Action<GameObject> HandleOnExitTile;
a0b6cb4 で修正しました

2020-10-10 13:52 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/Bottle/AbstractBottleController.cs
> +        protected event Action<GameObject> HandleOnEnterTile;
a0b6cb4 で修正しました

2020-10-10 13:53 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/Bottle/AbstractBottleController.cs
> +        public event Action<GameObject> HandleOnGetDamaged;
a0b6cb4 で修正しました

2020-10-10 13:53 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/BoardManager.cs
> +            if (!_bottlePositions.ContainsKey(bottle.gameObject)) return -1;
a0b6cb4 で修正しました
このbranchの前の状態に戻りました

2020-10-10 13:55 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/Bottle/AbstractBottleController.cs
> +        public virtual void OnEnterTile(GameObject targetTile)
a0b6cb4 で修正しました

2020-10-10 13:56 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/Bottle/LifeEffectController.cs
> +            _bottleController.HandleOnEndProcess += HandleOnEndProcess;
2096c09 で解除するようにしました

2020-10-10 13:56 UTC, takasusuke commented on Assets/Project/Scripts/GamePlayScene/Bottle/SelfishEffectController.cs
> +            _bottleController.HandleOnEndProcess += HandleOnEndProcess;
2096c09 で解除するようにしました

2020-10-10 13:58 UTC, takasusuke commented
a0b6cb4
[eventは外部クラスからは呼べない](https://stackoverflow.com/questions/253757/why-events-cant-be-used-in-the-same-way-in-derived-classes-as-in-the-base-class)ので、イベントを発火するクラスを作成して、
`BoardManager`からはそれを呼んでます

@xiii111 改めてお願いいたします

2020-10-10 14:56 UTC, takasusuke commented
abc774a
`Dictionary`参照時のnull errorや、前々からたまに出ていた"ステージ開始と同時に成功状態になるバグ"を修正しました。

成功判定ハンドラが付与されていない場合に、成功扱いとしていましたが、これではボトルAだけが作成されて成功判定が行われた時に、ボトルAの状態のみで判定されて成功扱いになっていました。

成功判定は`NormalBottleController`のみの機能だと思うので、呼び出し側をいじりました。
もし、成功判定が複数の`Controller`で実装されるなら他と同じくハンドラで実装すれば良いかと思います。

2020-10-13 12:23 UTC, xiii111 commented
後でみます

2020-10-13 13:31 UTC, xiii111 commented
> eventは外部クラスからは呼べないので、イベントを発火するクラスを作成して、BoardManagerからはそれを呼んでます

event が外部から呼べないのは理解しました．その C# の文法的経緯を見たら，外部から呼び出すことを制限するために event は delegate を拡張して実装していると分かりました．例えば，ボタンのタップイベントだったら，その event を宣言したクラス内からしか発火させないことが制約として大切です．うっかりイベントを発火させてしまうので．一方で，今回の `OnEnterTile` などの event はそのような制約をつけることが適切ですかね？event でなく delgate を使えば，外部クラスから発火させることもできるのですが，今回のコンテキストはどっちが良いかとか考えた経緯あったら教えて欲しいです！

2020-10-13 13:33 UTC, xiii111 commented
今からもう一度全差分見直すので，少し待ってください🙏

2020-10-13 14:32 UTC, xiii111 reviewed
コメントしました！細かい文法的な指摘ばかりです

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/AbstractBottleController.cs
> +        private event Action<GameObject> _onGetDamaged;
ちなみにこの変数は， `protected` までは許容されるであってますか？

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +            }
```suggestion
            add => _onPressed += value;
            remove => _onPressed -= value;
```

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +        private event Action _onPressed;
```suggestion
        private event Action _onPressedInvoker;
```

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +            }
```suggestion
            add => _onReleased += value;
            remove => _onReleased -= value;       
```

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +        private event Action _onReleased;
```suggestion
        private event Action _onReleasedInvoker;
```

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +            }
```suggestion
            add => _onEndProcess += value;
            remove => _onEndProcess -= value;
```

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +        public event Action OnPressed
`OnStartMove` と合わせるなら
```suggestion
        public event Action OnStartPressed
```

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +        public event Action OnEndProcess
この名前の方がいいかも
```suggestion
        public event Action OnEndGame
```

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +        private event Action _onEndProcess;
```suggestion
        private event Action _onEndProcessInvoker;
```

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +            }
```suggestion
            add => _onSucceed += value;
            remove => _onSucceed -= value;
```

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +        public static event Action OnSucceed
この名前の方がいいかも
```suggestion
        public static event Action OnSucceedGame
```

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +        private static event Action _onSucceed;
```suggestion
        private static event Action _onSucceedGameInvoker;
```

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +        public static event Action OnFail
この名前の方がいいかも
```suggestion
        public static event Action OnFailGame
```

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +            }
```suggestion
            add => _onFail += value;
            remove => _onFail -= value;
```

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +        private static event Action _onFail;
```suggestion
        private static event Action _onFailGameInvoker;
```

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/NormalBottleController.cs
> +            onExitTile += HandleOnExitTile;
これは `OnEnable` で書けるよね

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/NormalBottleController.cs
> +            onExitTile -= HandleOnExitTile;
これは `OnDisabled` で書けるよね

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/NormalBottleController.cs
> +            return _targetPos != 0 ? BoardManager.Instance.GetBottlePos(this) == _targetPos : false;
```suggestion
            return _targetPos != 0 && BoardManager.Instance.GetBottlePos(this) == _targetPos;
```

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/NormalBottleController.cs
> +        private void DoWhenSuccess()
```suggestion
        private static void DoWhenSuccess()
```

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/NormalBottleController.cs
>              GameObject.FindObjectOfType<GamePlayDirector>().CheckClear();
関係ないけど
```suggestion
            FindObjectOfType<GamePlayDirector>().CheckClear();
```

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/LifeEffectController.cs
> +        private Animator _animator;
これ使ってなくない？

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/AbstractBottleController.cs
> +        public void TriggerOnEnterTile(GameObject targetTile)
悩んだけど，外部クラスから event を発火するケースの方がレアな気がしたので．そのケースでは一旦 `Trigger{event 名}` という関数を通して発火させることにしましょう 👍

2020-10-13 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +            return _src.BottleDatas?.Where(x => x.type == EBottleType.Normal || x.type == EBottleType.AttackableDummy);
なんかここ変更漏れしそうだから， `AbstractBottleController` の `IsAttackable` を使いたいなと思ったけど，なんか `AimingMeteorite` とかも関連してきてて簡単じゃなさそうだな

2020-10-13 14:33 UTC, xiii111 commented
@takasusuke 

> なるほど、別にこだわりとか無いですね
> バッドプラクティスぽいので、発火メソッド持ってるeventはdelegateに変えていいかも.

意見ありがとう．もっと調べればベストプラクティスがわかると思うんだけど，一旦以下でコメントしたように，現状維持で大丈夫です👍
- https://github.com/LITO-apps/Treevel-client/pull/577#discussion_r503997964

2020-10-14 11:48 UTC, takasusuke commented on Assets/Project/Scripts/Utils.meta
> +fileFormatVersion: 2
5c358ed で削除しました

2020-10-14 11:48 UTC, takasusuke commented on Assets/Project/Scripts/Utils/Definitions/BottleDefinitions.cs
> +﻿namespace Project.Scripts.Utils.Definitions
5c358ed で削除しました

2020-10-14 11:49 UTC, takasusuke commented on Assets/Project/Scripts/Utils/Definitions/StringDefinitions.cs
> +﻿namespace Project.Scripts.Utils.Definitions
5c358ed で削除しました

2020-10-14 11:56 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/AbstractBottleController.cs
> +            }
良い

1f48d95 で修正しました

2020-10-14 11:56 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/AbstractBottleController.cs
> +            }
1f48d95 で修正しました

2020-10-14 12:05 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/AbstractBottleController.cs
> +        private event Action<GameObject> _onGetDamaged;
名前、良い
`**Invoker`は`protected`まで許容されるかどうか、今のところ需要が想像つかない。
`protected`に広げたくなった時に、許容するかもしれないし、設計を見直すかもしれない。

2020-10-14 12:05 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/AbstractBottleController.cs
> +        private event Action<GameObject> _onGetDamaged;
1f48d95 で修正しました

2020-10-14 12:05 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/AbstractBottleController.cs
> +        private event Action<GameObject> _onEnterTile;
1f48d95 で修正しました

2020-10-14 12:05 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/AbstractBottleController.cs
> +            }
1f48d95 で修正しました

2020-10-14 12:06 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/AbstractBottleController.cs
> +        private event Action<GameObject> _onExitTile;
1f48d95 で修正しました

2020-10-14 12:06 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +            }
1f48d95 で修正しました

2020-10-14 12:07 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +        private event Action _onStartMove;
1f48d95 で修正しました

2020-10-14 12:08 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +            }
1f48d95 で修正しました

2020-10-14 12:08 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +        private event Action _onEndMove;
1f48d95 で修正しました

2020-10-14 12:08 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +            }
1f48d95 で修正しました

2020-10-14 12:08 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +        private event Action _onPressed;
1f48d95 で修正しました

2020-10-14 12:08 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +            }
1f48d95 で修正しました

2020-10-14 12:08 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +        private event Action _onReleased;
1f48d95 で修正しました

2020-10-14 12:08 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +            }
1f48d95 で修正しました

2020-10-14 12:09 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +        private event Action _onEndProcess;
1f48d95 で修正しました

2020-10-14 12:11 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +            }
8431684 で修正しました

2020-10-14 12:12 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +        private static event Action _onSucceed;
8431684 で修正しました

2020-10-14 12:12 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +            }
8431684 で修正しました

2020-10-14 12:12 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +        private static event Action _onFail;
8431684 で修正しました

2020-10-14 12:12 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/NormalBottleController.cs
> +            return _targetPos != 0 ? BoardManager.Instance.GetBottlePos(this) == _targetPos : false;
天才

2020-10-14 12:20 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/NormalBottleController.cs
> +        private void DoWhenSuccess()
957211b で修正しました

意図と違うだろうけど、見直した結果、本来にこのメソッド内に書かれるべき成功時処理があったので、それをまとめました。

2020-10-14 12:20 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/NormalBottleController.cs
>              GameObject.FindObjectOfType<GamePlayDirector>().CheckClear();
957211b で修正しました

2020-10-14 12:28 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/LifeEffectController.cs
> +        private Animator _animator;
d95ee6c
ゲーム終了時も何もしない`LifeEffectAnimation`がループしていたので、終了するように変更しました

2020-10-14 12:30 UTC, takasusuke commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +            return _src.BottleDatas?.Where(x => x.type == EBottleType.Normal || x.type == EBottleType.AttackableDummy);
今後、増えてきたら、`EBottleType`の拡張メソッドに、`IsAttackable`を返すメソッドがあれば良さそう

2020-10-14 12:48 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/NormalBottleController.cs
> +            onExitTile -= HandleOnExitTile;
8168b8a で修正しました

2020-10-14 12:48 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/NormalBottleController.cs
> +            onExitTile += HandleOnExitTile;
8168b8a で修正しました

2020-10-14 12:49 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +        public event Action OnReleased
これは`Release`というジェスチャに紐づいているので、このままが良いですね

2020-10-14 12:52 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +        public event Action OnPressed
`Release`と似た理由になるけど、`Press`というジェスチャに紐づいているので、このままが良いです

2020-10-14 13:02 UTC, takasusuke commented
5c358ed : マージで消し忘れたファイルの削除
1f48d95 : eventのadd, removeの修正
8431684 : 1f48d95 と同じ修正、`GamePlayDirector`の修正し忘れてたので
957211b : `NormalBottle`の成功時の処理をまとめた
30958b7 : 短絡評価を用いたリファクタリング
d95ee6c : `LifeEffectAnimation`のストップ
14a841b : `LifeEffectAnimation`の追加
8168b8a : `OnEnable`, `OnDisable`での書き直し
1843c83 : `event`のリネーム


@xiii111 よろしくお願いしますーー

2020-10-14 13:03 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +        public static event Action OnSucceed
1843c83 で修正しました

2020-10-14 13:03 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +        public event Action OnEndProcess
1843c83 で修正しました

2020-10-15 11:05 UTC, xiii111 commented on Assets/Project/Scripts/Editor/StageDataEditor.cs
> +            return _src.BottleDatas?.Where(x => x.type == EBottleType.Normal || x.type == EBottleType.AttackableDummy);
確かに．てかそれ欲しいな．Issue にしといて欲しい

2020-10-15 11:05 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/LifeEffectController.cs
> +        private Animator _animator;
了解 !!

2020-10-15 11:07 UTC, xiii111 approved these changes
LGTM !! 最高の変更でした

2020-10-15 11:53 UTC, takasusuke commented
どうもー

2020-10-15 11:53 UTC, merged

2020-10-18 01:11 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +        public event Action OnReleased
ドキュメンテーションコメントから誤読した