ディレクトリ階層の刷新
LITO-apps/Treevel-client pull request #581
Opened 2020-10-11 05:12 UTC by xiii111

### 対象イシュー
Close #516 

### 概要
- Utils/ の階層がおかしいということで，ディレクトリ階層の刷新を行った
- ついでに namespace も変更． `Project.Scripts` の部分を `Treevel` に代替した

### 詳細

#### 現実装になった経緯
- #516

### 動作確認方法
- [ ] 今まで通り実行できること

2020-10-11 05:26 UTC, xiii111 commented
@takasusuke @takesi0627 レビューお願いします．全部見るのは大変だと思うので，ざっと動作確認と気になるところの確認などお願いします．namespace は各々の環境で自動補完ができるようにした方が良いです．

2020-10-11 08:33 UTC, takasusuke requested changes
お疲れ様です

動作確認できました

`Editor`以下のスクリプトの`namespace`を`Project.Scripts` → `Treevel`に変更お願いします

2020-10-11 08:33 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/UIs/StatusBarController.cs
> -#endif
これは残していいやつだと思う

2020-10-11 09:28 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/Constants.cs
> +            public const int NUMBER_BOTTLE_NUM = 8;
```suggestion
```
この制限多分もうないので消して欲しい。

2020-10-13 11:23 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/UIs/StatusBarController.cs
> -#endif
1c8a09f

2020-10-13 11:25 UTC, xiii111 commented on ProjectSettings/EditorSettings.asset
> +  m_ProjectGenerationRootNamespace: Treevel
namespace のルートに Treevel を設定

2020-10-13 11:25 UTC, xiii111 commented on Assembly-CSharp-Editor.csproj.DotSettings
> +	<s:Boolean x:Key="/Default/CodeInspection/NamespaceProvider/NamespaceFoldersToSkip/=assets_005Cproject_005Cscripts/@EntryIndexedValue">True</s:Boolean></wpf:ResourceDictionary>
Rider で適切な namespace を推薦するための変更．含めて損ないと思うので入れちゃった

2020-10-13 11:25 UTC, xiii111 commented on Assets/Project/Scripts/Common/Utils/Constants.cs
> +            public const int NUMBER_BOTTLE_NUM = 8;
0a89b64

2020-10-13 11:26 UTC, xiii111 reviewed
> Editor以下のスクリプトのnamespaceをProject.Scripts → Treevelに変更お願いします

db0cf16 で修正

2020-10-13 11:30 UTC, xiii111 commented
@takasusuke @takesi0627 再レビューおなしゃす！

2020-10-13 11:31 UTC, takasusuke approved these changes
㊗️

2020-10-13 11:32 UTC, xiii111 commented
感謝感激

2020-10-13 11:32 UTC, merged