個別記録画面のレイアウト作成
LITO-apps/Treevel-client pull request #591
Opened 2020-10-21 13:52 UTC by xiii111

### 対象イシュー
Close #564 

### 概要

### キャプチャ

### 動作確認方法

2020-10-21 13:54 UTC, xiii111 commented
### 進捗報告

![スクリーンショット 2020-10-21 22 38 04](https://user-images.githubusercontent.com/26104258/96729553-3a87f700-13f0-11eb-8edd-139ac4e7236d.png)

2020-10-24 12:43 UTC, xiii111 commented
画面下部の季節ボタンの実装を変更（通話より）
- 季節全体を覆う背景（灰色）を配置．radius を付与
- 4種類のボタン（透明）を配置．四角形にする
- 4種類のボタンのハイライトを配置（季節の色）．radius を付与
- toggle group を使う．

2020-11-01 00:09 UTC, xiii111 commented
@xiii111 残りタスクと，どれくらいに終わるかを報告する

2020-11-02 09:05 UTC, xiii111 commented
### 残りのタスクと，それぞれがどれくらいで終わりそうか
- [ ] 棒グラフ → prefab を作成し，ダミーを配置（丸みを帯びた長方形を作るだけならすぐできそう）
- [ ] x軸：棒グラフラベル（stage number）→ prefab を作成し，ダミーを配置（Text の Prefab を作るだけだから簡単そう）
- [ ] y軸：値ラベル → ダミー文字を入れて配置（比較的簡単か）
- [ ] 木を変更するプルダウン → Listener なしのボタンを配置（プルダウンっぽいアイコンが必要）
- [ ] ステージ選択画面に遷移するボタン → Listener なしのボタンを配置（右がとんがってるの難しそう）
- [ ] 季節を変更する Toggle → Listener なしの Toggle を配置（考えたくない．rounded corner を使いこなせないとダメ）

### 参考画像
|春|夏|
|---|---|
|![個別記録画面，春改良3](https://user-images.githubusercontent.com/26104258/88120566-291b2d00-cbfe-11ea-8033-cbb47ec62cff.png)|![個別記録画面，夏改良3](https://user-images.githubusercontent.com/26104258/88120581-36d0b280-cbfe-11ea-89fd-561b55d34014.png)|

2020-11-02 09:22 UTC, xiii111 commented
`develop` に追従し，季節を変更する Toggle の差分を Revert しました



<img src="https://user-images.githubusercontent.com/26104258/97851118-4cdf2a80-1d38-11eb-9efc-93cc4c818c14.png" width="300">

2020-11-03 01:19 UTC, takasusuke commented
7b26996 : 季節ToggleのPrefabを追加しました。Toggleの中身の実装はしていません。いかがでしょうか。

`Assets/Project/Actors/UI/MenuSelectScene/Record/SeasonSelectToggle.prefab`を
`MenuSelectScene/Record/Canvas/SafeAreaPanel/SnapScrollView/Content/IndividualRecord/`に配置。
`StartUpScene`から起動。`RecordScene`を開く。

`RoundCorner`はマテリアルごとにしか設定できないようなので、Toggle用のマテリアルを用意。
`Spring, Summer, Automn, Winter`Toggle用の`RoundCorner`のオブジェクトの他、背景に`Spring, Winter`と全く同じ大きさの`RoundCorner`のオブジェクトを配置。
背景部分は、左右の`RoundCorner`のオブジェクトと、真ん中部分の長方形の計３つのオブジェクトで構成されている。

もし、これで良い感じなら階層とか命名とかは自由に変更してください。

<img width="280" alt="スクリーンショット 2020-11-03 10 15 06" src="https://user-images.githubusercontent.com/26213141/97935985-873edb00-1dbd-11eb-84c1-d48d55f2c116.png"> <img width="281" alt="スクリーンショット 2020-11-03 10 15 31" src="https://user-images.githubusercontent.com/26213141/97935989-89089e80-1dbd-11eb-9af9-2cec6b592f35.png">

2020-11-06 15:57 UTC, xiii111 commented
- 9881f16 : prefab を scene に反映
- 74ee700 : テキストを配置
- 570e3bd : 余白など見た目を調整

これらにより，以下のような見た目になりました

|||
|---|---|
|![スクリーンショット 2020-11-07 0 53 01](https://user-images.githubusercontent.com/26104258/98386935-269cf000-2094-11eb-9d0a-9e9ec62d7007.png)|![スクリーンショット 2020-11-07 0 52 52](https://user-images.githubusercontent.com/26104258/98386930-24d32c80-2094-11eb-8693-6156107762f5.png)|

2020-11-09 14:22 UTC, xiii111 commented
e802155 : 棒グラフラベルの prefab を作成
1ca75c4 : 10 個分の棒グラフラベルを GraphArea という領域に均等に配置した

10 の数字が小さくなってしまうのを直すのは面倒なので一旦やらないです

<img src="https://user-images.githubusercontent.com/26104258/98552887-580afb00-22e2-11eb-9e2e-834fa73a96e0.png" width="300">

2020-11-10 11:12 UTC, xiii111 commented
こまめにまーじ

2020-11-10 12:05 UTC, xiii111 commented
87e0116 : 棒グラフ y 軸ラベルの prefab を作成
bf9b8e6 : 4 個分の棒グラフ y 軸ラベルを配置した

<img src="https://user-images.githubusercontent.com/26104258/98672005-72071500-2398-11eb-9234-4c4f6b3d514e.png" width="300">

2020-11-10 12:22 UTC, xiii111 commented
85599c0 : "プレイ回数" テキストを配置

|||
|---|---|
|![スクリーンショット 2020-11-10 21 18 11](https://user-images.githubusercontent.com/26104258/98673420-a4197680-239a-11eb-9543-7eb64ca00693.png)|![スクリーンショット 2020-11-10 21 18 25](https://user-images.githubusercontent.com/26104258/98673426-a5e33a00-239a-11eb-85ad-7e2b38945de1.png)|

2020-11-10 12:53 UTC, xiii111 commented
3c53180 : 木ボタンとステージ選択へボタンを配置した

なんか木ボタンと，ステージ選択へボタンの微妙に凝ったデザイン（ https://github.com/LITO-apps/Treevel-client/pull/591#issuecomment-720339205 ）が今回作った安易なデザインに対して優位性があると思えなくなってしまったので，とりあえずシンプルに作っちゃいました．部分的に今後デザインを直して行けたらなぁと思います

<img src="https://user-images.githubusercontent.com/26104258/98676464-fd83a480-239e-11eb-8826-1018cc9b83ca.png" width="300">

2020-11-10 12:55 UTC, xiii111 commented
0f07375 : 色を合わせた

<img src="https://user-images.githubusercontent.com/26104258/98676832-771b9280-239f-11eb-973e-3e3576dae08c.png" width="300">

2020-11-10 13:02 UTC, xiii111 commented
ce25534 : 棒グラフのフォントサイズを固定にした

<img src="https://user-images.githubusercontent.com/26104258/98677455-615a9d00-23a0-11eb-9ccb-d1adadb3a74b.png" width="300">

2020-11-10 13:04 UTC, xiii111 commented
@takasusuke @takesi0627 レビューお願いします．現状の懸念点は以下2点です．特段コメントがなければ，本 PR で対応するつもりはありません
- rounded corner は大きさによって丸みが違うため，棒グラフの高さによって丸みが変わってしまう
- 木ボタンと，ステージ選択へボタンが，当初のデザインと異なる

2020-11-11 15:03 UTC, takesi0627 commented
この二つが一つのプレハブとして作成した方が後々楽だと思います
![image](https://user-images.githubusercontent.com/17778395/98827602-668c1a80-247a-11eb-8fe3-fa19da71614e.png)

2020-11-11 15:04 UTC, takesi0627 commented
`AxisArea` は `GraphArea` に含まれた方が自然だと思いました（軸もグラフの一部だから）

2020-11-11 15:05 UTC, takesi0627 commented
木の選択は `DropDown` を使わないですか？

2020-11-11 15:11 UTC, takesi0627 commented
こちらの差分が出ていますので確認して欲しい
![image](https://user-images.githubusercontent.com/17778395/98828514-82dc8700-247b-11eb-9f73-d99cc6355b98.png)
![image](https://user-images.githubusercontent.com/17778395/98828573-94259380-247b-11eb-96ff-62154c223459.png)

2020-11-12 12:30 UTC, takasusuke requested changes
お疲れ様です。見た目はすばらしいです。

- `.../IndivisualRecord/AxisArea/Text`の４つにそれぞれ名前をつけて欲しい
- `.../IndivisualRecord/Button`の２つにそれぞれ名前をつけて欲しい
- `Text`オブジェクトは`Base Text`を使って欲しい(フォントなどを変更する時に楽)
- 容易に推測できない`Text`には名前をつけて欲しい("プレイ回数"の`Text`とかは`PlayNum`やら`Ylabel`やら)
- `.../IndivisualRecord/GraphArea/BarGraph`をprefabにして欲しい
- `BarGraph1`とかの子オブジェクトの`BarGraph`は`Bar`という名前でどうですか。
- `Assets/Project/Actors/UIs/MenuSelectScene/Record/`の要素をできれば`General`と`Indivisual`ディレクトリに分けて欲しい

`Toggle`のスペルミス直しといて、、、。
- `.../IndivisualRecord/SeasonSelectToggle/Background/Bar_Sumer_Auomn`→`.../IndivisualRecord/SeasonSelectToggle/Background/Bar_Summer_Autumn`
- `.../IndivisualRecord/SeasonSelectToggle/Background/Bar_Automn_Winter`→`.../IndivisualRecord/SeasonSelectToggle/Background/Bar_Autumn_Winter`
- `.../IndivisualRecord/SeasonSelectToggle/Toggle/Automn`→`.../IndivisualRecord/SeasonSelectToggle/Toggle/Autumn`
- `.../IndivisualRecord/SeasonSelectToggle/Toggle/Automn/AutomnBackground`→`.../IndivisualRecord/SeasonSelectToggle/Toggle/Autumn/AutumnBackground`

2020-11-12 12:48 UTC, takasusuke commented
今回のissueとは直接関わりありませんが、`RoundCorner`について。
デバイスの大きさでマテリアルの値が変わるので差分がちょくちょく出そうだけど、
ゲーム内で大きさが決まっているものについては楽そう。
(とりあえず1125x2436のデバイスでの値をcommitしてもらえれば)


以降は、今後の実装のメモです。特に返答は必要ないです。
ゲーム内で大きさが決まっていないもの(グラフの棒部分など)を同じ曲率で表現するためには、
- `RoundCorner`を拡張して、大きさに依存せず同じ曲率で丸められるようにする。
- 画像のタイリング(角の丸い正方形を作っておいて、下端、上端はそのまま、中央部分を縦に引き伸ばすことで、長さは違うけど角の曲率は同じものを作る)
の２通りで実現できるかなと現時点で思います。

前者は
- 自由に曲率を変えながら試せる
- 曲率の異なるオブジェクトの分だけマテリアルが必要
- 若干、シェーダの勉強が必要そう(コード見た感じ、本当に若干)
後者は
- 曲率を変えるには別画像が必要
- 曲率の異なるオブジェクトの分だけ画像が必要
- タイリングの方法を学ぶだけで実装の未来は見える
って感じだと思います。

2020-11-13 19:50 UTC, xiii111 commented
### レビューを受けて修正する内容
- [ ] グラフ本体とグラフのラベルを同じ prefab にする（ `.../IndivisualRecord/GraphArea/BarGraph` を prefab にする）
- [ ] `AxisArea` も `GraphArea` に含める
- [ ] `RoundedCorner` の `.mat` の差分をどうにかする
- [ ] `.../IndivisualRecord/AxisArea/Text`の 4 つにそれぞれ名前を付ける
- [ ] `.../IndivisualRecord/Button`の 2 つにそれぞれ名前を付ける
- [ ] `Text` には `Base Text` を使う
- [ ] 容易に推測できない `Text` には名前をつける（ `プレイ回数` の `Text` とかは `PlayNum` ．あとは `Ylabel` とか）
- [ ] `BarGraph` を `Bar` にリネーム
- [ ] `Assets/Project/Actors/UIs/MenuSelectScene/Record/`の要素を `General` と `Indivisual` ディレクトリに分けるなど，整理する
- [ ] `Toggle` のスペルミスを直す
    - `.../IndivisualRecord/SeasonSelectToggle/Background/Bar_Sumer_Auomn`→`.../IndivisualRecord/SeasonSelectToggle/Background/Bar_Summer_Autumn`
    - `.../IndivisualRecord/SeasonSelectToggle/Background/Bar_Automn_Winter`→`.../IndivisualRecord/SeasonSelectToggle/Background/Bar_Autumn_Winter`
    - `.../IndivisualRecord/SeasonSelectToggle/Toggle/Automn`→`.../IndivisualRecord/SeasonSelectToggle/Toggle/Autumn`
    - `.../IndivisualRecord/SeasonSelectToggle/Toggle/Automn/AutomnBackground`→`.../IndivisualRecord/SeasonSelectToggle/Toggle/Autumn/AutumnBackground`

2020-11-13 19:51 UTC, xiii111 commented
@takasusuke @takesi0627 お二人とも丁寧にレビューありがとうございます！！直していきます！

2020-11-13 20:31 UTC, xiii111 commented
### d6e804c
- `Record/Individual/Unused` は，以前記録画面のグラフ作成をした際に利用した prefab です．実装完了までに参考にする可能性があるのでいったん残している

2020-11-13 22:04 UTC, xiii111 commented
`RoundedCorner` の `.mat` の差分，出そうとすると出ない・・・笑

2020-11-14 07:03 UTC, takasusuke commented
> `RoundedCorner` の `.mat` の差分，出そうとすると出ない・・・笑

`StartUpScene`から実行して、個別記録画面開いたら出ん？？

2020-11-14 10:01 UTC, xiii111 commented
> > `RoundedCorner` の `.mat` の差分，出そうとすると出ない・・・笑
> 
> `StartUpScene`から実行して、個別記録画面開いたら出ん？？

もう一回やってみる！

2020-11-14 10:19 UTC, xiii111 commented
`.mat` ，同じデバイスサイズでも変更され続けちゃうな〜

2020-11-14 10:34 UTC, xiii111 commented
@takasusuke @takesi0627 再レビューお願いします！修正内容は https://github.com/LITO-apps/Treevel-client/pull/591#issuecomment-726998883 になります．あと，修正後のキャプチャを一応置いておきます！

<img src="https://user-images.githubusercontent.com/26104258/99145210-3d54cf80-26b0-11eb-8d88-67b2f05ecfc5.png" width="300">

2020-11-15 08:28 UTC, takasusuke commented on Assets/Project/Scenes/MenuSelectScene.unity
> +      value: ForthLabel
Fo"u"rth

2020-11-15 14:29 UTC, xiii111 commented on Assets/Project/Scenes/MenuSelectScene.unity
> +      value: ForthLabel
ワロタ

2020-11-15 14:32 UTC, xiii111 commented on Assets/Project/Scenes/MenuSelectScene.unity
> +      value: ForthLabel
4eafed4

2020-11-15 14:32 UTC, takasusuke approved these changes

2020-11-15 14:33 UTC, xiii111 commented
@takasusuke thanks!

2020-11-15 14:34 UTC, xiii111 commented
@takesi0627 よければレビューもらえると嬉しいです！

2020-11-16 14:42 UTC, takesi0627 commented
ToggleGroupの設定がされていなかったので e6e26f3 で設定しました。
![image](https://user-images.githubusercontent.com/17778395/99265185-beed5e80-2864-11eb-80fa-4e81135b02aa.png)


ただ、これでもトグルは想定通りに動作していない、原因は、トグルはイメージのイベントを受けて on/offをしているのですが、春以外のトグルはイメージのゲームオブジェクトが非アクティブになっているからイベントが発火されない。
この件に関しては次のタスクで解決するのもいいと思いますので修正するかどうかは自分で判断してください

2020-11-16 14:43 UTC, takesi0627 approved these changes

2020-11-16 23:03 UTC, xiii111 commented
> ToggleGroupの設定がされていなかったので [e6e26f3](https://github.com/LITO-apps/Treevel-client/commit/e6e26f34126ed93c672838e30d987cb1277bb42a) で設定しました。
> ![image](https://user-images.githubusercontent.com/17778395/99265185-beed5e80-2864-11eb-80fa-4e81135b02aa.png)
> 
> ただ、これでもトグルは想定通りに動作していない、原因は、トグルはイメージのイベントを受けて on/offをしているのですが、春以外のトグルはイメージのゲームオブジェクトが非アクティブになっているからイベントが発火されない。
> この件に関しては次のタスクで解決するのもいいと思いますので修正するかどうかは自分で判断してください

ありがとうございます！！！次のタスクでもまだやらないかもしれないですが， #566 のタスクでは確実にやると思います！

2020-11-16 23:03 UTC, merged