【ステージ概要】機能実装
LITO-apps/Treevel-client pull request #609
Opened 2020-11-12 16:58 UTC by takesi0627

### 対象イシュー
Close #569 

### 概要
#551 で作成したステージ概要ポップアップの機能実装

### 詳細
#### 現実装になった経緯

b739a8e : Unityアップグレード関連の差分
951daf1 : `Application.internetReachability` が `NotReachable`しか返ってこれなくなったため、サーバリクエスト飛ばしてレスポンスが返ってくるかどうかでローカルデータ使用するかどうかを判断するようにした。
8f1ed03 : `ETreeId`から `-`つなぎのキーを返す拡張メソッド
3d61a68 : API飛ばす処理、テキスト置き換え処理
5d9fb1e : `OverviewPopup.cs`を大掃除

#### 技術的な内容

### キャプチャ

### 動作確認方法
- [ ] `Spring-1-1`のステージ概要での表示と`curl localhost:8080/records/stats/stages/Spring-1-1`から得られたレスポンスの結果が同じであることを確認する

### 参考 URL
[`Application.internetReachability`が使えないについて](https://stackoverflow.com/questions/57929106/how-to-properly-check-for-internet-connection-in-unity/57931517#57931517)

2020-11-12 17:03 UTC, takesi0627 commented
@xiii111 @takasusuke レビューよろしくお願いします。`StageStats` のコードスタイルは今レスポンスに合わせています、どっちにするかはまた議論しましょう

2020-11-14 06:47 UTC, takasusuke commented on Assets/Project/Scripts/Modules/StageSelectScene/OverviewPopup.cs
> +            TimeSpan time = TimeSpan.FromSeconds(stats.min_clear_time);
```suggestion
            var time = TimeSpan.FromSeconds(stats.min_clear_time);
```

2020-11-14 06:59 UTC, takasusuke requested changes
動作OK!!
(キャプチャ欲しい)

- このタイミングで`transform.csv`の
```
StageSelectOverviewSuccessPercentage,前ユーザ成功割合,DUMMY
```
を
```
StageSelectOverviewSuccessPercentage,全ユーザ成功割合,DUMMY
```
に修正していただけませんか？

- リクエストを受け取る構造体をクライアントの記法にする、という話が出ていたと思うでのよろしくお願いいたします。

- `OverviewPopup`の`Awake()`で行っていた`transform.Find()`の処理を`OnEnable()`で行うことには反対です。ポップアップのON/OFFで毎回行う処理ではないと思います。

2020-11-14 07:07 UTC, takesi0627 commented
> * `OverviewPopup`の`Awake()`で行っていた`transform.Find()`の処理を`OnEnable()`で行うことには反対です。ポップアップのON/OFFで毎回行う処理ではないと思います。

`OnEnable` で行っていないと思います。（`Initialize`に移動しています）

なぜそうしたかというと、このポップアップは先にセットデータしてから `SetActive` にしていますので、 `Awake` は セットデータ（今の`Initialize`）の後に呼ばれています。データ渡した後すぐにテキストに適用したいので（余計にメンバー増やしたくない）、オブジェクトの取得とデータ渡すタイミングを同じようにした次第です。

2020-11-14 07:10 UTC, takasusuke commented
> > * `OverviewPopup`の`Awake()`で行っていた`transform.Find()`の処理を`OnEnable()`で行うことには反対です。ポップアップのON/OFFで毎回行う処理ではないと思います。
> 
> `OnEnable` で行っていないと思います。（`Initialize`に移動しています）
> 
> なぜそうしたかというと、このポップアップは先にセットデータしてから `SetActive` にしていますので、 `Awake` は セットデータ（今の`Initialize`）の後に呼ばれています。データ渡した後すぐにテキストに適用したいので（余計にメンバー増やしたくない）、オブジェクトの取得とデータ渡すタイミングを同じようにした次第です。

あ、ほんとだ。
差分見ながらでごっちゃになっちゃった。ごめんなさい。

2020-11-14 07:17 UTC, takesi0627 commented
> * リクエストを受け取る構造体をクライアントの記法にする、という話が出ていたと思うでのよろしくお願いいたします。

これについてまた議論すると思いますが、
サーバを修正しないのは同意しますけど、コードスタイルを合わせるために、わざわざマッピングする処理を書くのも違うだと思います。

`underbar_style`みてサーバからもらったデータだとわかるメリットもありますので、現状維持して、`Treevel.Common.Networks.Objects`で定義した構造体に別のルールにしてもいいんじゃないかと思っています

2020-11-14 08:30 UTC, xiii111 commented
ちょっと現状のコードも調査もきちんとできていない中，雑に投げますが， https://blog.yamamoworks.net/entry/ASPNET-Core-Web-API-with-SnakeCase-Body とかで snake_case と CamelCase の話が書かれていますね

2020-11-14 09:12 UTC, xiii111 reviewed
お疲れ様です！いくつかコメントしました．
動作確認は @takasusuke がやってくれたようなので，やっていません．

お願いします

2020-11-14 09:12 UTC, xiii111 commented on Assets/Project/Scripts/Common/Networks/Objects/StageStats.cs
> +        public string stage_id;
`snake case` と `lowerCamelCase` の話ですが， `getter` ， `setter` を使って実装するパターンや， `DataContractJsonSerializer` を使うパターンなどが色々なところで紹介されていましたね．正直 `C#` のコーディング規約に沿ってないコードを技術的な問題で放置したくはないですが，そのタスクはそれだけでそこそこのボリュームのタスクになりそうなので，今回は見送っても良いかもしれません．Issue は作っておいてもらえると助かります

- https://3c1u.hatenablog.com/entry/2019/10/05/164433

2020-11-14 11:17 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/TreeId.cs
> +            return treeId.ToString().Replace("_", "-");
`enum` なので `-` が使えません

2020-11-14 11:18 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/StageSelectScene/OverviewPopup.cs
> +            clearPercentageText.text = string.Format("{0:n2}%", stats.clear_rate * 100f);
採用

2020-11-14 11:20 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Networks/IServerRequest.cs
> -            if (Application.internetReachability == NetworkReachability.NotReachable) {
動かなくなったのもそうだけど、[Unity公式](https://docs.unity3d.com/ScriptReference/Application-internetReachability.html)はこれを使って接続状況を調べるのは非推奨になっている

2020-11-14 11:21 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Networks/Objects/StageStats.cs
> +        public string stage_id;
```
[Serializable]
public struct Senko {
    public string SenkoSan {
        get => senko_san;
        set => senko_san = value;
    }

    [SerializeField] private string senko_san;
}
```
この方法にしたいと思います

2020-11-14 11:29 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Networks/Objects/StageStats.cs
> +        public string stage_id;
18d6633 で修正

2020-11-15 08:38 UTC, takasusuke commented on Assets/Project/Scripts/Modules/StageSelectScene/OverviewPopup.cs
> +                var gimmickOverviewBottle = appearingGimmicks.transform.Find($"GimmickOverview{i}");
なんでこれ`Bottle`って付いてるんだっけ。

2020-11-15 08:40 UTC, takasusuke commented
> * このタイミングで`transform.csv`の
> 
> ```
> StageSelectOverviewSuccessPercentage,前ユーザ成功割合,DUMMY
> ```
> 
> を
> 
> ```
> StageSelectOverviewSuccessPercentage,全ユーザ成功割合,DUMMY
> ```
> 
> に修正していただけませんか？

よろしくお願いします

2020-11-15 13:57 UTC, xiii111 commented on Assets/Project/Scripts/Common/Networks/IServerRequest.cs
> -            if (Application.internetReachability == NetworkReachability.NotReachable) {
ほんとだ．この辺テストケースちゃんと作って動作確認しないと，エッジケースで動かなくなりそうだよね〜（まだまだ先の話だけど）この件は大丈夫です👍

2020-11-15 13:58 UTC, xiii111 commented on Assets/Project/Scripts/Common/Networks/Objects/StageStats.cs
> +        public string stage_id;
おおお，すごく良くなった！

2020-11-15 13:59 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/TreeId.cs
> +            return treeId.ToString().Replace("_", "-");
知らなかった〜了解！

2020-11-15 13:59 UTC, xiii111 commented on Assets/Project/Scripts/Modules/StageSelectScene/OverviewPopup.cs
> +        public void Initialize(ETreeId treeId, int stageNumber, StageStats stats)
以下でやってくれてるね！Resolve!
- c3ae4d1

2020-11-15 14:00 UTC, xiii111 approved these changes
LGTM!

2020-11-19 12:23 UTC, takasusuke approved these changes
approve

2020-11-19 12:24 UTC, merged