個別記録画面のレイアウトに機能やデータ注入を実装する
LITO-apps/Treevel-client pull request #614
Opened 2020-11-18 15:22 UTC by xiii111

### 対象イシュー
Close #565 

### 概要

### 詳細

#### 現実装になった経緯

#### 技術的な内容

### キャプチャ

### 動作確認方法

### 参考 URL

2020-11-23 14:16 UTC, xiii111 commented
27abf56 で `RoundedCorner` を利用しないようにしました．そのため，特定の UI が丸められていません．
#620 で対応するという話になったので，概要を更新しました

2020-11-23 16:37 UTC, xiii111 commented
@takasusuke @takesi0627 レビューお願いします！

2020-11-25 11:16 UTC, takasusuke commented
お疲れさま〜
動作確認だけした状態です！
- 桜のドロップダウンはすごい小さい文字で出ていますが、それは#566 で一緒に直す、という認識でいいですか？
- 棒グラフをタップとかで選択したらポップアップが出て回数が表示される、的なのは、、、？？
など、このbranchの対象じゃない部分を若干説明してもらえると助かります！

2020-11-25 15:35 UTC, takesi0627 approved these changes
`ClearStageNumDirector` は `StageSelectDirector` や `LevelSelectDirector` などの階層？と混同してしまうので `Director`ではなく他の名前にしてほしい。 `Controller`、`Component`とかがいいかも。

2020-11-25 15:35 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            var clearStageNum = stageStatuses.Select(stageStatus => stageStatus.successNum > 0 ? 1 : 0).Sum();
```suggestion
            var clearStageNum = stageStatuses.Count(stageStatus => stageStatus.successNum > 0);
```

2020-11-25 15:35 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            var clearStageNum = _stageStatuses.Select(stageStatus => stageStatus.successNum > 0 ? 1 : 0).Sum();
```suggestion
            var clearStageNum = _stageStatuses.Count(stageStatus => stageStatus.successNum > 0);
```

2020-11-25 15:36 UTC, takesi0627 commented
`Request Change`押そうとしたけど何故かアプルーブになっちゃったw

2020-11-25 15:45 UTC, takesi0627 commented
動作確認しました。 @takasusuke の質問以外特に問題ありませんでした

2020-11-26 11:30 UTC, takasusuke requested changes
お疲れ様でございます(-_-)

2020-11-26 11:30 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/ClearStageNumDirector.cs
> +        public void Setup(int clearStageNum, int totalStageNum, Color mainColor)
```suggestion
        public void SetUp(int clearStageNum, int totalStageNum, Color mainColor)
```
個人的にはこっち派

2020-11-26 11:30 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            _playDays.text = RecordData.Instance.StartupDays.ToString();
`_playDays.text`のセットは設定画面でリセットされないから、`Awake()`で良いかも

2020-11-26 11:30 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +
空行

2020-11-26 11:30 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }
```suggestion
            if (challengeNumMax > 990) {
                maxAxisLabelNum = 990;
                showPlus = true;
            } else {
                maxAxisLabelNum = (float) Math.Ceiling(challengeNumMax / 30) * 30;
            }
```

2020-11-26 11:30 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            _graphAxisLabels[2].text = showPlus ? ((int) maxAxisLabelNum).ToString() : (int) maxAxisLabelNum + "+";
`showPlus`の`T/F`逆じゃない？？

2020-11-26 11:30 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +                    var anchorMaxY = Mathf.Min(0.1f + 0.9f * challengeNum / maxAxisLabelNum, 1.0f);
ここの0.1fはコンポーネントのanchorのminYから取ってきた方が安全。

2020-11-26 11:30 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }
30, 990はメンバ変数に定数宣言お願いします。

2020-11-26 11:30 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            _graphAxisLabels[2].text = showPlus ? ((int) maxAxisLabelNum).ToString() : (int) maxAxisLabelNum + "+";
`_graphAxisLabels`のサイズでfor文回したい。。。
レイアウト変わることあるだろうからここは変更しなくても良いが、気になる。。。

2020-11-26 11:34 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }
このsuggested changeは普通に嘘ついたわ。。。
(✖︎o✖︎)

2020-11-26 11:35 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            float maxAxisLabelNum;
`int maxAxisLabelNum;`で進めた方が納得せん？

2020-11-26 11:39 UTC, xiii111 commented
@takasusuke 

> * 桜のドロップダウンはすごい小さい文字で出ていますが、それは#566 で一緒に直す、という認識でいいですか？

これは， #566 ですね

> * 棒グラフをタップとかで選択したらポップアップが出て回数が表示される、的なのは、、、？？

完全に忘れてた．通信するし別 Issue 作ってやるわ → #626

2020-11-26 11:58 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/ClearStageNumDirector.cs
> +        public void Setup(int clearStageNum, int totalStageNum, Color mainColor)
https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q14136299469 こんなのを見たので， `SetUp`

2020-11-26 12:03 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            _playDays.text = RecordData.Instance.StartupDays.ToString();
これはリセットされるからこのままで！

2020-11-26 12:12 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }
```
maxAxisLabelNum = Math.Clamp(Math.Ceiling(challengeNumMax / 30) * 30, 30, 990);
```

2020-11-26 12:18 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }
`maxAxisLabelNum = Mathf.Clamp((float)(Math.Ceiling(challengeNumMax / 30) * 30), 30.0f, 990.0f);`

2020-11-26 12:39 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            var clearStageNum = _stageStatuses.Select(stageStatus => stageStatus.successNum > 0 ? 1 : 0).Sum();
aba3bae

2020-11-26 12:39 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/GeneralRecordDirector.cs
> +            var clearStageNum = stageStatuses.Select(stageStatus => stageStatus.successNum > 0 ? 1 : 0).Sum();
aba3bae

2020-11-26 12:39 UTC, xiii111 commented
> `ClearStageNumDirector` は `StageSelectDirector` や `LevelSelectDirector` などの階層？と混同してしまうので `Director`ではなく他の名前にしてほしい。 `Controller`、`Component`とかがいいかも。

@takesi0627 5584d95

2020-11-26 12:40 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/GameDatas/StageData.cs
> +                .Select(stageId => $"{treeId.GetTreeIdAsKey()}{Constants.PlayerPrefsKeys.KEY_CONNECT_CHAR}{stageId}")
b991118

2020-11-26 12:40 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/ClearStageNumDirector.cs
> +        public void Setup(int clearStageNum, int totalStageNum, Color mainColor)
5390e10

2020-11-26 12:41 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +
af7fdb4

2020-11-26 12:45 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }
- a478ad6 : 定数宣言
- e3a58f7 : 30 まとめてたけど，30 は最小値と差の二つのコンテキストがあったので，定数を追加
- 41e5433 : 通話で 999 にしようってなった
- c438a98 : 通話で Clamp を使おうってなった

2020-11-26 12:47 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            _graphAxisLabels[2].text = showPlus ? ((int) maxAxisLabelNum).ToString() : (int) maxAxisLabelNum + "+";
可変長になったら for 文使う！

2020-11-26 12:48 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            _graphAxisLabels[2].text = showPlus ? ((int) maxAxisLabelNum).ToString() : (int) maxAxisLabelNum + "+";
> showPlusのT/F逆じゃない？？

`showPlus` 消えた

2020-11-26 12:54 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +                    var anchorMaxY = Mathf.Min(0.1f + 0.9f * challengeNum / maxAxisLabelNum, 1.0f);
7039661

2020-11-26 12:55 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            float maxAxisLabelNum;
気づいたら治ってた
- c438a98

2020-11-26 12:58 UTC, xiii111 commented
+ が表示されないみたいなので 9b6f1ea でフォントサイズを小さくした

2020-11-26 13:02 UTC, takasusuke approved these changes
ok

2020-11-26 13:13 UTC, merged