[WIP]汎用メッセージダイアログ
LITO-apps/Treevel-client pull request #627
Opened 2020-11-26 16:32 UTC by takesi0627

### 対象イシュー
Close #621 

### 概要

メッセージダイアログの実装

### 詳細

#### 現実装になった経緯

#### 技術的な内容

### キャプチャ
![image](https://user-images.githubusercontent.com/17778395/100374898-4fd7ed00-3050-11eb-98ee-c07e685ef3be.png)

### 動作確認方法

### 参考 URL

2020-11-29 09:04 UTC, takesi0627 commented on Assets/Project/Scenes/StartUpScene.unity
> +  m_SortingOrder: 102
UIManagerが持っているUIの優先度を上げました

2020-11-29 09:06 UTC, takesi0627 commented on Assets/Project/Scenes/StartUpScene.unity
> +    m_SubObjectName:
`UIManager` に `MessageDialog` をアタッチ

2020-11-29 09:06 UTC, takesi0627 commented on Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
> +    m_TargetAsset: {fileID: 0}
`MessageDialog`のプレハブをAAS化

2020-11-29 09:07 UTC, takesi0627 commented
@takasusuke @xiii111 レビューをよろしくお願いします。軽い方だと思います。

2020-11-30 00:22 UTC, xiii111 commented
@takesi0627 いつまでが良いですか？

2020-11-30 08:33 UTC, takesi0627 commented
#353 に必要な変更なので早めにレビューしていただけると助かります

2020-11-30 10:35 UTC, xiii111 commented
了解。今日か明日にやります

2020-11-30 11:57 UTC, xiii111 commented on Assets/Project/Scenes/StartUpScene.unity
> +  m_SortingOrder: 102
102 は適当の大きい数？

2020-11-30 12:20 UTC, xiii111 requested changes
### 動作確認
- [x] OKボタンを押したらログが出ること
- [ ] Cancelボタンを押したら閉じること
- [x] ポップアップの外側を押したら閉じること

いくつかコメントしました！

2020-11-30 12:20 UTC, xiii111 commented on Assets/Project/Resources/GameDatas/translation.csv
> +MessageDlgCancelBtnText,キャンセル,Cancel
経緯を忘れたんだけど、OK は何が起こることが期待されて、キャンセルは何が起こる期待されるんだっけ？現状 StartUpScene の OK はダイアログが消える。キャンセルは何も起きない。どっちを押したらダイアログが消えるのか、初見だと全く想像できないけど、これは仮でおいた UI だからってだけで、気にしなくて良いところ？

2020-11-30 12:20 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/UIs/MessageDialog.cs
> +                gameObject.SetActive(false);
`transition.csv` にも書いたけど、okButton はダイアログを閉じる、cancelButton では閉じない、ってどう分かる？cancelButton では何が起こる？

2020-11-30 12:20 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/UIManager.cs
> +        private AssetReferenceGameObject _messageDialogRef;
やっぱ `[SerializeField]` って上につけるべき？揃えた方が良いよね

2020-11-30 12:20 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/UIManager.cs
> +        /// 確認、キャンセルボタン付きメッセージダイアログを作成
```suggestion
        /// 確定、キャンセルボタン付きメッセージダイアログを作成
```

2020-11-30 12:20 UTC, xiii111 commented on Assets/Project/Scripts/Modules/StartUpScene/StartUpDirector.cs
> +            });
これらと、MultiLanguage の定義などは、この PR をマージするときに revert するのかな？

2020-11-30 12:20 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/UIManager.cs
> +            _messageDialog.gameObject.SetActive(true);
なるほど。UIManager に常に存在させて、GameObject を Active にするかどうかで管理するのね！（初期化、Destroy の時間を省略している？）この SetActive は Initialize したときにやりたいけど、Active == false のものは自身を SetActive(true) したりできないんだっけ？

2020-11-30 12:20 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/UIs/MessageDialog.cs
> +                gameObject.SetActive(false);
キャンセル → 常に存在。ダイアログを閉じるだけ。カスタマイズ不可
確定 → 存在させないこともできる。カスタマイズ可能

ってイメージであってる？だとすると、確定を表示させるかを設定できるようにしたいね

2020-11-30 13:25 UTC, takasusuke reviewed
- OK & キャンセルの２つのボタンのダイアログと、ボタンが１つだけのダイアログの２パターンがあると考えてました。いかがでしょうか？
- 背景部分をタップするとポップアップが消えますが、ちゃんとボタンを押さないと消えないようにするダイアログは需要があると思いますか？(エラーメッセージをユーザにちゃんと読んでもらいたいときとか？)

2020-11-30 13:25 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/UIManager.cs
> +        public void CreateOkCancelMessageDialog(ETextIndex textIndex, ETextIndex okTextIndex, Action okCallback)
```suggestion
        public void CreateOkCancelMessageDialog(ETextIndex message, ETextIndex okText, Action okCallback)
```

2020-11-30 13:25 UTC, takasusuke commented on Assets/Project/Scenes/StartUpScene.unity
> +  m_SortingOrder: 102
いっそのこと`200`でどうですか。
`StartUpScene`が`100~199`の順番を使うってことにして。(ここらへんの順序関係はUIをちゃんと考えるときにwikiか何かでまとめるつもり)

2020-11-30 14:50 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/UIManager.cs
> +        private AssetReferenceGameObject _messageDialogRef;
いっぱい並んでる時とかは頭につけた方がいいし、ここはただ長くなるから上につけるだけで、別に揃わなくてもいいと思います。

2020-11-30 14:53 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/UIManager.cs
> +            _messageDialog.gameObject.SetActive(true);
できると思いますが、ただそれの切り替えは `UIManager` がやるべきことだと思いました。
あと、`Initialize`「初期化」は「表示する」とは違うことと思うので表示は中でやらなくてもいいと思います

2020-11-30 15:04 UTC, takesi0627 commented
> * OK & キャンセルの２つのボタンのダイアログと、ボタンが１つだけのダイアログの２パターンがあると考えてました。いかがでしょうか？

なんか言ってた気がしたな・・今からもう一つのタイプを作る

> * 背景部分をタップするとポップアップが消えますが、ちゃんとボタンを押さないと消えないようにするダイアログは需要があると思いますか？(エラーメッセージをユーザにちゃんと読んでもらいたいときとか？)

まあ、確かにあちょっと考えたけど、そこまでカスタマイズしちゃうのかって感じ。
需要があると思うのでやります

2020-11-30 15:14 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/MessageDialog.cs
> +                gameObject.SetActive(false);
キャンセルボタンは完全に失念した。すみません。

一つだけのボタンの場合は今から実装します

2020-11-30 16:06 UTC, takesi0627 commented
- [x] キャンセルボタンに閉じる機能を追加
- [x] OKタイプダイアログの実装
- [x] 背景ボタンを無効化するメソッドを用意

デバッグはお手数おかけしますが、`SetUpDirector.cs:L28` の呼び出すところを変えるなどで確認してください。よろしくお願いします

2020-12-01 17:37 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/UIs/MessageDialog.cs
> +        }
```suggestion
            // OKボタンの位置設定
            if (dialogType == EDialogType.Ok_Cancel) {
                _okButton.transform.SetParent(_OkCancelTypeBtnPos, false);
                _cancelButton.gameObject.SetActive(true);
            } else if (dialogType == EDialogType.Ok) {
                _okButton.transform.SetParent(_OkTypeBtnPos, false);
                _cancelButton.gameObject.SetActive(false);
            }
        }
```

- `Ok`Dialogを作った後に、`OkCancel`Dialogを作ると、キャンセルが表示されない & Okの位置が中央になる
- `Ok`Dialogを作るときに、`SetBackgroundButtonActive(false)`にすると、次にDialogを作るときもその設定が反映される

```
private void Initialize() {
    SetBackgroundButtonActive(true);
}
```
みたいなのを`public void Initialize(dialogType, message, okText, okCallback)`から呼ぶと良いかも

2020-12-01 17:41 UTC, takasusuke commented
キャンセルの動作確認できました〜。

2020-12-02 00:03 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/UIManager.cs
> +        private AssetReferenceGameObject _messageDialogRef;
OK~~!

2020-12-02 00:04 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/UIManager.cs
> +            _messageDialog.gameObject.SetActive(true);
初期化することと、表示することは関心が分かれているべきで、その責務は UIManager が負うべきってことね！承知

2020-12-02 00:26 UTC, xiii111 reviewed
いくつかコメントしました

2020-12-02 00:26 UTC, xiii111 commented on Assets/Project/Actors/UIs/Common/MessageDialog.prefab
> +        m_CallState: 2
これねー OK ボタンは AddListener で登録していて、 Cancel ボタンは GUI で設定していると混乱するんだよな。スクリプトで登録して欲しいな

2020-12-02 00:26 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/UIs/MessageDialog.cs
> +        [SerializeField] private RectTransform _OkCancelTypeBtnPos;
長いけど、どのボタンの pos か分からない。どの pos か分からないことよりも長いことを懸念するならやらなくていい
```suggestion
        [SerializeField] private RectTransform _OkCancelTypeOkBtnPos;
```

2020-12-02 00:26 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/UIManager.cs
> +        /// <param name="okTextIndex"> OKボタン用文字 </param>
```suggestion
        /// <param name="message"> メッセージインデックス </param>
        /// <param name="okText"> OKボタン用文字 </param>
```

2020-12-02 00:26 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/UIManager.cs
> +        public void CreateOkMessageDialog(ETextIndex message, ETextIndex okText, Action okCallback)
`OkMessageDialog` の用途からすると、Action は特に必要ないように思えますが、どうですか？（警告などを伝えて OK を押して、ダイアログを閉じてもらうだけなど）もし、Action が必要ない場合が多いのであれば、この関数から Initialize を呼ぶときに空の Action を与えてしまって良い気がします

2020-12-02 00:29 UTC, xiii111 reviewed
動作確認問題なかった！

2020-12-02 00:29 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/UIManager.cs
> +        /// 確認、キャンセルボタン付きメッセージダイアログを作成
治ってない

2020-12-02 15:03 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/UIManager.cs
> +        public void CreateOkMessageDialog(ETextIndex message, ETextIndex okText, Action okCallback)
```suggestion
        public void CreateOkMessageDialog(ETextIndex message, ETextIndex okText, Action okCallback = null)
```

で対応します

2020-12-02 15:09 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/MessageDialog.cs
> +        }
>OkDialogを作った後に、OkCancelDialogを作ると、キャンセルが表示されない & Okの位置が中央になる
OkDialogを作るときに、SetBackgroundButtonActive(false)にすると、次にDialogを作るときもその設定が反映される

e0d2779 で修正

2020-12-02 15:10 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/UIManager.cs
> +        public void CreateOkMessageDialog(ETextIndex message, ETextIndex okText, Action okCallback)
4655025 で対応

2020-12-02 15:10 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/MessageDialog.cs
> +        [SerializeField] private RectTransform _OkCancelTypeBtnPos;
8ddf0a2

2020-12-02 15:31 UTC, takesi0627 commented on Assets/Project/Actors/UIs/Common/MessageDialog.prefab
> +        m_CallState: 2
cdbda18 で対応

2020-12-02 15:34 UTC, takesi0627 commented
> 動作確認問題なかった！一つコメント追加

5ee8ff1 で直っています・・・

2020-12-03 13:21 UTC, takasusuke approved these changes
GREAT=3=3=3!!!!

2020-12-03 14:49 UTC, takesi0627 commented
デバッグ用コードを削除しました。

2020-12-03 15:18 UTC, takesi0627 commented
`OkCancelTypeOkBtnPos` のレファランスが漏れてた

2020-12-04 00:24 UTC, xiii111 commented
> > 動作確認問題なかった！一つコメント追加
> 
> [5ee8ff1](https://github.com/LITO-apps/Treevel-client/commit/5ee8ff114808c03c238d9de4cb5a1666c44a4aaf) で直っています・・・

あれ、ごめん！リロードしてなかったのかも・・・

2020-12-04 00:29 UTC, xiii111 approved these changes
いやー素晴らしい！お疲れさま！

2020-12-04 14:03 UTC, merged