Button のダブルタップや同時タップをブロックする
LITO-apps/Treevel-client pull request #629
Opened 2020-11-28 09:46 UTC by xiii111

### 対象イシュー
Close #560 

### 概要
- 短時間の button ダブルタップを無効にする
- （結果的に）短時間の button 同時タップを無効にする（後にタップした方を無効にする）

### 詳細

### キャプチャ
|修正前|修正後|
|---|---|
|![修正前](https://user-images.githubusercontent.com/26104258/100498990-6c3b6d00-31a9-11eb-8f4e-d9ac4b9beeab.gif)|![修正後](https://user-images.githubusercontent.com/26104258/100498991-6e053080-31a9-11eb-8bb2-dd95a8a40954.gif)|

### 動作確認方法
- [ ] 上記キャプチャのように、Scene 読み込みを伴うボタンをダブルタップした場合に、後のタップが無効になっていること

### 参考 URL
- https://qiita.com/yuichi_katsuoka/items/0291a196d811a9d7be8a

2020-11-28 09:48 UTC, xiii111 commented
### 現状
- 大体終わっているが、全 Button に `ButtonClickBlocker` を Add するスクリプトがうまく動かない

2020-11-28 14:00 UTC, xiii111 reviewed
[セルフレビュー]
- Prefab をまず探索して、その後に Scene を探索

2020-11-30 00:56 UTC, xiii111 commented on Assets/Project/Scripts/Editor/ButtonClickBlockerAdder.cs
> +                    .Where(button => button != null)
8f6c194

2020-11-30 00:56 UTC, xiii111 commented on Assets/Project/Scripts/Editor/ButtonClickBlockerAdder.cs
> +                    .Where(button => button.gameObject.GetComponent<ButtonClickBlocker>() != null)
8f6c194

2020-11-30 00:56 UTC, xiii111 commented
> [セルフレビュー]
> 
> * Prefab をまず探索して、その後に Scene を探索

960866a

2020-11-30 00:58 UTC, xiii111 commented
### 7054a39
- 実際に `Button` に `ButtonClickBlocker` をアタッチ
- 変更された時に、自動で変更される関連（アプデ時に起こるやつ）が起きてる

2020-11-30 01:02 UTC, xiii111 commented
@takesi0627 @takasusuke お願いします！

2020-11-30 14:11 UTC, takasusuke requested changes
動作確認しました👍
- `ButtonClickBlocker`というクラス名、`MultiClickBlocker`とか用途に沿った名前が良いです。

2020-11-30 14:11 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/ButtonClickBlocker.cs
> +{
```
[RequireComponent(typeof(Button))]
``
ほしい

2020-11-30 14:11 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/ButtonClickBlocker.cs
> +        [SerializeField] private int _blockingTime = 1000;
これ`[SerializeField]`でなくても良いのでは。

2020-11-30 14:11 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/ButtonClickBlocker.cs
> +namespace Treevel.Common.Components
```suggestion
namespace Treevel.Common.Components.UIs
```
に階層移しても良いのでは？

2020-11-30 14:11 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/ButtonClickBlocker.cs
> +        private bool _isUnexpected = false;
参考URLみたいに`enable`を変更するかどうかのフラッグの方がしっくりくる。

2020-11-30 14:11 UTC, takasusuke commented on Assets/Project/Scripts/Editor/ButtonClickBlockerAdder.cs
> +        private static bool ChangeButtons()
呼び出し元を`AddButtonClickBlockerInAllButton`とかのメソッド名にして、
このメソッドを`AddButtonClickBlocker`とかにしていただきたい。
ドキュメンテーションコメントもそんな感じ。

2020-12-02 00:36 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/ButtonClickBlocker.cs
> +        [SerializeField] private int _blockingTime = 1000;
GUI から実行中など blocking time を確認できるように置いてる。見る機会が一切無さそうってことなら消しておくが。

2020-12-02 00:37 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/ButtonClickBlocker.cs
> +namespace Treevel.Common.Components
UI じゃないよ？

2020-12-02 00:46 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/ButtonClickBlocker.cs
> +{
今後 `BlockingButton` などを作って、そのボタンを `GameObject` にアタッチした時は `ButtonClickBlocker` を必ずアタッチする、などとする場合には `BlockingButton` に
```
[RequireComponent(typeof(ButtonClickBlocker))]
```
を付けるのは良いと思う。でも `ButtonClickBlocker` がアタッチされたら自動的に `Button` がアタッチされてしまうのは本意ではないと思う。ミスしてアタッチした場合に `Button` がアタッチされてしまうと、変な動作をしてしまいそう。

とはいえ、 `Button` がアタッチされていない `GameObject` に `ButtonClickBlocker` をアタッチするとエラーが発生するので、null check を追加しておいた → c585a84

2020-12-02 01:00 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/ButtonClickBlocker.cs
> +        private bool _isUnexpected = false;
参考 URL とは少し違うけど、そういう系統に変えた → 7ecfe8f

2020-12-02 01:01 UTC, xiii111 commented
以下、まだ終わってません。
- https://github.com/LITO-apps/Treevel-client/pull/629#pullrequestreview-540932820
- https://github.com/LITO-apps/Treevel-client/pull/629#discussion_r532623885

2020-12-02 11:50 UTC, xiii111 commented on Assets/Project/Scripts/Editor/ButtonClickBlockerAdder.cs
> +        private static bool ChangeButtons()
ごめんなさい。少し変更を混ぜてしまいましたが、以下で変更しました
- 2bc9b95

2020-12-02 11:50 UTC, xiii111 commented
> 動作確認しました👍
> 
> * `ButtonClickBlocker`というクラス名、`MultiClickBlocker`とか用途に沿った名前が良いです。

以下で変更しました！
- 2bc9b95

2020-12-02 11:57 UTC, xiii111 commented
@takasusuke 再レビューお願いします！先ほど develop をマージして、 `LevelTree.prefab` のコンフリクトを解決しました！

2020-12-02 12:05 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/ButtonClickBlocker.cs
> +        [SerializeField] private int _blockingTime = 1000;
なるほど。
```
using Treevel.Common.Attributes;
```
で
```
[SerializeField, NonEditable] private int _blockingTime = 1000f;
```
imspectorから確認できるけど、変更できないようにできる。

2020-12-02 12:06 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/ButtonClickBlocker.cs
> +namespace Treevel.Common.Components
確かに。
もっと種類が増えてきたら、UI関連のこういうクラスまとめれば良いか

2020-12-02 12:08 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/ButtonClickBlocker.cs
> +        [SerializeField] private int _blockingTime = 1000;
なんなら、エディタからなら変更できちゃっても良いと思ってるんだけど、どうかな

2020-12-02 12:08 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/ButtonClickBlocker.cs
> +namespace Treevel.Common.Components
@takasusuke に同意してもらえるなら Resolve !

2020-12-02 12:10 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/ButtonClickBlocker.cs
> +        [SerializeField] private int _blockingTime = 1000;
共通のprefabの値を設定するわけではなく、個々のボタンのダブルタップ防止時間を変更することになるので微妙に感じる。

2020-12-02 12:11 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/ButtonClickBlocker.cs
> +        [SerializeField] private int _blockingTime = 1000;
ふむふむ。確かに。個別に変更されたくないから NotEditable にする、で納得！変えます〜！

2020-12-02 12:14 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/ButtonClickBlocker.cs
> +        [SerializeField] private int _blockingTime = 1000;
3eeb550

2020-12-02 12:21 UTC, takasusuke commented
ここまでの変更自体はOKなんだけど、不具合に気付いてしまった。。。
再現手順
1.`MenuSelectScene`で`Spring-2`の木が押せない状態で押せないことを確認
2.`Spring-1`を押して`StageSelectScene`に遷移
3.`MenuSelectScene`に戻る
4.`Spring-2`が非解放状態なのに押せる

2020-12-02 12:30 UTC, xiii111 commented
> ここまでの変更自体はOK

ということで、以下は resolve にしますね！
- https://github.com/LITO-apps/Treevel-client/pull/629#discussion_r533819510
- https://github.com/LITO-apps/Treevel-client/pull/629#discussion_r532623885
- https://github.com/LITO-apps/Treevel-client/pull/629#pullrequestreview-540932820

2020-12-02 12:31 UTC, xiii111 commented
> 再現手順
> 1.`MenuSelectScene`で`Spring-2`の木が非解放状態で押せないことを確認
> 2.`Spring-1`を押して`StageSelectScene`に遷移
> 3.`MenuSelectScene`に戻る
> 4.`Spring-2`が非解放状態なのに押せる

んん、これはこのブランチで発生したのか。ピンと来なさすぎて怖い

2020-12-02 12:38 UTC, xiii111 commented
うん、案の定、以下のコミットからバグが混入
- 7054a39

2020-12-02 12:44 UTC, takasusuke commented
`Button`を使って`Scene`をLoadするとき、`HandleOnClick()`のうち、`_buttonEnabledChanged?.Invoke(false);`は変更前のSceneで呼ばれて、変更後のSceneで`_buttonEnabledChanged?.Invoke(true);`が呼ばれるっぽい？
その結果、全ての`Button`の`enabled`が`true`になってる感じがする。

`Button`の初期状態の`enabled`を保持しておいて、初期状態が`enabled==false`のButtonはそのままfalseにするとか。

`LevelTree`の`Button`の初期状態は`true`なので、
`Assets/Project/Actors/UIs/MenuSelectScene/LevelSelect/LeveTree.Prefab`の`Button.enabled`をfalseにしてもらえれば問題ないと思う。

同様の問題は`StageSelectScene`の`Stage`でも起こるけど、`Stage.Prefab`の`Button`は初期値`false`なので上記の変更さえ入れば大丈夫かと。

他にも、`false`のままにしておきたい`Button`があれば同様。

2020-12-02 12:51 UTC, xiii111 commented
直接的な原因は `MultiClickBlocker` の存在。Remove すれば、同現象は起きなくなる

2020-12-02 12:53 UTC, xiii111 commented
おお、上で大層なことが書かれてた。ありがとう

2020-12-02 15:44 UTC, takesi0627 commented
修正終わったらまた見ます

2020-12-03 13:12 UTC, takasusuke commented
Buttonの初期値見るのじゃダメかも。
`LevelTree`は初期値`enblad==false`にしても、そこから解放状態なら`enabled==true`に変更するから、`LevelTree`に関してはダブルタップ許す感じになっちゃうかも。

`Scene`を`Load`した直後に、`_buttonEnabledChanged?.Invoke(true);`だけ呼ばれるのなんとかした方が現実的かもしれない。。。

2020-12-04 00:18 UTC, xiii111 commented
@takasusuke 暫定対応だけど、 `interactable` を使うようにした。 `enabled` との違いは [この辺の記事](http://portaltan.hatenablog.com/entry/2016/05/24/144108) にまとめてある。今回のタスクで `interactable` を使うメリット・デメリットを言うと、以下のような感じ。

### メリット
- `LevelTree` , `Stage` など、別途 `enabled` を変更したい `Button` の邪魔をしない
- `interactable` にしてみると、本スクリプトの影響がどの程度なのか理解できる（デバッグの観点）
- 上記により、同時タップを適用するかどうか、ダブルタップを全ての `Button` で許さないようにするかなど、判断材料になる（意外と、本スクリプトの影響がでかいことに気付いた）

### デメリット
- 本番に入れるかどうかで考えると、 `interactable` は `Button` 自体が半透明になってしまうので、デザインに影響を与え、微妙そう
- 今後 `interactable` を利用する場合に、 `enabled` と同じ問題が起こる

このデメリットが大きいから変えてくれ！ってことだったら、再度検討する！とりあえず、一度実行してみると、こんなに無効になってるんだと思い、面白いと思う！（これをみて、 `blockingTime` も変更した）

2020-12-04 13:59 UTC, takasusuke commented
> ### デメリット
> * 本番に入れるかどうかで考えると、 `interactable` は `Button` 自体が半透明になってしまうので、デザインに影響を与え、微妙そう

`Button/Transition/Diabled Color`で`interactable`の`T/F`に応じたフィルタがかけらているようなので、この値を(255,255,255,255)にすれば、`interactable`の`T/F`で見た目が変わることはないので大丈夫です
この値を全ての`Button`の値で設定して欲しいところだけど、しんどいので、全ての`Button`の共通祖先`Prefab`を作り置き換えるissueがあれば良いと思います。

> * 今後 `interactable` をどこかで利用する場合に、 `enabled` と同じ問題が起こる
> 
確かに。そうそう無さそうだし、そうなったらそん時の人が苦労すれば良いさ。。。

2020-12-04 14:03 UTC, takasusuke commented
最近理解を改めたんだけど、
`[SerializeField]`だと、オブジェクトにその値が保存されているようなので、コードの値を変えても反映されないんですよね。。。
そこまで、ボタンのブロック時間をUIから見たい、というわけではなければ
`[Serialize Field, NonEditble]`を消した方が楽かも。。。

2020-12-04 15:12 UTC, xiii111 commented
- [ ] `[Serialize Field, NonEditble]` けす
- [ ] `Coroutine` + `enabled` で試す。うまくいかなかったら Issue にして、マージする

2020-12-05 12:55 UTC, xiii111 commented
@takasusuke すみません、 `coroutine` の使用や、現状の `async` のままで自身が `null` かどうかを見る、など色々試したのですが、思った動作になりませんでした。 `StartupScene` から `MenuSelectScene` に行く際に全ての `LevelTree` が `enabled == false` になったりしました。 `LevelTreeController` から `Button.enabled` をいじっているので、タイミングによって `enabled` がおかしくなっている可能性もあります。もう少し調べたらできるかもしれませんが、沼ったら長くなるので Issue を立てて、この PR では `interactable` を利用しようと思います！

2020-12-05 12:58 UTC, xiii111 commented
#636 を立てました！ approve ください！

2020-12-05 13:55 UTC, takesi0627 commented
@xiii111 一回試したコードをコミットしてもらえませんか

2020-12-05 14:08 UTC, takesi0627 requested changes

2020-12-05 14:08 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/MultiClickBlocker.cs
> +        [SerializeField] private Button _button;
今更申し訳ないですが、このスクリプトはボタンにアタッチしているので `_button` は `Awake` で `GetComponent`すれば取得できると思います。 `[SerializeField]` にしてエディターからアタッチする必要はないかと

2020-12-05 14:11 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/MultiClickBlocker.cs
> +        [SerializeField] private Button _button;
editor からアタッチしてないです

2020-12-05 14:11 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/MultiClickBlocker.cs
> +        [SerializeField] private Button _button;
`Reset()` で自動的にアタッチされます

2020-12-05 14:11 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/MultiClickBlocker.cs
> +        }
このメソッドはどこで使ってる？

2020-12-05 14:12 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/MultiClickBlocker.cs
> +        [SerializeField] private Button _button;
アタッチする必要はありますか

2020-12-05 14:13 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/MultiClickBlocker.cs
> +        }
アタッチされた時や、リセットが押された時に動く `MonoBehavior` のメソッドです
- https://docs.unity3d.com/ja/current/ScriptReference/MonoBehaviour.Reset.html

2020-12-05 14:15 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/MultiClickBlocker.cs
> +        }
なるほど。
でもそれでもやっぱり `SerializeField` は要らないじゃないですか

2020-12-05 14:16 UTC, xiii111 commented
> @xiii111 一回試したコードをコミットしてもらえませんか

色々試したので、その一つですが 476a7cb2 (`debug/block-double-tap`) みたいな感じだったと思います。 `StartUpScene` から `MenuSelectScene` に行った時に、 `enabled` がおかしくなります

2020-12-05 14:23 UTC, takesi0627 commented
なるほど・・・ `StartUpScene` はあらかじめ `MenuSelectScene` をロードしているから、今回は止めじゃいけなかったんですね

2020-12-05 14:25 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/MultiClickBlocker.cs
> +        }
ランタイム時に `GetComponent` をしないようにしたほうがパフォーマンスは上がりますが、その理論でいくと他に修正するところが多そうですし、ちゃんとパラメータに `GetComponent` のキャッシュをしていれば、大した問題じゃないと思ったので、言われた通りに修正します！

2020-12-05 14:32 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/MultiClickBlocker.cs
> +        }
a589182

2020-12-05 14:35 UTC, xiii111 commented
https://github.com/LITO-apps/Treevel-client/pull/629#issuecomment-739247496 でも言ったように、 `LevelTreeController` が `enabled` をいじっているというのも気になります。

2020-12-05 14:48 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/MultiClickBlocker.cs
> +        }
```suggestion
        private bool _shouldSkip = false;
        private void HandleButtonInteractableChanged(bool interactable)
        {
            if (_shouldSkip) {
                _shouldSkip = false;
                return;
            }

            if (enabled == false && interactable == false) {
                _shouldSkip = true;
            } else {
                enabled = interactable;
            }
        }
```
これでどうでしょうか。
一通り動作確認したが問題なさそう

2020-12-05 14:50 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/MultiClickBlocker.cs
> +        }
`enabled` は `button.enabled` ??

2020-12-05 14:51 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/MultiClickBlocker.cs
> +        }
そうか

2020-12-05 14:51 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/MultiClickBlocker.cs
> +        }
enabledだから問題ないか

2020-12-05 14:51 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/MultiClickBlocker.cs
> +        }
ちょっと確認する

2020-12-05 14:54 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/MultiClickBlocker.cs
> +        }
問題あった

2020-12-05 14:54 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/MultiClickBlocker.cs
> +        }
無視してくれ

2020-12-05 14:55 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/MultiClickBlocker.cs
> +        }
涙

2020-12-05 14:59 UTC, takesi0627 commented
まだ色々試してみますが、先に意見を言いますと、僕は問題解決せずにマージするのは反対です。
このタスク最初はそもそもただシーンが一瞬複数ロードされるだけで、動作には影響ないので急いでマージする必要はないですし、
https://github.com/LITO-apps/Treevel-client/pull/629#issuecomment-738798802 でも言ったように、今の状態だと後々また問題起こすのも目に見えているなので、調査などに時間かけても先にマージするものではないと思います。

2020-12-05 15:02 UTC, xiii111 commented
`interactable` で問題は発生していませんが、それでもマージしたくないのであれば PR を放置しますか？

2020-12-05 15:04 UTC, xiii111 commented
見た目の話？あと `interactable` を使えないことか。まぁ、確かにそれを懸念するならマージせずに凍結しても良いかもね

2020-12-05 15:09 UTC, takasusuke commented
`LevelTree`や`StageButton`など`enabled`をいじってるとこも含めて実装を考えることができるので、一旦マージしない、というのは良いのかもしれません。

2020-12-05 15:11 UTC, xiii111 commented
色々調査を進めて、憂いのない PR としてマージするようにしましょうか！

2020-12-05 15:12 UTC, takesi0627 commented
時間をかけて実装してもらった上で申し訳ないが、それでお願いします

2020-12-05 15:12 UTC, takasusuke commented
> 時間をかけて実装してもらった上で申し訳ないが、それでお願いします

わかる。
とても勉強になりました。

2020-12-05 15:13 UTC, xiii111 commented
懸念点含めて納得したので、全く問題ないです！！むしろ時間かけすぎてしまって、申し訳ない。

2021-02-18 00:15 UTC, xiii111 commented
📝 凍結されてるので Draft にしておく

2021-08-05 17:02 UTC, takesi0627 commented
@LITO-apps/engineer  これはクローズしていいのでは？

2021-08-08 07:20 UTC, xiii111 commented
#560 がクローズされたので閉じる

2021-08-08 07:20 UTC, closed without merging