個別記録画面を、すべての季節・木に拡張する
LITO-apps/Treevel-client pull request #673
Opened 2020-12-09 11:31 UTC by xiii111

### 対象イシュー
Close #566

### 概要

### 詳細

#### 現実装になった経緯

#### 技術的な内容

### キャプチャ

### 動作確認方法

### 参考 URL

2020-12-09 11:39 UTC, xiii111 commented
@takesi0627 

fbe5441 : 現在の季節・木を状態として持つようにした

d8212c2 : Text を BaseText に変えた際に外れていた参照を元に戻した

<img src="https://user-images.githubusercontent.com/26104258/101624979-2068ad80-3a5e-11eb-9dd7-5699d49595ca.png" width="350">

2df0d6f : Dropdown の選択肢で、季節に応じた木を表示するようにした

<img src="https://user-images.githubusercontent.com/26104258/101625198-70477480-3a5e-11eb-8e85-b5ae8326ee34.png" width="350">

2020-12-19 15:16 UTC, takesi0627 commented
- [x] プルダウンイベント
- [x] トグルプレハブ調整
- [ ]  プルダウン見た目調整
- [ ] トグルイベント

2020-12-22 16:35 UTC, takesi0627 commented
@xiii111 @takasusuke 
レビューよろしくお願いします。

@xiii111 おそらくPR出したからreviewerに設定できないのでそこはよしなにお願いします

2020-12-22 16:40 UTC, takesi0627 commented
ドロップダウンのアイコンも入れたかったけど、AASなど含む実装が多いし既に見積もり時間超えたので切り分けたいと思いました。
#686 にて対応予定です。

2020-12-24 17:19 UTC, takasusuke requested changes
お疲れ様です

2020-12-24 17:19 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
>              _clearStageNum.GetComponent<ClearStageNumController>().SetUp(clearStageNum, totalStageNum, Color.magenta);
ここの`Color.magenta`も今の季節の色でお願いします！

2020-12-24 17:19 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +        [SerializeField] private GameObject _dropdownTemplate;
これは何のためにあるのでしょう。。。。？

2020-12-24 17:19 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }).AddTo(this);
この部分を
```
SetDropDownOptions(_cirrentSeason);
```
より後に書けば`Skip(1)`無くて良いと思う。

2020-12-26 00:53 UTC, xiii111 commented
@takesi0627 

### 動作について
- `夏2` にいる状態から春のトグルを押下すると、表示されているデータは `春1` になっているのに、トグルのプルダウンは `春2` になっている

2020-12-26 01:35 UTC, xiii111 reviewed
とりあえず Rx 中心にコメントしました。まだコメントあるかもですが、結構コメントしたのでこれで議論したいです

2020-12-26 01:35 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/SeasonId.cs
> +                    return new List<ETreeId> {ETreeId.Winter_1, ETreeId.Winter_2, ETreeId.Winter_3};
@takesi0627 僕の変更なので、申し訳ないです。とりあえず、以下のように書けば要件を満たせます。 `GetTrees` に関しては、`enum` の網羅性をより厳密に対応するなら、`switch 文` を用意して `default` で `throw` すれば良いと思います

```
        private static readonly Dictionary<ESeasonId, List<ETreeId>> _TREES = new Dictionary<ESeasonId, List<ETreeId>
        {
            {ESeasonId.Spring, new List<ETreeId> {ETreeId.Spring_1, ETreeId.Spring_2, ETreeId.Spring_3}},
            {ESeasonId.Summer, new List<ETreeId> {ETreeId.Summer_1, ETreeId.Summer_2, ETreeId.Summer_3}},
            {ESeasonId.Autumn, new List<ETreeId> {ETreeId.Autumn_1, ETreeId.Autumn_2, ETreeId.Autumn_3}},
            {ESeasonId.Winter, new List<ETreeId> {ETreeId.Winter_1, ETreeId.Winter_2, ETreeId.Winter_3}},
        };

        public static List<ETreeId> GetTrees(this ESeasonId seasonId)
        {
            return _TREES[seasonId];
        }
```

2020-12-26 01:35 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +        [SerializeField] private GameObject _dropdownTemplate;
https://github.com/LITO-apps/Treevel-client/blob/ece7cc8d37e0a2ae1244a301857e01da7bff29ad/Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs#L97
で色を指定していることで、プルダウン時の色が季節ごとに変わっている。以下、上記の記述をコメントアウトした場合に、色が変わっていないことを示すキャプチャ

<img width="156" alt="スクリーンショット 2020-12-26 10 09 23" src="https://user-images.githubusercontent.com/26104258/103143878-bb51cf00-4762-11eb-9c46-094a55979107.png">

2020-12-26 01:35 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }).AddTo(this);
オペレータと購読は、インデントして欲しい。あとこれ、`Subscribe()` した瞬間に流れちゃったりはしなさそうだから `Skip(1)` は消せそう 。 @takasusuke のコメント試してみて。 `SetDropdownOptions` のタイミングでストリームがきているのかも・・・？違かったらちゃんと調べるので言ってください

2020-12-26 01:35 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +                .Subscribe(isOn => {
ここもインデントしてー

2020-12-26 01:35 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +                    if (!isOn) return;
これは素晴らしい提案

2020-12-26 01:35 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +                    _dropdownTemplate.GetComponent<Image>().color = seasonToggle.SeasonColor;
季節の色はトグルが持つのではなく、 `ESeasonId` が持つようにしたいです。季節の変更を検知して、色を変えたいです

2020-12-26 01:35 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +        private ETreeId _currentTree;
これら二つの変数を `ReactiveProperty` などで定義して
- ドロップダウン押下により行う処理
- 現在の季節・現在の木が変更された時に行う処理

を切り分けたいです（読みやすいので）

2020-12-26 01:35 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +        private ETreeId _currentTree;
`ReactiveProperty` は少し Rx っぽくないので、Subject 系でも良いけど、今回は `ReactiveProperty` の方が使い勝手が良さそう

2020-12-26 01:35 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            .ToList();
インデント

2020-12-26 01:35 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            .Select((stageStatus, index) => (_graphBars[index], stageStatus.successNum, stageStatus.challengeNum))
インデント

2020-12-26 01:35 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/SeasonSelectButton.cs
> +            }).AddTo(this);
読み慣れているのもあるけど、これもインデントしてほしい

2020-12-26 01:35 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/SeasonSelectButton.cs
> +                    image.color = Color.clear;
この程度の分岐なら三項演算子使いたい

2020-12-26 02:23 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }).AddTo(this);
インデントは自動コードフォーマットの仕業です。一回インデントしてコミットしてみたけどまた戻される

2020-12-26 02:25 UTC, takesi0627 commented
@xiii111 @takasusuke 
## `Skip`について
`Awake`でイベントの購読を行いたいが、その時点では実際初期化はいりません。なぜなら、`OnEnable`で実行されるからです。そのため、最初の値による初期化を無視するようにしています。

2020-12-26 02:26 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }).AddTo(this);
あれ、俺はされないんだけどw いずれにしてもその自動フォーマットを修正してほしい

2020-12-26 02:28 UTC, xiii111 commented
確認だけど

> その時点では実際初期化はいりません

これはなんで初期化のストリームが流れちゃうの？

2020-12-26 02:28 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +        private ETreeId _currentTree;
`ReactiveProperty` は知らなかった。調べてみる

2020-12-26 02:30 UTC, takesi0627 commented
> 確認だけど
> 
> > その時点では実際初期化はいりません
> 
> これはなんでストリームがきちゃうの？

ドロップダウンが `Observable` に変換されるときの仕様ではないかと

2020-12-26 02:48 UTC, xiii111 commented
まじか、なんで流れちゃうんだろう。

2020-12-26 02:48 UTC, xiii111 commented
ボタンとかは当然流れないのだけど

2020-12-26 03:16 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }).AddTo(this);
これフォーマットされちゃうなら linq もフォーマットされちゃう・・・？

2020-12-26 11:39 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }).AddTo(this);
Skip()の部分に関して、記事見つけました。
uGUIイベントから変換する時は、
Subscribe時に現在の初期値で発行する
```
OnValueChangedAsObservable();
```
Subscribe時に現在の初期値で発行しない
```
onValueChanged.AsObservable();
```
の使い分けがあるようです。

https://qiita.com/toRisouP/items/86fea641982e6e16dac6#ugui%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88%E3%81%8B%E3%82%89%E5%A4%89%E6%8F%9B%E3%81%99%E3%82%8B

2020-12-26 12:06 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }).AddTo(this);
確かにいつもと書き方違ったわww

2020-12-26 14:37 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }).AddTo(this);
すばらちぃ

2020-12-26 14:37 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }).AddTo(this);
もしかしたらRiderの設定かな？

2020-12-26 14:38 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }).AddTo(this);
(自分もこっそりRiderに乗り換えて同じ状態なので、多分設定周りな気がする)

2020-12-26 14:41 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }).AddTo(this);
@xiii111 助けてー

2020-12-26 15:12 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +                    if (!isOn) return;
75af99c

2020-12-26 15:13 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/SeasonId.cs
> +                    return new List<ETreeId> {ETreeId.Winter_1, ETreeId.Winter_2, ETreeId.Winter_3};
bb8225b

2020-12-26 15:15 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +                    _dropdownTemplate.GetComponent<Image>().color = seasonToggle.SeasonColor;
それも考えたんだけど、現状 `ESeasonId` に書くと、UIから色を選ぶことができなくなります。それでよかったらやりますが、色の調整したい時にめんどくさいじゃないかと

2020-12-26 15:43 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/SeasonSelectButton.cs
> +                    image.color = Color.clear;
2cf7ae0

2020-12-26 15:44 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +                    _dropdownTemplate.GetComponent<Image>().color = seasonToggle.SeasonColor;
まあコードが綺麗になるからいいや
2cf7ae0

2020-12-26 16:13 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +        private ETreeId _currentTree;
めっちゃくっちゃスッキリするぅぅぅぅ
9bffde0

2020-12-26 17:55 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }).AddTo(this);
あー、コードスタイルだよ多分。

2020-12-26 17:56 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }).AddTo(this);
ちょっと今スマホしかないからすぐ返せない

2020-12-28 10:41 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +        private ETreeId _currentTree;
素晴らしいーーー

2020-12-28 10:48 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }).AddTo(this);
`.githooks` が原因でした！直してもらえると助かります

2020-12-28 11:20 UTC, xiii111 reviewed
LGTM with nits

2020-12-28 11:20 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
>              _clearStageNum.GetComponent<ClearStageNumController>().SetUp(clearStageNum, totalStageNum, Color.magenta);
ここまだ変わってないね！

2020-12-28 11:20 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/SeasonSelectButton.cs
> +            var selectedColor = _seasonId.GetColor();
これ、一箇所でしか使ってないから、変数宣言しなくて良いんじゃない？

2020-12-28 11:26 UTC, xiii111 commented
https://github.com/LITO-apps/Treevel-client/pull/673#issuecomment-751305171 はちゃんと治ってました！

以下のコメントを修正してくれれば、僕からは終わりです！
- [ ] https://github.com/LITO-apps/Treevel-client/pull/673#discussion_r549307960
- [ ] https://github.com/LITO-apps/Treevel-client/pull/673#discussion_r549310330
- [ ] https://github.com/LITO-apps/Treevel-client/pull/673#discussion_r548929862
- [ ] https://github.com/LITO-apps/Treevel-client/pull/673#discussion_r549302351

2020-12-29 13:48 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
>              _clearStageNum.GetComponent<ClearStageNumController>().SetUp(clearStageNum, totalStageNum, Color.magenta);
38a6c6c
ここで変えています

2020-12-29 13:54 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
>              _clearStageNum.GetComponent<ClearStageNumController>().SetUp(clearStageNum, totalStageNum, Color.magenta);
9c0678c

2020-12-29 13:57 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/SeasonSelectButton.cs
> +            var selectedColor = _seasonId.GetColor();
9c0678c

2020-12-29 14:24 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            .Select((stageStatus, index) => (_graphBars[index], stageStatus.successNum, stageStatus.challengeNum))
e4aae49

2020-12-29 14:34 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }).AddTo(this);
すぐに直せそうにないな

2020-12-29 14:36 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }).AddTo(this);
https://github.com/orgs/LITO-apps/projects/2#card-51942276
アイデア作りました

2020-12-30 13:04 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/SeasonSelectButton.cs
> +            var selectedColor = _seasonId.GetColor();
640d7fb ね

2020-12-30 13:05 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
> +            }).AddTo(this);
なるほど辛い。早めにやりたいね

2020-12-30 13:05 UTC, xiii111 reviewed
LGTM!

2020-12-30 13:06 UTC, xiii111 commented
@takesi0627 すみません、僕から approve できません

2020-12-30 13:06 UTC, xiii111 commented
@takasusuke あとは任せました

2020-12-30 13:55 UTC, takesi0627 commented
と言うことで、 @takasusuke 他に問題なければアプルーブいただけると助かります

2020-12-30 15:12 UTC, takasusuke approved these changes
遅くなりました。。。
お疲れ様です！！

2020-12-30 15:13 UTC, merged

2020-12-30 15:13 UTC, takesi0627 commented
あざまーす