[WIP]【UniRx】Common
LITO-apps/Treevel-client pull request #682
Opened 2020-12-16 16:15 UTC by takesi0627

### 対象イシュー
Close #659 

### 概要
ゲーム全体の共通処理をUniRx/UniTask記述に改修

### 詳細

#### 現実装になった経緯

b85a70a プログレスバー周りの処理。主に `AddressableAssetManager`に `OnAssetLoadStart`イベントを用意、ロードするたびに発火する。プログレスバーはそのイベントを購読し、イベント発火されたらロード完了までに表示される。

9217bcf `LoadStageDependencies`がアセット全部ロード完了まで待つようにした。

#### 技術的な内容

### キャプチャ

### 動作確認方法

### 参考 URL

2020-12-16 16:23 UTC, takesi0627 commented
@takasusuke @xiii111 
コミットについてコメントがあればお願いします。

2020-12-17 12:44 UTC, xiii111 reviewed
コメントしました！

2020-12-17 12:44 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/UIs/ProgressBar.cs
> +            _onAssetLoadDisposable = AddressableAssetManager.OnAssetStartLoad.Subscribe(Load);
```suggestion
            AddressableAssetManager.OnAssetStartLoad
                .Subscribe(async op => {
                    _loadingOps.Add(op);
                    op.Completed += op1 => _loadingOps.Remove(op1);
                    if (gameObject.activeSelf == false) gameObject.SetActive(true);
                })
                .AddTo(this);
```

2020-12-17 12:44 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/UIs/ProgressBar.cs
> +            _onAssetLoadDisposable = AddressableAssetManager.OnAssetStartLoad.Subscribe(Load);
- `Subscribe(...)` の中で処理を書く
- 購読の解除は `OnDestroy` 時にやりたいだけなら `.AddTo(this)` で良い

2020-12-17 12:44 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/AddressableAssetManager.cs
> +
カプセル化するために、`onNext` ができてしまう `Subject` は外部公開しないようにしましょう。
```suggestion
        private static readonly Subject<AsyncOperationHandle> OnAssetStartLoadSubject = new Subject<AsyncOperationHandle>();
        
        public static readonly IObservable<AsyncOperationHandle> OnAssetStartLoad = OnAssetStartLoadSubject.AsObservable();
```

2020-12-17 15:12 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/ProgressBar.cs
> +            _onAssetLoadDisposable = AddressableAssetManager.OnAssetStartLoad.Subscribe(Load);
そうだったな

2020-12-17 15:13 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/AddressableAssetManager.cs
> +
なるほど・・

2020-12-17 15:19 UTC, takesi0627 commented
コメント2点修正しました。

2020-12-18 12:01 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/AddressableAssetManager.cs
> +                        tasks.Add(LoadAsset<GameObject>(Constants.Address.DYNAMIC_DUMMY_BOTTLE_PREFAB).ToUniTask());
`AddressableAssetManager.LoadAsset()`の返り値を`UniTask<TObject>`にするのはどうなんでしょうか。

2020-12-18 13:47 UTC, xiii111 commented
僕からのコメントは以上なので、いつでも引き継げます

2020-12-18 14:14 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/AddressableAssetManager.cs
> +                        tasks.Add(LoadAsset<GameObject>(Constants.Address.DYNAMIC_DUMMY_BOTTLE_PREFAB).ToUniTask());
そうします

2020-12-21 14:11 UTC, xiii111 commented
@takesi0627 修正ありがとう。こっからは引き継ぎます

2021-01-30 07:33 UTC, xiii111 commented
develop を取り込んで、コンフリクトを解決しました

2021-01-31 16:35 UTC, takasusuke commented
ごめん間違えて、このbranchに別のissueの差分をpushしてしまったから戻しました。

2021-02-04 12:02 UTC, xiii111 reviewed
📝

2021-02-05 12:47 UTC, xiii111 commented
📝 `ScheduleManager.cs` は以下の二点から今回の修正対象から外そうと思いました
- どのタイミングで更新されるかが決まってない
- 現状のコードはバックグラウンドに行った場合にもカウントしているように作ったはずだが、検証をしてみると、バックグラウンドにいる間はカウントしていない

以下のような issue を作ったので、ここで別途対応する

2021-02-07 08:15 UTC, xiii111 reviewed
📝

2021-02-07 08:15 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/RecordData.cs
> +                .Subscribe(startupDays => PlayerPrefs.SetInt(Constants.PlayerPrefsKeys.STARTUP_DAYS, startupDays))
`.SkipLatestValueOnSubscribe()` を用いても良いが、実行順序によってはバグりそうなので、つけない

2021-02-07 08:15 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Settings/ResetController.cs
> +        private static readonly Subject<Unit> _dataResetSubject = new Subject<Unit>();
`ResetController` がインスタンス化されていなくても購読できるようにした（これは正しいやり方なのか？）

2021-02-08 16:00 UTC, xiii111 reviewed
📝

2021-02-08 16:00 UTC, xiii111 commented on Assets/Project/Scripts/Modules/StageSelectScene/StageSelectDirector.cs
>          /// <summary>
今回のレビュー対象外

2021-02-08 16:02 UTC, xiii111 commented
@takasusuke @takesi0627 レビューお願いします。15 分 - 45 分くらいかなと思います。議論になりそうな点としては、

- https://github.com/LITO-apps/Treevel-client/pull/682#issuecomment-774012525
- `StageStatus` は対応不要と判断して、やらなかったこと

2021-02-08 16:03 UTC, xiii111 commented
@takesi0627 レビュー依頼が GitHub の仕様上できませんが、お願いします

2021-02-09 09:48 UTC, takesi0627 commented
タイトル変えました

2021-02-09 11:26 UTC, takasusuke commented on Assets/Project/Scripts/Common/Entities/RecordData.cs
空行

2021-02-09 12:43 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Components/UIs/MessageDialog.cs
> +                .AddTo(this);
```
_okButton.onClick.AsObservable()
    .Subscribe(_ => {
        _okCallBack?.Invoke();
        _okCallBack = null;
        gameObject.SetActive(false);
    }).AddTo(this);
```
これを `Awake` で書くのはどうですか？
現状も特に悪くないので判断お任せします

2021-02-09 13:01 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Settings/ResetController.cs
> +        private static readonly Subject<Unit> _dataResetSubject = new Subject<Unit>();
`Awake` で `_dataResetSubject.AddTo(this)` にしたため、インスタンスの破壊とともに `dispose` される。
そのため、 `LevelSelectDirector` とかで2回目購読しようとするとエラーが発生する。

再現手法：
StageSelectSceneに入ってからMenuSelectScene に戻る

`_dataResetSubject.AddTo(this)` を消せばおそらく治ると思うが、静的にする必要もないと考えている。

2021-02-09 15:19 UTC, takasusuke requested changes
ほぼほぼ素晴らしいと思います。

↓のバグが修正されたらそこをまた見ます。
https://github.com/LITO-apps/Treevel-client/pull/682/files#r572865276

2021-02-09 15:19 UTC, takasusuke commented on Assets/Project/Scripts/Common/Utils/DefaultConfigurations.cs
> +        };
見やすい。👍👍

ここは変えなくても良いけれど、こんな感じだと、新ギミックを追加するときに記述しなくて済むなあと思いました。
(当たり判定のないギミックも失敗回数0回になってしまうので、厳密にやろうとするならギミッククラスが失敗要因となるかどうかの変数持たないといけない)
(なので変更しなくても良いです)
```
/// <summary>
        /// 各失敗原因に対する失敗回数
        /// </summary>
        public static readonly Dictionary<EFailureReasonType, int> FAILURE_REASON_COUNT = GetInitialFailureReasounCount();

        private static Dictionary<EFailureReasonType, int> GetInitialFailureReasounCount()
        {
            var failureReasonCount = new Dictionary<EFailureReasonType, int>();
            foreach (var failureReasonType in Enum.GetValues(typeof(EFailureReasonType)))
            {
                failureReasonCount.Add((EFailureReasonType)failureReasonType, 0);
            }

            return failureReasonCount;
        }
```

2021-02-09 15:19 UTC, takasusuke commented on Assets/Project/Scripts/Common/Entities/RecordData.cs
> +            _lastStartupDate = PlayerPrefsUtility.GetDateTime(Constants.PlayerPrefsKeys.LAST_STARTUP_DATE);
これは、将来的には`RecordData`と`RecordDataManager`的なクラスを作って、`RecordDataManager`クラスは`GameObject`ととして、`StartUpScene`とか`MenuSelectScene`に置けばいい感じ？

2021-02-10 12:06 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/UIManager.cs
> +            var messageBoxObj = await _errorMessageBoxRef.InstantiateAsync(canvas);
一応検証して見て大丈夫だったみたいです

2021-02-10 12:07 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/UIManager.cs
> +            var messageBoxObj = await _errorMessageBoxRef.InstantiateAsync(canvas);
インスタンスが違うからじゃない？

2021-02-10 12:11 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/RecordData.cs
空行いらないってことかな？まぁ、どっちでも良いから消しておくわ
- 59512cd

2021-02-10 12:28 UTC, xiii111 commented on Assets/Project/Scripts/Common/Components/UIs/MessageDialog.cs
> +                .AddTo(this);
確かに `Awake()` で良さそう。 `_okCallBack` という名前、果たして CallBack なのか？という気持ちにはなったが、今回は放置
- 2ce6788

2021-02-10 12:34 UTC, xiii111 commented on Assets/Project/Scripts/Common/Utils/DefaultConfigurations.cs
> +        };
> 当たり判定のないギミックも失敗回数0回になってしまう

あれ、この書き方なら大丈夫そうじゃない？

2021-02-10 12:37 UTC, xiii111 commented on Assets/Project/Scripts/Common/Utils/DefaultConfigurations.cs
> +        };
そういう型だからね！

2021-02-10 12:51 UTC, xiii111 commented on Assets/Project/Scripts/Common/Utils/DefaultConfigurations.cs
> +        };
こんなんでどうだろ
- fc629bf

2021-02-10 12:52 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/RecordData.cs
> +            _lastStartupDate = PlayerPrefsUtility.GetDateTime(Constants.PlayerPrefsKeys.LAST_STARTUP_DATE);
うーーーんそうするのが良いのかなぁ。ちょっと、PlayFab を実装するときに二転三転しそうだから、その時考えようと思ってる

2021-02-10 13:05 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Settings/ResetController.cs
> +        private static readonly Subject<Unit> _dataResetSubject = new Subject<Unit>();
ResetController は設定画面の `ResetButton` がインスタンス化される時に生成される（MenuSelectScene が Load される時）。

つまり、ResetController のインスタンスプロパティを参照できるのは、MenuSelectScene が Load されているときのみ。

しかし、Reset された時に流れる Observable は MenuSelectScene が Load されていない時も購読したい。

では static class として GlobalSubject（いつでもアクセスできる Subject を定義するクラス）を作るか？と考えたが、dataResetSubject を onNext するのは ResetController 内部でのみなので、グローバルに Subject を公開したくない

ResetController の内部に static として持ってしまうか... が今です。

static な subject を dispose する必要はないので、とりあえず消します → 373f3fe

2021-02-10 13:08 UTC, xiii111 commented
@takasusuke @takesi0627 再レビューお願いします！

2021-02-10 13:17 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Settings/ResetController.cs
> +        private static readonly Subject<Unit> _dataResetSubject = new Subject<Unit>();
気持ちはとてもわかります、僕も同じことを悩んで最後にどうせ現状 `MenuSelectScene` しか購読してないからもう一方を選んだ。

`ResetController` の役割は「リセットボタン」の動作を定義するだけに限って、実際 `ResetData` の処理と `subject` はもっとグローバルなクラス（ `AppManager` とか）に持たせた方がいいかもしれないと、今思いました。

2021-02-10 13:28 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Settings/ResetController.cs
> +        private static readonly Subject<Unit> _dataResetSubject = new Subject<Unit>();
> 実際 ResetData の処理と subject はもっとグローバルなクラス（ AppManager とか）に持たせた方がいいかもしれない

これをすると、ResetController 以外からも onNext できてしまい、カプセル化（encapsulation）を崩してしまいますが、許容しますか？

2021-02-10 13:36 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Settings/ResetController.cs
> +        private static readonly Subject<Unit> _dataResetSubject = new Subject<Unit>();
`AppManager` でカプセルかすれば良いのでは？と思いましたが、
`ResetData` が公開されるから誰でもリセットできちゃうってことですね

2021-02-10 13:37 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Settings/ResetController.cs
> +        private static readonly Subject<Unit> _dataResetSubject = new Subject<Unit>();
です。

2021-02-10 13:38 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Settings/ResetController.cs
> +        private static readonly Subject<Unit> _dataResetSubject = new Subject<Unit>();
AppManager で Observable のみを公開したら、ResetController で今後は onNext できなくなります

2021-02-10 13:40 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/DefaultConfigurations.cs
> +        public static readonly Dictionary<EFailureReasonType, int> FAILURE_REASON_COUNT2 = Enum.GetValues(typeof(EFailureReasonType))
この変数名ってデバッグ用？

2021-02-10 13:41 UTC, xiii111 commented on Assets/Project/Scripts/Common/Utils/DefaultConfigurations.cs
> +        public static readonly Dictionary<EFailureReasonType, int> FAILURE_REASON_COUNT2 = Enum.GetValues(typeof(EFailureReasonType))
げ........................

2021-02-10 13:43 UTC, xiii111 commented on Assets/Project/Scripts/Common/Utils/DefaultConfigurations.cs
> +        public static readonly Dictionary<EFailureReasonType, int> FAILURE_REASON_COUNT2 = Enum.GetValues(typeof(EFailureReasonType))
何も見てない何も見てない
- c53b3e2

2021-02-10 13:45 UTC, takesi0627 commented
お疲れ様です。
@takasusuke おれはアプルーブできないので任せました。

2021-02-13 01:58 UTC, xiii111 commented
@takasusuke お手隙の際にお願いします🙏

2021-02-13 03:02 UTC, takasusuke approved these changes
🎉

2021-02-13 11:12 UTC, merged

2021-02-13 11:13 UTC, xiii111 commented
感謝のまーじ