[WIP]【UniRx】GamePlayScene
LITO-apps/Treevel-client pull request #688
Opened 2020-12-24 16:18 UTC by takasusuke

### 対象イシュー
Close #660

### 概要
GamePlaySceneでUniRx/UniTaskに利用できるところのリファクタリング

### 詳細

#### 現実装になった経緯

#### 技術的な内容

### キャプチャ

### 動作確認方法

### 参考 URL

2020-12-24 16:18 UTC, takasusuke commented
↑既存のevent部分を単純にUniRxに置き換えるところまでのcode

2020-12-25 16:49 UTC, takasusuke commented
3eb1305 , 1e25466
ゲーム開始前に、BottleとTileを読み込む部分をUniTaskに変更

2020-12-25 16:57 UTC, takasusuke commented
3eb1305
非同期で行いたい処理の後に、さらに何かを行うまでを1つのタスクにするのはこんな感じ？
もうちょい楽に書ける？

2020-12-25 17:05 UTC, takasusuke commented
@xiii111 
- [非同期で行いたい処理 + その後に行いたい処理] までを1つのタスクとする場合をUniTaskで記述しました。
(あんま自信ないので見てもらえると助かります)

@takesi0627 
全部できてからレビュー投げても大変だと思うので、良ければお願いします。

### 変更予定メモ

- [ ] `GamePlayDirector`に`Opening`という状態を追加して、読み込み後に`Playing`状態に遷移させたい

- [ ] `bottleData.type`だけでなく、`IsSelfish`とかの値を見て、あらかじめ必要な`Prefab`を読み込んでおく

- [ ] `selfishEffectController`などで仕方なく`Awake`で行っていた部分を、`StartPlaying`みたいなイベントを呼んでそのタイミングで処理したい

2020-12-26 00:43 UTC, xiii111 commented
Draft にしておいた、レビューはする！

2020-12-26 03:15 UTC, xiii111 reviewed
パッと気づいたところをコメントしていきました！読みやすくなって嬉しい

あと、Rx の記述には Linq と同じようにインデントをつけて欲しい。 #673 で自動フォーマットの話が出ていたのですが、インデントしないと読むのしんどいので、治したいです

2020-12-26 03:15 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +            }).AddTo(eventDisposable, this);
マージ。あと EndProcess のなかで .OnNext してるから2回通知しちゃってるかも？

2020-12-26 03:15 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/NormalBottleController.cs
> +                if (IsSuccess()) {
Where

2020-12-26 03:15 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/AbstractGimmickController.cs
> +                OnGameEnd();
この関数も Observable にしたいよね？

2020-12-26 03:15 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/AbstractGimmickController.cs
> +            }).AddTo(this);
マージ

2020-12-26 03:15 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/GimmickGenerator.cs
> +            }).AddTo(this);
マージ

2020-12-26 03:15 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/WarpTileController.cs
> +            }).AddTo(this);
マージ

2020-12-26 03:15 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/TileGenerator.cs
> +        private static UniTask<GameObject> CreateWarpTiles(int firstTileNum, int secondTileNum)
この関数を使っているところ見ると GameObject を返す必要がないように見える

2020-12-26 12:07 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/BottleGenerator.cs
> +                });
> await 部分の非同期処理が終わるまで続きの for 文が前に進まない気がする

お、なぜそうなるんだろう

2020-12-26 12:25 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/BoardManager.cs
> +            }).AddTo(this);
便利

2020-12-26 13:00 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/AbstractGimmickController.cs
> +                OnGameEnd();
ん？
いや、、、？

具体的に、、、どういうように、？

2020-12-26 14:22 UTC, takasusuke commented
起動して、１つ目のStageはどこでも動くけど、
２つ目のStageはエラーが出るな。。。
2回同じのをawaitするな、、、うーん、１つ前のが残ってるってこと。。。？
(お手上げ)
```
InvalidOperationException: Already continuation registered, can not await twice or get Status after await.
Cysharp.Threading.Tasks.AddressablesAsyncExtensions+AsyncOperationHandleConfiguredSource`1[T].OnCompleted (System.Action`1[T] continuation, System.Object state, System.Int16 token) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/External/Addressables/AddressablesAsyncExtensions.cs:361)
Cysharp.Threading.Tasks.UniTask+WhenAllPromise..ctor (Cysharp.Threading.Tasks.UniTask[] tasks, System.Int32 tasksLength) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTask.WhenAll.cs:185)
Cysharp.Threading.Tasks.UniTask.WhenAll (System.Collections.Generic.IEnumerable`1[T] tasks) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTask.WhenAll.cs:45)
Treevel.Modules.GamePlayScene.StageGenerator+<CreateStages>d__4.MoveNext () (at Assets/Project/Scripts/Modules/GamePlayScene/StageGenerator.cs:43)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <fb001e01371b4adca20013e0ac763896>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
```

2020-12-26 16:43 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/BottleGenerator.cs
> +        public static List<UniTask> CreateBottles(List<BottleData> bottleDatas)
```
public static IEnumerable<UniTask> CreateBottles(List<BottleData> bottleDatas)
{
    var tasks = bottleDatas
        .Where(x => _prefabAddressableKeys.ContainsKey(x.type))
        .Select(bottleData => AddressableAssetManager.Instantiate(_prefabAddressableKeys[bottleData.type]).ToUniTask()
            .ContinueWith(bottle =>
                bottle.GetComponent<AbstractBottleController>().Initialize(bottleData)
            )
    );

    return tasks;
}
```
読みやすいかちょっと怪しいが、参考までに

2020-12-28 11:33 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/BottleGenerator.cs
> +                });
> await 部分の非同期処理が終わるまで続きの for 文が前に進まない気がする

ごめん、そんなことなかったわ

2020-12-28 11:49 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/AbstractBottleEffectController.cs
> +    public class AbstractBottleEffectController : MonoBehaviour
定例会で議論した通り、以下のクラスは、この機能を持つクラスを継承するようにしましょう
- `AbstractGimmickController`
- `AbstractBottleController`
- `AbstractTileController`

2020-12-28 11:50 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/BottleGenerator.cs
> +        public static List<UniTask> CreateBottles(List<BottleData> bottleDatas)
こんな感じかな
```
        public static UniTask CreateBottles(List<BottleData> bottleDatas)
        {
            var tasks = bottleDatas
                .Where(bottleData => _prefabAddressableKeys.ContainsKey(bottleData.type))
                .Select(bottleData => 
                    AddressableAssetManager.Instantiate(_prefabAddressableKeys[bottleData.type]).ToUniTask()
                        .ContinueWith(bottle => {
                            bottle.GetComponent<AbstractBottleController>().Initialize(bottleData);
                        })
                );

            return UniTask.WhenAll(tasks);
        }
```

2020-12-28 11:52 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/BottleGenerator.cs
> +        public static List<UniTask> CreateBottles(List<BottleData> bottleDatas)
`TileGenerator.Instance.CreateTiles` も `UniTask` を返すようにして、 `StageGenerator` では

```
await UniTask.WhenAll(
    TileGenerator.Instance.CreateTiles(stageData.TileDatas),
    BottleGenerator.CreateBottles(stageData.BottleDatas)
);
```

にしよう

2020-12-28 11:55 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/AbstractGimmickController.cs
> +                OnGameEnd();
定例会で話したけど、 `Subject` を `AbstractGimmickController` が所持して、子供クラスには `Observable` を提供。購読したい場合には、 `Observable` を `Subscribe` する

2020-12-28 12:02 UTC, xiii111 commented
一通りコメントに返信などしました。再レビューが必要な時にはまた教えてください

以下の話はパッと見じゃ分からなかったので、また今度みます

> 起動して、１つ目のStageはどこでも動くけど、
> ２つ目のStageはエラーが出るな。。。
> 2回同じのをawaitするな、、、うーん、１つ前のが残ってるってこと。。。？
> (お手上げ)
> 
> ```
> InvalidOperationException: Already continuation registered, can not await twice or get Status after await.
> Cysharp.Threading.Tasks.AddressablesAsyncExtensions+AsyncOperationHandleConfiguredSource`1[T].OnCompleted (System.Action`1[T] continuation, System.Object state, System.Int16 token) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/External/Addressables/AddressablesAsyncExtensions.cs:361)
> Cysharp.Threading.Tasks.UniTask+WhenAllPromise..ctor (Cysharp.Threading.Tasks.UniTask[] tasks, System.Int32 tasksLength) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTask.WhenAll.cs:185)
> Cysharp.Threading.Tasks.UniTask.WhenAll (System.Collections.Generic.IEnumerable`1[T] tasks) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTask.WhenAll.cs:45)
> Treevel.Modules.GamePlayScene.StageGenerator+<CreateStages>d__4.MoveNext () (at Assets/Project/Scripts/Modules/GamePlayScene/StageGenerator.cs:43)
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0)
> System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <fb001e01371b4adca20013e0ac763896>:0)
> UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
> UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
> ```

2020-12-28 12:06 UTC, xiii111 commented
あ、 `StageGenerator.cs:43` なのか！そしたらとりあえず https://github.com/LITO-apps/Treevel-client/pull/688#discussion_r549320079 での修正をすれば、該当箇所が書き変わるから、そっから様子を見よう

2020-12-30 13:08 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/BottleGenerator.cs
> +        public static List<UniTask> CreateBottles(List<BottleData> bottleDatas)
@takesi0627 意見あったらお願い

2021-01-02 09:15 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/WarpTileController.cs
> +            }).AddTo(this);
6618b12 , a59fd8d

2021-01-02 09:15 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/GimmickGenerator.cs
> +            }).AddTo(this);
6618b12 , a59fd8d

2021-01-02 09:15 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/AbstractGimmickController.cs
> +            }).AddTo(this);
6618b12 , a59fd8d

2021-01-02 09:15 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +            }).AddTo(eventDisposable, this);
6618b12 , a59fd8d

2021-01-02 09:15 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkEffectController.cs
> +            }).AddTo(eventDisposable, this);
6618b12 , a59fd8d

2021-01-02 09:15 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/BoardManager.cs
> +            }).AddTo(this);
6618b12 , a59fd8d

2021-01-02 09:18 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkEffectController.cs
> +            }).AddTo(eventDisposable, this);
8582c91

2021-01-02 09:21 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/NormalBottleController.cs
> +                if (IsSuccess()) {
1b0b8fb

2021-01-02 09:24 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/AbstractBottleEffectController.cs
> +        protected CompositeDisposable eventDisposable = new CompositeDisposable();
5357844

2021-01-02 10:55 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkEffectController.cs
> +                DisposeEvent();
64279a2 , 06aad75

`Bottle`が`GamePlayDirector`の`GameSucceeded`と`GameFailed`を購読していました。
そして、`Bottle`が`EndGame`を提供して、`BottleEffect`がそれを購読していました。
↓
`Bottle`, `Gimmick`, `Tile`, `BottleEffect`が共通のクラスを継承する必要になりました。
`BottleEffect`は`Bottle`の`EndGame`を購読するのではなく、`GamePlayDirector`の`GameSucceeded`と`GameFailed`を直接購読するように変更しました。

----------------
`AbstractGimmickController`が`GameSucceeded`と`GameFailed`を購読し、
`GameEnd`というメソッドを提供していました。
`AbstractGimmickController`を継承する各クラスは、`GameEnd`メソッドを実装していました。
↓
各クラスが`GamePlayDirector`の`GameSucceeded`と`GameFailed`を直接購読するように変更しました。

2021-01-02 10:56 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/AbstractBottleEffectController.cs
> +    public class AbstractBottleEffectController : MonoBehaviour
64279a2 , 06aad75

2021-01-02 10:56 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/AbstractGimmickController.cs
> +                OnGameEnd();
64279a2 , 06aad75

2021-01-02 11:18 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/BottleGenerator.cs
> +        public static List<UniTask> CreateBottles(List<BottleData> bottleDatas)
713e752, 6a6c3a9

2021-01-02 11:20 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/StageGenerator.cs
> +                await UniTask.WhenAll(tasks);
713e752, 6a6c3a9

`GimmickGenerator`の初期化処理もここに含めました。
含めなかったら、実行して２種類目のステージでギミックが登場しない。
↑の問題もあるけど、ゲーム準備の流れの観点からここに含めるのが適切と判断しました。

2021-01-02 11:22 UTC, takasusuke commented
一旦、いただいたレビューをもとに修正を行った結果、バグはなくなりました。

いくつか手をつけていなく、変更する部分が残っていますが、ここまでの修正部分のレビューを推奨します。

2021-01-04 13:27 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/BoardManager.cs
> +            .Subscribe(_ => {
インデント

2021-01-04 13:28 UTC, xiii111 commented
ちらっと眺めてみたけど、この後変更あるなら、全て変更が終わった後にもう一度ちゃんとみるわ

2021-01-04 13:30 UTC, xiii111 commented
インデント周りはコメントするのが辛いから、意識してもらえると助かる
```
hogeObservable
    .Where(...)
    .Subscribe(...)
    .AddTo(this)

var task = hogeTask
    .Where(...)
    ...
```

2021-01-08 12:32 UTC, takasusuke commented
146a031 , 23a45af : BottleEffectに関するAssetを事前にロード
040822a , 3da8d64 : GimmickおよびBoardManagerのCoroutineをUniTaskに置換  
c6c2608 : Bottle関連のTaskをUniTaskに変換
12a0383 , 2501ac8 : ゲーム開始時に呼びたい処理を規定
cb67dbd : 衝突判定をUniRxに変換
5a3b77f , 9716125 : (commit名間違えた...) ゲーム終了時にTornadoのWarningの消すように修正。
5617354 : 一時停止からプレイ画面に戻ったときに、ギミックを作り直してしまうバグを修正
640804a : developをmerge

2021-01-08 12:34 UTC, takasusuke commented
@xiii111 @takesi0627 
たくさんご教示願います。

2021-01-09 12:45 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/BoardManager.cs
> +        private CancellationTokenSource _tokenSource;
ごめん、これは僕のせいだと思いますけど、
現状`BoardManager`は`GameplayScene`がアンロードしてもい続けるからこのような対応していると思いますが、`GamePlayScene`にあらかじめ`BoardManager`のゲームオブジェクトを配置しておけば、`DontDestroyOnLoad`が呼ばれないのでゲーム終了時に削除される。そうすれば、普段通りに`addTo(this)`で完結するかと思います

2021-01-09 12:47 UTC, takesi0627 commented
`Spring-3-1`入ってすぐ抜けるとステージ画面でギミックが発動する

https://user-images.githubusercontent.com/17778395/104091946-2e5f5780-52c4-11eb-9fff-b0a78bcfe8f2.mov

2021-01-09 13:13 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/BoardManager.cs
> +        private CancellationTokenSource _tokenSource;
いや、失敗時にやり直す時のための対応かこれ・・

でも結局 `GameplayScene`以外に`BoardManager`が居残るのは良くないことなので、`GameplayScene`に`BoardManager` 置いてくれないか

2021-01-09 13:18 UTC, takesi0627 commented
`Spring-1-1`をプレイし、成功後ステージ選択画面に戻るってしばらく（1秒程度）するとエラーが出ます

```
NullReferenceException: Object reference not set to an instance of an object
Treevel.Modules.GamePlayScene.GamePlayDirector+OpeningState..ctor (Treevel.Modules.GamePlayScene.GamePlayDirector caller) (at Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs:317)
System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) (at <fb001e01371b4adca20013e0ac763896>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Reflection.MonoCMethod.DoInvoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Reflection.MonoCMethod.Invoke (System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <fb001e01371b4adca20013e0ac763896>:0)
System.RuntimeType.CreateInstanceImpl (System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Activator.CreateInstance (System.Type type, System.Object[] args) (at <fb001e01371b4adca20013e0ac763896>:0)
Treevel.Modules.GamePlayScene.GamePlayDirector.AddState (Treevel.Modules.GamePlayScene.GamePlayDirector+EGameState state) (at Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs:146)
Treevel.Modules.GamePlayScene.GamePlayDirector.Awake () (at Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs:115)
UnityEngine.GameObject:AddComponent()
Treevel.Common.Patterns.Singleton.SingletonObject`1:get_Instance() (at Assets/Project/Scripts/Common/Patterns/Singleton/SingletonObject.cs:38)
Treevel.Modules.GamePlayScene.AbstractGameObjectController:OnEnable() (at Assets/Project/Scripts/Modules/GamePlayScene/AbstractGameObjectController.cs:18)
Treevel.Modules.GamePlayScene.Gimmick.TornadoController:OnEnable() (at Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/TornadoController.cs:89)
UnityEngine.AddressableAssets.Addressables:InstantiateAsync(Object, Transform, Boolean, Boolean)
Treevel.Common.Managers.AddressableAssetManager:Instantiate(Object, Transform, Boolean) (at Assets/Project/Scripts/Common/Managers/AddressableAssetManager.cs:149)
Treevel.Modules.GamePlayScene.Gimmick.<CreateGimmickCoroutine>d__6:MoveNext() (at Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/GimmickGenerator.cs:70)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:Run() (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/CompilerServices/StateMachineRunner.cs:189)
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTask.cs:21)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(AsyncUnit) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.DelayFramePromise:MoveNext() (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTask.Delay.cs:409)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:RunCore() (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/Internal/PlayerLoopRunner.cs:163)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Update() (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/Internal/PlayerLoopRunner.cs:137)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Run() (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/Internal/PlayerLoopRunner.cs:104)
```

2021-01-09 13:20 UTC, takesi0627 commented
・Unityを起動し直す
・`Spring-1-1` をプレイ
・ゲームを再起動
・もう一度`Spring-1-1`をプレイ
・それ以降`Spring-1-1`をプレイする度にエラーが発生
```
InvalidOperationException: Already continuation registered, can not await twice or get Status after await.
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].OnCompleted (System.Action`1[T] continuation, System.Object state, System.Int16 token) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTaskCompletionSource.cs:291)
Cysharp.Threading.Tasks.AddressablesAsyncExtensions+AsyncOperationHandleConfiguredSource`1[T].OnCompleted (System.Action`1[T] continuation, System.Object state, System.Int16 token) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/External/Addressables/AddressablesAsyncExtensions.cs:360)
Cysharp.Threading.Tasks.UniTask+Awaiter.SourceOnCompleted (System.Action`1[T] continuation, System.Object state) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTask.cs:351)
Cysharp.Threading.Tasks.UniTask+WhenAllPromise..ctor (Cysharp.Threading.Tasks.UniTask[] tasks, System.Int32 tasksLength) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTask.WhenAll.cs:185)
Cysharp.Threading.Tasks.UniTask.WhenAll (System.Collections.Generic.IEnumerable`1[T] tasks) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTask.WhenAll.cs:45)
Treevel.Modules.GamePlayScene.Tile.TileGenerator.CreateTiles (System.Collections.Generic.ICollection`1[T] tileDatas) (at Assets/Project/Scripts/Modules/GamePlayScene/Tile/TileGenerator.cs:60)
Treevel.Modules.GamePlayScene.StageGenerator+<CreateStages>d__4.MoveNext () (at Assets/Project/Scripts/Modules/GamePlayScene/StageGenerator.cs:38)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <fb001e01371b4adca20013e0ac763896>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
```

2021-01-10 01:57 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/BoardManager.cs
> +        private CancellationTokenSource _tokenSource;
わかりました

2021-01-11 06:16 UTC, xiii111 reviewed
- Code Style のコンフリクトの解決と、 `Build-in: Reformat Code` の適用をお願いします！

2021-01-12 13:18 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/SelfishEffectController.cs
> +            }).AddTo(this);
9e0cbdf

2021-01-13 15:09 UTC, takasusuke commented
`Gimmick`に関する変更は、元の`coroutine`による実装に戻します。
ゲーム画面でギミックの生成、ギミックの動きを一時停止する必要がありますが、`UniTask`で上手い方法が見つからないこと、以前の方法の方はわかりやすいからです。

2021-01-14 11:51 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/BoardManager.cs
> +        private CancellationTokenSource _tokenSource;
b82f67f

2021-01-14 12:42 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +            if (await BoardManager.Instance.HandleFlickedBottle(this, directionInt)) FlickNum++;
返り値は`UniTask<bool>`にしていたので、想定通り、Flickできたかどうかを返していました。
でも、移動後の成功判定後に`FlickNum++`しているので、成功時の`Flick`が加算されていませんでした。
移動の直前に加算するようにしました。

39853bb

2021-01-14 14:08 UTC, takasusuke commented
> ・Unityを起動し直す
> ・`Spring-1-1` をプレイ
> ・ゲームを再起動
> ・もう一度`Spring-1-1`をプレイ
> ・それ以降`Spring-1-1`をプレイする度にエラーが発生
> 
> ```
> InvalidOperationException: Already continuation registered, can not await twice or get Status after await.
> Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].OnCompleted (System.Action`1[T] continuation, System.Object state, System.Int16 token) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTaskCompletionSource.cs:291)
> Cysharp.Threading.Tasks.AddressablesAsyncExtensions+AsyncOperationHandleConfiguredSource`1[T].OnCompleted (System.Action`1[T] continuation, System.Object state, System.Int16 token) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/External/Addressables/AddressablesAsyncExtensions.cs:360)
> Cysharp.Threading.Tasks.UniTask+Awaiter.SourceOnCompleted (System.Action`1[T] continuation, System.Object state) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTask.cs:351)
> Cysharp.Threading.Tasks.UniTask+WhenAllPromise..ctor (Cysharp.Threading.Tasks.UniTask[] tasks, System.Int32 tasksLength) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTask.WhenAll.cs:185)
> Cysharp.Threading.Tasks.UniTask.WhenAll (System.Collections.Generic.IEnumerable`1[T] tasks) (at Library/PackageCache/com.cysharp.unitask@3115efb672/Runtime/UniTask.WhenAll.cs:45)
> Treevel.Modules.GamePlayScene.Tile.TileGenerator.CreateTiles (System.Collections.Generic.ICollection`1[T] tileDatas) (at Assets/Project/Scripts/Modules/GamePlayScene/Tile/TileGenerator.cs:60)
> Treevel.Modules.GamePlayScene.StageGenerator+<CreateStages>d__4.MoveNext () (at Assets/Project/Scripts/Modules/GamePlayScene/StageGenerator.cs:38)
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0)
> System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <fb001e01371b4adca20013e0ac763896>:0)
> UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
> UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
> ```

febc336
なぜこれで直ったのか。。。

2021-01-14 14:10 UTC, takasusuke commented
6686a78 : timerのバグを生み出していたので修正しました
0c3790c : coroutineの実装に戻しました
b82f67f : BoardManagerをGamePlaySceneに配置しました
39853bb : FlickNumを加算するタイミングを修正しました
febc336 : 2回awaitしてしまう問題がWarpTileの出現するステージで起きていました。多分直ったはずです。

2021-01-14 14:10 UTC, takasusuke commented
@xiii111 @takesi0627 
よろしくお願いします。

2021-01-14 15:47 UTC, takesi0627 commented
`Spring-1-2`で警告画像が消えない現象が起きています。
（なんかソースコードは前と違ったようですが、何か不具合がありましたか？）

https://user-images.githubusercontent.com/17778395/104613898-0b211780-56cb-11eb-99c8-d49b31c27317.mov

2021-01-14 16:51 UTC, takesi0627 requested changes

2021-01-14 16:51 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/TornadoController.cs
> +                }).AddTo(this);
ここで`StopAllCoroutines()`をやると https://github.com/LITO-apps/Treevel-client/pull/688#issuecomment-760281809 のバグを直せる

2021-01-14 16:51 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/ThunderController.cs
> +                // TODO:退場演出
なんかTODOの場所微妙に違うな

2021-01-14 16:51 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/AbstractGameObjectController.cs
> +                    compositeDisposable.Dispose();
`compositeDisposable`は失敗/成功時に破棄されるけど、リトライするときに新しく作成しなくてもいいんですか

2021-01-14 16:51 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +            } catch (OperationCanceledException) { }
```suggestion
            SetGesturesEnabled(false);
            _startMoveSubject.OnNext(Unit.Default);

            while (transform.position != targetPosition) {
                if (token.IsCancellationRequested) break;

                transform.position = Vector2.MoveTowards(transform.position, targetPosition, _SPEED);
                await UniTask.Yield(PlayerLoopTiming.FixedUpdate);
            }

            _endMoveSubject.OnNext(Unit.Default);
            SetGesturesEnabled(true);
```

https://lito-apps.slack.com/archives/C01E5GTPRV3/p1610372210041800
この方法使ったら `try/catch`いらないと思う

2021-01-14 16:51 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/AbstractGameObjectController.cs
> +                    compositeDisposable.Dispose();
1時間ぐらいコード読んでようやくちょっとだけわかったぐらい難解なので`compositeDisposable`を使うタイミングをドキュメントに書いて欲しい。

以下僕の理解、間違ったら訂正してください
* 購読の処理は他のオブジェクトに依存する場合
且つ
* 購読したイベントが発火するタイミングは `GameSucceeded`と`GameFailed`**以外**の場合

2021-01-15 11:20 UTC, xiii111 reviewed
コメントしました！いくつか他にも気になるところはありましたが、今回の PR で全て完璧にやるのはしんどすぎるので、最低限の修正で良いと思っていますので、コメントした分だけお願いします！

2021-01-15 11:20 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/AbstractBottleController.cs
> +                    throw new ArgumentNullException("ボトル画像の読み込みが失敗しました");
この変更も `built-in: full cleanup` の影響だな

2021-01-15 11:20 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/AttackableDummyBottleController.cs
> +            var lifeEffect = await AddressableAssetManager.Instantiate(Constants.Address.LIFE_EFFECT_PREFAB).ToUniTask();
これ `ToUniTask` いらないはず。以下全て同じ

FYI: https://lito-apps.slack.com/archives/C01E5GTPRV3/p1610283744019400

2021-01-15 11:20 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkEffectController.cs
>              _bottleController.releaseGesture.Released += HandleReleased;
これらって Observable に変換できないんだっけ？

2021-01-15 11:20 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +        private readonly Subject<Unit> _startMoveSubject = new Subject<Unit>();
`_moveStarted` とかどうでしょうか（嫌なら良いです）

2021-01-15 11:20 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +        private readonly Subject<Unit> _endMoveSubject = new Subject<Unit>();
`_moveFinished` とかどうでしょうか（嫌なら良いです）

2021-01-15 11:20 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/LifeEffectController.cs
> +            Observable.Merge(GamePlayDirector.Instance.GameSucceeded, GamePlayDirector.Instance.GameFailed)
今更だけど、随所で `Observable.Merge(GamePlayDirector.Instance.GameSucceeded, GamePlayDirector.Instance.GameFailed)` という表現をするから、 `GamePlayDirector` に `Merge` 後の `IObservable` を用意したらどうだろう？

2021-01-15 11:20 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/NormalBottleController.cs
> +                DoWhenSuccess();
一文の場合には `Subscribe()` をもう少し簡潔に書けた気がする。他のところも同様

2021-01-15 11:20 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/GimmickGenerator.cs
> +            // 出現時間経つまで待
？？？？？

2021-01-15 11:20 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/GimmickGenerator.cs
> +
なんだろうこの空行

2021-01-15 11:28 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +            } catch (OperationCanceledException) { }
こういうエラーが出る。
Flick event だからとか関係あるかも。

<img width="952" alt="スクリーンショット 2021-01-15 20 27 33" src="https://user-images.githubusercontent.com/26213141/104719647-22661080-5770-11eb-8843-84d8944ab05f.png">

2021-01-16 13:30 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/AbstractGameObjectController.cs
> +                    compositeDisposable.Dispose();
> > compositeDisposableは失敗/成功時に破棄されるけど、リトライするときに新しく作成しなくてもいいんですか
> 
> これは...確証を持っては言えないけど、詰め込まれたものを `dispose` してる（捨ててる）だけだから、リトライした後も再利用されるんじゃない？

現状、リトライするとゲームオブジェクトが破棄され作り直してるから問題ありませんが、一度

2021-01-16 13:57 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +            } catch (OperationCanceledException) { }
ここの `await` に `token` を渡していないからだと思いますが、まあそもそも `BoardManager` の設計が悪いから一旦これで大丈夫

![image](https://user-images.githubusercontent.com/17778395/104813617-a04c1980-584d-11eb-86ce-e78bbaa16a80.png)

2021-01-16 15:30 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/AbstractBottleController.cs
> +                    throw new ArgumentNullException("ボトル画像の読み込みが失敗しました");
これはこのままで良いのでは。

2021-01-16 15:30 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/GimmickGenerator.cs
> +
905496c

2021-01-16 15:30 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/GimmickGenerator.cs
> +            // 出現時間経つまで待
905496c

2021-01-16 15:31 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/AbstractBottleController.cs
> +        ///     無敵状態かどうか
905496c

2021-01-16 15:35 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/AttackableDummyBottleController.cs
> +            var lifeEffect = await AddressableAssetManager.Instantiate(Constants.Address.LIFE_EFFECT_PREFAB).ToUniTask();
b022961

2021-01-16 15:43 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +        private readonly Subject<Unit> _startMoveSubject = new Subject<Unit>();
うーん、保留で。

`Bottle Move Starts` or `Bottle Starts to Move`ね。。。

2021-01-16 15:44 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +        private readonly Subject<Unit> _endMoveSubject = new Subject<Unit>();
このコメントと同じ
https://github.com/LITO-apps/Treevel-client/pull/688#discussion_r558933203

2021-01-16 15:46 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/LifeEffectController.cs
> +            Observable.Merge(GamePlayDirector.Instance.GameSucceeded, GamePlayDirector.Instance.GameFailed)
`PiledUpPoewderController.cs`の
```
GamePlayDirector.Instance.GameSucceeded.Subscribe(_ => {
                Destroy(gameObject);
            }).AddTo(this);
```
ように成功時のみ行う処理があるので、このままが良いです。

2021-01-16 15:50 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/LifeEffectController.cs
> +            Observable.Merge(GamePlayDirector.Instance.GameSucceeded, GamePlayDirector.Instance.GameFailed)
両方公開すれば良いと思います

2021-01-16 15:52 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +        private readonly Subject<Unit> _startMoveSubject = new Subject<Unit>();
文型に従うのも大事ですが、伝わりやすさも視野に入れて今後改良していきたいね！

2021-01-16 15:53 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/AbstractBottleController.cs
> +                    throw new ArgumentNullException("ボトル画像の読み込みが失敗しました");
まぁ、そうだね。 `build-in full cleanup` の影響であることを伝えておいた

2021-01-16 15:56 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/LifeEffectController.cs
> +            Observable.Merge(GamePlayDirector.Instance.GameSucceeded, GamePlayDirector.Instance.GameFailed)
僕も @xiii111 の意見に賛成です
`GameSucceeded`、`GameFailed`、`GameEnd`
三種類用意した方がいいと思います

2021-01-16 15:56 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/LifeEffectController.cs
> +            Observable.Merge(GamePlayDirector.Instance.GameSucceeded, GamePlayDirector.Instance.GameFailed)
`GameEnd`ちょっと違うか？

2021-01-16 16:01 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/LifeEffectController.cs
> +            Observable.Merge(GamePlayDirector.Instance.GameSucceeded, GamePlayDirector.Instance.GameFailed)
言葉の問題になるけど、
ゲーム成功、という終了状態
ゲーム失敗、という終了状態
に遷移するわけで、ゲーム成功を呼んで、ゲーム終了を呼ぶのはなんか違う気がする。
`EndState`があるなら多少納得できるかもだけど。

2021-01-16 16:05 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/LifeEffectController.cs
> +            Observable.Merge(GamePlayDirector.Instance.GameSucceeded, GamePlayDirector.Instance.GameFailed)
単に便利だから用意したいかな。別に状態がなくても、公開したほうが便利だから欲しいかな

2021-01-16 16:22 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/NormalBottleController.cs
> +                DoWhenSuccess();
d93444f

2021-01-16 17:30 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkEffectController.cs
>              _bottleController.releaseGesture.Released += HandleReleased;
dfb9b99
思いの外スッキリした。
参考(Observable.FromEventで引数を受け取りたい場合)
https://befool.co.jp/blog/8823-scholar/unirx-from-event-args/

2021-01-16 17:38 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/AbstractGameObjectController.cs
> +                    compositeDisposable.Dispose();
`CompositeDisposable`インスタンス自体を再利用したい場合は`CompositeDisposable.Clear()`。
再利用しない場合は`CompositeDisposable.Dispose()`。
参考
https://qiita.com/su10/items/4e01023a7a1607e8323e

2021-01-16 17:44 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/AbstractGameObjectController.cs
> +                    compositeDisposable.Dispose();
> 購読の処理は他のオブジェクトに依存する場合
これは必須条件ではないと思う

2021-01-16 21:18 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/AbstractGameObjectController.cs
> +                    compositeDisposable.Dispose();
ゲーム終了時のタイミングで、購読を解除したい場合に用います。
現時点では、フリック、ホールドなどGestureに関わる処理にのみ使用しています。
952e311

2021-01-18 13:00 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/LifeEffectController.cs
> +            Observable.Merge(GamePlayDirector.Instance.GameSucceeded, GamePlayDirector.Instance.GameFailed)
4d3338e , 92d4828

2021-01-18 13:00 UTC, takasusuke commented
@xiii111 @takesi0627 
レビュー修正終えましたーーーー

2021-01-18 15:51 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkEffectController.cs
>              _bottleController.releaseGesture.Released += HandleReleased;
[slack](https://lito-apps.slack.com/archives/C01E5GTPRV3/p1610984854018000)で説明したように、`longPressGesture.OnLongPress`を使えば `AsObservable`で変換できます。ただ、 `longPressGesture.UseUnityEvent` を `true` にする必要あるので、 `bottleController` の `Awake` か `Initialize` でやっておくといいでしょう。

2021-01-18 15:53 UTC, takesi0627 commented
@takasusuke 
https://github.com/LITO-apps/Treevel-client/pull/688#discussion_r559659276
`FromEvent`の話あたりについてコメントしました。修正はそんなにかからないと思うのでお手数ですがよろしくお願いします。

2021-01-20 12:19 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkEffectController.cs
>              _bottleController.releaseGesture.Released += HandleReleased;
aacd6b5
FlickGestureはUnityEventがありませんでしたので、そのままです

2021-01-20 14:29 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +        public FlickGesture _flickGesture;
`private` にするか、 `flickGesture` にするかどちらかでお願いします

2021-01-20 14:30 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +        public FlickGesture _flickGesture;
4486c4c

2021-01-20 14:31 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +            Observable.FromEvent<EventHandler<EventArgs>, Tuple<object, EventArgs>>(h => (x, y) => h(Tuple.Create<object, EventArgs>(x, y)), x => _flickGesture.Flicked += x, x => _flickGesture.Flicke
```suggestion
            Observable.FromEvent<EventHandler<EventArgs>, Tuple<object, EventArgs>>(h => (x, y) => h(Tuple.Create(x, y)), x => _flickGesture.Flicked += x, x => _flickGesture.Flicked -= x)
```
`Create`に型指定いらないだとRider様がおっしゃいました。

2021-01-20 14:34 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +            Observable.FromEvent<EventHandler<EventArgs>, Tuple<object, EventArgs>>(h => (x, y) => h(Tuple.Create<object, EventArgs>(x, y)), x => _flickGesture.Flicked += x, x => _flickGesture.Flicke
6720515

2021-01-20 14:41 UTC, takesi0627 approved these changes
LGTM with nits

2021-01-20 14:41 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +
```suggestion
                .Select(x => x.Item1 as FlickGesture)
                .Where(_ => IsMovable)
                .Where(x => x != null && x.State == Gesture.GestureState.Recognized)
                .Subscribe(async gesture => {
```
使うかどうか任せる

2021-01-20 15:12 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
> +
ありがと！
21e03d2

2021-01-21 11:06 UTC, xiii111 approved these changes
お疲れ様でーっす！！ 🎉 🎉 🎉 🎉 🎉 🎉 🎉

2021-01-21 11:38 UTC, merged