Feature/individual record/show popup on tapping graph
LITO-apps/Treevel-client pull request #689
Opened 2020-12-26 00:39 UTC by xiii111

### 対象イシュー
Close #626 

### 概要
- [x] グラフのタップ時にポップアップを出す
- [x] ポップアップの位置をグラフの上部にする
- [ ] ポップアップの位置をグラフの x 座標に合わせた位置にする
- [ ] グラフからポップアップに線を伸ばす
- [x] ポップアップに挑戦回数と成功率を表示する
- [ ] ポップアップのテーマからを季節に合わせる（ #566 を取り込み次第 ）

### 詳細

#### 現実装になった経緯

#### 技術的な内容

### キャプチャ

### 動作確認方法

### 参考 URL

2021-01-04 13:15 UTC, xiii111 reviewed
セルフレビュー

2021-01-04 13:15 UTC, xiii111 commented on Assets/Project/Scripts/Common/Networks/IServerRequest.cs
> +
デバッグ用

2021-01-04 13:15 UTC, xiii111 commented on Assets/Project/Scripts/Common/Networks/Requests/GetStageStatsRequest.cs
> +            var stageStats = new StageStats(clearRate: Random.Range(0.0f, 1.0f), minClearTime: 1f, stageID: "1-1");
デバッグ用

2021-01-04 13:15 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/GraphPopupController.cs
> +            rectTransform.position = position;
`rectTransform.position.x` には setter がないから、x と y セットで代入しなきゃいけない。調べたところ、以下のような書き方をする必要があるよう

```
var position = GetComponent<RectTransform>().position;
position.x = 5;
GetComponent<RectTransform>().position = position;
```

2021-01-04 13:15 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/GraphPopupController.cs
> +            var data = await NetworkService.Execute(new GetStageStatsRequest(StageData.EncodeStageIdKey(treeId, stageNumber)));
`Observable` に変換してもよかったんだけど、単発ストリームの場合には `Async / Await` を使うべき、と `UniRx` 作った人が言ってたからこうした

2021-01-04 13:19 UTC, xiii111 commented
@takasusuke @takesi0627 レビューお願いします！

2021-01-09 11:35 UTC, takesi0627 commented
この「成功率」って自分の挑戦の中に何割成功したかって解釈されるんじゃないかと危惧しているんですけど、どうでしょうか

2021-01-09 12:00 UTC, takesi0627 requested changes
・現状`GraphBar`をタップすることでしかポップアップがでないですが、バーが短い時にタップすること自体が難しくなるので、トリガーとして、バー自体ではなく、そのステージの縦の領域として用意した方が良いではないかと思いました。
![スクリーンショット 2021-01-09 20 56 40](https://user-images.githubusercontent.com/17778395/104090907-3ff13100-52bd-11eb-8bb6-096112f7efb5.png)

・同様に、現状ポップアップを閉じる手段としても、バーをもう一度タップすることなので、同じ問題が生じます。`OverviewPopup`みたいに閉じるためのマスクを用意した方がいいと思いました。

2021-01-09 17:41 UTC, takasusuke requested changes
- 挑戦回数は○回プレイとかの表示が優しいと思います。

- 以下はiPhone XS 2688 x 1242 の表示です
`GraphPopup`の横幅、縦幅、marginの値を画面サイズに依存させてもらえないでしょうか。
例えば、`margin`の大きさは`max(画面横幅 * 0.04, 50)`とする(めっちゃ適当。単に横幅*0.04でも良いし)など。
また、`indicatorLine`の`(minY, maxY)`の値を`(ポップアップの下限、グラフの上限?)`とかに設定することをお願いいたします。(次の項目と関わる部分あり)
<img width="219" alt="スクリーンショット 2021-01-10 2 29 57" src="https://user-images.githubusercontent.com/26213141/104104497-e5bb9480-52eb-11eb-9307-2ba670134e76.png">

- 以下は、挑戦回数30回の時の表示です。意図した表示でしょうか。
ポップアップの高さ自体をもう少し高くする？ポップアップを手前に描画する？
<img width="219" alt="スクリーンショット 2021-01-10 2 38 11" src="https://user-images.githubusercontent.com/26213141/104104697-06d0b500-52ed-11eb-9c66-32755782c8d2.png">

2021-01-09 17:41 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/GraphPopupController.cs
> +        public async void Initialize(ESeasonId seasonId, ETreeId treeId, int stageNumber, Vector3 graphPosition)
```suggestion
        public async void Initialize(Color seasonColor, ETreeId treeId, int stageNumber, Vector3 graphPosition)
```
にしても良い気もします。

2021-01-09 17:41 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/GraphPopupController.cs
> +            _challengeNumText.text = challengeNum.ToString();
グラフは999+までなので、999回を上限にするか、
グラフよりも桁数を増やすにしても、表示の問題もあるので、9999+とかのチェックが欲しいです。

2021-01-09 17:41 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/GraphPopupController.cs
> +            _indicatorLine.GetComponent<RectTransform>().position = linePosition;
```suggestion
            lineRectTransform.position = linePosition;
```

2021-01-09 17:41 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/GraphPopupController.cs
> +            var data = await NetworkService.Execute(new GetStageStatsRequest(StageData.EncodeStageIdKey(treeId, stageNumber)));
```
var stageStats = (StageStats) await NetworkService.Execute(new GetStageStatsRequest(StageData.EncodeStageIdKey(treeId, stageNumber)));
```
でどうでしょうか。

2021-01-11 14:02 UTC, xiii111 commented
> ・現状`GraphBar`をタップすることでしかポップアップがでないですが、バーが短い時にタップすること自体が難しくなるので、トリガーとして、バー自体ではなく、そのステージの縦の領域として用意した方が良いではないかと思いました。

> 
> ・同様に、現状ポップアップを閉じる手段としても、バーをもう一度タップすることなので、同じ問題が生じます。`OverviewPopup`みたいに閉じるためのマスクを用意した方がいいと思いました。

2021-01-11 14:12 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/GraphPopupController.cs
> +            }
59b2c47

2021-01-11 14:14 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/GraphPopupController.cs
> +            var margin = 50 + rectTransform.rect.width / 2;
dbb513a

2021-01-12 12:03 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/GraphPopupController.cs
> +            _indicatorLine.GetComponent<RectTransform>().position = linePosition;
7205312

2021-01-12 12:03 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/GraphPopupController.cs
> +        public async void Initialize(ESeasonId seasonId, ETreeId treeId, int stageNumber, Vector3 graphPosition)
7205312

2021-01-12 12:21 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/GraphPopupController.cs
> +            _challengeNumText.text = challengeNum.ToString();
1ef7761

2021-01-12 12:27 UTC, xiii111 commented
> > ・同様に、現状ポップアップを閉じる手段としても、バーをもう一度タップすることなので、同じ問題が生じます。`OverviewPopup`みたいに閉じるためのマスクを用意した方がいいと思いました。
> 
> これに関しては、同意なので、ポップアップ以外の領域をタップした場合には閉じるようにしたいと思います

これやると言いましたが、やらない方向に考えが変わりました。理由としては、`OverviewPopup` は表示領域以外には関心がないので、ポップアップ以外のところに半透明のマスクを用意し、半透明部分をタップしたらポップアップを消すようにすることができますが、今回はポップアップは部分的な表示に過ぎず、 `OverviewPopup` と同様のコンテキストでマスクを使いたくありません。

しかしながら、それだとタップ領域が狭過ぎてしんどいだろうと思ったので、

> ・現状GraphBarをタップすることでしかポップアップがでないですが、バーが短い時にタップすること自体が難しくなるので、トリガーとして、バー自体ではなく、そのステージの縦の領域として用意した方が良いではないかと思いました。

やらないと言っていた、こっちの修正をしようと思います。

2021-01-12 12:31 UTC, xiii111 commented
やることがぐちゃぐちゃになってきたので、残っているやることを以下に書きます

- [ ] GraphBar 自体ではなく、Graph Bar が存在しうる縦の領域をタップした場合にポップアップを表示するようにする
- [ ] GraphPopup の横幅、縦幅、margin の値を画面サイズに依存させる
- [ ] indicatorLine の (minY, maxY) の値を (ポップアップの下限、グラフの上限?) とかに設定する

2021-01-14 13:06 UTC, xiii111 commented
@takesi0627 @takasusuke 

> indicatorLine の (minY, maxY) の値を (ポップアップの下限、グラフの上限?) とかに設定する

だけ手こずっていて終わっていませんが、他は終わったので再レビューの依頼だけさせてください。

2021-01-14 15:21 UTC, takesi0627 commented
> * [x]  GraphBar 自体ではなく、Graph Bar が存在しうる縦の領域をタップした場合にポップアップを表示するようにする → [3e4891e](https://github.com/LITO-apps/Treevel-client/commit/3e4891e945915ff01bf6e8b27d58d125e1da362b)
> * [x]  GraphPopup の横幅、縦幅、margin の値を画面サイズに依存させる → [5c99e4e](https://github.com/LITO-apps/Treevel-client/commit/5c99e4e8e68fe9002e6ab06c804ef1f88ac7a9e8)

上記2点特に問題ありませんでしあ

2021-01-19 11:47 UTC, takasusuke approved these changes

2021-01-19 11:49 UTC, xiii111 commented
📝 

> indicatorLine の (minY, maxY) の値を (ポップアップの下限、グラフの上限?) とかに設定する

は #704 で今後対応することになりました（with @takasusuke ）

2021-01-19 11:50 UTC, xiii111 commented
@takasusuke @takesi0627 再レビューお願いします🙏

2021-01-19 11:50 UTC, xiii111 commented
@takesi0627 問題なければマージします！

2021-01-19 15:05 UTC, takesi0627 approved these changes
何が起きてるのかわからないが任せた

2021-01-19 15:16 UTC, merged