Erasable Bottle no
LITO-apps/Treevel-client pull request #706
Opened 2021-01-22 08:10 UTC by xiii111

### 対象イシュー
Close 

### 概要

### 詳細

#### 現実装になった経緯

#### 技術的な内容

### キャプチャ

### 動作確認方法

### 参考 URL

2021-01-22 08:15 UTC, xiii111 commented
📝 一旦、`StageDataEditor` を用いて作成できる `ErasableBottle` を実装しています。ここから自動生成されるように修正していきます

2021-01-23 07:29 UTC, xiii111 commented
📝 一旦、`StageDataEditor` を用いて作成できる `ErasableBottle` を実装しています。ここから自動生成されるように修正していきます

2021-01-24 02:12 UTC, takesi0627 commented
## StartUpScene 
* 歓迎する雰囲気のBGM

x 1

## MenuSelectScene
* LevelSelect/Record/Settingの画面切り替えで特にBGMは変わらない
* （要検討）地図のスクロール位置の季節に応じてBGMを変える
* （要検討）時間帯による変化

x 1

## StageSelectScene
* 季節毎にBGMを用意
* 木全クリアした状態でアレンジする

x 8
 
## GamePlayScene
* チュートリアル中/Opening中のBGM
* PlayingステートのBGM
* 難しいステージはアレンジする

x 4?

2021-01-27 11:18 UTC, xiii111 reviewed
📝

2021-01-27 11:18 UTC, xiii111 commented on Assets/AddressableAssetsData/AssetGroups/Bottles.asset
>      m_SerializedLabels:
`ErasableBottle` の画像と Prefab を AAS に追加してタグ付けしただけ

2021-01-27 11:18 UTC, xiii111 commented on Assets/AddressableAssetsData/AssetGroups/Gimmicks.asset
>      m_ReadOnly: 0
`ErasablePrefab` の Prefab を AAS に追加してタグ付けしただけ

2021-01-27 11:18 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/GimmickType.cs
> +                    throw new ArgumentOutOfRangeException(nameof(type), type, "このギミックで失敗することはない");
本質的には関係ない部分ですが、ついでに直しました

2021-01-27 11:18 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/ErasableBottleController.cs
> +                .AddTo(this);
- `Animator` のレイヤーに以下を手動でアタッチする必要がある
<img width="563" alt="スクリーンショット 2021-01-27 20 17 02" src="https://user-images.githubusercontent.com/26104258/105983837-a60eee00-60dc-11eb-87a5-bd3ea630733e.png">

2021-01-27 11:20 UTC, xiii111 commented
@takasusuke @takesi0627 レビューお願いします。アニメーションに関してはインスペクタで確認をお願いします！レビュー時間は 1 時間くらいだと思います！

2021-01-27 12:31 UTC, takesi0627 commented
プルリクまだDraftのままだけど、それでいいんですか？

2021-01-27 12:45 UTC, xiii111 commented
> プルリクまだDraftのままだけど、それでいいんですか？

ミスです！

2021-01-27 13:14 UTC, takesi0627 requested changes
動作は問題ない！
細かいことについてコメントしました。よろしくお願いします

2021-01-27 13:14 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/ErasableBottleController.cs
> +                .AddTo(this);
最高っすねこれ

2021-01-27 13:14 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/BottleType.cs
> +        Erasable,
なんか `EBottleType` に `Erasable` を追加するのは `StageDataEditor` で除外の実装をしなきゃいけなくなっただけでもはや要らないのではないかと思いましたけど、どうでしょうか

2021-01-28 14:26 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/BottleType.cs
> +        Erasable,
バグるので現状維持

2021-01-29 12:23 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/GimmickType.cs
> +                    throw new ArgumentOutOfRangeException(nameof(type), type, "このギミックで失敗することはない");
77191a6

2021-01-29 12:23 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/AddressableAssetManager.cs
> +                        LoadAsset<Sprite>(Constants.Address.ERASABLE_BOTTLE_SPRITE);
不要でした！
- 9a31f87

2021-01-29 12:24 UTC, xiii111 commented
@takesi0627 修正しました！

@takasusuke レビュー通話で言われたことを修正しました。また、`compositeDisposable` をリネームしました。微妙だったら言ってください
- 70d4de9
- 3a70f6f

2021-01-29 12:46 UTC, takesi0627 approved these changes
Marvelous!!!

2021-01-29 17:52 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/ErasableController.cs
> +
自分なら、NormalTileの位置の`List<(int, int)>`を１度だけ計算・保持しておいて、
`InstantiateErasbaleBottle()`では、それらのうちemptyなものを１つ選択しますがいかがでしょうか。

2021-01-29 17:53 UTC, takasusuke reviewed
すばらしいと思います。
以下含め2点コメントしました。

`ErasbaleBottle`の出現アニメーション中にステージを終了させても、ErasbaleBottleのアニメーションは続く。
- そういう仕様
- 出現アニメーションの途中で止める(`PiledUpPowderontroller`など)
止めた方が良いかと思いますが、いかがでしょうか。

2021-01-30 04:14 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/ErasableController.cs
> +
現時点では tile の位置が塗り変わることがないので、計算量削減のためにも指摘通りにしました！
- 577fe5f

2021-01-30 04:17 UTC, xiii111 commented
> すばらしいと思います。
> 以下含め2点コメントしました。
> 
> `ErasbaleBottle`の出現アニメーション中にステージを終了させても、ErasbaleBottleのアニメーションは続く。
> 
> * そういう仕様
> * 出現アニメーションの途中で止める(`PiledUpPowderontroller`など)
>   止めた方が良いかと思いますが、いかがでしょうか。

正直、どっちにするか微妙ですが、実装自体は簡単なので実装してしまいました。`PiledUpPowederController` では `animator` の `param` をいじることで、アニメーションを停止させていましたが、`_animator.enabled = false` で良いらしいのでそうしました（`_animator.stop()` は `Obsolete` らしい？）
- ae4891d

2021-01-30 04:18 UTC, xiii111 commented
@takasusuke 修正しました！再レビューお願いします！

2021-01-30 05:37 UTC, takasusuke approved these changes
お疲れ様でした

2021-01-30 05:38 UTC, merged