NormalTileを他Tileと同じように生成する
LITO-apps/Treevel-client pull request #745
Opened 2021-02-13 16:21 UTC by takasusuke

### 対象イシュー
Close #741

### 概要
NormalTileをGamePlaySceneにあらかじめ配置するのではなく、ゲーム開始前に生成する

### 詳細
概要通り

#### 現実装になった経緯
特になし

#### 技術的な内容
- NormalBottleはインスタンス生成時にfinalTileを必要とするので、全体としてTileの生成後にBottleの生成が行われるようにした
- 今まではWarpTileなどを生成する場所のNormalTileは画面に見えないようにしていたが、そもそも生成しないようにした

### キャプチャ
HierarchyでNormalTileがTileGeneratorの子要素から独立していることがわかる
<img width="279" alt="スクリーンショット 2021-02-14 1 15 50" src="https://user-images.githubusercontent.com/26213141/107854886-5d885c00-6e62-11eb-95b9-13644d5bc063.png">

### 動作確認方法
- [ ] Spring_1_1をプレイ。ゲーム画面が変わりないことを確認。
- [ ] 実行前にGamePlaySceneにNormalTileがないことを確認。実行時、GamePlaySceneにNormalTileが生成されていることを確認。

### 参考 URL

2021-02-13 16:24 UTC, takasusuke commented on Assets/Project/Scripts/Common/Entities/GameDatas/TileData.cs
> +        [Range(1, 15)] public short pairNumber;
`number`と型を一致させた

2021-02-13 16:24 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/StageGenerator.cs
> +                await BottleGenerator.CreateBottles(stageData.BottleDatas);
`Tile`の生成後に`Bottle`を生成

2021-02-13 16:24 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/NormalTileController.cs
> +            GetComponent<SpriteRendererUnifier>().Unify();
spriteを生成したら必ずspriteの大きさを調整するので、１つのメソッドにまとめた
(`NormalBottleController.cs`で別々に呼んでいた部分を修正)

2021-02-13 16:24 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/TileGenerator.cs
> +                        .Where(tileNum => !tileNumList.Contains((short)tileNum))
あらかじめ特殊タイルの場所を把握しておいて、そこ以外にNormalTileを配置する

2021-02-13 16:25 UTC, takasusuke commented
@xiii111 @takesi0627 
どちらかお願いいたします。
30minくらいだと思います。

2021-02-14 03:24 UTC, takesi0627 requested changes

2021-02-14 03:24 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/TileGenerator.cs
> +                        )
```suggestion
                        .Select(tileNum => CreateTile(ETileType.Normal, tileNum))
```
メソッドにまとめましょう
```
        private UniTask CreateTile(ETileType type, int tileNum)
        {
            return AddressableAssetManager.Instantiate(_prefabAddressableKeys[type]).ToUniTask()
                .ContinueWith(tileObj => {
                    tileObj.GetComponent<AbstractTileController>().Initialize(tileNum);
                    BoardManager.Instance.SetTile(tileObj.GetComponent<AbstractTileController>(), tileNum);
                    tileObj.GetComponent<SpriteRenderer>().enabled = true;
                });
        }
```

2021-02-14 03:24 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/TileGenerator.cs
>                          .Where(tileData => tileData.type == ETileType.Holy || tileData.type == ETileType.Spiderweb || tileData.type == ETileType.Ice)
```suggestion
                        .Where(tileData.type != ETileType.Warp && tileData.type != ETile.Normal)
```
タイル種類が増えた時に考えるとこの方が変更忘れがなさそう

2021-02-14 06:53 UTC, xiii111 reviewed
コメントしました！

2021-02-14 06:53 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/StageGenerator.cs
> +                await BottleGenerator.CreateBottles(stageData.BottleDatas);
コメントをつけておこう。Tile の生成を待つ必要がある、など

2021-02-14 06:53 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/TileGenerator.cs
> +using Unity.UNetWeaver;
不要

2021-02-14 06:53 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/TileGenerator.cs
> +                        )
`CreateWarpTiles` みたいに関数にまとめたい

2021-02-14 06:53 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/TileGenerator.cs
>                          .Select(tileData => AddressableAssetManager.Instantiate(_prefabAddressableKeys[tileData.type]).ToUniTask()
`CreateWarpTiles` みたいに関数にまとめたい

2021-02-14 06:53 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/NormalTileController.cs
> +using UnityEditor;
使われてない

2021-02-14 06:53 UTC, xiii111 commented on Assets/Project/Scripts/Common/Managers/AddressableAssetManager.cs
> +
そうか、どれも使う可能性があるから初期化しておかなきゃいけないのか。今後いい感じにできたら良いね

2021-02-14 06:53 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/TileGenerator.cs
> +                .Concat(
素晴らしい書き方 🎉

2021-02-14 11:26 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/StageGenerator.cs
> +                await BottleGenerator.CreateBottles(stageData.BottleDatas);
9cd2ede

2021-02-14 11:28 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/NormalTileController.cs
> +using UnityEditor;
5dc81ac

2021-02-14 11:28 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/TileGenerator.cs
> +using Unity.UNetWeaver;
5dc81ac

2021-02-14 11:31 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/TileGenerator.cs
>                          .Where(tileData => tileData.type == ETileType.Holy || tileData.type == ETileType.Spiderweb || tileData.type == ETileType.Ice)
bd8a291

2021-02-14 11:40 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/TileGenerator.cs
>                          .Select(tileData => AddressableAssetManager.Instantiate(_prefabAddressableKeys[tileData.type]).ToUniTask()
c9f2e92

2021-02-14 11:40 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/TileGenerator.cs
> +                        )
c9f2e92

2021-02-14 11:40 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/TileGenerator.cs
> +                        )
c9f2e92

2021-02-14 11:43 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/AddressableAssetManager.cs
> +
若っっっっっっk干、気にはなるけれど、そのうちって感じだね。

2021-02-14 11:43 UTC, takasusuke commented
@xiii111 @takesi0627 
ありがとうございます。
修正いたしました。よろしくお願いいたします。

2021-02-15 14:04 UTC, takesi0627 approved these changes
Marvelous!!!

2021-02-16 13:03 UTC, xiii111 approved these changes

2021-02-16 13:03 UTC, takasusuke commented
感謝

2021-02-16 13:03 UTC, merged