[WIP] Bottleの色とTileの色を別々に指定する
LITO-apps/Treevel-client pull request #758
Opened 2021-02-21 15:03 UTC by takasusuke

### 対象イシュー
Close #757

### 概要
タイトルまま

### 詳細
傷画像を組み込む(#723)にあたり、BottleがTileの色を指定する(=Tileが自分の色をわかっていない)のは不都合があったので、BottleとTileの色を別々に指定するリファクタリングを行った
(Tile自身が、成功状態なのかわからないと、Tileに乗っている傷を消したり表示させたりするために、乗ってくるBottleがTileを探して関数を呼ばないといけない。Tileが乗ってくるBottleの色を判断して自分で表示を変更したい。)

その結果、BottleとTileが1:1である保証がなくなった。(N:Nができるようになったとも言える。)
なので、StageDataEditorでBottleの色の数とTileの色の数の整合性を保証するようにした。

また、BottleがTileを指定しなくなったので、画像をStageDataEditorで指定するのではなく、色だけを指定して、色から画像が一意に決まるようにした。

#### 現実装になった経緯
#723 でGoalTile.csの概念を導入して、傷画像とかを組み込む予定なので、あくまでリファクタリングを主とした。
なので、GoalTileに記述を移動する予定のコードをNormalTile.csに残している。

今は、StageDataEditorで生成するTileにNormalTileを指定していますが、GoalTileを指定するようにして、NormalTileは指定できないようにするつもりです。

#### 技術的な内容
特にないです。

### キャプチャ

### 動作確認方法

- [ ] Spring-1-1をプレイ

### 残実装

- [ ] NormalBottleがGoalColor.Noneを指定していないことをチェックする
- [ ] NormalTIleがGoalColor.Noneを指定していないことをチェックする
- [ ] NormalBottleの色とNormalTileの色の整合性をチェックする
- [ ] コメントを書く
- [ ] 全てのステージのpropertyを修正する
- [ ] 全てのギミック、ボトル、タイルでバグが起きないことを確認する

### 参考 URL

2021-02-27 05:21 UTC, takasusuke commented
549bc83 : `NormalTile`がリトライ時に削除されていないので修正しました。

6e86fb2 : このコミットで行ったリネームは、後の e3bc476 で取り消しました。

115e753 : ステージデータ、修正するの面倒すぎたので、ギミックとか無くして全部1-1と同じにしました。

2021-02-27 05:32 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/NormalTileController.cs
> -        public void SetSprite(Sprite sprite)
このメソッドは`NormalTile`でしか使っていなかったのでここにありましたが、今回`NormalBottle`でも使うようになりました。
`SpriteRendererUnifier.cs`に関わる汎用的なメソッドなのでそちらに移動しました。

2021-02-27 05:32 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/BoardManager.cs
> +        public EGoalColor GetTileColor(NormalBottleController bottle)
このメソッド、`GetTileColor`という名前だと、`tile`を引数に与えて`color`を取得する感じある。
(引数の型で判断できるけど)

気になるなら`GetParentTileColor`とかでしょうか。

2021-02-27 05:33 UTC, takasusuke commented
@xiii111 @takesi0627 
お願いします。
1h くらい、でしょうか。

2021-02-27 12:03 UTC, takesi0627 commented
タイトルからWIP消しますね

2021-02-27 13:31 UTC, takesi0627 requested changes
軽く動作確認したが、
ステージデータで `GoalColor` 全部反映されず、ステージに入る時も色がないと怒られる。

![image](https://user-images.githubusercontent.com/17778395/109388583-575aab00-794b-11eb-9261-18e2c1f0291f.png)
![image](https://user-images.githubusercontent.com/17778395/109388608-7d804b00-794b-11eb-9689-f6e6fec2403b.png)

2021-02-27 13:31 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/ErrorCode.cs
> +        InvalidTileColor,   // タイルの色が不適当
`TextIndex.cs` と `translation.csv` にも追加してあげてください

2021-02-27 14:09 UTC, takasusuke commented
> 軽く動作確認したが、
> ステージデータエディターで `GoalColor` 全部反映されず、ステージに入る時も色がないと怒られる。
>

えっと、Spring-1-1をSTageDataEditorで開いたらcolorが全部Noneになっているってこと？
そこで色を設定して保存しても反映されないってこと？

2021-02-27 14:12 UTC, xiii111 commented
余裕があったら見るけど、 @takesi0627 に任せるかも

2021-02-27 14:12 UTC, takasusuke commented on Assets/Project/Actors/Bottles/Normal/NormalBottlePrefab.prefab
> +  m_Size: {x: 240, y: 264}
今回、何もいじらずただ今までの変更分を取り込んだだけですが、
サイズを100倍にするissueでの変更(`2`→`200`)と、
NormalBottleの画像を適用するissueで画像サイズが変わった変更(`200`→`240`, `200`→`264`)です。

2021-02-27 14:34 UTC, takesi0627 commented
> > 軽く動作確認したが、
> > ステージデータエディターで `GoalColor` 全部反映されず、ステージに入る時も色がないと怒られる。
> 
> えっと、Spring-1-1をStageDataEditorで開いてもcolorが全部Noneになっているってこと？
> さらに、そこで色を設定して保存しても反映されない？

色設定して保存するまではやってなかった。ただ差分取り込んでも反映されないのは挙動としては問題あるかと思うので報告した。

色保存してやってみる

2021-02-27 14:36 UTC, takesi0627 commented
普通にしんどいな

2021-02-27 14:36 UTC, takesi0627 commented
ボトルまで全部設定しないといけないのか・・・

2021-02-27 14:46 UTC, takesi0627 commented
@takasusuke 一回データいじって、Unityを立ち上げ直すと治った。（データいじらずに立ち上げ直しても治らない）
またUnityの謎仕様かもしれない

2021-02-27 14:48 UTC, takesi0627 commented
動作確認できました。
翻訳周り修正したらアプルーブします！

2021-02-27 15:12 UTC, xiii111 reviewed
軽くコメントしました〜

2021-02-27 15:12 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/GoalColor.cs
> +            return Constants.Address.NUMBER_TILE_SPRITE_PREFIX + goalColor;
NumberTile って存在は、もう少し先で消えるんだっけ？

2021-02-27 15:12 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/NormalBottleController.cs
> +
空行にインデントがある？

2021-02-27 17:18 UTC, takasusuke commented on Assets/Project/Scripts/Common/Components/SpriteRendererUnifier.cs
> +            _renderer.enabled = true;
その通りでございます。

2021-02-27 17:25 UTC, takasusuke commented on Assets/Project/Scripts/Common/Entities/GoalColor.cs
> +            return Constants.Address.NUMBER_TILE_SPRITE_PREFIX + goalColor;
消える予定ではあるけど、ここは`GOAL_TILE`にした方が自然だね。
気づかんかった。

2021-02-27 17:33 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/NormalBottleController.cs
> +
30b7b73

2021-02-27 17:33 UTC, takasusuke commented on Assets/Project/Scripts/Common/Entities/GoalColor.cs
> +            return Constants.Address.NUMBER_TILE_SPRITE_PREFIX + goalColor;
698c352

2021-02-27 17:34 UTC, takasusuke commented on Assets/Project/Scripts/Common/Entities/ErrorCode.cs
> +        InvalidTileColor,   // タイルの色が不適当
a2683ff
なるほどそうなのか。さすがText周りの作成者様です。

2021-02-27 17:37 UTC, takasusuke commented
@takesi0627 
改めてお願いいたします。

2021-02-28 01:19 UTC, takesi0627 approved these changes
OKです。
お疲れ様です

2021-02-28 01:35 UTC, takesi0627 commented
ごめん今気づいたけど、ギミックなんか全部消えたんですが、それは意図して消した？

2021-02-28 02:33 UTC, takasusuke commented
> ごめん今気づいたけど、ギミックなんか全部消えたんですが、それは意図して消した？

意図して消しました。
>> 115e753 : ステージデータ、修正するの面倒すぎたので、ギミックとか無くして全部1-1と同じにしました。

2021-02-28 02:45 UTC, takesi0627 commented
ごめんそれも気づかなかったw

2021-02-28 04:07 UTC, merged