BGM
LITO-apps/Treevel-client pull request #761
Opened 2021-02-24 16:22 UTC by takesi0627

### 対象イシュー
Close 

### 概要

### 詳細

#### 現実装になった経緯

#### 技術的な内容

### キャプチャ

### 動作確認方法

### 参考 URL

2021-02-24 16:27 UTC, takesi0627 commented
@xiii111 @takasusuke 
レビューよろしくお願いします

2021-02-24 16:30 UTC, takesi0627 commented
`ループの先頭にフェイドイン、最後にフェイドアウトするように` 
この要件忘れてたので一旦WIPにします

2021-02-28 10:51 UTC, takesi0627 commented
@takasusuke @xiii111 

レビューお願いします。コードの理解はそんなにかからないと思うが、ループ周りの動作確認は時間かかるかもしれない

2021-02-28 14:29 UTC, takasusuke requested changes
動作確認しました！

2021-02-28 14:29 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +            ResetVolume();
`ResetBGMVolume()`みたいな、BGMの音量だけリセットした方が良いのではないか。

2021-02-28 14:29 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
>          }
```suggestion
        /// <param name="from">初期値(0.0 to 1.0)</param>
        /// <param name="to">終値(0.0 to 1.0)</param>
        /// <param name="time">変化する時間(>0)</param>
        private async UniTask FadeBGMVolume(float from, float to, float time)
        {
            var elapsed = 0f;
            while (elapsed < time) {
                _bgmPlayer.volume = Mathf.Lerp(from, to, elapsed / time);
                await UniTask.WaitForEndOfFrame();
                elapsed += Time.deltaTime;
            }
            _bgmPlayer.volume = to;
        }
```

2021-02-28 14:29 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
>          }
- 引数の値域についてのコメントが欲しい
- while文が終わった時にtoの値に設定しないと、toより少し小さい(or大きい)値になると思う

2021-02-28 14:29 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopBGM(float fadeOutTime = 2.0f)
```suggestion
        public void StopBGM(float fadeOutTime = _BGM_LOOP_FADE_TIME)
```

ということでOK？

2021-02-28 15:41 UTC, xiii111 commented
@takasusuke 任せます！

2021-03-03 14:15 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopBGM(float fadeOutTime = 2.0f)
ループで再生している場合と明示的にメソッドを呼び出す時場合のパラメータは
少し意味合い違うと思ったからわざと一緒にしていなかったです。

2021-03-03 14:25 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +            ResetVolume();
c73fab4

2021-03-03 14:27 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
>          }
c4b602c

6b3b861

2021-03-03 14:28 UTC, takesi0627 commented
@takasusuke 
修正しました、確認お願いします

2021-03-03 15:26 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopBGM(float fadeOutTime = 2.0f)
そうなると、fadeOutTimeのデフォルト値は0fが妥当じゃない？

2021-03-03 15:28 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
>          }
ごめん、条件間違えたんだけど、
time>=0かも

2021-03-03 15:30 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopBGM(float fadeOutTime = 2.0f)
パタっと音を切りたいかどうかによると思うですが、自分の仕事のプロジェクトではデフォルトでフェイドアウトするようにしています

2021-03-03 15:32 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopBGM(float fadeOutTime = 2.0f)
一般的にこの関数を呼ぶ時はBGMがまだ再生途中なので、急に音消えるとユーザに不快感を与えてしまう？かもしれない

2021-03-03 15:32 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopBGM(float fadeOutTime = 2.0f)
デフォルトでフェイドアウトするならデフォルトのフェイドアウト時間が定数定義されてないと、後で調整しづらいと思う

2021-03-03 15:39 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopBGM(float fadeOutTime = 2.0f)
他のところも使うならわかるけど、ここでしか使わないなら巻数のシグネーチャー見れば十分これがデフォルトのフェイドアウト時間とわかるなんじゃないか？（シグネーチャーが定数の定義になっている）

2021-03-03 15:48 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopBGM(float fadeOutTime = 2.0f)
確かに。

> ループで再生している場合と明示的にメソッドを呼び出す場合のパラメータは
> 少し意味合い違うと思ったからわざと一緒にしていなかったです。

そして、ここの意味が分かってきた。

2021-03-03 15:49 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopBGM(float fadeOutTime = 2.0f)
ループの時の、フェードイン、フェードアウトは全てのBGMで共通で良いの？
（PlayBGMの引数に追加しなくて良いの？）

2021-03-03 15:51 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopBGM(float fadeOutTime = 2.0f)
追加してもいいけど、そかまでする必要ないかと

2021-03-03 15:52 UTC, takasusuke approved these changes

2021-03-03 15:53 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        public void StopBGM(float fadeOutTime = 2.0f)
あんまりBGMがループすることは想定してないから、固定値で良いか、という感じかな。
必要になったらで良いか。
OK！

2021-03-03 15:53 UTC, takesi0627 commented
あざます

2021-03-03 15:53 UTC, merged