一時停止ボタンのデザイン適用
LITO-apps/Treevel-client pull request #773
Opened 2021-03-14 12:54 UTC by takasusuke

### 対象イシュー
Close #722

### 概要
タイトルまま

### 詳細
- 一時停止ボタンの画像変更
- 一時停止ボタンの配置方法の変更
- 一時停止ボタンの表示タイミングの修正
- 一時停止中の背景、一時停止ボタン、一時停止ポップアップの初期状態をdisableに変更

#### 現実装になった経緯
正方形に表示したかったので、縦方向の大きさはデバイスの縦の大きさに依存。
横方向の大きさは一時停止ボタンの縦の大きさに依存に設定。
デバイスの縦方向を参照した理由は、横方向を参照すると、極端なデバイスでは縦方向の大きさが大きくなり、タイルやボトルに被るリスクがあるから。
縦方向を参照すると、ボタンが小さくなりすぎることはあっても、大きくなりすぎてタイルやボトルに被ることはない。
※ そもそもそんなギリギリに置いてないから多少大きくなっても大丈夫だし、そんな極端に小さくなることもないと思ってる。
※ 極論、一時停止ボタンが小さすぎて押せなくなってもいいけど、大きすぎてゲームが遊べないのは致命的。

#### 技術的な内容
一時停止中の背景、一時停止ボタン、一時停止ポップアップの初期状態をoffにしたかった。
初期状態をoffにすると、Find()で探せないので、GUIで直接アタッチした。

### キャプチャ
<img width="266" alt="スクリーンショット 2021-03-14 21 51 54" src="https://user-images.githubusercontent.com/26213141/111069255-8e19ef00-850f-11eb-9e14-9923d52faf5a.png"> <img width="263" alt="スクリーンショット 2021-03-14 21 52 01" src="https://user-images.githubusercontent.com/26213141/111069257-8f4b1c00-850f-11eb-8e7d-4fa769052182.png">
<img width="262" alt="スクリーンショット 2021-03-14 21 52 06" src="https://user-images.githubusercontent.com/26213141/111069261-91ad7600-850f-11eb-904b-bcbe1e4ed600.png"> <img width="270" alt="スクリーンショット 2021-03-14 21 52 12" src="https://user-images.githubusercontent.com/26213141/111069263-92dea300-850f-11eb-8453-c56eca23cde8.png">

### 動作確認方法
Spring-1-1をプレイ。
- [ ] チュートリアル中に一時停止ボタンが表示されない。

- [ ] ゲーム中に一時停止ボタンが表示される。

- [ ] 一時停止中に一時停止ボタンが表示されない。

- [ ] ゲーム終了時に一時停止ボタンが表示されない。

### 参考 URL

2021-03-14 12:55 UTC, takasusuke commented
ゲーム画面の文字にボタンが被ってるのはこのissueで考慮することではないです。

2021-03-14 12:56 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                Instance.pauseButton.SetActive(false);
ここのすぐ上で、SoundManager.Instanceとかって呼ぶんだから、(GamePlayDirector).Instanceで呼べば良くない？って思って変えました。

2021-03-14 12:56 UTC, takasusuke commented
@xiii111 @takesi0627 
どちらかヨロです。

2021-03-15 10:14 UTC, takesi0627 requested changes
動作問題ないです。
`pauseBackground`、`pauseButton`、`pauseWindow` をプライベートにしてほしい

2021-03-15 10:14 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +        public GameObject pauseBackground;
```suggestion
       [SerializeField] private GameObject pauseBackground;
```
ここは `private` にしましょう

2021-03-15 10:14 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                Instance.pauseButton.SetActive(false);
いいと思います。
が、これらのゲームオブジェクトは `public` として公開するのは良くないと思いますので、 `private` にしてほしいです

2021-03-15 13:44 UTC, xiii111 approved these changes
LGTM with nits!

2021-03-15 13:44 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +
ここも GUI 操作での参照のために `public` なら `[SerializeField] private` にして欲しいです~

2021-03-15 15:11 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +
200e2ef

2021-03-15 15:12 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +        public GameObject pauseBackground;
200e2ef

2021-03-15 15:12 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                Instance.pauseButton.SetActive(false);
200e2ef
内部クラスからなら`private`でも参照できるのか〜

2021-03-15 15:13 UTC, takasusuke commented
@takesi0627 
修正しました！

2021-03-17 13:50 UTC, takesi0627 approved these changes
`private` メンバーの変数名は `_` をつけましょう。それだけ

2021-03-18 15:15 UTC, takasusuke commented
修正しました
ありがとうございました！

2021-03-18 15:15 UTC, merged