SE仮適用
LITO-apps/Treevel-client pull request #791
Opened 2021-04-02 17:12 UTC by takesi0627

### 対象イシュー
Close #662 

### 概要

[リスト](https://github.com/LITO-apps/Treevel-client/issues/663#issuecomment-808359731)に基づきSEを鳴らす実装をする

### 詳細

fc6f78b 与えられた複数のタグからランダムで一つを選んで再生する関数を作った
a2cf2ee ランダム再生する際再生されたタグが分からないので、同時に複数のSEを停止することができる関数を用意した
66b0f3f 概要ポップアップは開く閉じる何回繰り返すと複数回 `Subscribe`してしまう問題があったので修正しました。

### 動作確認方法
一通りゲーム進んでSEの確認してください。
Summer-1-1 : WarpTile、Thunder
Summer-1-2: GustWind
Summer-1-3: Powder

### 特記事項
対象外：
* SEの音量バランス調整
* MeteoriteのSE実装（演出未実装のため）
* MenuSelectSceneのフッターボタンのSE（現在制御できるスクリプトがないため）

2021-04-02 17:15 UTC, takesi0627 commented
@xiii111 @takasusuke 
レビューお願いします。結構時間かかると思います。

ボタンの音は結構適当に振り分けているので、違和感があれば教えてください。
StageSelectSceneめちゃくちゃバグってるので `StageController.ReflectTreeState`をいじってステージが必ず解放されるようにすることをお勧めします

2021-04-03 09:45 UTC, takasusuke requested changes
#### 1
fc6f78b : ちょうどバグ報告してた問題が改善されとる。神。

#### 2
Summer_2をplayして待っていると、以下のようなエラーメッセージが出ます。
<img width="1102" alt="スクリーンショット 2021-04-03 18 22 53" src="https://user-images.githubusercontent.com/26213141/113474215-a4312480-94a9-11eb-83c8-1a7824b7ea83.png">

#### 3
以下の場面のSEもお願いします。Footerみたいにスクリプトがないものはなしで大丈夫です。
- MenuSelectScene/SettingsのButtonのSE
- チュートリアル画面を閉じるボタンのSE
- エラーメッセージを閉じるボタンのSE
- スライダーのSEは未定...?

2021-04-03 09:45 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        private const int _MAX_SE_NUM = 16;
`ask`
ここの数字って、考えられる最大のSEの数？
ギミック１つに対して3つSEがある場合、ギミックが10種類あったりしたら、_MAX_SE_NUM=30以上に設定しないといけないよね？
どんどん、Gimmick, Bottle. Tileが増えたりするとここの数字も増やさないといけない、という認識で合ってる？？

SoundManagerを２つ用意して、種類の多いステージは_MAX_SE_NUM=9999のSoundManagerを使って、
それ以外の場面では_MAX_SE_NUM=8のSoundManagerにするとか、そういうことも将来的に必要？
それとも、_MAX_SE_NUM=9999のSoundManagerがあれば良い？

2021-04-03 09:45 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/ThunderController.cs
> +            SoundManager.Instance.PlaySERandom(new[] { ESEKey.Gimmick_Thunder_1 , ESEKey.Gimmick_Thunder_2} );
`nits`
Code Cleanup

2021-04-03 09:45 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                    SoundManager.Instance.PlaySERandom(new []{ ESEKey.GamePlay_Failed_1, ESEKey.GamePlay_Failed_2});
`nits`
Code Cleanup

2021-04-03 09:45 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/ThunderController.cs
> +                SoundManager.Instance.StopSE(new [] { ESEKey.Gimmick_Thunder_1 , ESEKey.Gimmick_Thunder_2});
`nits`
Code Cleanup

2021-04-03 09:45 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        UI_Button_Click2,
`UI_Button_Click1`と`UI_Button_Click2`だとどっちがどっちか覚えられない。。。
以下のようにするのはどうでしょうか。

#### 1
`UI_Button_Click_Positive`と`UI_Button_Click`とか印象で名前つける

#### 2
`UI_Button_Click1`っていうSEを
`UI_Start_App_Button_Click`と`UI_Start_Game_Button_Click`の２つの名前で用意しておいて、
最初の画面のボタンは`UI_Start_App_Button`、
GamePlaySceneに遷移するボタンは`UI_Start_Game_Button`にしておく。
あと、`UI_Button_Click2`は`UI_Button_Click`にしておく。

2021-04-04 09:44 UTC, xiii111 commented
@takesi0627 

@takasusuke が結構ちゃんとレビューしてくれてる様子なので、任せます。

2021-04-05 14:42 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        private const int _MAX_SE_NUM = 16;
同時発声数が多ければいいほどゲームに良いわけではないので、9999はいらないと考えている。
多くても32ぐらいがちょうどいいかと考えております。それ以上同時発生が必要な場合は、ステージの設計を考え直す必要があると思います

2021-04-05 15:03 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/ThunderController.cs
> +            SoundManager.Instance.PlaySERandom(new[] { ESEKey.Gimmick_Thunder_1 , ESEKey.Gimmick_Thunder_2} );
c210183

2021-04-05 15:04 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                    SoundManager.Instance.PlaySERandom(new []{ ESEKey.GamePlay_Failed_1, ESEKey.GamePlay_Failed_2});
cd9c480

2021-04-05 15:06 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        UI_Button_Click2,
`UI_Button_Click_Start_App`
`UI_Button_Click_Start_Game`
`UI_Button_Click_General`
にしたいと思います

2021-04-05 15:32 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        UI_Button_Click2,
933e2c1

2021-04-07 17:11 UTC, takasusuke commented on Assets/Project/Scripts/Common/Managers/SoundManager.cs
> +        private const int _MAX_SE_NUM = 16;
理解した！

2021-04-07 17:18 UTC, takasusuke approved these changes

2021-04-07 17:18 UTC, takasusuke commented
Conflictすまぬ。。。

2021-04-07 17:20 UTC, takasusuke commented
一応確認だけど、以下の問題はこのissueとはたぶん関係ないよね？？？
- ステージに入るたびに、`DontDestroyOnLoad`に`SoundManager`が増える。
- ゲームクリアして、BGMがフェードアウトしてる間に、StageSelectSceneに戻って別のゲームを始めると、BGMが流れない。

2021-04-09 15:58 UTC, takesi0627 commented
> 一応確認だけど、以下の問題はこのissueとはたぶん関係ないよね？？？(アイデア追加済)
> 
> * ステージに入るたびに、`DontDestroyOnLoad`に`SoundManager`が増える。

謎すぎる・・・関係ないと思います

> * ゲームクリアして、BGMがフェードアウトしてる間に、StageSelectSceneに戻って別のゲームを始めると、BGMが流れない。

これも今回とは関係ないと思います

2021-04-09 15:58 UTC, merged