EffectをAttributeにリネーム
LITO-apps/Treevel-client pull request #866
Opened 2021-04-12 14:17 UTC by takasusuke

### 対象イシュー
Close #863

### 概要
タイトルまま

### 詳細

#### 現実装になった経緯
- Effectだと、演出の意味と被るから

#### 技術的な内容
特になし

#### その他
`WarpTileController.cs`の
```
// warpTileEffectを止める
```
というコメントは演出の意味のEffectなのでそのまま

### キャプチャ
<img width="230" alt="スクリーンショット 2021-04-12 23 16 08" src="https://user-images.githubusercontent.com/26213141/114409125-14942000-9be5-11eb-8517-7d8847abcfe4.png">

### 動作確認方法

- [ ] Spring-1-1をプレイ。Selfish, Dark, Reverse, Lifeが問題なく動作する

### 参考 URL

2021-04-12 14:18 UTC, takasusuke commented
15aca1d (最初のcommit) : commitメッセージにスペルミスしてるのに気付きました。。。
```
Rename LifeEffect to LifeAttribute
```
です。

dcf8921 : 実行したら現れた差分のcommit

2021-04-12 14:20 UTC, takasusuke commented
@xiii111 @takesi0627 
どちらかお願いします。
動作確認お願いします。
一応、commitごとに１つのスクリプトor１つのファイルのrenameを見て、スペルミスしてないか見るのをお願いします。

20min以内です。
木曜以降で良いですが、あまり放置したくないので早め希望です。

2021-04-12 14:34 UTC, xiii111 reviewed
`Spring-1-1` をプレイしようとしたら、以下のような画面になり、エラーも出たのですが、私の環境だけでしょうか？

<img width="334" alt="スクリーンショット 2021-04-12 23 32 04" src="https://user-images.githubusercontent.com/26104258/114411868-89685980-9be7-11eb-9798-6da4421dc9d8.png">


<img width="1956" alt="スクリーンショット 2021-04-12 23 32 46" src="https://user-images.githubusercontent.com/26104258/114411886-8ff6d100-9be7-11eb-9d6f-73555fdc5e78.png">

2021-04-12 14:42 UTC, xiii111 requested changes
https://github.com/LITO-apps/Treevel-client/pull/866#pullrequestreview-633613669 の動作だけ確認お願いいたします。

コミットが分かれていてとても読みやすかったです👍

2021-04-12 14:42 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/BottleAttributeType.cs
>          /// 0番目はBottleの描画順序なので、Effectの順序は1番以降
```suggestion
        /// 0番目はBottleの描画順序なので、Attributeの順序は1番以降
```

2021-04-12 14:53 UTC, takasusuke commented on Assets/Project/Scripts/Common/Entities/BottleAttributeType.cs
>          /// 0番目はBottleの描画順序なので、Effectの順序は1番以降
不覚。。。

2021-04-12 14:54 UTC, takasusuke commented
ここの右下、何が入ってる？
何も入ってない場合、左上からアタッチして保存したら差分出る？

<img width="1508" alt="スクリーンショット 2021-04-12 23 50 57" src="https://user-images.githubusercontent.com/26213141/114415035-4bb90000-9bea-11eb-902c-04ee27ae72e1.png">

2021-04-13 13:39 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/BottleAttributeType.cs
>          /// 0番目はBottleの描画順序なので、Effectの順序は1番以降
Thanks → b8cdd80

2021-04-13 13:45 UTC, xiii111 commented
@takasusuke 

> ここの右下、何が入ってる？

何も入ってない

<img width="605" alt="スクリーンショット 2021-04-13 22 42 00" src="https://user-images.githubusercontent.com/26104258/114562720-b9783100-9ca9-11eb-976f-72d402e11f23.png">

> 何も入ってない場合、左上からアタッチして保存したら差分出る？

アタッチできない ... 

https://user-images.githubusercontent.com/26104258/114562879-de6ca400-9ca9-11eb-8bcf-26308218b042.mov

2021-04-13 14:07 UTC, takasusuke commented
> 
> アタッチできない ...
> 
ProjectウィンドウのLifeAttributePrefabをダブルクリックして、Hierarchy ウィンドウのLifeAttributePrefabを選択した状態で、同じようにLife_Valueをアタッチしてみて。

<img width="1500" alt="スクリーンショット 2021-04-13 23 06 30" src="https://user-images.githubusercontent.com/26213141/114566091-e712a980-9cac-11eb-8f3e-3f5fba559ce1.png">

2021-04-13 14:15 UTC, xiii111 commented
@takasusuke なぜか今実行したら問題なく実行できました！ Life Object も None ではなく、きちんとした値が入っていました！
これは、別の問題ですが、若干ボトルなどが表示されるのが遅い気がしますが、問題ないですか？

https://user-images.githubusercontent.com/26104258/114567300-11189b80-9cae-11eb-89d4-e53459b4b28f.mov

2021-04-13 14:23 UTC, takasusuke commented
> これは、別の問題ですが、若干ボトルなどが表示されるのが遅い気がしますが、問題ないですか？
> 
>  test.mov

#784 でGameの開始直前に描画するようにしたので以前より遅くなってるとは思います。
(この描画タイミングのあとに開始アニメーションが入れば気にはならないかなと思ってる。)
Attribute関連は、開始直前に描画する設定を入れてなくて、インスタンスが作成されたらそのまま描画されるので、Attribute関連が先に見えるのは不具合です。

→ #868 作成

2021-04-13 14:26 UTC, xiii111 approved these changes
Great work!

2021-04-13 15:04 UTC, takesi0627 commented
今からみます

2021-04-13 15:36 UTC, takesi0627 approved these changes
問題ないですが、レビューして気づいたんですけど、Addressables Groups設定が見れなくなってる。
developもそうなのでどこかのタイミングからバグったかもしれない。共有だけ。

![image](https://user-images.githubusercontent.com/17778395/114579971-5f7f6780-9cb9-11eb-8e14-c212c3619939.png)

2021-04-13 15:38 UTC, takasusuke commented
感謝

2021-04-13 15:38 UTC, merged