カウントダウンステート実装
LITO-apps/Treevel-client pull request #875
Opened 2021-04-17 14:15 UTC by takesi0627

### 対象イシュー
Close #834 

### 概要
ゲーム開始前のカウントダウンの演出のための機能実装

### 詳細
* 仮の演出に `Text Mesh Pro` 導入してみた。
* カウントダウンステートはアニメーションの再生のみ、再生終了後Playingステートに移行する。

#### 現実装になった経緯

### キャプチャ

https://user-images.githubusercontent.com/17778395/115116005-5c92b880-9fd2-11eb-8df5-2b5b59212aa1.mov

### 動作確認方法
- [ ] 任意のステージに入り、カウントダウンアニメーションが再生されてからゲーム開始することを確認
- [ ] ギミックのあるステージをプレイし、失敗後リトライする際、カウントダウンアニメーションが**再生されない**ことを確認

2021-04-17 14:16 UTC, takesi0627 commented
@xiii111 @takasusuke 
よろしくお願いします
コードのレビューはすぐ終わると思うが、アニメーションの設定など細かくみたい場合ちょっと時間かかるかも。

2021-04-18 01:14 UTC, xiii111 commented
📝 ステージのカウントダウンが `Ready Go` が終わるより前から始まっている

2021-04-18 01:34 UTC, takesi0627 commented
🗒アニメーション演出ブラッシュアップイシュー立てる

2021-04-18 02:11 UTC, takesi0627 commented
🗒操作できないことを伝えるため半透明のマスクを用意する

2021-04-18 13:59 UTC, takesi0627 commented
ぼかすってこんなに大変なんだ・・・
https://edom18.hateblo.jp/entry/2019/04/03/112154

2021-04-18 14:03 UTC, xiii111 commented
👀 Apex Legends

2021-04-20 15:40 UTC, takesi0627 commented
88be916
マスク追加しました。

https://user-images.githubusercontent.com/17778395/115424858-0b84fd80-a23a-11eb-97d3-2138e6669f22.mov

2021-04-20 15:45 UTC, takesi0627 commented
@xiii111 @takasusuke 
改めてレビューお願いします

2021-04-21 14:50 UTC, takasusuke requested changes
アニメーション見ました。
動きがあって結構お気に入り。

2021-04-21 14:50 UTC, takasusuke commented on Assets/Project/Actors/UIs/GamePlayScene/CountDown.prefab
> +  m_SizeDelta: {x: 835.6959, y: 260.688}
`must` 倍率でお願いします。。。
```suggestion
  m_AnchorMin: {x: 0.15, y: 044}
  m_AnchorMax: {x: 0.58, y: 0.56}
  m_AnchoredPosition: {x: 0, y: 0}
  m_SizeDelta: {x: 0, y: 0}
```

2021-04-21 14:50 UTC, takasusuke commented on Assets/Project/Actors/UIs/GamePlayScene/CountDown.prefab
> +  m_Pivot: {x: 0.5, y: 0.5}
`must` 倍率でお願いします。。。
```suggestion
  m_AnchorMin: {x: 0.15, y: 044}
  m_AnchorMax: {x: 0.58, y: 0.56}
  m_AnchoredPosition: {x: 0, y: 0}
  m_SizeDelta: {x: 0, y: 0}
```

2021-04-21 14:50 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                Instance.IsRetry = from is FailureState;
`must`
アニメーション中にGimmicが開始したり、BottleAttributeが発動してしまっているので、
OpeningStateのOnExit()の中身を全てPlayingStateのOnEnter()に記述お願いします。


また、OpeningStateのコンストラクタの
```
// タイマー設定
_timerText = GameObject.Find(_TIMER_TEXT_NAME).GetComponent<Text>();
_customTimer = caller.gameObject.AddComponent<CustomTimer>();
_customTimer.Initialize(_timerText);
```
の記述もPlayingStateのコンストラクタが適切かと思いますので移動をお願いいたします。

2021-04-21 15:45 UTC, takesi0627 commented on Assets/Project/Actors/UIs/GamePlayScene/CountDown.prefab
> +  m_Pivot: {x: 0.5, y: 0.5}
この変更そのまま使っていい？

2021-04-21 15:46 UTC, takesi0627 commented on Assets/Project/Actors/UIs/GamePlayScene/CountDown.prefab
> +  m_Pivot: {x: 0.5, y: 0.5}
@takasusuke

2021-04-21 15:48 UTC, takasusuke commented on Assets/Project/Actors/UIs/GamePlayScene/CountDown.prefab
> +  m_Pivot: {x: 0.5, y: 0.5}
だいたい元の大きさと同じくらいで設定したつもりです。
使って大丈夫です。

2021-04-21 15:49 UTC, takesi0627 commented on Assets/Project/Actors/UIs/GamePlayScene/CountDown.prefab
> +  m_Pivot: {x: 0.5, y: 0.5}
あざっす

2021-04-21 15:52 UTC, takesi0627 commented on Assets/Project/Actors/UIs/GamePlayScene/CountDown.prefab
> +  m_Pivot: {x: 0.5, y: 0.5}
そのまま使っちゃダメみたいです・・・申し訳ないがコミット戻させていただきます

2021-04-21 15:54 UTC, takasusuke commented on Assets/Project/Actors/UIs/GamePlayScene/CountDown.prefab
> +  m_Pivot: {x: 0.5, y: 0.5}
あれごめん。。。(?)
UIから設定お願いします。。。

2021-04-21 16:07 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                Instance.IsRetry = from is FailureState;
6e29c27
これがないとタイルとボトルが描画されないので、これだけOpeninState.OnExitに残している
```
// ゲーム開始時のイベント
Instance._gameStartSubject.OnNext(Unit.Default);
```

2021-04-21 16:08 UTC, takesi0627 commented
@takasusuke 再レビューお願いします

2021-04-21 16:27 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                Instance.IsRetry = from is FailureState;
あーそうかー。。。
今、ゲーム開始時のイベントのタイミングで
- Bottleの描画
- BottleAttributeの描画
- BottleAttributeの内部時間の計測開始
- BottleAttributeのアニメーション開始
- Tileの描画
を行っている。

CountDownアニメーションのタイミングで
- Bottleの描画
- BottleAttributeの描画
- Tileの描画
を行って、
ゲーム開始時のイベントのタイミングで
- BottleAttributeの内部時間の計測開始
- BottleAttributeのアニメーション開始
を行う必要があるのか。(GohstAttributeを見るとわかる)
もう1個イベントを定義しないといけないと。

2021-04-21 16:28 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                Instance.IsRetry = from is FailureState;
https://user-images.githubusercontent.com/26213141/115588653-ecee3780-a309-11eb-865e-03d857ad8f67.mov

2021-04-21 16:29 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                Instance.IsRetry = from is FailureState;
#868 の修正とも被るから、#868 の修正が終わったらこの問題は引き受けますので、このissueはOKです。

2021-04-21 16:30 UTC, takasusuke approved these changes
https://github.com/LITO-apps/Treevel-client/pull/875#discussion_r617703197
このコメントを読んでくれたらOKです。

2021-04-21 16:34 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                Instance.IsRetry = from is FailureState;
了解です。よろしくお願いします🙇‍♂️

2021-04-21 16:35 UTC, takesi0627 commented
@xiii111 
マージしてもいいですか？

2021-04-21 23:15 UTC, xiii111 approved these changes
良さそうです

2021-04-22 12:02 UTC, merged