StageStatus 取得失敗時に、PlayerPrefs からデータを取る
LITO-apps/Treevel-client pull request #885
Opened 2021-04-19 11:26 UTC by xiii111

### 対象イシュー
Close #873 

### 概要
- `StageStatus` を `PlayFab` から取得することに失敗した場合、`PlayerPrefs` から取得するようにする
- `PlayerPrefs` の保存ロジックを移動した

### 実装対象外
- オフライン状態の時に `PlayerPrefs` から取得する想定だったが、オフラインの場合には既存の多くの部分がエラーハンドリングを記述していないため、まともに確認できる状態ではなかった。なので、オフライン時には `PlayerPrefs` から取得することはできない。オフライン対応についてはアイデアに起票した

### 詳細

#### 現実装になった経緯
- 実装対象外の問題があり、今回の修正コードでは、どのような時にこんなこと起こるの？状態ですが、イメージとしては `GetAllStageStatusListRequest` した際に、何らかの原因で取得に失敗した場合には空のリストが返ってくる、という前提での実装になっています。なので `GetAllStageStatusListRequest` した際に例外が throw される場合の対応は含まれていません。

### 動作確認方法
- セルフレビューに記載

2021-04-19 11:31 UTC, xiii111 commented
@takasusuke @takesi0627 レビューお願いします！

2021-04-19 16:40 UTC, takesi0627 requested changes
動作確認済み

2021-04-19 16:40 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/PlayerPrefsUtility.cs
> +        }
`nits` 気をつければいいですが、 `T` が `Serializable` ではない場合想定外の挙動になると思います。 ドキュメントに書くといいかもしれない

2021-04-19 16:40 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Networks/Requests/UpdateStageStatusRequest.cs
> +        public UpdateStageStatusRequest(string key, StageStatus data)
`nits` コンストラクター消さずに両方用意しておいてもいいと思います

2021-04-20 12:19 UTC, xiii111 commented on Assets/Project/Scripts/Common/Utils/PlayerPrefsUtility.cs
> +        }
c295229 で修正しました。他にもたくさん `try catch` できていないところはあると思いますが、ここに関しては、`try catch` をするようにしました。例外処理は今後まとめてやらないといけない気がします

2021-04-20 12:19 UTC, xiii111 commented on Assets/Project/Scripts/Common/Networks/Requests/UpdateStageStatusRequest.cs
> +        public UpdateStageStatusRequest(string key, StageStatus data)
残しました → 09b9095

2021-04-20 12:19 UTC, xiii111 commented
@takesi0627 再レビューお願いします

2021-04-20 14:05 UTC, takesi0627 approved these changes
修正確認しました。問題なさそうですが、
改めて動作確認したら以下2点不具合がありました。

が、イシューの対象と言っていいが怪しいので、対応しない場合イシューを立てていただけると助かります。

* リセットするとSpring-1が遊べなくなる
* リセット機能は効かない（ステージデータがクリアされない）

![image](https://user-images.githubusercontent.com/17778395/115409066-5f88e580-a22c-11eb-9197-0b7a67302126.png)

2021-04-20 15:29 UTC, xiii111 commented
@takesi0627 #890 #891 を起票しました！

2021-04-20 15:30 UTC, merged