BottleAttributeがGame開始時に描画されるようにする
LITO-apps/Treevel-client pull request #886
Opened 2021-04-19 15:15 UTC by takasusuke

### 対象イシュー
Close #868

### 概要
タイトルまま

### 詳細
特になし

#### 現実装になった経緯
特になし

#### 技術的な内容
特になし

### キャプチャ
変更前 | 変更後
https://user-images.githubusercontent.com/26213141/115260058-5edd4a00-a16d-11eb-9d75-3c50f65d83d8.mov https://user-images.githubusercontent.com/26213141/115259913-42d9a880-a16d-11eb-8c6e-f206b17e36c8.mov

### 動作確認方法

- [ ] Spring-1-1をプレイ(記録画面からステージ選択画面に飛べば選択できる)。BottleAttributeが先に描画されることが起きないことを確認。

### 参考 URL

2021-04-19 15:18 UTC, takasusuke commented
@xiii111 @takesi0627 
どちらかお願いいたします。
いつでも良いです。
20min程度で終わります。

2021-04-20 12:44 UTC, xiii111 reviewed
コメントしました

2021-04-20 12:44 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/BottleAttributeControllerBase.cs
> +        }
### [ask]

`Awake()` ではなく `Initialize()` に置く理由はなんでしたっけ？ `ReverseAttributeController.cs` などでは、もともとは購読処理を `Awake()` でやってるように見えます

2021-04-20 12:44 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/LifeAttributeController.cs
> +                spriteRenderer.enabled = false;
### [ask]

`BottleAttributeControllerBase` の購読処理により一度 `enabled = true` になる気がしますが、あってますか？なのであれば、`BottleAttributeControllerBase` の購読処理は各 `BottleAttribute` に任せた方が良いと思いました（`BottleAttribute` によって、`enabled = true` にする場合としない場合があるのだから）

2021-04-20 12:44 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/LifeAttributeController.cs
> +                spriteRenderer.enabled = false;
`else 節` で `Initialize()` を読んでいるから、こちらでは `enabled = true` にはならないのかな？であれば、デフォルト値は `enabled = false` なのだから、この記述はいらないと思いました

2021-04-21 14:12 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/LifeAttributeController.cs
> +                spriteRenderer.enabled = false;
確かに。この記述はいらない。

2021-04-21 14:12 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/BottleAttributeControllerBase.cs
> +        }
768f92b
引数を受け取って購読処理を`Initialize()`で行うのに合わせて全部購読処理は`Initialize()`に書いたけど、
やっぱりできるものは`Awake()`に書きました。

2021-04-21 14:13 UTC, takasusuke commented
@xiii111 
再ヨロです

2021-04-21 16:13 UTC, takesi0627 commented
コメントするのは遅くて申し訳ないですが、 @xiii111 に任せます

2021-04-21 16:33 UTC, takasusuke commented
#834 のカウントダウンの実装がmergeされたら、そのdevelopをmergeして、
BottleAttributeの描画タイミング(カウントダウンの前)と
BottleAttributeのアニメーション開始・内部時間計測開始タイミング(カウントダウンの直後)を分ける修正を行います。
なので、一旦draftにします。

2021-04-21 23:15 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/BottleAttributeControllerBase.cs
> +        }
それが良い気がします！

2021-04-21 23:21 UTC, xiii111 approved these changes
LifeAttribute が共通処理で書けないということで、子クラスに処理を移動したんですね！良いと思います！

2021-04-21 23:22 UTC, xiii111 commented
@takasusuke 

> BottleAttributeの描画タイミング(カウントダウンの前)と
BottleAttributeのアニメーション開始・内部時間計測開始タイミング(カウントダウンの直後)を分ける修正を行います。

こちらの修正が入ったら、メンションください

2021-04-21 23:23 UTC, xiii111 requested changes
↑ の件を見落としていたので、一回マージできないように塞いでおきます

2021-04-24 07:40 UTC, takasusuke commented
アニメーションをゲーム開始時まで待つことでだいぶそれっぽくなってきました。
https://user-images.githubusercontent.com/26213141/115951374-6610a900-a51b-11eb-8012-a649690ead7f.mov

動作確認
Spring_1_1をプレイ
- [ ] オープニング開始時にBottleAttributeが描画されている（アニメーションは無し）
- [ ] ゲーム開始時にアニメーションが再生
- [ ] ゲーム終了時にアニメーションが停止
- [ ] 失敗後のリトライ時、オープニング無しの時もアニメーションが再生

2021-04-24 07:40 UTC, takasusuke commented
@xiii111 
ヨロです。

2021-04-24 07:41 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> -            _animator.SetBool(_ANIMATOR_IS_DARK, !_isSuccess);
bottle.EnterTileが最初に呼ばれるので、ここの初期状態の登録は不要でした。

2021-04-24 09:50 UTC, takasusuke commented
34f2cc1
後で修正しようとして適当なコメントのcommit残ってる。。。

2021-04-26 12:56 UTC, xiii111 reviewed
いくつか質問をしました

2021-04-26 12:56 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                Instance._openingAnimationStartSubject.OnNext(Unit.Default);
### ask

`CountDownState.OnEnter` に書かないのは何故でしたっけ？

2021-04-26 12:56 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> +                animator.enabled = false;
### ask

初期値を `false` にしておけば、ここで書く必要はないですか？（以下同様）

2021-04-26 12:56 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> +            GamePlayDirector.Instance.GameEnd.Subscribe(_ => animator.enabled = false).AddTo(this);
### ask

`compositeDisposableOnGameEnd` を含めないのは何故ですか？（以下 `this` だけのところは同様）

2021-04-26 12:56 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> -            animator.SetBool(_ANIMATOR_IS_DARK, !_isSuccess);
### ask

この条件消しちゃって大丈夫ですか？（もともと成功状態の時も Dark が作動してしまいませんか？）

2021-04-26 12:56 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/SelfishAttributeController.cs
>                  _bottleAnimator.SetFloat(_ANIMATOR_PARAM_FLOAT_SPEED, 0f);
### ask

この処理だけ取り残されているのは何故ですか？

2021-04-26 12:57 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> -            animator.SetBool(_ANIMATOR_IS_DARK, !_isSuccess);
https://github.com/LITO-apps/Treevel-client/pull/886#discussion_r619605568 で解決

2021-04-26 17:19 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/SelfishAttributeController.cs
>                  _bottleAnimator.SetFloat(_ANIMATOR_PARAM_FLOAT_SPEED, 0f);
`_bottleAnimator`は
関数`Initialize(ynamicBottleController bottleController)`から取得する
`_bottleAnimator = bottleController.GetComponent<Animator>();`だからです。

2021-04-26 17:45 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> +            GamePlayDirector.Instance.GameEnd.Subscribe(_ => animator.enabled = false).AddTo(this);
`GameObjectControllerBase.cs`で
```
GamePlayDirector.Instance.GameEnd.Subscribe(_ => compositeDisposableOnGameEnd.Dispose()).AddTo(this);
```
しているので、
処理順次第では`DarkAttributeController.cs`とかのGameEndの購読処理が実行されずに購読解除される恐れがあると思うからです。
(実際にどういう順序で実行されるのかは知らない)

2021-04-26 18:02 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> +                animator.enabled = false;
fe927a7

2021-04-27 11:17 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> +            GamePlayDirector.Instance.GameEnd.Subscribe(_ => animator.enabled = false).AddTo(this);
それであれば、 `GameEnd` のタイミングで `compositeDisposableOnGameEnd.Dispose()` を呼ぶのではなく、リトライなどによりオブジェクトを掃除するタイミング（`GamePlayDirector.CleanObject()`）でイベントを流して、そのタイミングで `Dispose()` をした方が良いと思います。

> 処理順次第ではDarkAttributeController.csとかのGameEndの購読処理が実行されずに購読解除される恐れがあると思うからです。

という問題意識はわかりますが、それを理由に `Dispose()` をしなければ、大量にリトライした際にメモリリークします

2021-04-27 11:21 UTC, xiii111 commented
@takasusuke 返答しました。以下二点だけ議論が残っています
- https://github.com/LITO-apps/Treevel-client/pull/886#discussion_r621106763
- https://github.com/LITO-apps/Treevel-client/pull/886#discussion_r621111261

2021-04-27 11:31 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> +            GamePlayDirector.Instance.GameEnd.Subscribe(_ => animator.enabled = false).AddTo(this);
Game終了時に後ろのBottleをフリックできなくするために
`compositeDisposableOnGameEnd`が有効に働いています

2021-04-27 11:34 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> +            GamePlayDirector.Instance.GameEnd.Subscribe(_ => animator.enabled = false).AddTo(this);
では以下のようなところを含め、多くのところでは無駄に `compositeDisposableOnGameEnd` をつけてしまっている、という現状でしょうか？

https://github.com/LITO-apps/Treevel-client/blob/bc0517d3daeefb7a31bd0c6a6f9d8db29f292dd4/Assets/Project/Scripts/Modules/GamePlayScene/Tile/GoalTileController.cs#L39-L43

2021-04-27 11:38 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> +            GamePlayDirector.Instance.GameEnd.Subscribe(_ => animator.enabled = false).AddTo(this);
おっしゃる通り、大量にリトライしたとき問題はそもそも`CleanObject()`がリトライで呼ばれるので起きないです。
CleanObjectせずに使い回すならそのタイミングで購読解除するのが適切かと思います。

基本的に、GameStartなどおそらくオブジェクトが生成されてから１回しか呼ばれないであろうeventは無駄ですね。
Game終了時に、勝手にOnGameStart呼んだときに変な挙動が起きないようになっている、、、くらい。

2021-04-27 11:41 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> +            GamePlayDirector.Instance.GameEnd.Subscribe(_ => animator.enabled = false).AddTo(this);
`compositeDisposableOnGameEnd`を作成したときに、どのような条件の時に`AddTo()`に付与するのかわかりにくくなるので、`OnGameEnd`以外は基本的につけるようになりました。
(つけてすぎてて無駄ではあるけど安全ではあるから)

2021-04-27 11:43 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> +            GamePlayDirector.Instance.GameEnd.Subscribe(_ => animator.enabled = false).AddTo(this);
と、色々あるのでこのissueでここら辺の修正はしたくないです。

2021-04-27 11:47 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> +            GamePlayDirector.Instance.GameEnd.Subscribe(_ => animator.enabled = false).AddTo(this);
状況把握しました。`compositeDisposableOnGameEnd を必要な箇所のみに適用する` というような issue を作成して、ここでの対応はやめましょう

2021-04-27 11:48 UTC, xiii111 approved these changes
以下二点治れば、マージしてOKです
- [ ] https://github.com/LITO-apps/Treevel-client/pull/886#discussion_r621106763
- [ ] https://github.com/LITO-apps/Treevel-client/pull/886#discussion_r621131031

2021-04-27 11:51 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                Instance._openingAnimationStartSubject.OnNext(Unit.Default);
これ移動させたらダメなやつだった

2021-04-27 11:55 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                Instance._openingAnimationStartSubject.OnNext(Unit.Default);
通常
Opening → Countdown → Playing
リトライ時
Opening → Playing
なので、Countdownに書くとBottleとか描画されない。

このイベント、オープニング開始というより、
ゲームの準備完了を知らせるイベント(CreateStageAsync()の後に呼ばれる)なので
`createdStage`とかにリネームしてここに置いときます。

2021-04-27 11:58 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                Instance._openingAnimationStartSubject.OnNext(Unit.Default);
`preparedStage` or `hasPreparedStage` とかどうですか？

2021-04-27 12:00 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                Instance._openingAnimationStartSubject.OnNext(Unit.Default);
`hasPreparedStage`いただき

2021-04-27 12:03 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                Instance._openingAnimationStartSubject.OnNext(Unit.Default);
`has` を使うと、持っているか？という Boolean だと勘違いされそうだから `have` の方が良いかも

2021-04-27 12:03 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                Instance._openingAnimationStartSubject.OnNext(Unit.Default);
それか、`stagePrepared` とかも良いかも

2021-04-27 12:09 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                Instance._openingAnimationStartSubject.OnNext(Unit.Default);
Opening stateとCountdown stateは
Preparing stateとOpening state説は結構ある

`stagePrepared`で。

2021-04-27 12:10 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                Instance._openingAnimationStartSubject.OnNext(Unit.Default);
> Opening stateとCountdown stateは
Preparing stateとOpening state説は結構ある

わかる

2021-04-28 22:16 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DarkAttributeController.cs
> +            GamePlayDirector.Instance.GameEnd.Subscribe(_ => animator.enabled = false).AddTo(this);
#903 を作成しました

2021-04-28 22:32 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                Instance._openingAnimationStartSubject.OnNext(Unit.Default);
794d1e4 ~ f5a7117

2021-04-28 22:33 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +            public OpeningState(GamePlayDirector caller)
`State`は`Opening`にリネームしたけど、
OpeningAnimationとしてはCountdown的な実装なので、アニメーション名はリネームしてない。

諸説ある。

2021-04-28 22:34 UTC, takasusuke commented
@xiii111 @takesi0627 
https://github.com/LITO-apps/Treevel-client/pull/886#discussion_r622610660
ここのリネームは納得？

2021-04-29 04:05 UTC, xiii111 commented
@takasusuke よい。こちらからは以上です

2021-05-01 14:49 UTC, merged