`RecordData` を整理する
LITO-apps/Treevel-client pull request #892
Opened 2021-04-22 14:00 UTC by xiii111

### 対象イシュー
Close #880

### 概要
- `RecordData` を `UserRecord` にリネーム
- `StageStatus` も `StageRecord` にリネーム
- `failureReasonCount` を `StageRecord` に移動する

### 詳細

#### 現実装になった経緯
- クラス内の辞書型を `Serializable` にするのは、外部ライブラリを使わないと困難だったので、クラスとして定義した
- 記録画面は初回リリースに入るかわからないので、簡易的に実装した

### 動作確認方法
- [ ] ステージを失敗した際に、PlayFab に失敗情報が保存されていること
- [ ] ステージの失敗が、記録画面に反映されていること

### 備考
- データ構造が変わっているので、既存の PlayFab データ、PlayerPrefs データは破棄した方が確認で詰まらないと思います

2021-04-22 14:17 UTC, xiii111 reviewed
📝

2021-04-22 14:17 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/StageRecord.cs
> +        }
この関数からフィールドを返すことで、FailureReasonType への追従を忘れないようにする

2021-04-22 14:17 UTC, xiii111 commented on Assets/Project/Scripts/Modules/MenuSelectScene/Record/GeneralRecordDirector.cs
> +                .ToDictionary(type => type, type => stageRecordArray.Sum(record => record.failureReasonNum.Get(type)));
Dictionary を一切使わなくても良いが、一からロジックを書き直すコストが高かったので、既存の引数になっていた表現に変換する処理だけを書いて済ませた

2021-04-22 14:17 UTC, xiii111 commented
@takasusuke @takesi0627 レビューお願いします！

2021-04-23 16:41 UTC, takesi0627 requested changes
動作確認OK。
一点だけ修正お願いします

2021-04-23 16:41 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/StageRecord.cs
> +        }
`comment`
いつの間にか 8.0 の機能が使えるようになったのか

2021-04-23 16:41 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/StageSelectScene/StageController.cs
> +        private StageRecord stageRecord;
`must`
```suggestion
        private StageRecord _stageRecord;
```

2021-04-24 03:19 UTC, xiii111 commented on Assets/Project/Scripts/Common/Entities/StageRecord.cs
> +        }
ねー。試しに使ってみた

2021-04-24 03:23 UTC, xiii111 commented on Assets/Project/Scripts/Modules/StageSelectScene/StageController.cs
> +        private StageRecord stageRecord;
直しました！
- c86c77f

2021-04-24 03:23 UTC, xiii111 commented
@takesi0627 再レビューお願いします！

2021-04-24 03:29 UTC, takesi0627 approved these changes

2021-04-24 03:48 UTC, xiii111 commented
@takesi0627 thanks

2021-04-24 03:48 UTC, merged