バナー広告実装
LITO-apps/Treevel-client pull request #923
Opened 2021-05-11 17:09 UTC by takesi0627

### 対象イシュー
Close #840 

### 概要
バナー広告を実装

### 詳細

#### 現実装になった経緯

f68cc27 : [公式スタートガイド](https://developers.google.com/admob/unity/quick-start?hl=ja)に従ってSDKをインポートする
c66246a : [Resolverあたりの変更](https://developers.google.com/admob/unity/quick-start?hl=ja#include_the_mobile_ads_sdk)
6ff848e : 広告表示処理を共通化するために、`AdvertiseService.cs` を作成
5405afa : バナー広告を一時停止画面とステージ選択画面に実装
56ddb47 : app id 漏洩防止のため `GoogleMobileAds/Resources/` を ignore

#### 技術的な内容

* サイズの指定について
  [広告サイズのカスタマイズセクション](https://developers.google.com/admob/unity/banner?hl=ja#optional_custom_ad_sizes)でサイズをカスタマイズする方法を紹介しているものの、エディター上では `GoogleMobileAds/Playform/Unity/BannerClient.cs` で定義されている幾つかのサイズをしか表示できないので、`AdvertiseService.cs` ではそのための分岐を記述しています。
  ![image](https://user-images.githubusercontent.com/17778395/117855110-1ffe6800-b2c5-11eb-802f-22f72e3eebb5.png)
※実際にイシューとして上げられています（https://github.com/googleads/googleads-mobile-unity/issues/1503）

* StartUpSceneについて
スタートアップシーンでバナーを実装する予定でしたが、広告のビューのキャナバスの `Sort Order` がデフォルト値 0 でいじれないので、表示されないため断念しました。

*  `GoogleMobileAds`のパスはPlayFabと同じ理由（設定ファイルの生成に使うパスが書き込まれている）で `ThirdParties` 以下に置けないです。

### AppID と広告ユニットID
広告を表示するのに `App ID` と `広告ユニット` の二つのIDが必要になります

* App ID はこちらから確認できます
![image](https://user-images.githubusercontent.com/17778395/118001217-7a5cfe80-b381-11eb-91d2-e113db0bfb0e.png)

* 広告ユニットIDはこちらから確認できます
![image](https://user-images.githubusercontent.com/17778395/118000807-19352b00-b381-11eb-8873-45bd86692dfe.png)

詳しくはこちらの[導入動画](https://www.youtube.com/watch?v=68EzJiw2Kqk)を見ていただくとよりわかると思います

### キャプチャ

| ステージ選択画面 |  一時停止画面 |
|-----------------|--------------|
| ![image](https://user-images.githubusercontent.com/17778395/117853792-c6e20480-b2c3-11eb-91ca-a47e5eb0696d.png)|![image](https://user-images.githubusercontent.com/17778395/117853844-d6f9e400-b2c3-11eb-8b86-619b79245d1f.png)|

### 動作確認方法
1.  Slackで共有したアイパスで [AdMob](https://apps.admob.com/v2/home)にログインします。
2. [App id](https://developers.google.com/admob/unity/quick-start?hl=ja#set_your_admob_app_id)の設定を行います
3. 動作確認
    - [x] ステージ選択画面で広告が表示されることを確認します 
    - [x] 一時停止画面で広告が表示されることを確認します

### 参考 URL

2021-05-12 13:34 UTC, takasusuke requested changes
> StartUpSceneについて
スタートアップシーンでバナーを実装する予定でしたが、広告のビューのキャナバスの Sort Order がデフォルト値 0 でいじれないので、表示されないため断念しました。

なるほど。
StartupSceneのCanvasのsortOderを0
MenuSelect/FooterのCanvasのsortOrderを-100
MenuSelect/SettingsのCanvasのsortOrderを-200
MenuSelect/RecordのCanvasのsortOrderを-200
とかに設定してStartupSceneに広告を表示しても構いません（なくても良いけど）


- `must`:広告を出すと
```
```
というwarningが出る件について。
https://groups.google.com/g/google-admob-ads-sdk/c/0MBTZjD7fN4?pli=1 を参考に
`BannerClient.cs`の
```
buttonBehaviour = new ButtonBehaviour();
```
を
```
var ob = new GameObject();
ob.AddComponent<ButtonBehaviour>();
buttonBehaviour = ob.GetComponent<ButtonBehaviour>();
```
に書き換えると良いらしい。

- `must?`
広告を、SafeAreaPanelをアタッチしたCanvas上に配置してもらって良い？
(特に一時停止画面にある上の広告はSimulatorだと見えなくなる)
面倒だったら別issueで大丈夫。

2021-05-12 13:34 UTC, takasusuke commented on Assets/Project/Scripts/Common/Utils/Constants.cs
> +            public const string BANNER_UNIT_ID_STAGE_SELECT = "ca-app-pub-3388557544498929/3390697828";
`ask`
ごめん、ここの文字列がどこから生まれたのかちょっとわからなかった。。。

2021-05-12 15:26 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/Constants.cs
> +            public const string BANNER_UNIT_ID_STAGE_SELECT = "ca-app-pub-3388557544498929/3390697828";
AppIDと広告ユニットIDについて概要に追加しました。確認していただけばと思います

2021-05-12 15:37 UTC, takesi0627 commented
> > StartUpSceneについて
> > スタートアップシーンでバナーを実装する予定でしたが、広告のビューのキャナバスの Sort Order がデフォルト値 0 でいじれないので、表示されないため断念しました。
> 
> なるほど。
> StartupSceneのCanvasのsortOderを0
> MenuSelect/FooterのCanvasのsortOrderを-100
> MenuSelect/SettingsのCanvasのsortOrderを-200
> MenuSelect/RecordのCanvasのsortOrderを-200
> とかに設定してStartupSceneに広告を表示しても構いません（なくても良いけど）

元々表示する意思がそんなにないじゃなかったっけ？
もしかしたらエディタ上だけsortOrderがそうなってるかもしれないから（広告が一番上に出さないと意味ないし、そんなクソ仕様グーグルが考えるわけがないという思い）
ゆくゆく実機で検証してみてから考えます。
あんまりそれのために今の実装を変えたくない。

> * `must`:広告を出すと
> 
> ```
> You are trying to create a MonoBehaviour using the 'new' keyword.  This is not allowed.  MonoBehaviours can only be added using AddComponent(). Alternatively, your script can inherit from ScriptableObject or no base class at all
> UnityEngine.MonoBehaviour:.ctor ()
> ```
> 
> というwarningが出る件について。
> https://groups.google.com/g/google-admob-ads-sdk/c/0MBTZjD7fN4?pli=1 を参考に
> `BannerClient.cs`の
> 
> ```
> buttonBehaviour = new ButtonBehaviour();
> ```
> 
> を
> 
> ```
> var ob = new GameObject();
> ob.AddComponent<ButtonBehaviour>();
> buttonBehaviour = ob.GetComponent<ButtonBehaviour>();
> ```
> 
> に書き換えると良いらしい。


あんまりライブラリに手入れたくなかったがこれに関してはやらんとあかんね。


> * `must?`
>   広告を、SafeAreaPanelをアタッチしたCanvas上に配置してもらって良い？
>   (特に一時停止画面にある上の広告はSimulatorだと見えなくなる)
>   面倒だったら別issueで大丈夫。

広告のインスタンス生成はライブラリ内で行なっているので配置するキャンバスは指定できません。
でも出す位置は細かく設定できるはずなのでちょっとやってみる。

2021-05-12 15:51 UTC, takasusuke commented
> StartUpSceneについて
スタートアップシーンでバナーを実装する予定でしたが、広告のビューのキャナバスの Sort Order がデフォルト値 0 でいじれないので、表示されないため断念しました。
別にStartupSceneに広告を載せるために今、色々変えなくても大丈夫です。
sortOrderを調整すれば表示できるよ、というお話でした。
ちなみに、`Sort Order がデフォルト値 0 でいじれない`はどのように再現するのでしょうか。。。？
スクリプトから値を書き換えできない、ということ？

2021-05-12 16:01 UTC, takesi0627 commented
> > StartUpSceneについて
> > スタートアップシーンでバナーを実装する予定でしたが、広告のビューのキャナバスの Sort Order がデフォルト値 0 でいじれないので、表示されないため断念しました。
> 
> StartupSceneに広告を載せるために今、色々変えなくても大丈夫です。
> sortOrderを調整すれば表示できるよ、というお話でした。
> ちなみに、`Sort Order がデフォルト値 0 でいじれない`はどのように再現するのでしょうか。。。？
> スクリプトから値を書き換えできない、ということ？

IBannerClient はsort order を変更するための関数を公開していないので、いじれない。
プレハブの値を変えればそれでエディタ上では表示されるかもしれないが、実機ではそのプレハブを使用されていないので意味ない。
ちなみに実機の動作は多分Plugins/iOS下にあるものに依存しています。

2021-05-12 16:50 UTC, takesi0627 commented
fd2f088
セーフエリアを考慮した実装にしました。下に出す場合も考慮した方が良いんですかね？
ついでにスマートバナーよりアダプティブバナーの方が良さそうなので変えました。
https://developers.google.com/admob/unity/banner/adaptive?hl=ja

2021-05-13 11:18 UTC, xiii111 commented
📝 動作確認が完了したら approve する

2021-05-13 11:55 UTC, takasusuke approved these changes
approve

2021-05-13 11:56 UTC, xiii111 approved these changes
動作確認終わりました

2021-05-13 11:57 UTC, merged