木をデータ化し、木の解放周りの実装を変更する
LITO-apps/Treevel-client pull request #926
Opened 2021-05-15 13:37 UTC by takesi0627

### 対象イシュー
Close #909 

### 概要
タイトル通り

### 詳細

#### 現実装になった経緯

#### 技術的な内容
* #798 の変更と似たように、本来全ての道、木のステートを保存する代わりに、演出を見たことのある道、木のみ保存するようにしました。（`LevelSelectDirector.releasedAnimationPlayedRoads`, `LevelSelectDirector.releasedAnimationPlayedTrees`参照）

### キャプチャ
https://user-images.githubusercontent.com/17778395/118362765-e2068a00-b5cb-11eb-8902-946657fac338.mov

### 動作確認方法
- [ ] 木の解放演出が今まで通りであることを確認。
- [ ] 木の解放条件が正常に反映されていることを確認。

### 参考 URL

2021-05-15 13:38 UTC, takesi0627 commented
@LITO-apps/engineer 
お待たせしました。レビューよろしくお願いします
ちょっと複雑なので理解するのに時間かかるかもしれません（一応わかりやすいように書いたつもりですが・・）

2021-05-15 13:49 UTC, takesi0627 commented on Assets/AddressableAssetsData/AddressableAssetSettings.asset
> +  m_ContiguousBundles: 1
ここら辺はUnity　Updateの差分かと思われる

2021-05-15 13:49 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs
> +        public override void UpdateState()
1. 解放条件がない -> ClearHandlerから取得した状態を反映
2. 解放条件がある かつ 解放条件未達成 -> そのまま状態反映(ロック状態)
3. 解放条件がある かつ まだ演出見たことがない -> ロック状態を反映し、RoadControllerからの解放を待つ
4. 解放条件がある かつ 演出見たことがある -> ClearHandlerから取得した状態を反映

2021-05-15 13:49 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/StartUpScene/StartUpDirector.cs
> +            await GameDataManager.InitializeAsync();
`LevelSelectScene`の木の更新で木のデータが必要なので、`MenuSelectScene`を読み込む前に先に`GameDataManager`を初期化する必要がある

2021-05-16 15:31 UTC, takasusuke requested changes

2021-05-16 15:31 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs
> +            });
でも、`NumClearTreeHandler.cs`でインスタンスを作成したときの`_stageRecords`のまま更新されていないので解放されません。
https://github.com/LITO-apps/Treevel-client/issues/899
で`StageRecord`がstructになったので、developをmergeしつつ、
`_stageRecords`を更新するようにしていただけないでしょうか。

`IClearTreeHandler`を`ClearTreeHandlerBase`とかにして、そっちで更新した方が良いかも

2021-05-16 15:37 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs
> -            PlayerPrefs.SetInt(Constants.PlayerPrefsKeys.TREE + treeId, Convert.ToInt32(state));
### must

これが無くなったので、
`StageTreeController.cs`の`UpdateState()`の
```
 // 現在状態をPlayerPrefsから得る
            state = (ETreeState)Enum.ToObject(typeof(ETreeState),
                                              PlayerPrefs.GetInt(Constants.PlayerPrefsKeys.TREE + treeId,
                                                                 Default.TREE_STATE));
```
が更新されなくなり、`StageTree`が解放されなくなったので、修正を何卒お願いいたします。。。。。

2021-05-17 11:45 UTC, xiii111 commented
@takasusuke 頼む🙏

2021-05-17 14:04 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/GameDataManager.cs
> +            var treeDataList =
ちょっとstageDatasが英語的にどうかと思い始めたからstageDatasの方を直したいと思います

2021-05-17 14:14 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/GameDatas/TreeData.cs
> +        public List<TreeConstraint> constraintTree;
36f330c

2021-05-17 14:20 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/StageRecordService.cs
> +        public StageRecord Get(string stageId)
112e97f
使えるところを置き換えました

2021-05-17 14:37 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs
> -            PlayerPrefs.SetInt(Constants.PlayerPrefsKeys.TREE + treeId, Convert.ToInt32(state));
83f76e8
完全に見逃しておった

2021-05-17 15:49 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Managers/GameDataManager.cs
> +            var treeDataList =
df7c26c

2021-05-17 15:51 UTC, takesi0627 commented
@takasusuke 
`ClearTreeHandler` 周りも `TreeData` から設定するようにしました。
その他レビュー対応もしましたので合わせてご確認いただければと思います。よろしくお願いします

2021-05-18 11:49 UTC, takasusuke commented on Assets/Project/Scripts/Common/Utils/StageRecordService.cs
> +        public StageRecord Get(string stageId)
わがままを言うと
```
public StageRecord Get(ETreeId treeId, int stageNumber)
        {
            return _cachedStageRecordDic[StageData.EncodeStageIdKey(treeId, stageNumber)];
        }
```
と
```
public StageRecord Get(string stageId)
        {
            var (treeId, stageNumber) = StageData.DecodeStageIdKey(stageId);
            return Get(treeId, stageNumber);
        }
```
ではなく、
```
public StageRecord Get(ETreeId treeId, int stageNumber)
        {
            return Get(StageData.EncodeStageIdKey(treeId, stageNumber));
        }
```
と
```
public StageRecord Get(string stageId)
        {
            return _cachedStageRecordDic[stageId];
        }
```
にしていただけないでしょうか。

2021-05-18 11:50 UTC, takasusuke commented on Assets/Project/Scripts/Common/Utils/StageRecordService.cs
> +        public StageRecord Get(string stageId)
stageId → (treeId, stageNumber) → stageId
と変換しているのを直したい

2021-05-18 12:12 UTC, takasusuke commented
### ask
0785fa8 って、 36f330c の更新のためのスクリプトってことで良いよね？？

2021-05-18 12:22 UTC, takasusuke commented on Assets/Project/Scripts/Common/Entities/GameDatas/TreeData.cs
> +        public IClearTreeHandler GetClearTreeHandler()
うーん。。。
毎回、アクセスするときにその時最新のStageのクリア状況でインスタンスを作るのがなあ。。。
できれば以前と同様に、１つの木に対して１つのclearHandlerのインスタンスにして、
適切なタイミングで`_stageRecords`だけ更新したい。。。

ここまで書いて思ったけど、
`StageTree( & _stageRecords)`が更新されないのって、このissueで起きた不具合じゃなくて結構前からあったのか。
ならリファクタリングissueだけあればここは一旦このままでも良い。

2021-05-18 14:25 UTC, takesi0627 commented
> ### ask
> [0785fa8](https://github.com/LITO-apps/Treevel-client/commit/0785fa88414a3608860d62be4de07de40538d5a1) って、 [36f330c](https://github.com/LITO-apps/Treevel-client/commit/36f330c2a5162bb870cbc3c6e44d6e2d8419a4e0) とか [8758bcb](https://github.com/LITO-apps/Treevel-client/commit/8758bcbf4ae3cd16b9bb00d2b7955230bc67b3cf) の更新のためのスクリプトってことで良いよね？？

そうとも言えますが、あった方が良いと思うので、更新がなくも `TreeData` が実装された時点でも実装すべきだとふと思いましたのでやっときました

2021-05-18 15:00 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Utils/StageRecordService.cs
> +        public StageRecord Get(string stageId)
47fc5b7

2021-05-18 15:01 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/GameDatas/TreeData.cs
> +        public IClearTreeHandler GetClearTreeHandler()
2ca7776

ClearTreeHandler をキャッシュするようにした。
そのため `GetTreeState` で最新のステージ記録を取得しないといけないので、メンバーから消して毎回 `StageRecordService`　から取るようにした

2021-05-18 15:02 UTC, takesi0627 commented
@takasusuke 
対応しました。ご確認よろしくお願いします

2021-05-18 16:17 UTC, takasusuke approved these changes
お疲れ様です。
色々修正ありがと！！

2021-05-18 16:18 UTC, merged