テストを増やす
LITO-apps/Treevel-client pull request #946
Opened 2021-05-29 15:19 UTC by takesi0627

### 対象イシュー
なし

### 概要

### 詳細
テストを適切に増やす。

### 参考 URL
https://www.youtube.com/watch?v=z9SIWlGXkAw
この動画を参考にテストを書いてる

2021-06-12 16:40 UTC, takesi0627 commented
シェルからコンテンツをビルドする
https://forum.unity.com/threads/build-for-content-update-using-command-line.775334/

自前のホストでアクションを実行する
https://framesynthesis.jp/tech/github/actions-unity/

2021-07-23 15:53 UTC, takesi0627 commented
コミットがカオスしすぎるので `rebase` してやり直す

2021-08-20 15:25 UTC, takesi0627 commented on Assets/Project/Scripts/Common/Entities/GameDatas/StageSummaryGenerator.cs
> +#endif
`StageSummaryGenerator.cs`が`Editor`に置くとどのAssemblyにも所属していないので`Treevel.PlayTest`からアクセスすることができないので、`StageData`と同じ層に移動しました。
それに伴って、`UnityEditor`関連のコードはこのようにマクロで括る必要になる。

2021-08-20 15:25 UTC, takesi0627 commented on Assets/Tests/PlayModeTest/StageDataTest.cs
> +            }
各テストが実行される前に `SetUp` が呼ばれるので、複数回読み込み処理行わないようにしている。

`OneTimeSetUp`みたいな通しで一回しか呼ばれない初期化関数もありますが、あいにく非同期処理書けないのでAASの読み込みは書けない。

2021-08-20 15:27 UTC, takesi0627 commented
@xiii111 @takasusuke 
レビューよろしくお願いします。
急がないので時間あればで大丈夫です。

2021-08-21 03:06 UTC, xiii111 requested changes
テスト拡充ありがとうございます！素晴らしいと思います！
いくつかコメントしました

### ask
> Assert.That ~ Is.XXX の方が読みやすいと思ったので今後もこのスタイルで書いていきたいと思います（書く機会があれば）

`.That()` の具体的にどういうところが読みやすいと思いましたか？（認識の確認です、外部リンクはそんな念入りには読めてないです）

`.That()` の方が新しい API で、将来的に先にサポートが終了するのは `.AreEqual()` のようですね。あとは、`.AreEqual()` に比べて、実際値と期待値の順番が統一されるのも良いところだとは思います。一方で、`Assert.That(5, Is.EqualTo(5));`、`Assert.That(5, Is.Positive);` のように `.That()` でなんでも出来てしまって、`.That()` という関数を見ても何をしているのか概要すら伝わらず、引数を確認する必要があるというデメリットもあると思います。

2021-08-21 03:06 UTC, xiii111 commented on Assets/Tests/PlayModeTest/StageDataTest.cs
> +    public void ValidateLifeSettings()
### imo

`[Test]` がつくテスト関数の命名規則はどういうポリシーにしていますか？`Test` がついているものとついていないものがあったり、何をしているかの粒度がまばらな気がします。単体テストのネーミングについては、調べると死ぬほど出てくると思うので、`Treevel` プロジェクトにおける大体の命名規則を定めてしまった方が今後書きやすい気がします。`[作業単位_テスト条件_想定行動]` などなど

2021-08-24 09:54 UTC, xiii111 commented
@takasusuke 余裕があったら眺めるだけでも価値あり、かもです！

2021-08-24 12:59 UTC, takasusuke commented on Assets/Tests/PlayModeTest/StageDataTest.cs
> +                        Assert.That(tornadoData.randomRow.Sum(), Is.Not.Zero, $"[{stageData.StageId}]: random row not valid");
この関数に[0,0,0,0]みたいな配列が入るので多分エラー出る。
厳密にいうと、randomDIrectionがToLeft, ToRightしか絶対出ないような値になっているなら、
randomRowしか使われないから、randomColumnは[0,0,0,0]でも良いはず。
だとしても、randomColumnに[1,1,1,1]とか入れておいた方が何かあっても安全ではある。
なので、良いテスト。

https://github.com/LITO-apps/Treevel-client/blob/79b6cf5007cad6301221afd2369022291bbb92df/Assets/Project/Scripts/Common/Utils/GimmickLibrary.cs#L26

2021-08-24 13:12 UTC, takasusuke commented on Assets/Tests/PlayModeTest/StageDataTest.cs
> +                        Assert.That(tornadoData.randomRow.Sum(), Is.Not.Zero, $"[{stageData.StageId}]: random row not valid");
1関数に6個のAssertがあるけど、6個の関数にすることもできる。
1関数1個のAssertなら命名は楽そう。
テストの区切り方について、ご意見・ご知見あれば教えてください。

2021-08-28 04:16 UTC, xiii111 commented on Assets/Tests/PlayModeTest/StageDataTest.cs
> +                        Assert.That(tornadoData.randomRow.Sum(), Is.Not.Zero, $"[{stageData.StageId}]: random row not valid");
3回読み直したけど、なるほど。
ランダムが選ばれているのなら、少なくとも一つの方向は0より大きい値が入っているべきってことね。ちょっとわかりづらいから、具体的なコメントつけておいてほしい

2021-08-28 04:18 UTC, xiii111 commented on Assets/Tests/PlayModeTest/StageDataTest.cs
> +    public void ValidateLifeSettings()
ok

2021-08-28 04:25 UTC, xiii111 commented on Assets/Tests/PlayModeTest/StageDataTest.cs
> +                        Assert.That(tornadoData.randomRow.Sum(), Is.Not.Zero, $"[{stageData.StageId}]: random row not valid");
> テストの区切り方について、ご意見・ご知見あれば教えてください。

基本的には一つの動作を保証するテストが1関数になっているのが良いと思います。そのテストをする際に、さまざまな角度から検証する時は、1関数内でAssertが複数になっていても良いと思います

例えば、`func calc(int a, int b, CalcType type)` という関数があって、`type` には足し算と引き算と掛け算と割り算を与えられるとします（関数分けろよ、というのはその通りだけど、今回説明しやすいように）
このテストをするときには基本的には、`type` ごとにテスト関数は分けるべきです。期待されている動作が違うので。一方で足し算や掛け算のテストをする際には、色々なインプットが考えられると思います 。これらのインプット群は一つの関数内で複数のAssertで表現されて良いと思います

今回で言うと、少なくともランダムの挙動を保証するテストと、ランダム以外の挙動を保証するテストは分かれている方が良いけど、今回コメントしてくれている3行は別関数に分かれる必要はないかなと考えています

2021-08-28 04:27 UTC, xiii111 commented
@takesi0627 

> これに関しては AreEqualsも引数確認するまでテストの内容分からないので特にデメリットとは思えないんですが・・

`AreEquals` というだけで、等価判定をする検証がなされているんだなと伝わります。他にも非等価や `True` など検証の種類が関数を見ればすぐにわかります。なので、引数を確認するまで分からないというのは僕がデメリットと思っている箇所と話が違います

2021-08-29 01:08 UTC, takasusuke approved these changes
@xiii111 
任せた

2021-08-29 13:43 UTC, xiii111 commented
やってほしいこと
- [ ] https://github.com/LITO-apps/Treevel-client/pull/946#discussion_r697804117

新しくコメントしたこと
- https://github.com/LITO-apps/Treevel-client/pull/946#discussion_r697804887
- https://github.com/LITO-apps/Treevel-client/pull/946#issuecomment-907565733

2021-09-06 11:43 UTC, takesi0627 commented
> やってほしいこと
> 
> * [ ]  [テストを増やす #946 (comment)](https://github.com/LITO-apps/Treevel-client/pull/946#discussion_r697804117)

727ca55 にて対応しました

2021-09-07 00:00 UTC, xiii111 approved these changes
LGTM with nits!

2021-09-07 00:00 UTC, xiii111 commented on Assets/Tests/PlayModeTest/StageDataTest.cs
> +                        // isRandomがtrueの場合、GimmickLibrary.SamplingArrayIndexの計算でこれらこれらの配列の要素の和がゼロの場合エラーになるため検証する必要がある
### nits

```suggestion
                        // isRandomがtrueの場合、GimmickLibrary.SamplingArrayIndexの計算でこれらの配列の要素の和がゼロの場合エラーになるため検証する必要がある
```

2021-09-07 00:01 UTC, xiii111 commented
@takesi0627 

https://github.com/LITO-apps/Treevel-client/pull/946#issuecomment-907565733 への意見があれば、話したいです（本 pr とは関係なく）

2021-09-09 03:42 UTC, merged