Bottleの移動が完全に終了してから成功判定を行う
LITO-apps/Treevel-client pull request #973
Opened 2021-06-12 10:09 UTC by takasusuke

### 対象イシュー
Close #762

### 概要
- ゲーム終了時のイベントの発火後にゲーム結果を保存するようにした

### 詳細
- ゲーム結果を保存処理の終了を待ってからゲーム終了時のイベント（ギミックを止めたりなど）が発火していたので、先にイベントを発火してゲーム結果を保存するようにした
↓
成功判定や失敗判定が遅延しなくなったので、本来の問題解決（Bottleの移動が完全に終了してから成功判定）を行う

#### 現実装になった経緯

#### 技術的な内容

### キャプチャ

### 動作確認方法

### 参考 URL

2021-06-12 18:04 UTC, takasusuke commented
@LITO-apps/engineer 
お願いいたします。30minくらいだと思います。

2021-06-12 18:05 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/BoardManager.cs
> -
単純に使ってないメソッドだったので消した

2021-06-12 18:07 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/GoalBottleController.cs
> +            isSuccess.SkipLatestValueOnSubscribe().Subscribe(value => {
Awake()でイベントが呼ばれると、`_spriteGlowEffect`が`null`でエラーになるのでskipする
ゲーム開始のタイミングで`BoardManager`から全ての`EnterTile`が呼ばれて、そこで`isSuccess`が`false`から`true`になればここの処理が走るので初回はskipして大丈夫

2021-06-18 12:12 UTC, xiii111 requested changes
いくつかコメントしました！

> BottleAが移動中に、BottleBがGustwindの効果で高速移動し成功判定を行うと、BottleAがまだ目的のTileに移動しきっていないのに、ゲームがクリアされてしまっていた。

まじか。これってどういうプログラム上の挙動でクリアになってしまうの？BottleA が目的の Tile に移動しきっていないのに成功になる理由が気になる。あと、BottleB がGustwind の効果で高速移動した先が BottleB の目的の Tile かどうかなどが明記されていないから状況が少しわかりづらいかも。

2021-06-18 12:12 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/BoardManager.cs
> +            _numOfSuccessBottles = 0;
### nits

以下のような書き方ではダメなんだっけ？
```csharp
private int _numOfSuccessBottles = 0;
```

2021-06-18 12:12 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/BoardManager.cs
> +        public void CheckClear(bool isSuccess)
### imo

なんかこの関数は名前と処理が一致していないかも。後半部分の `if (...)` は成功判定を確かにしているのだけど、前半部分は `Board` 全体の話ではなく、`Bottle` 一つの話をしている。また引数も `Bottle` 一つの話。少しわかりづらい

2021-06-18 12:12 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/GoalBottleController.cs
> +            EnterTile.Subscribe(_ => isSuccess.Value = GoalColor != EGoalColor.None && BoardManager.Instance.GetTileColor(this) == GoalColor).AddTo(this);
### imo

`GetColor != EGoalColor.none` は前提条件だから `Where` とかで入れても良さそう

2021-06-18 12:12 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                await Task.Delay(500);
### nits

マジックナンバーなので、定数に定義しましょう

2021-06-18 12:12 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                await StageRecordService.Instance.SaveAsync(treeId, stageNumber, Instance._stageRecord);
確かにこの処理の位置は悪かったな🙏

2021-06-18 12:21 UTC, takasusuke commented
> > BottleAが移動中に、BottleBがGustwindの効果で高速移動し成功判定を行うと、BottleAがまだ目的のTileに移動しきっていないのに、ゲームがクリアされてしまっていた。
> 
> まじか。これってどういうプログラム上の挙動でクリアになってしまうの？BottleA が目的の Tile に移動しきっていないのに成功になる理由が気になる。あと、BottleB がGustwind の効果で高速移動した先が BottleB の目的の Tile かどうかなどが明記されていないから状況が少しわかりづらいかも。

BottleAがフリックでGoalTileに到着、BottleBがGustWIndでGoalTileに到着するケースを考える。
1. BottleAがフリックされる
2. BottleAの移動元のTileから移動先のTileにデータを更新する(見た目はまだ)
3. BottleAが移動を開始する
4. BottleBがGustWindで移動する
5. BottleBが移動元のTileから移動先のTileにデータを更新する(見た目はまだ)
6. BottleBが移動を開始する
7. BottleAの移動が終了する
8. BottleAの成功判定が行われる
9. 8で成功判定となるので、GamePlayDirectorのゲームの成功判定が行われる(BottleBはまだ移動途中)
10. BottleBの移動が終わっていなくても、データはすでに移動先になっているので、GamePlayDirectorの成功判定(データから成功状態かどうか判定)では成功扱いになる
11. ゲームクリアになる

複数同時にBottleが移動したときに、１つ目のBottleの移動が終わったタイミングで全体の成功判定が行われて、かつ、そのときにデータ的には成功状態になっているので問題が起こっていた。
重複して同じ場所にBottleが移動しないようにSquareクラスのデータ更新は移動開始で行う必要があるけれど、それと成功判定は別タイミングのロジックなので分けました。

2021-06-18 18:32 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/BoardManager.cs
> +            _numOfSuccessBottles = 0;
初期値は0なので代入の必要がないので入れてません。
ここは初回プレイ時にはむしろ無駄ですが、リトライ時は必ず必要なのでここで書いてます。

2021-06-18 18:43 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                await Task.Delay(500);
ここ、あえてマジックナンバーにしている、というか
別に、
`await Task.Delay(n);`の`n`で調整したいわけじゃなくて
```
// 成功盤面を一定時間表示
Debug.Log("ここで待つ");
```
とか
```
// アニメーションの終了を待つ
```
くらいの感覚なんだけど、定数定義する？

（肌感覚として、定数定義すると、`await Task.Delay(n);`という処理で演出が決定されるように感じる。
けど、どんな時もマジックナンバーは悪になる、ということでしたらとりあえず定数定義します。
結局、現処理の`await Task.Delay(n);`を受け入れてそのままになる可能性もあるでしょ、と言われると確かにあり得る、、、と思う。）

2021-06-18 18:49 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Bottle/GoalBottleController.cs
> +            EnterTile.Subscribe(_ => isSuccess.Value = GoalColor != EGoalColor.None && BoardManager.Instance.GetTileColor(this) == GoalColor).AddTo(this);
7b764fd

2021-06-18 19:03 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/BoardManager.cs
> +        public void CheckClear(bool isSuccess)
03782d7
言われると確かに。

しっくり来るメソッド名難しい。。。
`CheckClear`よりは`UpdateNumOfSuccessBottle`の方が変にこねてないけど、bestとも思えない。

2021-06-18 19:08 UTC, takasusuke commented
@xiii111 
よろしくお願いします。
524f50a では複数スレッドで共有の変数を操作するのに排他制御していなかったので修正しました。`interlock`は最も高速の排他制御らしいです。
https://blog.siongames.net/entry/lockcontro#2-InterLocked

2021-06-19 07:49 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/BoardManager.cs
> +            _numOfSuccessBottles = 0;
> 初期値は0なので代入の必要がないので入れてません。

`_numOfGoalBottles = 0;` と書くなら、こういう風に書けば良いのでは？と思って書きました。下のコメントに続きます

> ここは初回プレイ時にはむしろ無駄ですが、リトライ時は必ず必要なのでここで書いてます。

リトライ時も `Initialize` が呼ばれるのですね。このプロジェクトにおける `Initialize` はコンストラクタの代わりのようなものを想定して設計していたつもりで、実際にそのような呼ばれ方（基本的に `Awake()` と同じようなライフサイクルで高々一回呼ばれるようなもの）だと思っていたので、2回目呼ばれることを想定していなかったです。なんかバグの温床な気がしてならないですが、とりあえずオッケーです

2021-06-19 07:55 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/BoardManager.cs
> +        public void CheckClear(bool isSuccess)
変更後でだいぶ良くなったと思います👍 成功判定の処理が複雑であれば、別途 `CheckClear` という関数を作りたいですが、現状一行で済んでいますし許容できます。ここで `isSuccess` というのが何の情報なのかがパッと分からないので、ドキュメンテーションコメントを挟んでおきたいです。このままでは、`NumOfSuccessBottles` を更新する処理だが、引数としてはひとつのボトルの成功可否を伝えるんだよ、と分からない

2021-06-19 07:57 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                await Task.Delay(500);
> どんな時もマジックナンバーは悪になる

とは思ってないけど、この処理ってユーザの体験に影響するよね？`Debug.Log()` や `//` などのコメントはユーザに一切の影響を与えないので好きにやってもらって良いけど、この処理はユーザに成功盤面を `n` 秒間表示するんだよって昨日だと思っていた。認識間違っていた？

2021-06-19 08:01 UTC, xiii111 commented
> > > BottleAが移動中に、BottleBがGustwindの効果で高速移動し成功判定を行うと、BottleAがまだ目的のTileに移動しきっていないのに、ゲームがクリアされてしまっていた。
> > 
> > 
> > まじか。これってどういうプログラム上の挙動でクリアになってしまうの？BottleA が目的の Tile に移動しきっていないのに成功になる理由が気になる。あと、BottleB がGustwind の効果で高速移動した先が BottleB の目的の Tile かどうかなどが明記されていないから状況が少しわかりづらいかも。
> 
> BottleAがフリックでGoalTileに到着、BottleBがGustWIndでGoalTileに到着するケースを考える。
> 
> 1. BottleAがフリックされる
> 2. BottleAの移動元のTileから移動先のTileにデータを更新する(見た目はまだ)
> 3. BottleAが移動を開始する
> 4. BottleBがGustWindで移動する
> 5. BottleBが移動元のTileから移動先のTileにデータを更新する(見た目はまだ)
> 6. BottleBが移動を開始する
> 7. BottleAの移動が終了する
> 8. BottleAの成功判定が行われる
> 9. 8で成功判定となるので、GamePlayDirectorのゲームの成功判定が行われる(BottleBはまだ移動途中)
> 10. BottleBの移動が終わっていなくても、データはすでに移動先になっているので、GamePlayDirectorの成功判定(データから成功状態かどうか判定)では成功扱いになる
> 11. ゲームクリアになる
> 
> 複数同時にBottleが移動したときに、１つ目のBottleの移動が終わったタイミングで全体の成功判定が行われて、かつ、そのときにデータ的には成功状態になっているので問題が起こっていた。
> 重複して同じ場所にBottleが移動しないようにSquareクラスのデータ更新は移動開始で行う必要があるけれど、それと成功判定は別タイミングのロジックなので分けました。

細かい説明とても助かります🙏

> 重複して同じ場所にBottleが移動しないようにSquareクラスのデータ更新は移動開始で行う必要がある

これが問題を難しくしていたのか ...

2021-06-19 08:02 UTC, xiii111 reviewed
スレッドに返信を行いました

2021-06-19 11:44 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                await Task.Delay(500);
いやそうなんだけど、
`n`秒間表示する実装として
- ただn秒待つ
- 盤面を見せつつ、何かしら演出オブジェクトを加える（のでそれのアニメーションの終了を待つ）
- 前のアプリで言うBottleの点滅アニメーションを行う(のでそれを待つ）

とかあるので、
```
await UniTask.WaitUntil(() => _animator.GetCurrentAnimatorStateInfo(0).shortNameHash != _ANIMATOR_NAME_HASH_BOTTLEIN);
```
みたいに書く可能性あるよね、と。
だから、
`await Task.Delay(n);`という記述自体破壊するある（というより、ほぼそうすると思う）から、`n`を定数で管理するのって必要かな？という疑問でした。


なんだろう。DBがまだない状態でDBからデータ取ってくる時間を考えて一旦
```
// ここでデータ取得
await Task.Delay(1);
```
って書いてる感じ。

2021-06-19 11:46 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                await Task.Delay(500);
ここまで書いてあれだけど、別に定数定義したくないんじゃなくて、
ここの処理ってめちゃめちゃ暫定的だよ？？ってことが伝わればそれで良い。

2021-06-19 11:52 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/BoardManager.cs
> +        public void CheckClear(bool isSuccess)
34d5798

2021-06-19 11:54 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/BoardManager.cs
> +        public void CheckClear(bool isSuccess)
コメント書いて思ったけど、このメソッド、`public`にして色々呼ばれる危険性あるのやだな。
クリア判定のメソッド作成して、
`GoalBottle`の`isSuccess`を`BoardManager`がその都度見に行く形にしよー。
ちょっと作業中に戻します。

2021-06-19 13:18 UTC, xiii111 commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                await Task.Delay(500);
> `await Task.Delay(n);` という記述自体破壊する可能性ある

なるほど。では `await Task.Delay(n);` の上に、アニメーションを待つ方が良いという旨を `TODO: ` コメントをつけておくのはどうですか？

2021-06-21 12:33 UTC, xiii111 commented
@takasusuke まだ全て終わっていないのに In Review に戻していませんか？

2021-06-21 12:37 UTC, takasusuke commented
> @takasusuke まだ全て終わっていないのに In Review に戻していませんか？（ミス？）

ええ。。。
結局現実装を変えることはせず、↓の`TODO:`コメントだけつけてmergeするってなって、
でもapproveしてもらってない、みたいなとこで終わってる認識。
もうそれだけだからやっぱレビュー中に戻しとくわって。。。なった。。。
https://github.com/LITO-apps/Treevel-client/pull/973#discussion_r654795572

2021-06-21 12:38 UTC, xiii111 commented
@takasusuke https://github.com/LITO-apps/Treevel-client/pull/973#discussion_r654795572 これやりました？

2021-06-21 12:39 UTC, xiii111 commented
@takasusuke https://github.com/LITO-apps/Treevel-client/pull/973#discussion_r654795572 これ終わってると思ってその発言しちゃったわ

2021-06-21 12:40 UTC, xiii111 approved these changes
僕が悪かったみたいです。とりあえず approve しときますね

2021-06-21 12:40 UTC, takasusuke commented
> @takasusuke [#973 (comment)](https://github.com/LITO-apps/Treevel-client/pull/973#discussion_r654795572) これ終わってると思ってその発言しちゃったわ。実際には終わってなかったから、認識ミス？って思って聞いた

昨日作業してないし、今からやるのに聞かれて泣いてる。

2021-06-21 12:41 UTC, xiii111 commented
ごめんなさい

2021-06-21 12:42 UTC, xiii111 commented
ただの認識ミスなので、普通に指摘してもらえると助かります🙏

2021-06-21 12:51 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/GamePlayDirector.cs
> +                await Task.Delay(500);
eaeb60f

2021-06-21 12:52 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/BoardManager.cs
> +        public void CheckClear(bool isSuccess)
外部から呼ばれる危険性はありますが、より優先度の高い実装を先に行うということでこのままにします。
不用意に呼ばない、という気をつけることになりました。

2021-06-21 12:57 UTC, merged