【レベル選択画面】木の解放演出
LITO-apps/Treevel-client pull request #978
Opened 2021-06-15 16:45 UTC by takesi0627

### 対象イシュー
ref #817

### 概要
道の解放の演出に続く木の解放の演出実装

### 詳細

#### 現実装になった経緯

#### 技術的な内容

### キャプチャ

### 動作確認方法

### 参考 URL

2021-06-19 17:20 UTC, takesi0627 commented
@LITO-apps/engineer 
お待たせしました。レビューよろしくお願いします。
主にタイムラインとパーティクルの部分を見ていただければと思います。
タイムラインの実装は #970 とそんなに変わらないです

2021-06-21 12:34 UTC, xiii111 commented
申し訳ないですが、@takasusuke お願いします🙏

2021-06-21 13:45 UTC, takasusuke requested changes
- `ParticleSystem/Velocity over Lifetime`のyは0のままにして、
`ParticleSystem/RendererPの`Order in Layer`を1より大きくするのはいかがでしょうか。

- Particleの演出は色・大きさ・スピード・Particleの画像など、まだ調整したい項目は何がありますでしょうか。
結構良いと思います。以下のよう設定すると個人的にはより好みです。
`Radius Chickness` : 0だとConeのEdgeからParticleが出る。1だとConeの内部からバラバラにParticleが出る
`Spread` : Paricle同士の間隔。`0.25`とか`0.5`に設定するとどういう値なのかわかりやすいと思う。
<img width="456" alt="スクリーンショット 2021-06-21 22 41 30" src="https://user-images.githubusercontent.com/26213141/122771930-da7c8400-d2e1-11eb-80c4-2bc201d99062.png">

2021-06-21 13:45 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/TreePlayableBehaviour.cs
> +            if (!_isReflectedTreeState && progress > 0.5f) {
```suggestion
            if (progress > 0.5f) {
```

2021-06-21 13:45 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/TreePlayableBehaviour.cs
> +            if (!_isReflectedTreeState && progress > 0.5f) {
### imo

0.5f は定数化したい。

2021-06-21 13:45 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/TreePlayableBehaviour.cs
> +            // なんか視点ズレてるから修正する
```suggestion
            // TODO: なんか視点ズレてるから修正する
```

2021-06-21 15:31 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/TreePlayableBehaviour.cs
> +            // なんか視点ズレてるから修正する
ごめんコメントが変化もしれない、
MTGで説明したように、道の解放の最後に止まってるところは木が見切れてしまうので、
ここで「視点を修正する」という意味のコメントですので、TODOではない

2021-06-21 15:35 UTC, takasusuke commented on Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/TreePlayableBehaviour.cs
> +            // なんか視点ズレてるから修正する
あーーーーなるほどーーー。
じゃあ
`視点を修正する`
とかで大丈夫っす

2021-06-21 16:13 UTC, takesi0627 commented
@takasusuke 
再レビューを願いします
4af7d17 でパラメータ微調整しました

2021-06-22 12:16 UTC, takasusuke approved these changes

2021-06-22 13:16 UTC, merged