GustWindの演出実装
LITO-apps/Treevel-client pull request #993
Opened 2021-06-23 14:26 UTC by takasusuke

### 対象イシュー
Close #847

### 概要
タイトルまま

### 詳細
- 全てのGimmickに適切にTagをつけました
- GustWindの動きに関して、符号間違いにより不具合があったので修正しました。（while loopの中に入ることが全くなく、Gustwindがその場から動いていなかった問題を修正）
これに合わせて、GustWind本体のアニメーション開始時に一瞬GustWIndが中央に表示されてしまうバグがありましたので、SpriteRendererの表示タイミングをアニメーションではなく、スクリプトで制御するようにしました。
- GustWind自体の透明度を修正しました
- （まだ）ParticleSystemを使って、警告およびGustWind本体に葉っぱを散らせる。

#### 現実装になった経緯

#### 技術的な内容

### キャプチャ

### 動作確認方法

- [ ] Spring_1_8をプレイ。GustWindを眺める。

### 参考 URL

2021-06-23 14:29 UTC, takasusuke commented
@takesi0627 
signが間違っていて、GustWind.csのwhile loopに全く入ってなかったので修正しました。(自分もちゃんとレビューしたつもりだったのに。。。)
ParticleSystemの演出が完成したら改めてReview request出しますが、while loopの不具合と、SpriteRendererの表示/非表示をスクリプトで制御するようにした部分はもう完成しておりますので、先にReview Requestを出しておきます🙇‍♂️

2021-06-25 03:19 UTC, takasusuke commented
@LITO-apps/engineer 
レビューお願いいたしマウス。30minくらいです。
アニメーションのコメントお待ちしております。

2021-06-25 16:41 UTC, takesi0627 commented
アニメーションを見た感想ですが、警告段階の風のコマ数もうちょっと増やしたほうがいいかもしれない。
葉っぱの動きがすごく滑らかに対して、コマ数が少ない風の動きは少しギクシャクになっているような気がしました。
もちろんこれはオプショナルです。全然今のクオリティでリリースしてもいいと思います

2021-06-25 17:11 UTC, takesi0627 requested changes
確認お願いします

2021-06-25 17:11 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/GustWindController.cs
> +            _coreBoxCollider2D.enabled = true;
### `imo`
これはアニメーションで組めます。
メリットとしては `_coreBoxCollider2D`を取らなくて良くなるとかが挙げられます。

2021-06-25 17:11 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/GustWindController.cs
> +            GamePlayDirector.Instance.GameEnd.Subscribe(_ => _animator.enabled = false).AddTo(this);
### `must`
* Particleも止める必要がありそうです
* `_animator.enabled = false` だとアニメーションをその場で止めるのではなく、ゲームオブジェクトを元の状態に戻してしまうので、おそらく想定した挙動ではない。
https://user-images.githubusercontent.com/17778395/123461033-7c260d00-d623-11eb-9935-d0c959e0c21b.mov

2021-06-26 10:21 UTC, xiii111 commented
@takesi0627 レビューありがとう

2021-06-28 15:46 UTC, takesi0627 commented
まだ作業中みたいなので作業中に戻します

2021-06-29 13:19 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/GustWindController.cs
> +            _coreBoxCollider2D.enabled = true;
GustwindのアニメーションでBoxCollider2D制御してたのをやめた理由。

ここの直前の記述の
```
transform.position = _attackStartPos;
```
でpositionを設定する前は警告と同じ位置にGustwindがあるので、Gustwindのアニメーションが始まった瞬間に当たり判定起きる。

なので、positionを設定してから当たり判定が起きるようにしている。

2021-06-29 13:38 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/GustWindController.cs
> +            GamePlayDirector.Instance.GameEnd.Subscribe(_ => _animator.enabled = false).AddTo(this);
なるほど。
46a42cb

2021-06-29 13:39 UTC, takasusuke commented
> アニメーションを見た感想ですが、警告段階の風のコマ数もうちょっと増やしたほうがいいかもしれない。
> 葉っぱの動きがすごく滑らかに対して、コマ数が少ない風の動きは少しギクシャクになっているような気がしました。
> もちろんこれはオプショナルです。全然今のクオリティでリリースしてもいいと思います

ブラッシュアップで対応します。力尽きました。。。
#1003

2021-06-29 13:40 UTC, takasusuke commented
@takesi0627 
再度お願いいたします。

2021-06-29 14:42 UTC, takesi0627 approved these changes
> > アニメーションを見た感想ですが、警告段階の風のコマ数もうちょっと増やしたほうがいいかもしれない。
> > 葉っぱの動きがすごく滑らかに対して、コマ数が少ない風の動きは少しギクシャクになっているような気がしました。
> > もちろんこれはオプショナルです。全然今のクオリティでリリースしてもいいと思います
> 
> ブラッシュアップで対応します。力尽きました。。。
> #1003

それで大丈夫です。
ありがとうございました。

2021-06-30 16:40 UTC, merged