HolyTile演出実装
LITO-apps/Treevel-client pull request #994
Opened 2021-06-23 17:51 UTC by takesi0627

### 対象イシュー
Close #857 

### 概要
* いただいた画像の組み込み
* その他演出実装

### 詳細

#### 技術的な内容

レイヤー順（奥→手前）
1. 普通のタイル画像（樹皮）
2. Tileの上に乗せる黄色背景の画像（HolyTilePrefab/HolyTileColor）
3. 光が注ぐ画像（HolyTilePrefab/HolyTileEffect）
4. Bottleの上に乗せる黄色のワンポイント画像（HolyTilePrefab/HolyBottlePoint）
5. Bottleの画像
6. Bottleの上に乗せる黄色の画像（HolyTileBottleMask） 

### キャプチャ

https://user-images.githubusercontent.com/17778395/123143471-992cd580-d495-11eb-95f1-d0dd7cc1364b.mov

### 動作確認方法
- [ ] Spring-1-3をプレイし演出を確認。

2021-06-23 17:56 UTC, takesi0627 commented
@LITO-apps/engineer 
レビューよろしくお願いします。
なるべくゲームロジックと演出を切り分けたいのでゲームオブジェクトのOn／Offなど全部アニメーションで制御するようにしました。

@takasusuke 
特にレイヤ順ちょっと確信がないの確認していただけると助かります

2021-06-25 01:12 UTC, takasusuke requested changes
お疲れ様ーー
レイヤー順序は完璧だと思いまーす

- 成功/失敗時にHolyTileのアニメーションを止めたいです
- `HolyTileEffect`のアニメーションに１フレーム追加して、最後のpngを追加しないと、最後のpngは表示されてないと思う。（で合ってるかな？）
最後のpngを持続する時間がない気がする。
- `Animation`の`FPS`を`60`で統一したい
（60で統一できてないとこもあるんだけど、他のアニメーションも基本的には60FPSにしてる）
inspectorをDebug modeで開いたら設定できる
<img width="348" alt="スクリーンショット 2021-06-25 9 59 22" src="https://user-images.githubusercontent.com/26213141/123353257-18a4cc80-d59c-11eb-885a-8c7232a4bf2a.png">


- `HolyTile@idle`のスピードなんだけど、個人的にはもう少し早い(2倍くらい)アニメーションだと思ってたけどどうですか？
`Animation`で調整しなくても`Animatr`のinspectorの`Speed`で調整で良いです。

- `HolyTile@bottle_in`と`HolyTile@bottle_out`のアニメーションの時間はもう少し短い感じを想像してた

- 以下のTransition入れた方が、HolyTileに入ってすぐ出るときに自然かと思います。
<img width="650" alt="スクリーンショット 2021-06-25 10 11 06" src="https://user-images.githubusercontent.com/26213141/123353990-b056ea80-d59d-11eb-9a9d-ad731811bdf8.png">

2021-06-25 01:12 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/HolyTileController.cs
> +            private static readonly int _ANIMATOR_PARAM_TRIGGER_BOTTLE_EXIT = Animator.StringToHash("BottleExit");
### imo
Triggerの名前も`BottleIn`、`BottleOut`でどうでしょうか？

2021-06-25 16:31 UTC, takesi0627 commented
> お疲れ様ーー
> レイヤー順序は完璧だと思いまーす
> 
> * 成功/失敗時にHolyTileのアニメーションを止めたいです

05f07e8

> * `HolyTileEffect`のアニメーションに１フレーム追加して、最後のpngを追加しないと、最後のpngは表示されてないと思う。（で合ってるかな？）
>   最後のpngを持続する時間がない気がする。


b04d580

> * `Animation`の`FPS`を`60`で統一したい
>   （60で統一できてないとこもあるんだけど、他のアニメーションも基本的には60FPSにしてる）
>   inspectorをDebug modeで開いたら設定できる

b99096f
ちなみにDebug modeじゃなくてもここから設定できますよ
![image](https://user-images.githubusercontent.com/17778395/123455411-a0cab680-d61c-11eb-92ec-c6cc884d3ec7.png)


> * `HolyTile@idle`のスピードなんだけど、個人的にはもう少し早い(2倍くらい)アニメーションだと思ってたけどどうですか？
>   `Animation`で調整しなくても`Animatr`のinspectorの`Speed`で調整でも大丈夫です。
> * `HolyTile@bottle_in`と`HolyTile@bottle_out`のアニメーションの時間はもう少し短い感じを想像してた

FPSを60にしたら多分5倍速になったのでとりあえず修正後見てもらってから調整したいです。


> * 以下のTransition入れた方が、HolyTileに入ってすぐ出るときに自然かと思います。
> 
> <img alt="スクリーンショット 2021-06-25 10 11 06" width="650" src="https://user-images.githubusercontent.com/26213141/123353990-b056ea80-d59d-11eb-9a9d-ad731811bdf8.png">

304da08

2021-06-25 16:35 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/HolyTileController.cs
> +            internal HolyTileBottleHandler(HolyTileController parent)
2897daf

2021-06-25 16:35 UTC, takesi0627 commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/HolyTileController.cs
> +            GetComponent<SpriteRendererUnifier>().SetSprite(AddressableAssetManager.GetAsset<Sprite>(Constants.Address.NORMAL_TILE_SPRITE_PREFIX + tileData.number));
e55b148

2021-06-25 16:36 UTC, takesi0627 commented
@takasusuke 再レビューお願いします

2021-06-26 10:04 UTC, xiii111 commented
@takasusuke レビューありがとう

2021-06-27 14:02 UTC, takasusuke commented on Assets/Project/Scripts/Modules/GamePlayScene/Tile/HolyTileController.cs
> +            private static readonly int _ANIMATOR_PARAM_TRIGGER_BOTTLE_EXIT = Animator.StringToHash("BottleExit");
理解！

2021-06-27 14:04 UTC, takasusuke commented
> > * `HolyTile@idle`のスピードなんだけど、個人的にはもう少し早い(2倍くらい)アニメーションだと思ってたけどどうですか？
> >   `Animation`で調整しなくても`Animatr`のinspectorの`Speed`で調整でも大丈夫です。
> > * `HolyTile@bottle_in`と`HolyTile@bottle_out`のアニメーションの時間はもう少し短い感じを想像してた
> 
> FPSを60にしたら多分5倍速になったのでとりあえず修正後見てもらってから調整したいです。

5倍、、、は早く見える。。。半分くらい？
IceTileの演出に比べて極端に早いor遅い演出じゃなければ良いと思います！
良い感じに調整してmergeしちゃってください！

2021-06-27 14:04 UTC, takasusuke approved these changes

2021-06-28 14:37 UTC, takesi0627 commented
いい感じに速度を調整しました

2021-06-28 14:37 UTC, merged